[DONE] Pampletousse/feature download qrcode
EsupPortail/Esup-Pod pull request #1015
Opened 2023-12-18 09:27 UTC by pampletousse

Add download button for QR Code (to replace usage of right-click -> save as) + Fix border red on all share video pannel -> only on if is draft

2023-12-18 15:33 UTC, ptitloup requested changes
Merci

2023-12-18 15:33 UTC, ptitloup commented on pod/main/static/js/main.js
> +document.getElementById("btnDowloadQrCode").addEventListener('click', (e) => {
je pense qu'il faut d'abord tester si l'element est présent avant de lui asigner un event listener non ?
Ne pourait-on pas mettre ce code dans un fichier de l'app video plutot ? c'est utilisé que sur une page de visualisation de la vidéo.
Merci

2023-12-18 15:33 UTC, ptitloup commented on pod/video/templates/videos/video-info.html
> +        <div>
ok pour moi

2023-12-18 15:33 UTC, ptitloup commented on pod/video/templates/videos/video-info.html
> +          <div class="card text-white border-danger mb-3">
oui ok pour ne mettre que la bordure en rouge plutot que le fond mais il me semble que les remarques de l'époque disait que ce n'etait pas assez visible... peut etre que les temps ont changé.

2024-01-04 09:06 UTC, SebastienCozeDev requested changes
Je n'ai regardé que le code pour le moment

2024-01-04 09:16 UTC, AymericJak requested changes
Merci pour les changements, juste une petite révision et c'est bon pour moi :)

2024-01-04 09:16 UTC, AymericJak commented on pod/video/templates/videos/video-info.html
> +                     alt="{% trans 'QR code' %}" id="qrcode" loading="lazy" class="collapse m-2">
En balise alt, je mettrais plutôt un truc du style : `alt="{% blocktrans with video_title=video.title %}QR code to access the video “{{ video_title }}”{% endblocktrans %}`

2024-01-09 13:30 UTC, pampletousse commented on pod/main/static/js/main.js
> +document.getElementById("btnDowloadQrCode").addEventListener('click', (e) => {
J'étais d'accord jusqu'à ce que je m'aperçoive que le QR code est aussi disponible pour les évènements live ^^ Je vais donc le laisser dans main et faire aussi la modif côté live. Je peux aussi l'externaliser dans un fichier js spécifique mais peu d'interêt vu le nombres de lignes...

2024-01-23 07:48 UTC, pampletousse commented
Branche rebased sur develop, conservation de l'ancien qrcode d'édition rapide d'un évènement, ajout d'un QRCode de lecture (lien direct) vers event, basé sur le même principe que celui de vidéo.

@AymericJak pour les traductions _("QR code event's link") et _("QR code video's link") te conviennent ou tu préfères "QR code to access the video" / event ?

2024-01-23 08:23 UTC, AymericJak commented
> @AymericJak pour les traductions _("QR code event's link") et _("QR code video's link") te conviennent ou tu préfères "QR code to access the video" / event ?

J'étais plutôt de l'avis d'être plus précis que ça, quel est ton avis sur le sujet @Badatos ?

2024-01-23 08:28 UTC, Badatos commented
> > @AymericJak pour les traductions _("QR code event's link") et _("QR code video's link") te conviennent ou tu préfères "QR code to access the video" / event ?
> 
> J'étais plutôt de l'avis d'être plus précis que ça, quel est ton avis sur le sujet @Badatos ?

Ca dépend du contexte ^^.
Une chose en tout cas : il faut être constant, et ne pas avoir de temps en temps "Download qrcode" et d'autre fois "QR code to access the video" => toujours utiliser 'QR code' plutôt que "qrcode" par exemple

2024-01-23 08:34 UTC, Badatos requested changes

2024-01-23 08:34 UTC, Badatos commented on pod/live/templates/live/event-info.html
> +                  </div>
ici préférez "Download this QR code" en title

2024-01-23 08:34 UTC, Badatos commented on pod/video/templates/videos/video-info.html
> +                  <button id="btnDownloadQrCode" type="submit" data-slug="{{ video.slug }}" class="btn btn-primary my-2" title="{% trans 'Download qrcode' %}">{% trans 'Download' %}</button>
idem, préférez "QR code" à "qrcode"

2024-01-23 08:35 UTC, Badatos commented
> se en tout cas : il faut être constant, et ne pas avoir de temps en temps "Download qrcode" et d'autre fois "QR code to access the video" => toujours utiliser 'QR code' plutôt que "qrcode" par exemple

Si le texte est dans un bouton, alors autant rester concis, mais si c'est dans un title ou dans un texte d'aide on peut se permettre d'être le plus précis possible en effet.

2024-01-24 08:30 UTC, AymericJak requested changes

2024-01-24 08:30 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "QR code pour le lien de l'évènement :"
Petit problème de trad. Il manque les `:` le id

2024-01-24 08:30 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "QR code pour le lien de la vidéo :"
Pareil, petit problème

2024-01-24 08:55 UTC, pampletousse commented on pod/main/utils.py
> +def generate_qrcode(url, id, alt, request=None):
Dans l'en-tête, entre les parenthèses ? Car dans la pydoc pour moi c'est bon j'ai fait comme je l'ai trouvé ailleurs dans le code

2024-01-24 11:50 UTC, pampletousse commented on pod/live/templates/live/event-info.html
>                      <label for="txtpartage">{% trans 'Use this link to share the video:' %}</label>
ça marche !

2024-01-24 14:09 UTC, AymericJak requested changes

2024-01-24 14:09 UTC, AymericJak commented on pod/live/templatetags/event_tags.py
> +def get_event_qrcode(event_id: int):
Peux tu spécifier le type de retour aussi : `def get_event_qrcode(event_id: int)->str:`

2024-01-24 14:09 UTC, AymericJak commented on pod/video/templatetags/video_tags.py
> +def get_video_qrcode(video_id: int):
Pareil il faudrait le type de retour

2024-01-24 14:18 UTC, Badatos commented on pod/main/utils.py
> +        + f'width="200px" height="200px" alt={alt}>'
Est-ce qu'il ne manque pas des guillemets autour de {alt} ?

2024-01-24 14:20 UTC, Badatos approved these changes
Juste une question sur des guillemets manquants, sinon c'est ok pour moi :)

2024-01-24 14:20 UTC, pampletousse commented on pod/main/utils.py
> +        + f'width="200px" height="200px" alt={alt}>'
Fait, j'envoie !

2024-01-24 14:39 UTC, AymericJak approved these changes
Et c'est bon pour moi !
Thanks

2024-01-25 08:53 UTC, SebastienCozeDev approved these changes
Parfait niveau code pour moi. Merci !

2024-01-25 09:47 UTC, ptitloup approved these changes
ok pour moi

2024-01-25 09:47 UTC, merged