[WIP] Ptitloup/improve subtitle accessibility
EsupPortail/Esup-Pod pull request #1018
Opened 2024-01-11 14:16 UTC by ptitloup

…file to improve accessibility of subtitle

Before sending your pull request, make sure the following are done :

* [ ] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [ ] Your PR targets the `develop` branch.
* [ ] The title of your PR starts with `[WIP]` or `[DONE]`.

2024-01-15 11:53 UTC, AymericJak requested changes

2024-01-15 11:53 UTC, AymericJak commented on pod/video_encode_transcript/transcript.py
Pourrais tu faire la pydoc des fonctions ?

2024-01-15 13:58 UTC, ptitloup commented on pod/video/views.py
> +    """
ce n'est pas ma fonctoin dans le sens ou je ne l'ai pas codé. Seulement, le pydoc faisant plus de 79car de long, flake me le signalait donc j'ai coupé le texte

2024-01-15 14:17 UTC, SebastienCozeDev reviewed
Je suis d'accord avec les remarques de Aymeric. J'attends donc que tu aies corrigé.

2024-01-15 14:23 UTC, ptitloup commented on pod/video_encode_transcript/transcript.py
> +    return '{:02d}:{:02d}:{:06.3f}'.format(hours, minutes, seconds)
j'ai positionné cette fonction dans le fichier transcript model pour la partager au sein de l'app de transcription - utile seulement pour le forma webvtt, je ne vois pas son utilité ailleurs mais je peux me tromper

2024-01-15 14:23 UTC, ptitloup commented
> Je suis d'accord avec les remarques de Aymeric. J'attends donc que tu aies corrigé.

fait

2024-01-15 14:36 UTC, SebastienCozeDev requested changes

2024-01-15 14:36 UTC, SebastienCozeDev commented on pod/video_encode_transcript/transcript.py
Il serait, selon moi, préférable de mettre la documentation sous ce format :

```py
def function(param1: type1, param2: type2) -> type3 :
    """
    Function description
    
    Args:
        param1 (type1): Description
        param2 (type2): Description
    
    Returns:
        type3: Description
    """
```

Voici un exemple :

```py
def check_video_in_playlist(playlist: Playlist, video: Video) -> bool:
    """
    Verify if a video is present in a playlist.

    Args:
        playlist (:class:`pod.playlist.models.Playlist`): The playlist object
        video (:class:`pod.video.models.Video`): The video object

    Returns:
        bool: True if the video is on the playlist, False otherwise
    """
```

2024-01-15 18:16 UTC, ptitloup commented on pod/video_encode_transcript/transcript.py
ok je vais m'en occuper

2024-01-16 08:51 UTC, ptitloup commented on pod/video_encode_transcript/transcript.py
fai

2024-01-16 08:56 UTC, SebastienCozeDev approved these changes
Parfait niveau code

2024-01-16 09:04 UTC, AymericJak approved these changes
C'est bon pour moi, merci !

2024-01-16 09:04 UTC, merged