[DONE] Pampletousse/fix dashboard translation
EsupPortail/Esup-Pod pull request #1021
Opened 2024-01-18 15:19 UTC by pampletousse

Fix missing tranlsations for Dashboard

2024-01-18 15:33 UTC, pampletousse commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgid "Aucun élément trouvé"
D'où ça sort ça, j'étais sur la bonne branch pourtant.. Est ce qu'il ne faudrait pas modifier la commande make lang pour exclure TOUT ce qu'il y a dans le répertoire custom ??

2024-01-19 07:47 UTC, ptitloup commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgid "Aucun élément trouvé"
En effet, il faut faire attention à ne pas prendre en compte les fichiers custom !

2024-01-19 08:18 UTC, pampletousse commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgid "Aucun élément trouvé"
Modif faite ! Je pense que c'est bon maintenant

2024-01-19 09:29 UTC, Badatos requested changes

2024-01-19 09:29 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +
Chaine à traduire

2024-01-19 14:02 UTC, Badatos approved these changes

2024-01-19 14:04 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "Un language de transcription disponible doit être spécifié."
Concrètement, il faudrait plutôt écrire "une lange de transcription" plutôt que "un language" (et dans tous les cas, langage s'écrit sans `u` en français ^^)

2024-01-19 15:10 UTC, AymericJak requested changes
Hello,
Un mini changement et c'est tout bon !

2024-01-19 15:10 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgstr[1] "Veuillez confirmer l'édition des vidéos suivantes:"
Il faut mettre un espace avant les `:` en français :)

2024-01-19 15:25 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgstr[1] "Veuillez confirmer l'édition des vidéos suivantes:"
Bien vu ! Un espace insécable de surcroit ;) (nbsp)

2024-01-22 08:17 UTC, AymericJak approved these changes
Parfait, merci :)

2024-01-22 08:21 UTC, ptitloup approved these changes
ok pour moi

2024-01-22 08:22 UTC, merged

2024-01-22 08:23 UTC, SebastienCozeDev requested changes
Merci pour cette PR ! Il y a juste une petite erreur de traduction

2024-01-22 08:23 UTC, SebastienCozeDev commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Save meeting in Dashboard"
Il me semble que la traduction n'est pas correct

2024-01-22 08:25 UTC, ptitloup commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Save meeting in Dashboard"
on va la corriger en develop après une passe globale, merci pour ton retour