Check extesion allowed video filename
EsupPortail/Esup-Pod pull request #1033
Opened 2024-01-29 14:10 UTC by marchal-julien

Before sending your pull request, make sure the following are done :

* [ ] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [ ] Your PR targets the `develop` branch.
* [ ] The title of your PR starts with `[WIP]` or `[DONE]`.

2024-01-29 14:25 UTC, ptitloup requested changes
merci pour la contribution ! 
demande de modification : amélioration de l'indentation, retrait de jquery.

2024-01-29 14:25 UTC, ptitloup commented on pod/video/templates/videos/add_video.html
> +	    if ($.inArray("."+extension,allow_extension_array) == -1) {
$ fonction jquery qui ne doit plus etre utilisé ! :(

2024-01-29 14:25 UTC, ptitloup commented on pod/video/templates/videos/add_video.html
> +          gettext("The file extension not in the allowed extension:") +
est-ce que cette chaine de caractère est déjà traduite ? sinon il faut egalement publier les fichiers de trad

2024-01-29 14:25 UTC, ptitloup commented on pod/video/templates/videos/add_video.html
> +		    $(".hide-on-processing").hide();
jquery ! beurk

2024-01-29 14:25 UTC, ptitloup commented on pod/video/templates/videos/add_video.html
> +        $(".show-on-processing").show();
idem, jquery !

2024-01-29 14:42 UTC, Badatos requested changes
en gros, même remarques que Nicolas : tant qu'on peut éviter Jquery c'est mieux ;)

2024-01-29 14:42 UTC, Badatos commented on pod/video/templates/videos/add_video.html
> +	    if ($.inArray("."+extension,allow_extension_array) == -1) {
à priori ceci devrait être équivalent :

`if (allow_extension_array.includes("."+extension) == false) {`

2024-01-30 09:40 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +          gettext("The file extension not in the allowed extension:") +
oui elle l'est

2024-01-30 09:40 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +		    $(".hide-on-processing").hide();
même si je suis d'accord c'est juste le code d'origine de la page...

2024-01-30 09:41 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +        $(".show-on-processing").show();
même si je suis d'accord c'est juste le code d'origine de la page...

2024-01-30 09:44 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +		    $(".hide-on-processing").hide();
Je ne sais pas faire, par quoi avez vous remplacer les hide show de jquery dans le reste de pod ?

2024-01-30 09:44 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +        $(".show-on-processing").show();
Je ne sais pas faire, par quoi avez vous remplacer les hide show de jquery dans le reste de pod ?

2024-01-30 10:18 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +	    if ($.inArray("."+extension,allow_extension_array) == -1) {
solve (merci pour l'aide)

2024-01-30 10:19 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +          gettext("The file extension not in the allowed extension:") +
solve (merci pour l'aide)

2024-01-30 10:19 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +		    $(".hide-on-processing").hide();
solve (merci pour l'aide)

2024-01-30 10:19 UTC, marchal-julien commented on pod/video/templates/videos/add_video.html
> +        $(".show-on-processing").show();
solve (merci pour l'aide)

2024-01-30 10:19 UTC, ptitloup approved these changes
ok pour moi, merci !

2024-01-30 10:35 UTC, Badatos commented on pod/video/templates/videos/add_video.html
> +			    elementsShowProcessing[i].style.display = 'block';
ici, il est préférable de retirer la classe "d-none" plutot que d'ajouter un style inline.

2024-01-30 10:36 UTC, ptitloup commented on pod/video/templates/videos/add_video.html
> +			    elementsShowProcessing[i].style.display = 'block';
Nous avons regardé mais ces elements n'ont pas la classe d-none ! Ils ont juste un style display=none

2024-01-30 10:43 UTC, Badatos commented on pod/video/templates/videos/add_video.html
> +			    elementsShowProcessing[i].style.display = 'block';
Je ne comprend pas : le d-none vient juste d'etre ajouté 2 lignes plus haut o_O

2024-01-30 10:44 UTC, Badatos commented on pod/video/templates/videos/add_video.html
> +			    elementsShowProcessing[i].style.display = 'block';
(Ligne 178)

2024-01-30 10:44 UTC, ptitloup commented on pod/video/templates/videos/add_video.html
> +			    elementsShowProcessing[i].style.display = 'block';
ce ne sont pas les mêmes éléments ! (show-on-processing et hide-on-processing)

2024-01-30 10:46 UTC, Badatos commented on pod/video/templates/videos/add_video.html
> +			    elementsShowProcessing[i].style.display = 'block';
ils devaient bien avoir un display block avec JQ, mains maintenant qu'on a corrigé, y'a pas de raison

2024-01-30 10:57 UTC, Badatos approved these changes

2024-01-30 10:58 UTC, Badatos commented on pod/video/templates/videos/add_video.html
> +			    elementsShowProcessing[i].style.display = 'block';
> ce ne sont pas les mêmes éléments ! (show-on-processing et hide-on-processing)

aaaah oki, j'avais pas vu, My bad !
Je valide ;)

2024-01-30 10:59 UTC, merged