[WIP] Quiz feature
EsupPortail/Esup-Pod pull request #1047
Opened 2024-02-08 09:20 UTC by AymericJak

# Quiz feature

2024-03-08 14:39 UTC, Badatos requested changes

2024-03-08 14:39 UTC, Badatos commented on pod/quiz/models.py
> +        return None
BaseQuestionForm c'est pas du tout None ^^

2024-03-08 14:39 UTC, Badatos commented on pod/quiz/static/quiz/js/create-quiz.js
>        deleteButton.setAttribute("aria-hidden", "true");
attention : si deleteButton porte l'action, il ne doit pas etre en aria-hidden

2024-03-08 14:43 UTC, Badatos commented on pod/quiz/static/quiz/js/create-quiz.js
>        deleteButton.setAttribute("aria-hidden", "true");
au passage, si ce doit etre un bouton, plutot utiliser "a" que "i" et ajouter `role=button`

2024-03-08 14:43 UTC, Badatos commented on pod/quiz/static/quiz/js/create-quiz.js
>        deleteButton.setAttribute("aria-hidden", "true");
... et un title compréhensible

2024-03-08 14:49 UTC, AymericJak commented on pod/completion/templates/video_completion.html
> +      <div class="breadcrumb">
Je mettais aussi posé la question. Je vais voir pour mettre une classe alternative à celle-ci !

2024-03-08 14:51 UTC, AymericJak commented on pod/completion/templates/video_completion.html
> +              <a class="btn btn-secondary btn-danger" href="{% url 'quiz:remove_quiz' video_slug=video.slug %}">{% trans 'Delete your quiz' %}</a>
Erreur copié collé :sweat_smile: 

On choisit le danger évidemment ^^

2024-03-08 14:52 UTC, AymericJak commented on pod/completion/templates/video_completion.html
> +        <div id="collapse-5" class="collapse card-text small">
J'avais dans la même logique que les éléments du fichier.

Je vais tout modifier ! Ce sera plus parlant

2024-03-08 14:53 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Unique choice"
ça va être long de tout changer, mais ok :)

2024-03-08 14:54 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Unique choice"
pas besoin de renommer les classes hein, juste les chaines de traduction ^^

2024-03-08 14:54 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "Horodatage de Départ"
Je ne Sais Pas j'avais l'envie sur l'instant :grin: 

J'enlève ça !

2024-03-08 14:56 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "L'horodatage de début doit être inférieure à l'heure de fin."
ça ressemblait à un mot féminin :joy: 

C'est noté

2024-03-08 14:57 UTC, AymericJak commented on pod/quiz/static/quiz/js/create-quiz.js
> +      input.type = "checkbox";
Ok je vais ajouter ça.
Je ne savais pas que c'était obligatoire

2024-03-08 15:00 UTC, AymericJak commented on pod/quiz/models.py
> +        return None
C'est la méthode parent. Je la redéfinie dans les classes héritantes ;)

C'est donc voulu

2024-03-08 15:02 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Unique choice"
Après j'aurais pu. Tant que la maj n'est pas faite. Après ce serait plus compliqué avec les migrations :)

2024-03-08 15:04 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "L'horodatage de début doit être inférieure à l'heure de fin."
On va dire que tu l'a fait pour célébrer la journée de la femme ;)

2024-03-08 15:07 UTC, Badatos commented on pod/quiz/static/quiz/js/create-quiz.js
> +      input.type = "checkbox";
c'est obligatoire pour l'accessibilité en tout cas ;)

2024-03-08 15:15 UTC, Badatos commented on pod/quiz/models.py
> +            BaseQuestionForm: Form for the question.
ici le retour est un UniqueChoiceQuestionForm et non un BaseQuestionForm

2024-03-08 15:16 UTC, Badatos commented on pod/quiz/models.py
> +            BaseQuestionForm: Form for the question.
ici aussi, retour  imprécis dans la pydoc

2024-03-08 15:16 UTC, Badatos commented on pod/quiz/models.py
> +            BaseQuestionForm: Form for the question.
idem

2024-03-18 16:43 UTC, Badatos approved these changes
Merci pour les corrections ;)
Au niveau du code, c'est OK pour moi ;)

2024-05-27 10:10 UTC, ptitloup approved these changes
ok pour moi ! cela me semble top mais il va falloir tester au niveau fonctionnelle pour valider l'ergonomie :)

2024-05-27 11:11 UTC, merged

2024-06-03 15:04 UTC, fanfounet commented
PB
Sur ma 2eme question, j'ai oublié le titre, à l'enregistrement j'ai bien eu l'erreur comme quoi j'avais oublié le titre par contre j'ai perdu sur mes 2 questions les choix des réponses

2024-06-03 15:07 UTC, fanfounet commented
PB
Quand on clique sur "Afficher la réponse dans la vidéo" il faut absolument que la vidéo dans le player soit lancé sinon elle ne se lance pas et ne va pas au timecode choisi

2024-06-03 15:46 UTC, ptitloup commented
tu peux les mettre ici ou le canal team ou sur la 1025, comme vous voulez