[WIP] Fix dressing Watermark path
EsupPortail/Esup-Pod pull request #1048
Opened 2024-02-09 09:55 UTC by Badatos

* Replace `settings.BASE_DIR` by watermark.file.path for video dressi…ng watermark
* Some code formatting & docs

2024-02-13 08:23 UTC, vsabatie approved these changes
Ça me semble bon. Merci pour ce travail, notamment sur la partie dressing :)

2024-02-13 09:16 UTC, SebastienCozeDev requested changes

2024-02-13 09:29 UTC, AymericJak requested changes

2024-02-13 09:29 UTC, AymericJak commented on pod/live/templates/live/event_immediate_edit.html
> +          console.log('clockbox');
Console log à retirer ?

2024-02-13 09:29 UTC, AymericJak commented on pod/live/templates/live/event_immediate_edit.html
> +              + ');"> ' + i + ':00</a></li>';
Ce serait plus compréhensible :

```
var newLink = `<li><a href="javascript:DateTimeShortcuts.handleClockQuicklink(${clockCount}, ${i});">${i}:00</a></li>`;
```

2024-02-13 09:29 UTC, AymericJak commented on pod/video/static/js/change_video_owner.js
> +*/
Fichier ajouté en 2.8.2

2024-02-13 09:29 UTC, AymericJak commented on pod/video/templates/videos/change_video_owner.html
> +  <script src="{% static 'js/change_video_owner.js' %}"></script>
Ajouter un `?ver={{VERSION}}` ?

2024-02-13 09:37 UTC, Badatos commented on pod/dressing/templates/my_dressings.html
>            {% endfor %}
Aucune idée, ce n'est pas mon code. je n'ai fait que de l'indentation ;)

2024-02-13 09:37 UTC, Badatos commented on pod/dressing/templates/my_dressings.html
>              <a href="../../video/{{ dressing.opening_credits|slugify }}" title="{% trans 'View the video'%}">{{ dressing.opening_credits }}</a>
Bien vu en effet, passer par "url" me semblerait plus solide oui !

2024-02-13 10:34 UTC, Badatos commented on pod/live/live_transcript.py
> +"""Esup-Pod live transcription."""
Je crois que Black fera cela très bien tout seul ;)

2024-02-13 16:07 UTC, Badatos commented on pod/dressing/templates/my_dressings.html
> +            {% if not forloop.last %}, {% endif %}
Bien vu, je corrige.

2024-02-13 16:11 UTC, Badatos commented on pod/live/templates/live/event_immediate_edit.html
> +              + ');"> ' + i + ':00</a></li>';
bien vu ! en effet, je corrige.

2024-02-13 16:27 UTC, Badatos commented
Merci beaucouyp @AymericJak et @SebastienCozeDev 🙏 
Changements apportés :)

2024-02-14 07:45 UTC, AymericJak requested changes
2 petites remarques et c'est bon pour moi !

2024-02-14 07:45 UTC, AymericJak commented on pod/cut/templates/video_cut.html
>  {% endblock more_script %}
Il manque une ligne vide en fin de fichier

2024-02-14 07:45 UTC, AymericJak commented on pod/dressing/utils.py
> +def get_position_value(position, height) -> str:
Est-ce que tu pourrais mettre aussi le type des paramètres ?

Exemple : `get_position_value(position: str, height: str) -> str:`

ça facilite quand on fait appel à la fonction :)

2024-02-14 09:32 UTC, Badatos commented on pod/cut/templates/video_cut.html
>  {% endblock more_script %}
bien vu ;)

2024-02-14 10:08 UTC, Badatos commented
Changements apportés ;)

2024-02-14 14:17 UTC, AymericJak approved these changes

2024-02-14 14:23 UTC, SebastienCozeDev requested changes

2024-02-15 08:33 UTC, Badatos commented
Cette fois on devrait être prêts à fusionner si vous n'avez plus rien à ajouter ;)

2024-02-15 09:21 UTC, SebastienCozeDev approved these changes
Tout est bon pour moi. Merci pour cette PR !

2024-02-15 09:23 UTC, merged