[DONE] WebTV - Dynamic home page
EsupPortail/Esup-Pod pull request #1051
Opened 2024-02-13 08:59 UTC by vsabatie

Cette PR ajoute la possibilité de personnaliser sa page d'accueil en créant des "blocs" de différents types (slider, card list...) avec des objets (playlist, chaîne, thème...).

Un grand merci à L'Université de Lorraine qui m'a grandement aidée en partageant le travail qu'elle avait commencé.

J'attends vos premiers retours avec impatience !

2024-02-13 14:03 UTC, AymericJak requested changes

2024-02-13 14:03 UTC, AymericJak commented on pod/main/templatetags/flat_page_edito_filter.py
> +        title = "Les dernières vidéos"
à traduire ?

2024-02-13 14:03 UTC, AymericJak commented on pod/main/templatetags/flat_page_edito_filter.py
Peux tu :
- ajouter la pydoc pour les fonctiones de ce fichier ;
- modifier les variable pour appliquer le snake_case ;
- typer les signatures des fonctions (ex : `def fonction(attribut: type) -> type_de_retour`

2024-02-15 09:20 UTC, SebastienCozeDev requested changes
Fonctionnel de mon côté. Merci pour cette PR :+1: 

Quelques remarques niveau code

2024-02-15 09:49 UTC, Badatos commented
Il y a un petit conflit à résoudre ;)

2024-02-15 10:17 UTC, vsabatie commented on pod/main/templates/block/card_list.html
> +				  <p><a class="btn btn-lg btn-primary btn-sm" href="{% url 'videos:videos' %}">{% trans "Show all videos" %} <i class="bi bi-arrow-right-circle" aria-hidden="true"></i></a></p>
Je n'ai pas bien compris 👀

2024-02-15 10:58 UTC, vsabatie commented on pod/main/static/css/block.css
> +    display: flex!important;
Je ne crois pas

2024-02-15 11:02 UTC, vsabatie commented on pod/main/templates/block/slider.html
C'est-à-dire ?

2024-02-15 13:07 UTC, SebastienCozeDev commented on pod/main/templates/block/slider.html
Si je ne trompe pas, l'indentation est actuellement de 4 espaces. Je pense qu'il serait préférable de la mettre à 2

2024-02-15 13:42 UTC, Badatos commented
Y'a toujours un conflit :/

2024-02-15 13:59 UTC, Badatos commented
GG, plus de conflits :D

2024-02-15 14:30 UTC, Badatos commented
GG, plus de conflits ! ;)

2024-02-15 15:03 UTC, Badatos requested changes

2024-02-15 15:03 UTC, Badatos commented on pod/main/templates/block/multi_carousel.html
> +                                        <img src="{{ element.get_thumbnail_url }}" class="img-fluid" alt="thumbnail">
virer tous les alt="thumbnail" répétitifs.
Remplacer par `alt=""` pour les images décoratives.

2024-02-15 15:03 UTC, Badatos commented on pod/main/templates/block/multi_carousel.html
> +                <span class="visually-hidden">Next</span>
Traduire Previous et Next

2024-02-15 15:03 UTC, Badatos commented on pod/main/templates/block/multi_carousel.html
> +        $('#carousel_{{ container.slug }}_{{ uniq_id }}').ready(function () {
Remplacer tous le jquery par du vanilla JS

2024-02-15 15:29 UTC, vsabatie commented on pod/main/templates/block/multi_carousel.html
> +        $('#carousel_{{ container.slug }}_{{ uniq_id }}').ready(function () {
Je veux bien un petit coup de main sur ce coup là car ça ne fonctionne plus correctement lorsque j'essaye de traduire

2024-02-15 15:39 UTC, Badatos commented on pod/main/templates/block/multi_carousel.html
> +        $('#carousel_{{ container.slug }}_{{ uniq_id }}').ready(function () {
Il va falloir une doc de fonctionnement. je vois comment ajouter un bloc via l'admin, mais pas comment les afficher. o_O

2024-02-15 15:48 UTC, Badatos commented on pod/main/templates/block/carousel.html
> +						aria-label="Vidéo {{ forloop.counter0 }}"></button>
remplacer le "aria-label" par un "title", et traduire le texte.

2024-02-15 15:50 UTC, vsabatie commented on pod/main/templates/block/slider.html
Merci

2024-02-15 15:59 UTC, Badatos commented on pod/main/models.py
> +        default=True,
mettre auto_slide par défaut à False (il est préférable pour l'accessibilité d'éviter d'avoir des élements qui bougent sans action de l'utilisateur

2024-02-15 16:16 UTC, Badatos commented on pod/main/static/css/block.css
> +    border: 3px solid #fff !important;
retirer le "!important" et ajouter le style suivant pour avoir un retour au focus :
```
.edito-carousel .carousel-indicators button:hover,
.edito-carousel .carousel-indicators button:focus {
  border-color: var(--pod-primary);
  opacity:1;
}
```

2024-02-26 10:28 UTC, AymericJak requested changes
Il reste à fixer les remarques d'Olivier ainsi que mes remarques précédentes ;)

2024-02-26 12:02 UTC, SebastienCozeDev requested changes
Rien à dire de mon côté au niveau code. Il reste à fixer les remarques d'Olivier, d'Aymeric, ainsi que mes remarques précédentes

2024-03-28 20:03 UTC, closed without merging