[WIP] Récupération du login pour l'authentification par OPENID
EsupPortail/Esup-Pod pull request #1061
Opened 2024-02-23 08:17 UTC by FBrosset

Ajout du login

Before sending your pull request, make sure the following are done :

* [ ] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [ ] Your PR targets the `develop` branch.
* [ ] The title of your PR starts with `[WIP]` or `[DONE]`.

2024-02-23 10:27 UTC, ptitloup commented
Bojour et merci pour cette contribution, si elle est terminée, merci de la passer en DONE

2024-02-23 10:28 UTC, ptitloup approved these changes
ok pour moi mais à tester

2024-02-23 11:07 UTC, Badatos requested changes

2024-02-23 11:07 UTC, Badatos commented on pod/authentication/backends.py
> +OIDC_CLAIM_PREFERRED_USERNAME = getattr(settings, "OIDC_CLAIM_PREFERRED_USERNAME", "preferred_username")
Il faudrait ajouter ce paramètre dans configuration.json pour génération automatique de la doc.

2024-02-26 07:10 UTC, FBrosset commented on pod/authentication/backends.py
> +OIDC_CLAIM_PREFERRED_USERNAME = getattr(settings, "OIDC_CLAIM_PREFERRED_USERNAME", "preferred_username")
Bonjour,

Pour info la valeur "preferred_username" dépend du mappage de l'attribut dans la configuration du client KeyCloak

2024-02-26 10:19 UTC, FBrosset commented on pod/authentication/backends.py
> +OIDC_CLAIM_PREFERRED_USERNAME = getattr(settings, "OIDC_CLAIM_PREFERRED_USERNAME", "preferred_username")
Et où se trouve le fichier json s'il te plait ?

2024-02-26 10:30 UTC, Badatos commented on pod/authentication/backends.py
> +OIDC_CLAIM_PREFERRED_USERNAME = getattr(settings, "OIDC_CLAIM_PREFERRED_USERNAME", "preferred_username")
pod/main/configuration.json

2024-03-01 13:16 UTC, Badatos approved these changes
Merci pour la doc ;)

2024-03-01 14:55 UTC, merged