[WIP] add coveralls in pod-encoding action
EsupPortail/Esup-Pod pull request #1067
Opened 2024-03-05 15:29 UTC by ptitloup

Before sending your pull request, make sure the following are done :

* [X] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [X] Your PR targets the `develop` branch.
* [X] The title of your PR starts with `[WIP]` or `[DONE]`.

2024-03-11 11:13 UTC, ptitloup reviewed
Il manque pod_main.yml

2024-03-11 16:10 UTC, Badatos approved these changes
quelques questions mineures, sinon code Ok pour moi ;)

2024-03-11 16:10 UTC, Badatos commented on dockerfile-dev-with-volumes/pa11y-ci/config.json
> +}
manque une ligne vide en fin de fichier

2024-03-11 16:10 UTC, Badatos commented on dockerfile-dev-with-volumes/pa11y-ci/config_mobile.json
> +}
manque une ligne vide en fin de fichier

2024-03-11 16:15 UTC, Badatos commented
Attention, j'ai l'impression qu'n ayant retiré le "Check for pa11y failures" , s'il y a des erreurs A11y, elle seront transparentes et on ne les verra plus :/
```
- name: Check for pa11y failures.
         if: contains(steps.pa11y_output.outputs.content, 'Errors in http://')
         run: |
           echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
           exit 1
```

2024-03-11 16:20 UTC, Badatos requested changes
mettre à jour actions/setup-node@v3 en actions/setup-node@v4

2024-03-11 16:20 UTC, Badatos commented on .github/workflows/pod_dev.yml
> +          node-version: 19
Attention :
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

2024-03-12 09:15 UTC, ptitloup commented
> Attention, j'ai l'impression qu'en ayant retiré le "Check for pa11y failures" , s'il y a des erreurs A11y, elle seront transparentes et on ne les verra plus :/
> 
> ```
> - name: Check for pa11y failures.
>          if: contains(steps.pa11y_output.outputs.content, 'Errors in http://')
>          run: |
>            echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
>            exit 1
> ```

Nope, s'il y a des erreurs, pa11y-ci sort avec le code 2 ce qui stop les tests

2024-03-12 09:19 UTC, ptitloup commented on .github/workflows/pod_dev.yml
> +          node-version: 19
comprend pas, je peux laisser 19 ou c'est mieux de mettre 20 ?

2024-03-12 09:53 UTC, LoicBonavent approved these changes
Pour ma part, après les points remontés par Olivier et modifiés, cela me semble bon.
Après, c'est sûr qu'un max-complexity plus élevé serait top :)

2024-03-12 10:07 UTC, Badatos approved these changes

2024-03-12 10:41 UTC, merged