[DONE] Correctly counts the number of sub-theme videos in a theme
EsupPortail/Esup-Pod pull request #1068
Opened 2024-03-06 11:24 UTC by LoicBonavent

Correctly counts the number of sub-theme videos in a theme, and displays different messages according to channel / theme / sub-theme level.
See issue #1007

2024-03-06 11:36 UTC, Badatos approved these changes

2024-03-06 13:08 UTC, AymericJak requested changes
2 petites améliorations, et c'est parfait pour moi :)

2024-03-06 13:08 UTC, AymericJak commented on pod/video/views.py
> +    """Get theme children as a list, and not a Queryset."""
Il faudrait ajouter les types (paramètres et retour)

Et les écrire dans la doc :)

2024-03-07 09:34 UTC, LoicBonavent commented on pod/video/views.py
> +            videos_list = videos_list.filter(theme__in=list_theme)
C'est vrai :) Fait

2024-03-07 09:35 UTC, LoicBonavent commented on pod/video/views.py
> +    """Get theme children as a list, and not a Queryset."""
C'est fait aussi

2024-03-07 09:35 UTC, AymericJak approved these changes
Super merci !

2024-03-07 09:35 UTC, LoicBonavent commented on pod/video/views.py
> +    """Get theme children as a list, and not a Queryset."""
J'ai également modifier la nouvelle fonction pour que cela soit sérializable en sortie, ce qui empêchait les tests de passer.

2024-03-08 10:26 UTC, SebastienCozeDev approved these changes
Parfait pour moi au niveau du code. Merci pour cette contribution !

2024-03-08 10:39 UTC, merged