[DONE] Feature add personal meeting room
EsupPortail/Esup-Pod pull request #1073
Opened 2024-03-08 16:01 UTC by LoicBonavent

New functionality to manage a personal meeting room in the meetings module.

 - Addition of is_personal field in base
 - Creation of a personal meeting room, for each user, on 1st connection to the meetings module.
 - This room always appears in 1st position
 - This room cannot be deleted
 - This room is permanent; there is no date management (neither when modifying, nor when sending an invitation email).

Minor bug fixes in the meetings module (voice bridge no., rights, etc.)

2024-03-08 16:02 UTC, LoicBonavent commented
Gère l'Issue #1049

2024-03-12 10:17 UTC, Badatos requested changes

2024-03-12 10:17 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +"Il s’agit de la salle de réunion personnelle de “%(full_name)s”, "
Utilisez les guillemets français : « %(full_name)s » (avec espaces insécables)

2024-03-12 10:17 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +"        <p>%(owner)s vous invite à la réunion <b>%(meeting_title)s</b>.</p>\n"
utiliser "strong" plutôt que "b" (le premier donne une info sémantique utile en accessibilité, alors que le second ne fait que du gras visuel.)

2024-03-12 10:17 UTC, Badatos commented on pod/meeting/templates/meeting/add_or_edit.html
> +    time_fieldset.style.display = 'none';
est-il possible d'utiliser la classe "d-none" plutot que le style inline ?

2024-03-12 10:17 UTC, Badatos commented on pod/meeting/views.py
> +                <p>Regards</p>
strong plutot que `<b>`

2024-03-12 11:08 UTC, LoicBonavent commented on pod/locale/fr/LC_MESSAGES/django.po
> +"Il s’agit de la salle de réunion personnelle de “%(full_name)s”, "
Fait

2024-03-12 11:08 UTC, LoicBonavent commented on pod/locale/fr/LC_MESSAGES/django.po
> +"        <p>%(owner)s vous invite à la réunion <b>%(meeting_title)s</b>.</p>\n"
Fait

2024-03-12 11:09 UTC, LoicBonavent commented on pod/meeting/templates/meeting/add_or_edit.html
> +    time_fieldset.style.display = 'none';
Bien sûr :), fait

2024-03-12 11:09 UTC, LoicBonavent commented on pod/meeting/views.py
> +                <p>Regards</p>
Fait

2024-03-12 11:15 UTC, Badatos approved these changes
Merci pour les corrections ;)

2024-03-13 10:13 UTC, ptitloup requested changes

2024-03-13 10:13 UTC, ptitloup commented on pod/meeting/templates/meeting/link_meeting.html
> +  {% if not meeting.is_personal or meeting.owner == request.user %}
l'edition des reunions non personnelle dont oni est le prop additionnel est egalement possible. Il manque ce cas

2024-03-13 10:36 UTC, LoicBonavent commented on pod/meeting/forms.py
> +            self.fields[field].widget = forms.HiddenInput()
Avec remove_field, cela ne fonctionne pas (du moins pour start...), d'où le fait de les cacher.

2024-03-13 10:38 UTC, ptitloup commented on pod/meeting/forms.py
> +            self.fields[field].widget = forms.HiddenInput()
je crois qu'il faut les retirer dans le init form pour que ca fonctionne

2024-03-13 10:39 UTC, LoicBonavent commented on pod/meeting/templates/meeting/link_meeting.html
> +  {% if not meeting.is_personal or meeting.owner == request.user %}
Oui, ce code bloque seulement l'édition d'une salle de réunion personnelle d'un autre user. On peut très bien éditer une réunion non personnelle d'un autre usager.

2024-03-13 10:41 UTC, LoicBonavent commented on pod/meeting/models.py
> +        default=False,
Fait

2024-03-13 10:45 UTC, LoicBonavent commented on pod/meeting/forms.py
> +            self.fields[field].widget = forms.HiddenInput()
Le code est lancé depuis __init__ de la classe MeetingForm; c'est pas le bon emplacement ?

2024-03-13 13:39 UTC, ptitloup approved these changes
ok pour moi, des petits details mais ca le fait pour une première version. merci

2024-03-13 13:39 UTC, ptitloup commented on pod/meeting/forms.py
> +            self.fields[field].widget = forms.HiddenInput()
si pourtant mais je comprends pas pourquoi ca veut pas ! En tout cas, il faudra voir un jour pour les mettre en remove plutot qu'en hidden

2024-03-14 10:12 UTC, merged