[DONE] Liveevent unmute
EsupPortail/Esup-Pod pull request #1075
Opened 2024-03-12 10:50 UTC by mattbild

- Enable sound on live event (live stream + video on hold)
- Wait 1.5sec before playing video on hold after page load

2024-03-12 13:11 UTC, Badatos requested changes

2024-03-12 13:11 UTC, Badatos commented on pod/live/templates/live/event-script.html
> +      pvp_options = options;
il faut un "let" pour déclarer cette nouvelle variable dont la portée est le bloc courant.

2024-03-12 13:11 UTC, Badatos commented on pod/live/templates/live/event-script.html
> +        pvohp_options = options;
il faut un "let" pour déclarer cette nouvelle variable dont la portée est le bloc courant.

2024-03-12 14:43 UTC, mattbild commented on pod/live/templates/live/event-script.html
> +      pvp_options = options;
très juste

2024-03-12 14:43 UTC, mattbild commented on pod/live/templates/live/event-script.html
> +        pvohp_options = options;
fait

2024-03-12 14:46 UTC, ptitloup requested changes
juste quelques question par curiosité

2024-03-12 14:46 UTC, ptitloup commented on pod/live/templates/live/event-script.html
> +      let pvp_options = options;
Je suppose que de créer une nouvelle variable a un but précis, peux-tu nous le dire stp ?

2024-03-12 14:46 UTC, ptitloup commented on pod/live/templates/live/event-script.html
> +        let pvohp_options = options;
même question ! :)

2024-03-12 14:46 UTC, ptitloup commented on pod/live/templates/live/event-script.html
> +            // timeout pour éviter que la video d'attente démarre pour moins d'une sec et demie
Pourquoi 1second et demi ? A quoi correspond ce temps ?

2024-03-12 15:29 UTC, Badatos approved these changes

2024-03-13 08:15 UTC, mattbild commented on pod/live/templates/live/event-script.html
> +      let pvp_options = options;
C'est vrai que l'intérêt est limité.
Quand j'avais testé en modifiant directement les options du player, ça ne fonctionnait pas. En restant ce matin, il semble que j'avais mal vu /fait.
Je corrige

2024-03-13 08:19 UTC, mattbild commented on pod/live/templates/live/event-script.html
> +            // timeout pour éviter que la video d'attente démarre pour moins d'une sec et demie
Je pense qu'ajouter un délais avant de lancer la vidéo d'attente est nécessaire, sinon le vidéo démarre avec le son et elle est remplacée très vite par le flux dès qu'il est disponible.
En revanche, le 1.5s est complétement aléatoire.
J'aurais pu mettre 1s ou possiblement moins mais pour éviter ce lecture inutile j'ai mis 1.5s. J'imagine que c'est un temps acceptable avant de qu'une vidéo se lance quand on arrive sur une page.
Dis moi ce que tu en penses

2024-03-13 10:28 UTC, ptitloup approved these changes
ok pour moi

2024-03-13 10:28 UTC, merged