[DONE] Add a submit button on the add video page
EsupPortail/Esup-Pod pull request #1088
Opened 2024-04-03 15:28 UTC by Badatos

The submit button let user choose if he want to upload or not, and have more time to choose transcription lang
+ Add a required checkbox for legal notice

2024-04-04 07:44 UTC, ptitloup reviewed
ok pour moi niveau code, à tester avant d'approuver

2024-04-05 12:10 UTC, ptitloup approved these changes
ok pour moi (le script php sera supprimé dans les prochaines version (tout comme l'ancienne app bbb)

2024-04-05 12:31 UTC, Badatos commented
> ok pour moi (le script php sera supprimé dans les prochaines version (tout comme l'ancienne app bbb)

Ca fera 900 lignes de moins, ca va nous augmenter la couverture ^^

2024-04-08 08:05 UTC, SebastienCozeDev requested changes

2024-04-08 08:42 UTC, Badatos commented on pod/main/configuration.json
> +                                    "À moins que votre site ne doive être disponible sur des connexions SSL et non SSL,",
Bien vu, Seb ! Je corrige

2024-04-08 08:43 UTC, Badatos commented on pod/main/static/css/pod.css
> +/* Drag over styles */
non, parce que c'est une sous-entité de `/** Upload page **/`

2024-04-08 08:49 UTC, Badatos commented on pod/video/templates/videos/add_video.html
> +      $(this).is(':checked');
J'avoue que je ne comprend pas à quoi sert cette ligne en fait. Est-ce que tu vois un intéret à tester si this est "checked" si on en fait rien ? Je loupe un truc quelque-part ?

2024-04-08 14:25 UTC, Badatos commented on pod/video/templates/videos/add_video.html
> +      $(this).is(':checked');
bon ben je l'ai mis en commentaire, ca semble toujours fonctionner ^^

2024-04-09 07:18 UTC, SebastienCozeDev approved these changes
C'est bon pour moi au niveau du code. Merci pour cette contribution !

2024-04-09 07:31 UTC, merged