[DONE] Feature: Webinar management in the meetings module
EsupPortail/Esup-Pod pull request #1092
Opened 2024-04-08 15:04 UTC by LoicBonavent

Add webinar management in the meetings module:
 - Add webinar parameters: USE_MEETING_WEBINAR, MEETING_WEBINAR_SIPMEDIAGW_URL, MEETING_WEBINAR_SIPMEDIAGW_TOKEN, MEETING_WEBINAR_FIELDS, MEETING_WEBINAR_AFFILIATION, MEETING_WEBINAR_GROUP_ADMIN
 - Manage webinars fields (is_webinar, show_chat, enable_chat), classes (Livestream and Ingester) and rules
 - Manage SIPMediaGW API to start / stop / toggle and send a message to this RTMP Gateway
 - Add actions buttons to manage a webinar (restart a live, stop a live, stop webinar (meeting and live))
 - Add REST meeting views

2024-04-08 15:39 UTC, Badatos requested changes

2024-04-08 15:39 UTC, Badatos commented on pod/live/templates/live/event-script.html
> +              returnElement.classList.add('alert-info');
tu peux simplifier ainsi :
`returnElement.classList.add('alert', 'alert-info');`
(idem en dessous)

2024-04-08 15:39 UTC, Badatos commented on pod/live/templates/live/event-script.html
> +              returnElement.style.display = "none";
y'a moyen d'utiliser la classe "d-none" à la place ?

2024-04-08 15:39 UTC, Badatos commented on pod/live/templates/meeting/meeting_live_form.html
> +            <div class="form-group">
indenter les templates avec 2 espaces plutot que 4 pour plus de lisibilité

2024-04-08 15:39 UTC, Badatos commented on pod/live/templates/meeting/meeting_live_form.html
> +                <textarea name="message" rows="2" cols="70" maxlength="100" class="form-control" id="message"></textarea>
il manque un label à ce textarea

2024-04-08 15:39 UTC, Badatos commented on pod/live/templates/meeting/meeting_live_form.html
> +<div id="container-fluid" class="tab-pane fade active show pod-live-info"></div>
ajouter une ligne vide en fin de fichier

2024-04-08 15:39 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "Souhaitez-vous montrer le chat public en direct ?"
"tchat" n'est pas une erreur. Le mot est dans le larousse : https://www.larousse.fr/dictionnaires/francais/chat/14895
Il évite d'ailleurs toute confusion avec un éventuel minou.

2024-04-08 15:39 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +"N'oubliez pas de ne pas utiliser les <b>salles privées</b> dans ce cas."
évitez les doubles négations. Préférez ici "Rappelez-vous de ne pas..."

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/static/css/meeting.css
> +}
une ligne vide en fin de fichier

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +    </div>
ne pas laisser d'espace en fin de chaine i18n

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +      </p>
préférez la balise "em" à "i".

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +      </p>
préférez la balise strong à "p"

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +          <li>{% trans "Remember to not use <b>breakout rooms</b> in this case." %}</li>
idem (strong)

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/views.py
> +    """Manage a webinar is possible for the user?
la premiere ligne d'une pydoc doit terminer par un point, pas un ?

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/views.py
> +    """End a meeting is allowed for the user?"""
idem

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/webinar.py
> +            "stop_webinar_livestream %s : %s" % (
pas d'espace avant les double points en anglais

2024-04-08 15:39 UTC, Badatos commented on pod/meeting/webinar_utils.py
> +        "Other webinars : <b>%s</b>"
pas d'espace avant les :

2024-04-09 07:48 UTC, LoicBonavent commented on pod/live/templates/live/event-script.html
> +              returnElement.style.display = "none";
Fait

2024-04-09 07:48 UTC, LoicBonavent commented on pod/live/templates/meeting/meeting_live_form.html
> +            <div class="form-group">
Fait (désolé, reprise de vieux code)

2024-04-09 07:48 UTC, LoicBonavent commented on pod/live/templates/meeting/meeting_live_form.html
> +                <textarea name="message" rows="2" cols="70" maxlength="100" class="form-control" id="message"></textarea>
Ajouté

2024-04-09 07:48 UTC, LoicBonavent commented on pod/live/templates/meeting/meeting_live_form.html
> +<div id="container-fluid" class="tab-pane fade active show pod-live-info"></div>
Fait

2024-04-09 07:51 UTC, LoicBonavent commented on pod/locale/fr/LC_MESSAGES/django.po
> +"N'oubliez pas de ne pas utiliser les <b>salles privées</b> dans ce cas."
Fait, bien vu

2024-04-09 07:51 UTC, LoicBonavent commented on pod/meeting/static/css/meeting.css
> +}
Ok

2024-04-09 07:51 UTC, LoicBonavent commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +    </div>
Ok

2024-04-09 07:51 UTC, LoicBonavent commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +      </p>
Fait

2024-04-09 07:51 UTC, LoicBonavent commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +      </p>
ok, plus de b, mais des strong

2024-04-09 07:52 UTC, LoicBonavent commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +          <li>{% trans "Remember to not use <b>breakout rooms</b> in this case." %}</li>
Yes

2024-04-09 07:52 UTC, LoicBonavent commented on pod/meeting/views.py
> +    """Manage a webinar is possible for the user?
ok

2024-04-09 07:52 UTC, LoicBonavent commented on pod/meeting/views.py
> +    """End a meeting is allowed for the user?"""
ok

2024-04-09 07:52 UTC, LoicBonavent commented on pod/meeting/webinar.py
> +            "stop_webinar_livestream %s : %s" % (
yes

2024-04-09 07:52 UTC, LoicBonavent commented on pod/meeting/webinar_utils.py
> +        "Other webinars : <b>%s</b>"
yes

2024-04-09 09:31 UTC, Badatos approved these changes
Un dernier changement mineur sinon OK pour moi niveau Code. Merci pour les modifs ;)

2024-04-09 09:31 UTC, Badatos commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +          <li>{% trans "Please do not <strong>end the meeting</strong> before it is actually over." %}</li>
Une balise P ne peut pas contenir de balise OL. Il faut donc finir le P avant.

2024-04-09 09:49 UTC, LoicBonavent commented on pod/meeting/templates/meeting/filter_aside_meeting.html
> +          <li>{% trans "Please do not <strong>end the meeting</strong> before it is actually over." %}</li>
OK, fait. Thx

2024-04-10 08:31 UTC, SebastienCozeDev requested changes

2024-04-10 08:31 UTC, SebastienCozeDev commented on pod/meeting/urls.py
> +        ),
Pourquoi ne pas utiliser `path` ?

2024-04-10 08:40 UTC, LoicBonavent commented on pod/meeting/urls.py
> +        ),
En fait, j'avais utilisé path, mais, de mémoire, cela m'avait provoqué une erreur en lien avec le format du paramètre, ou de ce style.
Alors je suis reparti de l'ancien live_publish_chat qui existe pour l'ancien module BBB, avec une URL et non un path, mais qui fonctionne.

2024-04-10 08:46 UTC, SebastienCozeDev approved these changes
C'est bon pour moi niveau code. Merci pour cette contribution !

2024-04-12 11:32 UTC, merged