[WIP] Add settings and fix bugs
EsupPortail/Esup-Pod pull request #1098
Opened 2024-04-11 14:28 UTC by SebastienCozeDev

Before sending your pull request, make sure the following are done :

* [ ] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [ ] Your PR targets the `develop` branch.
* [ ] The title of your PR starts with `[WIP]` or `[DONE]`.

2024-04-12 11:56 UTC, Badatos approved these changes
Ok pour moi niveau Code

2024-04-12 13:18 UTC, ptitloup requested changes
un petit changement et une remarque générale, les varibale passées dans le context processor sont chargées dans le context request-response et donc seules les variables utilisez dans les templates doivent être chargées our ne pas alourdir le context

2024-04-12 13:18 UTC, ptitloup commented on pod/playlist/context_processors.py
> +RESTRICT_PROMOTED_PLAYLIST_ACCESS_TO_STAFF_ONLY = getattr(
sauf erreur de ma part, cette variable n'est pas utilisée dans les templates et donc ne doit pas figurer dans ce fichier.

2024-04-12 13:34 UTC, LoicBonavent approved these changes
Nickel côté code. Il y a juste la remarque de Nicolas (perso, j'aurais fait comme toi :) )
Merci

2024-04-12 13:37 UTC, ptitloup approved these changes
ok pour moi merci !

2024-04-12 13:55 UTC, ptitloup approved these changes
ok merci !

2024-04-12 14:00 UTC, Badatos commented on pod/playlist/models.py
>      )
Attention,, il faut aussi changer le help_text en conséquence (ainsi que la traduction).
Au passage, est-il possible de mettre "max_length" en variable dans la chaine, de manière à ne pas avoir à changer les traductions quand on change la valeur ?

2024-04-12 14:03 UTC, ptitloup commented on pod/playlist/models.py
>      )
on pourrait déclarer un maxlength en globale au fichier et l'utiliser dans tous les champs ou cela est nécessaire (attention à certains slugqui doivent contenir au min 5 caractères de plus)

2024-04-15 08:42 UTC, ptitloup approved these changes

2024-04-15 10:04 UTC, merged