[DONE] Fanfounet/update access tokens
EsupPortail/Esup-Pod pull request #1102
Opened 2024-04-15 08:07 UTC by fanfounet

Before sending your pull request, make sure the following are done :

* [x] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [x] Your PR targets the `develop` branch.
* [x] The title of your PR starts with `[WIP]` or `[DONE]`.
* [x] Add field token name
* [x] Add aside help
* [x] unit test

2024-04-23 07:42 UTC, AymericJak requested changes

2024-04-23 07:42 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +
À corriger ;)

+ enlever le fuzzy et #| ...

2024-04-23 07:42 UTC, AymericJak commented on pod/video/models.py
> +    name = models.CharField(_("token name"), max_length=100, blank=True, default=_("change me"))
Peux tu spécifier comme suit : `verbose_name=_("Token name"), ...`

2024-05-15 07:15 UTC, AymericJak approved these changes
RAS de mon côté.
Merci !

2024-05-15 07:54 UTC, Badatos approved these changes
une toute petite remarque, sinon Ok pour moi ;)

2024-05-15 08:59 UTC, merged