Opencast with Extron
EsupPortail/Esup-Pod pull request #1104
Opened 2024-04-16 07:05 UTC by mattbild

## Ajout la possibilité de récupérer l'enregistrement d'un live sur matériel SMP en utilisant le module Opencast (testé_ sur 351 uniquement)

## Paramétrage nécessaire :

- ### Côté Pod
  - Paramétrer un Diffuser (Broadcaster) avec l'implémentation SMP et la configuration du boitier pour piloter l'enregistrement : 
{
"server_url":"http://xxx.xxx.xx.x", "sftp_port":"", "user":"xx", "password":"xx", "record_dir_path":"/recordings", 
"rtmp_streamer_id":"x" , "use_opencast":"**true**"
}
  - Ajouter un Enregistreur (Recorder) dans l'admin de Pod avec l'Ip du SMP (définir un Salt, Login, Password)

- ### Côté SMP
  - Activer (ou installer) le plugin Opencast depuis l'interface de gestion du matériel (Configuration -> Advanced Features)
  - Paramétrer la publication vers le opencast de Pod (Scheduled Events -> Publish Settings -> Active Profiles )
 Opencast Server Address = celle de Pod
Username et Password  = ceux définis dans le Recorder
Tester la connexion pour valider les paramètres 
  
![smp_publish_config](https://github.com/EsupPortail/Esup-Pod/assets/34771705/856590c6-ae97-485f-a94d-ba398815206a)

2024-04-16 08:13 UTC, Badatos requested changes
Merci pour ce code :)
Quelques remarques mineures.

2024-04-16 08:13 UTC, Badatos commented on pod/recorder/tests/test_views.py
> +        print(" --->  test_digest_services_available of StudioDigestViews: OK!")
Ajouter des pydocs à chaque fonction

2024-04-16 08:13 UTC, Badatos commented on pod/recorder/utils.py
> +    return compute_digest(
manque une petite pydoc

2024-04-16 08:13 UTC, Badatos commented on pod/recorder/views.py
> +            except Exception as e:
Est-ce qu'on peut préciser l'exception ?

2024-04-16 08:13 UTC, Badatos commented on pod/recorder/views.py
> +def studio_static(request, file):
Manque des pydocs

2024-04-16 08:13 UTC, Badatos commented on pod/recorder/views.py
> +    return open_studio_static(request, file)
plusieurs pydocs à ajouter

2024-04-16 08:13 UTC, Badatos commented on pod/recorder/views.py
> +                    "memory": 2082471936,
Comment est définie la valeur de memory ? Le préciser en commentaire.

2024-04-16 08:13 UTC, Badatos commented on pod/recorder/views.py
> +                    "title": "admin",
Pourquoi une date en 2023 ? Pourquoi pas la date du jour ?

2024-04-16 08:13 UTC, Badatos commented on pod/recorder/views.py
> +                    "error_state_trigger": 0,
Pourquoi ces dates ?

2024-04-16 10:13 UTC, mattbild commented on pod/recorder/views.py
> +            except Exception as e:
encore mieux on peut le supprimer.
Il y a avait un `# TODO remove try catch` à côté duquel j'étais passé.

2024-04-16 12:21 UTC, mattbild commented on pod/recorder/views.py
> +                    "memory": 2082471936,
Je ne sais pas vraiment comment on peut récupérer une 'vraie' valeur.
J'ai copié le retour de la doc de Opencast :
https://stable.opencast.org/docs.html?path=/services
et particulièrement l'exemple :
https://stable.opencast.org/services/hosts.json

Le paramètre est visiblement nécessaire mais je ne sais pas s'il est exploité, ni comment, dans le module opencast du SMP.

2024-04-16 12:57 UTC, Badatos commented on pod/recorder/views.py
> +                    "memory": 2082471936,
ptet ajouter un commentaire `# cf https://stable.opencast.org/docs.html?path=/services & 
https://stable.opencast.org/services/hosts.json` ?

2024-04-16 14:54 UTC, mattbild commented on pod/recorder/views.py
> +                    "title": "admin",
modifié par la date de la veille

2024-04-16 14:55 UTC, mattbild commented on pod/recorder/views.py
> +                    "error_state_trigger": 0,
modifié par la date de la veille

2024-04-16 14:56 UTC, mattbild commented on pod/recorder/tests/test_utils.py
> +            type=r_type,
modifié en 127.1.1.1 car elle ne sert à rien de précis

2024-04-16 15:30 UTC, Badatos approved these changes
Merci pour ce code très propre et bien documenté, J'approuve ;)

2024-04-17 09:31 UTC, fanfounet commented
### Réalisation de tests fonctionnels

- Mise en place du recorder OK (Attention en utilisant POD de test sous docker en mode réseau NAT, on ne voit pas le SMP avec son IP mais avec celle du NAT du Docker)
- Mettre USE_OPENCAST_STUDIO à True (Sachant qu'il n'y a pas besoin d'installer le Studio, uniquement créer un recorder Studio => A mettre dans la documentation)
- Créer le recorder Studio OK
- Création d'un événement (mode manuel)
Lancer le stream avec le bouton (OK)
Démarrer un enregistrement (OK)
Arrêter un enregistrement (OK)
Création de l'enregistrement (OK)
Démarrer un nouvel enregistrement dans la même session LIVE (OK)
Arrêter un nouvel enregistrement dans la même session LIVE (OK)
Création de l'enregistrement (OK)
Si event brouillon => Enregistrement brouillon
Si event public => Enregistrement public
Lien des enregistrements à l'événement (OK)

- EVENT_ACTIVE_AUTO_START à True pour faire apparaitre la possibilité de mettre l'enregistrement en auto
- Création d'un événement (mode auto)
- Lancer le cron (checkLiveStartStop)
- Stream démarré au début de l'événement (OK)
- Enregistrement démarré au début de l'événement (OK)
- Stream arrêté à la fin de l'événement (OK)
- Enregistrement arrêté à la fin de l'événement (OK)
- Création de l'enregistrement (OK)
- Enregistrement lié à l'événement (NON OK)

Tests additionnels
- Démarrer et arrêter un enregistrement du SMP
Création d'un enregistrement avec un titre par défaut (nom du SMP et date), mode brouillon et le user par défaut

Suggestions / Questions
- Si pas besoin de mettre en place le OPENCAST Studio peut etre choisir un autre settings que USE_OPENCAST_STUDIO
- Possibilité de forcer ou cocher par défaut l'enregistrement auto de l'événement
- dans le checkLiveStartStop démarrer et arrêter le stream même en mode non auto
- La création d'un enregistrement à partir du SMP est intéressante mais qui devrait peut être suivre (ou avoir le choix) la philosophie du dépôt FTP et donc revendication

2024-04-29 14:38 UTC, merged