[WIP] Code improvements
EsupPortail/Esup-Pod pull request #1121
Opened 2024-05-06 15:22 UTC by Badatos

QoC:
* replace some == by === in JS
* correct some double quotes in shell scripts
* Add some missing types in .py
* Replace `len(xxx.sites.all())` by `xxx.sites.count()`
* Remove unused vars in Php

2024-05-15 09:55 UTC, ptitloup commented
pourquoi une telle diminution du taux de couverture ? Est-ce ok pour une review ?

2024-05-15 10:24 UTC, Badatos commented
> pourquoi une telle diminution du taux de couverture ? Est-ce ok pour une review ?

Je voulais en parler sur Rocket justement ;)

OK pour la review en tout cas ^^.

2024-05-15 13:38 UTC, Badatos commented
Et voila : sans le `branch=True`, le calcul de la couverture est de suite plus flateur ^^

COVERAGE: 71.36% (+0.1%) FROM 71.229%

2024-05-15 13:46 UTC, ptitloup requested changes
faut pas faire desz PR aussi longue ! ok pour moi juste une petite modif js a apporter

2024-05-15 13:46 UTC, ptitloup commented on pod/playlist/static/playlist/js/add-or-edit.js
> +        helpText.textContent = gettext('<b>Public:</b> the playlist can be accessed by anyone.');
Attention, il me semble qu'il faille laisser innerHTML pour que les balises b puissent être prise en compte

2024-05-15 13:46 UTC, ptitloup commented on pod/playlist/static/playlist/js/add-or-edit.js
> +        helpText.textContent = gettext('<b>Password-protected:</b> the playlist can be accessed by anyone with the appropriate link and password.');
idem

2024-05-15 13:46 UTC, ptitloup commented on pod/playlist/static/playlist/js/add-or-edit.js
> +        helpText.textContent = gettext('<b>Private:</b> only you have access to this playlist.');
idem

2024-05-15 13:46 UTC, ptitloup commented on pod/video/management/commands/check_obsolete_videos.py
> +    def get_video_archived_deleted_treatment(self) -> tuple:  # tuple[dict, dict]
add comment to python 3.8 compatibility

2024-05-15 13:46 UTC, ptitloup commented on scripts/bbb-pod-live/bbb-pod-live.php
> +/**
Les scripts et la partie bbb vont être amené à disparaitre.. il ne faut pas passer trop de temps la dessus

2024-05-16 07:30 UTC, Badatos commented on pod/playlist/static/playlist/js/add-or-edit.js
> +        helpText.textContent = gettext('<b>Public:</b> the playlist can be accessed by anyone.');
tout à fait, bien vu en effet !

2024-05-16 13:03 UTC, ptitloup approved these changes
Ok pour moi Merci !

2024-05-17 07:38 UTC, pampletousse commented on pod/completion/static/js/completion.js
> +    var file_name = file_abs_path.match(/([\w\d_-]+)(\.vtt)/)[1].toLowerCase();
Changement voulu du regex ?

2024-05-17 07:39 UTC, Badatos commented on pod/completion/static/js/completion.js
> +    var file_name = file_abs_path.match(/([\w\d_-]+)(\.vtt)/)[1].toLowerCase();
Oui. Le caractere `-` n'a pas besoin d'être escapé ici.

2024-05-17 07:43 UTC, pampletousse commented on pod/enrichment/templates/enrichment/edit_enrichment.html
> -    /*** For the Cancel button ***/
Pas nécessaire ?

2024-05-17 07:47 UTC, pampletousse commented on pod/main/static/js/main.js
> +if (typeof ownerBoxNavBar === "undefined") {
Le type doit rester undefined sans quote non ? Sinon ça devient une string et la condition n'est plus la même

2024-05-17 07:49 UTC, pampletousse commented on pod/playlist/static/playlist/js/playlist-player.js
> +if (typeof videos === "undefined") {
Pareil, attention au undefined qui devient une string (voulu ?)

2024-05-17 07:49 UTC, Badatos commented on pod/enrichment/templates/enrichment/edit_enrichment.html
> -    /*** For the Cancel button ***/
oui en effet, je me suis rendu compte que ce code n'était jamais appelé, car supplanté par 
```
document.addEventListener("click", (e) => {
  if (e.target.id != "cancel_enrichment") return;
 ```
 dans completion.js

2024-05-17 07:51 UTC, Badatos commented on pod/main/static/js/main.js
> +if (typeof ownerBoxNavBar === "undefined") {
surtout pas. ;)
En fait, soit on fait
```js
ownerBoxNavBar === undefined
```
(ici sans quotes)

Mais si on utilise typeof les guillemets sont obligatoires :
```js
typeof ownerBoxNavBar === "undefined"
```

Sinon, il renvoit toujours false et on entre jamais dans ce cas.

2024-05-17 08:27 UTC, pampletousse commented on setup.cfg
> -exclude = .git,pod/*/migrations/*.py,test_settings.py,node_modules/*/*.py,pod/static/*.py,pod/custom/tenants/*/*.py
possible d'ajouter ./venv/* (si ça ne casse pas la commande) pour le dev en local ?

2024-05-17 08:28 UTC, pampletousse reviewed
Quelques questionnements mais globalement je pense que c'est bon

2024-05-17 08:29 UTC, pampletousse commented on pod/main/static/js/main.js
> +if (typeof ownerBoxNavBar === "undefined") {
Ah okay ! bien vu : )

2024-05-17 08:47 UTC, Badatos commented on setup.cfg
> -exclude = .git,pod/*/migrations/*.py,test_settings.py,node_modules/*/*.py,pod/static/*.py,pod/custom/tenants/*/*.py
à priori oui je ne vois pas le souci.

2024-05-17 08:50 UTC, Badatos commented on pod/main/static/js/main.js
> +if (typeof ownerBoxNavBar === "undefined") {
C'est Codacy qui l'a repéré pour moi ;)
Je le recommande : https://www.codacy.com

2024-05-17 12:38 UTC, pampletousse approved these changes

2024-05-17 12:45 UTC, merged