[WIP] Fanfounet / webtv speaker app
EsupPortail/Esup-Pod pull request #1145
Opened 2024-06-03 07:02 UTC by fanfounet

Before sending your pull request, make sure the following are done:

* [ ] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [ ] Your PR targets the `develop` branch.
* [ ] The title of your PR starts with `[WIP]` or `[DONE]`.

### ToDo
* [x] Create Speaker app
* [x] Speaker model
* [x]  Admin app
* [x] USE_SPEAKER setting
* [ ] add view in completion
* [ ] add edit speakers
* [ ] show speakers in video
* [ ] test
* [ ] langs

2024-06-14 08:48 UTC, AymericJak requested changes
Quelques remarques d'un point de vue code.
Je n'ai pas regardé les fichiers HTML.

Ensuite point de vue fonctionnel :
- Il manque le fichier `migrations/__init__.py` dans ton application. Sans cela, les migrations ne peuvent pas être prises en compte.
- Traductions manquantes, mais c'est normal, les faire à la fin est plus pratique.
- Erreur de copié / collé 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/07048e79-a912-4b60-bfa2-e72a7db0b8df)
Il n'y est pas question d'habillage ici ;)
- Quand je souhaite aller sur la page de complétion de d'une vidéo, erreur
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/68b807ca-f779-49cc-98c1-50b523a9c107)
- Pour l'ajout d'un speaker, peut être se baser sur l'ajout d'un contributeur dans la completion d'une vidéo. 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/b7f72b81-5228-4f30-bf29-f95bac9e8bc1)
Garder le principe de fieldset, et la même logique que dans les autres formulaires du site.
- Dans le cas de l'ajout de jobs, j'aurais tendance à dire que le "+" devrait être sur la derniere ligne et non sur la première. Ça fait bizarre là.
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/c54d93c0-5be2-435b-a513-1daaa4049de9)
Mais ça pourrait porter à confusion je pense aussi... 
Ou bien avoir le même principe que pour l'ajout des choix dans les questions à choix.
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/9d50e03b-6293-40af-bbea-73443fc03f79)


Mais dans le fond, est ce que les speakers ne sont pas vraiment des contributeurs ??
Y aurait il pas moyen de lier les 2 ???

2024-06-14 08:48 UTC, AymericJak commented on pod/main/configuration.json
> +                        "en": "Seaker application configuration",
Il manque un p à Seaker

2024-06-14 08:48 UTC, AymericJak commented on pod/main/templates/navbar.html
> +                <a class="nav-item nav-link" href="{% url 'speaker:speaker_management' %}"><i class="bi bi-megaphone pod-nav-link-icon mx-1" aria-hidden="true"></i>{% trans 'Speakers management' %}</
Entre le <i> et le texte, il manque un `&nbsp;`

2024-06-14 08:48 UTC, AymericJak commented on pod/speaker/forms.py
> +from django import forms
il manque la doc de début de fichier

2024-06-14 08:48 UTC, AymericJak commented on pod/speaker/models.py
> +class JobVideo(models.Model):
Une petite doc oubliée ;)

2024-06-14 08:48 UTC, AymericJak commented on pod/speaker/views.py
> +        raise PermissionDenied
Code jamais exécuté. Si c'est un superuser, on raise l'exception dans la condition du dessus

2024-06-14 08:49 UTC, AymericJak commented
Et pourquoi avoir mis `USE_SPEAKER` à False ? Plutôt qu'à true ?

2024-06-14 20:05 UTC, fanfounet commented on pod/main/templates/navbar.html
> +                <a class="nav-item nav-link" href="{% url 'speaker:speaker_management' %}"><i class="bi bi-megaphone pod-nav-link-icon mx-1" aria-hidden="true"></i>{% trans 'Speakers management' %}</
je ne vois pas où tu veux dire

2024-06-17 05:58 UTC, AymericJak commented on pod/main/templates/navbar.html
> +                <a class="nav-item nav-link" href="{% url 'speaker:speaker_management' %}"><i class="bi bi-megaphone pod-nav-link-icon mx-1" aria-hidden="true"></i>{% trans 'Speakers management' %}</
`ria-hidden="true"></i>&nbsp;{% trans 'Speakers man`

2024-06-17 07:10 UTC, fanfounet commented
Merci Aymeric pour ces premières remarques. j'ai corrigé les petits trucs ! Puis j'ai fait comme toi pour le quiz dans la partie des jobs. C'est drôle j'ai bien le dossier migrations avec le fichier init mais ça ne doit pas le pusher étrange.
Pour ta première question, oui un speaker est bien un contributeur (contributeur est plus large car il y a les auteurs, les réalisateurs etc), mais le but est de laisser l'app contributeur qui gère différemment l'association d'un contributeur à une vidéo, donc pour ne rien casser l'idée est de laisser contributeur et ajouter speaker qui à mon sens est plus utile dans un contexte webtv (voir l'issue). Du fait je pense qu'il faut mettre USE_SPEAKER à false car par défaut on laisse contributeur et on ajouter speaker si besoin de cet usage

2024-06-17 08:34 UTC, AymericJak commented
Pour ce qui est du Speaker OK. Ça évitera de tout casser. Puis éventuellement proposer une fusion / struture plus optimisée dans le futur.

Pour ce qui est du __init__.py, c'est normal que ça ne s'ajoute pas en faisant un `git add`.
Il fait faire : `git add --force lien/du/fichier`

2024-06-17 08:39 UTC, ptitloup commented
Hello, on sépare les contributeurs des intervenants dans Pod. Les contributeurs sont ceux qui ont participé à la conception tans que les intervenants sont ceux filmés ! :) De plus, d'un point de vue technique, on a choisit de séparer les 2 pour faciliter le dev et la maintenance.

2024-06-24 11:55 UTC, AymericJak requested changes
Quelques modifications à faire niveau code.

Ensuite, d'un point de vue fonctionnel. Quelques subtilités.

- Quand j'appuie sur `Add a new speaker`, ceci s'affiche : 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/70357dc7-a168-4f61-a927-9a06cb9f774b)
Je ne peux pas entrer de nom/prénom, mais juste un job.

Je viens de faire les migrations, donc aucun jobs en BD. Je me dis donc : "Allez, let's go dans le panel admin pour en ajouter". MAIS, pour ajouter un job, je suis obligé d'avoir un speaker. 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/b9a35b94-4bdc-4bc1-afb4-58955e99b6a5)

- Maintenant que j'ai créé mon speaker et mon job. Je peux l'ajouter à la vidéo.
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/c7c53fb4-999d-49a1-b5c5-592e0d3f5318)

Mais je trouve ça assez étrange que l'on doit exclusivement passer par l'admin.
Je pensais à un formulaire où l'on met le nom prénom puis un job.

Dans cette optique, il faudrait aussi modifier le modèle de données. pour que l'on puisse créer un job sans forcément l'associer à un speaker.

- Quand on souhaite ajouter un speaker déjà présent, on a ceci : 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/1f523a2a-4d1a-4cc2-ae00-441e0332ea3d)
Peut être améliorer le message. Et prevent le refresh de la page.

- Manque de praticité :

Exemple quand il y a beacoup de speakers
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/a41f30fe-ed5b-4110-9e90-7898ba44b569)

Quand on a plusieurs fois le même job, pas simple à choisir dans la liste des speakers 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/dda57781-3171-4b58-965c-037adeec373a)


Je pense qu'on devrait avoir la possibilité de mettre nom prénom. Si existe déjà, on prend celui de la BD, sinon on le créé.
Puis pour le job, on choisi parmi la liste des jobs.

2024-06-24 12:20 UTC, AymericJak commented
Autant pour moi, il y a le speaker manager !!!

2024-06-24 13:36 UTC, AymericJak commented
Liste de petits changements vu en visio :
- title sur les boutons dans la page `Speaker manager`
- ![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/5bf07595-ce0d-4a3a-bb09-ee131436dd25)

Modifier le title pour mettre le nom prénom et job.
- Rendre possible la recherche avec le firstname
- `Speaker manager` : Modifier le bouton éditer et supprimer (title)
- `Speaker manager` remplacer les icone dans le `<th>` par 'Actions'
- Modifier style de la modale 'Add speaker'
`<div class="d-flex align-items-center">`
- Ajouter dans le SpeakerForm
```python
    def __init__(self, *args, **kwargs):
        """Init method."""
        super(SpeakerForm, self).__init__(*args, **kwargs)
        self.fields = add_placeholder_and_asterisk(self.fields)
```

2024-06-26 06:40 UTC, fanfounet commented
J'ai passé la PR en DONE après avoir corrigé les remarques d'Aymeric. Question css vou préférez quoi ?

<img width="790" alt="Capture d’écran 2024-06-26 à 08 38 26" src="https://github.com/EsupPortail/Esup-Pod/assets/17542516/93f872a9-4a61-40ba-9a51-446d9716bdc5">

2024-06-26 07:21 UTC, Badatos commented
> J'ai passé la PR en DONE après avoir corrigé les remarques d'Aymeric. Question css vou préférez quoi ?
> 
> <img alt="Capture d’écran 2024-06-26 à 08 38 26" width="790" src="https://private-user-images.githubusercontent.com/17542516/343036442-93f872a9-4a61-40ba-9a51-446d9716bdc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODY3MzcsIm5iZiI6MTcxOTM4NjQzNywicGF0aCI6Ii8xNzU0MjUxNi8zNDMwMzY0NDItOTNmODcyYTktNGE2MS00MGJhLTlhNTEtNDQ2ZDk3MTZiZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Mzc1MDc1YjQ4NTg0Mzg5YjExMDRhNGRmMjUzMjE5Njc5NzU2ZmRhMGYwYzEyODZiYWFmZTg1Y2ZlZjRmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZeMej5mwA8RuA3WiOCpnFo8n1SgymjQL-4-MXL2y--8">

Faudrait demander à Apolline ^^

2024-06-26 07:57 UTC, AymericJak commented
> J'ai passé la PR en DONE après avoir corrigé les remarques d'Aymeric. Question css vou préférez quoi ?
> 
> <img alt="Capture d’écran 2024-06-26 à 08 38 26" width="790" src="https://private-user-images.githubusercontent.com/17542516/343036442-93f872a9-4a61-40ba-9a51-446d9716bdc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODg0NzksIm5iZiI6MTcxOTM4ODE3OSwicGF0aCI6Ii8xNzU0MjUxNi8zNDMwMzY0NDItOTNmODcyYTktNGE2MS00MGJhLTlhNTEtNDQ2ZDk3MTZiZGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA3NDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwOTYzNjczMTk1YWNhOWMxOTliN2Q0YWYzMmZkZjAzNTczMTdhZGIzNzAwZmYzY2Q1ZTg0MTMzY2RkMzQ5MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Om0ZJeaC4WM3XHSd3TTOm0dqZfoH5zCyblZ9aTYP3as">

L'option du haut pour moi.

2024-06-26 08:02 UTC, Badatos reviewed
Merci pour cette feature :)
Quelques remaqres sur le code :

2024-06-26 08:52 UTC, fanfounet commented on pod/speaker/templates/speaker/speakers_management.html
> +                    <li class="text-left">{{ job.title }}</li>
non par défaut on est center

2024-06-26 11:49 UTC, fanfounet commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "Nom"
Ah ouiais ! j'ai toujours mis ça collé !! Je corrige

2024-06-26 12:47 UTC, fanfounet commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Firstname"
je vois que je ne suis pas le seul à l'écrire comme ça, dnas completion contributor y'a déjà ! je corrige également pendant que j'y suis ?

2024-06-26 13:05 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Firstname"
ah ben oui s'il te plait ;)

2024-06-26 13:58 UTC, fanfounet commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Firstname"
fait !

2024-06-28 09:39 UTC, AymericJak requested changes

2024-06-28 09:39 UTC, AymericJak commented on pod/speaker/templates/speaker/speakers_management.html
> +          <form method="post" action="{% url 'speaker:speaker_management' %}" onsubmit="return confirm('{{ confirmDelete|escapejs }}');" style="display: inline;">
Utiliser la classe bootstrap `d-inline`

2024-06-28 09:39 UTC, AymericJak commented on pod/speaker/views.py
> +        return True
Qu'en est-il du cas où il n'y a pas de job ?
L'objet n'est pas créé, mais l'utilisateur a le message SUCCESS ?!

2024-06-28 09:39 UTC, AymericJak commented on pod/speaker/views.py
> +        messages.add_message(request, messages.ERROR, _("Speaker not found."))
Revoir le message, plutôt un truc du style : "L'intervenant n'a pas pu être ajouté"

2024-07-02 06:41 UTC, fanfounet commented on pod/speaker/static/speaker/js/speakers-management.js
> +            document.getElementById('speakerModalLabel').innerText = gettext("Add a speaker");
idem

2024-07-02 07:06 UTC, fanfounet commented on pod/speaker/views.py
> +        return True
L'intervenant est tout de même créé avec son nom prénom mais il n'a pas de job associé (voir la liste). A mon sens ce n'est pas génant d'obliger de mettre un job tout de suite sachant que l'on peut y revenir (editer à nouveau) et que de toute manière tu ne pourras pas ajouter d'intervenant dans ta vidéo si tu n'as pas le Job, donc je laisserai comme cela

2024-07-02 08:20 UTC, AymericJak requested changes

2024-07-02 08:20 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +#~ "traitement en appuyant sur l’icône du robot."
C'est normal que l'on perd ces traductions Aristote ?

2024-07-02 08:20 UTC, AymericJak commented on pod/speaker/static/speaker/js/speakers-management.js
Juste la doc des fonctions à revoir pour qu'elles soient un peu plus conventionnelles.

2024-07-02 09:20 UTC, SebastienCozeDev requested changes
Juste une petite remarque pour ma part

2024-07-02 09:20 UTC, SebastienCozeDev commented on pod/speaker/tests/test_models.py
> +    def test_attributs_full(self):
Il manque une petite pydoc

2024-07-02 09:21 UTC, fanfounet commented on pod/locale/fr/LC_MESSAGES/django.po
> +#~ "traitement en appuyant sur l’icône du robot."
bah non j'ai vu mais j'ai fait un make lang, je corrige avec poedit et dans poedit ne ne voit pas cette partie aristote en orange pourtant ?

2024-07-02 09:26 UTC, fanfounet commented on pod/speaker/static/speaker/js/speakers-management.js
exemple ?

2024-07-02 10:39 UTC, AymericJak commented on pod/speaker/static/speaker/js/speakers-management.js
```js
  /**
   * Retrieves question data from the initial data based on the provided question form.
   * @param {HTMLElement} questionForm - The HTML form element representing a question.
   * @returns {Object|null} - The data associated with the question or null if no initial data is available.
   */
  function getQuestionData(questionForm) {
    if (!initialData) {
      return null;
    }
    const questionIndex = Number(questionForm.getAttribute("data-question-index"));
    return initialData.existing_questions[questionIndex];
  }
```

2024-07-02 10:40 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +#~ "traitement en appuyant sur l’icône du robot."
Je n'utilise pas Poedit. Je ne peux te répondre

2024-07-08 10:29 UTC, AymericJak requested changes
Je n'ai pas testé les derniers changements en local

2024-07-08 10:29 UTC, AymericJak commented on pod/completion/templates/video_completion.html
> +  <script src="{% static 'django_select2/django_select2.js' %}"></script>
Il manque le `?ver={{VERSION}}`

2024-07-08 10:29 UTC, AymericJak commented on pod/main/configuration.json
> +                            "pod_version_init": "3.x.x"
On va la sortir en `3.7.1` je dirais

2024-07-08 10:29 UTC, AymericJak commented on pod/speaker/templates/speaker/form_speaker.html
Pense à respecter une tabulation de 2 pour les fichers HTML

2024-07-08 10:29 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Job's speaker"
C'est inversé, il faut mettre à la place : Speaker's job

2024-07-08 10:29 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgid "Job Title"
Pas besoin de la majuscule à Title

2024-07-08 10:29 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "Supprimer l’intervenant “%(speaker_firstname)s %(speaker_lastname)s”"
Guillemets dans le mauvais format, c'est plutôt « »

2024-07-08 10:29 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgid "remove job"
Il manque la majuscule à Remove

2024-07-10 08:45 UTC, AymericJak approved these changes
Toutes les modifs que j'ai demandées ont été apportées.
Merci beaucoup Franck !

2024-07-10 08:59 UTC, SebastienCozeDev approved these changes
Tout est bon pour moi niveau code 👍

2024-07-10 10:06 UTC, merged