[DONE] Pampletousse/fix improve dashboard
EsupPortail/Esup-Pod pull request #1149
Opened 2024-06-06 14:42 UTC by pampletousse

Amélioration de l'écran du dashboard :
- Ajout d'un bouton "Tout sélectionner" -> sélectionne toutes les cards visibles
- Refonte des catégories avec logique déportée dans le back 
- Changement de sélection checked_overlay -> cases à cocher

2024-06-26 12:21 UTC, Badatos requested changes
Belle PR 😻 !
Mais je n'allais pas te laisser sans commentaires, faut bien que tu soit content de partir 😆

2024-06-26 12:27 UTC, pampletousse commented on pod/locale/fr/LC_MESSAGES/django.po
Bein oui pourtant je suis bien rebase sur develop, juste après "bump urlib3", bizarre

2024-06-26 13:02 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
si tu relance un "make lang" c'est pas mieux ?

2024-06-26 13:16 UTC, Badatos commented on pod/video/static/css/video_category.css
> +#category-modal-videos-list .video-card > .card-thumbnail{
Est-ce que `category-modal-videos-list`est une classe ou un id ? avant la ligne 229, il semble traité comme une classe.

2024-06-26 13:16 UTC, Badatos commented on pod/video/templates/videos/card_select.html
> +               {% if not category_modal %}
Du coup, maintenant qu'il n'y a plus d'aria-label, il manque un label du coup :/

Soit on met un aria-label cohérent, soit il faut une balise label associée à ce checkbox.

2024-06-26 13:16 UTC, Badatos commented on pod/video/tests/test_category.py
> +        """
* Les pydocs qui tiennent sur une ligne ne doivent pas avoir de saut de ligne :
```py
"""Test get add new category modal."""
```
* Chaque pydoc doit terminer par un point.

2024-06-28 12:10 UTC, AymericJak requested changes

2024-06-28 12:10 UTC, AymericJak commented on pod/video/templates/videos/category_modal.html
> +        <button type="button" id="confirm_category_btn" data-action="edit" data-slug="{{ category.slug }}" class="btn btn-primary">{% trans "Save category" %} </button>
Des espaces en trop après les textes dans les boutons

2024-06-28 12:10 UTC, AymericJak commented on pod/video/views.py
> +    ) | request.user.owners_videos.all().filter(sites=site)
On peut directement faire un `filter()` sans forcément faire un `all()` avant me semble

2024-07-03 09:14 UTC, AymericJak commented
@pampletousse Je prends la suite de cette PR :)

2024-07-10 08:38 UTC, ptitloup commented
Bonjour,
Est-ce possible de terminer cette PR pour ce vendredi svp ?
Merci

2024-07-15 06:40 UTC, AymericJak commented on pod/video/static/css/video_category.css
> +#category-modal-videos-list .video-card > .card-thumbnail{
C'est aussi un ID

2024-07-15 14:18 UTC, ptitloup approved these changes
ok pour moi nieau code mais juste une remarque sur les intitulés des classes et identifiant de balise : est-ce qu'on utilise le "-" ou le "_" car là il y a les deux...

2024-07-15 14:18 UTC, ptitloup commented on pod/video/static/css/video_category.css
> +#category_modal.show {
vis a vis des ID ci-après, ne devrait-on pas mettre category-modal au lieu de category_modal ? mais je me demande si l'on peut utiliser le "-"

2024-07-15 14:26 UTC, Badatos commented on pod/video/static/css/video_category.css
> +#category_modal.show {
Tout a fait, ce serait mieux avec un "-". Dans l'idéal, il faudrait que nos CSS soient en *kebab-case* pour uniformiser.

2024-07-15 14:27 UTC, Badatos commented on pod/video/static/css/video_category.css
> +#category-modal-videos-list .video-card > .card-thumbnail{
n'est-ce pas source potentielle de problème si c'est à la fois une classe et un ID ?

2024-07-15 14:31 UTC, AymericJak commented on pod/video/static/css/video_category.css
> +#category_modal.show {
Yess, c'est sous `cette-forme`.

Je n'avais pas modifié toutes les classes étant donné que ce n'est pas ma PR. Je vais voir pour en modifier au max :)

2024-07-15 14:46 UTC, AymericJak commented on pod/video/static/js/video_select.js
> +      console.log(item);
Tout à fait :)

2024-07-15 14:48 UTC, SebastienCozeDev approved these changes
Aucun problème pour ma part

2024-07-15 14:57 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> -msgstr "Créer catégorie"
`Create category` n'est plus utilisé par exxemple.

Je vais check les trads supprimées, mais de mon côté, tout est à jour. Donc normalement, c'est normal

2024-07-16 09:14 UTC, AymericJak approved these changes

2024-07-16 09:28 UTC, Badatos approved these changes
Merci pour tous ces changements 🤩 
Il reste 2 remarques

2024-07-16 09:28 UTC, Badatos commented on pod/video/templates/videos/category_modal.html
> +          <input type="text" placeholder="{% trans 'Category title' %}" id="cat-title" name="cat-title"
je ne pense pas qu'il faut changer l'attribut "name"

2024-07-16 09:28 UTC, Badatos commented on pod/video/templates/videos/category_modal.html
> +                 class="cat-title_input form-control" required>
il reste un `_`, c'est voulu ?

2024-07-16 09:35 UTC, AymericJak commented on pod/video/templates/videos/category_modal.html
> +                 class="cat-title_input form-control" required>
À vrai, cette classe est écrite particulièrement :vomiting_face: 

J'ai peur que certains fichiers JS récupèrent les éléments en faisant de la concaténation du style `field + "_input"`

Donc j'ai laissé cette partie telle quelle. Au cas où :)

2024-07-16 09:37 UTC, AymericJak commented on pod/video/templates/videos/category_modal.html
> +          <input type="text" placeholder="{% trans 'Category title' %}" id="cat-title" name="cat-title"
Pourquoi ?

2024-07-16 10:45 UTC, AymericJak commented on pod/video/templates/videos/category_modal.html
> +          <input type="text" placeholder="{% trans 'Category title' %}" id="cat-title" name="cat-title"
![image](https://github.com/user-attachments/assets/4ff45067-3721-4d61-97c4-d032926e54a6)

Dans la doc, ils utilise bien cette convention pour les attributs `name`.


D'autre part, toutes les occurences de `catTitle` ont bien été remplacées par `cat-title`

2024-07-16 11:29 UTC, SebastienCozeDev requested changes

2024-07-16 11:29 UTC, SebastienCozeDev commented on pod/video/static/js/video_select.js
> +function getHTMLBadgesSelectedTitles(container) {
Est-il possible d'ajouter le paramètre `container` dans le JSDoc ?

2024-07-16 11:29 UTC, SebastienCozeDev commented on pod/video/templates/videos/card_select.html
> +  <div class="card-header ">
Pourquoi avoir ajouter un espace ici ?

2024-07-16 11:29 UTC, SebastienCozeDev commented on pod/video/views.py
> +def get_videos_for_owner(request):
Il manque l'option request dans la pydoc

2024-07-16 12:03 UTC, SebastienCozeDev approved these changes

2024-07-16 12:05 UTC, merged

2024-07-16 12:21 UTC, Badatos commented on pod/video/templates/videos/category_modal.html
> +                 class="cat-title_input form-control" required>
bonne idée ;)

2024-07-16 12:22 UTC, Badatos commented on pod/video/templates/videos/category_modal.html
> +          <input type="text" placeholder="{% trans 'Category title' %}" id="cat-title" name="cat-title"
c'etait surtout pour ne pas interferer avec d'éventuels codes qui en dépendraient ^^