[WIP] Update the restriction fields in the video form
EsupPortail/Esup-Pod pull request #1158
Opened 2024-06-11 12:42 UTC by SebastienCozeDev

Before sending your pull request, make sure the following are done:

* [ ] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [ ] Your PR targets the `develop` branch.
* [ ] The title of your PR starts with `[WIP]` or `[DONE]`.

2024-07-15 14:45 UTC, AymericJak requested changes
Quelques détails mineurs

2024-07-15 14:45 UTC, AymericJak commented on pod/video/static/js/video_edit.js
> +    console.log(passwordField);
Tu as oublié un log

2024-07-15 14:45 UTC, AymericJak commented on pod/video/static/js/video_edit.js
> +      // idRestrictToGroupsField.parentElement.classList.remove("d-none");
Tu peux aussi delete

2024-07-15 14:45 UTC, AymericJak commented on pod/video/static/js/video_edit.js
> +      // idRestrictToGroupsField.parentElement.classList.add("d-none");
Et ça aussi

2024-07-15 14:45 UTC, AymericJak commented on pod/video/static/js/video_edit.js
>  function display_option_desc(selectBox, container) {
Par la même occasion, peux tu ajouter la doc de la fonction ?

2024-07-15 14:45 UTC, AymericJak commented on pod/video/tests/test_views.py
> +        [print(m) for m in get_messages(response.wsgi_request)]
Logs aussi oubliés

2024-07-16 07:53 UTC, AymericJak approved these changes
ok pour moi.

Je n'ai pas testé localement

2024-07-16 08:27 UTC, ptitloup commented
Hello, je viens de tester. Il manque les traductions en francais et la case à cocher quand on séléctionne accès restreint. En effet, quand on sélectionne accès restreint, il faut qu'on puisse choisir si on veut restreindre par authentification (et à ce moment là, on peut choisir éventuellement un groupe s'il y en a dans Pod) et/ou par mot de passe. Merci !

2024-07-16 11:03 UTC, AymericJak reviewed
Toujours RAS au niveau du code. Je vais tester

2024-07-16 11:08 UTC, AymericJak commented
J'ai une remarque quand je teste : 
![image](https://github.com/user-attachments/assets/d73ea5a4-953e-4ccd-b899-c47eb0f9360a)

Le field pour les groupes ne s'affiche pas correctement.

2024-07-16 14:28 UTC, ptitloup approved these changes
ok pour moi

2024-07-16 14:45 UTC, Badatos commented on pod/video/forms.py
> +        ("restricted", _("Restricted")),
Ici, je mettrais "Restricted access" dans le texte pour être plus clair.

2024-07-16 15:18 UTC, ptitloup commented on pod/video/forms.py
> +        """Save video access fileds depends of the visibility field value."""
fait

2024-07-16 15:31 UTC, Badatos approved these changes
Beau travail, merci :)
Il faudra juste peut-etre refaire un dernier compilemessages, car certains textes n'étaient pas traduits dans mon dernier essai.

2024-07-17 06:55 UTC, fanfounet commented
Hello,
Je viens de tester fonctionnellement cette partie. Tout fonctionne correctement. J'ai toutefois une remarque. Quand on choisit "Accès restreint" si on remplit la case mot de passe on enregistre ça fonctionne mais si on édite à nouveau le champ mot de passe est vide. Ça peut être troublant pour l'utilisateur de se demander si il a bien ou pas ajouté un mdp. Peut etre également coté UX la case à cocher accès restreint par authentification au dessous de la partie mdp est peut être compliqué à comprendre. Plus simple, pour bien segmenter, de faire la liste déroulante avec "public", "brouillon/privé", "accès restreint par mot de passe", "accès restreint par authentification" c'est une idée ;-)

2024-07-17 07:28 UTC, SebastienCozeDev commented
> Hello, Je viens de tester fonctionnellement cette partie. Tout fonctionne correctement. J'ai toutefois une remarque. Quand on choisit "Accès restreint" si on remplit la case mot de passe on enregistre ça fonctionne mais si on édite à nouveau le champ mot de passe est vide. Ça peut être troublant pour l'utilisateur de se demander si il a bien ou pas ajouté un mdp. Peut etre également coté UX la case à cocher accès restreint par authentification au dessous de la partie mdp est peut être compliqué à comprendre. Plus simple, pour bien segmenter, de faire la liste déroulante avec "public", "brouillon/privé", "accès restreint par mot de passe", "accès restreint par authentification" c'est une idée ;-)

Bonjour, merci d'avoir testé. Je vais regarder pour le mot de passe. Pour ce qui est de séparer l'accès restreint par mot de passe et par l'authentification, je serais plus d'avis à mettre une balise `<hr>` entre les deux. Ça permettrait à l'utilisateur d'utiliser les deux possibilités en même temps s'il le souhaite.

2024-07-17 07:32 UTC, fanfounet commented
Comme tu veux mais l'important c'est de faire comprendre que c'est fromage ou dessert et pas fromage et dessert pour l'accès restreint !!! ;-)

2024-07-17 08:33 UTC, Badatos commented
> Comme tu veux mais l'important c'est de faire comprendre que c'est fromage ou dessert et pas fromage et dessert pour l'accès restreint !!! ;-)

et pourquoi ce ne serait pas "formage ET/OU dessert" ? ;)

2024-07-17 08:58 UTC, ptitloup approved these changes
ok pour moi, merci

2024-07-17 09:09 UTC, merged