[DONE] Feature: Add menu in the video card and the video page
EsupPortail/Esup-Pod pull request #1171
Opened 2024-07-01 09:24 UTC by SebastienCozeDev

# Before sending your pull request, make sure the following are done

* [x] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [x] Your PR targets the `develop` branch.
* [x] The title of your PR starts with `[WIP]` or `[DONE]`.

- Remove icons from the card and the video page (except favorite, edition and playlist icons).
- Remove icons from the meeting card (except edition).
- Add icon to open a menu with all video options.

2024-07-02 11:00 UTC, AymericJak requested changes
C'est globalement bon, et va grandement améliorer l'expérience utilisateur.

Remarques supplémentaires :
- Je ferai le même principe pour les cartes d'une réunion
- Le dropdown menu pour les vidéos dans le tableau de bord ne possèdent pas les icônes. Tu devrais reprendre le même design et améliorer cette partie du tabeau de bord (affiche en lignes)
- Bug ultra spécifique. 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/e9375480-7697-480f-8122-dd5446f3532d)
Quand on est dans ce cas précis, lorsque l'on enlève la 2e vidéo des favoris, il y a un refresh de la page.

2024-07-02 11:00 UTC, AymericJak commented on pod/playlist/templates/playlist/playlist-list-modal.html
- Il faut respecter la tabulation de 2
- Il manque une ligne vide en fin de fichier

2024-07-02 11:00 UTC, AymericJak commented on pod/video/templates/videos/link_video.html
> +<a href=""
Il manque le `data-bs-original-title`.

Fais comme sur l'image de profil, pour avoir le bon style du title

2024-07-02 11:00 UTC, AymericJak commented on pod/video/templates/videos/link_video.html
> +         title="{% trans 'Enhance the video with AI' %} ({{ video.title }})"
Le title n'est pas cohérent avec les autres. Sur les autres, il n'y a pas les parenthèses

2024-07-02 11:00 UTC, AymericJak commented on pod/video/templates/videos/link_video.html
> +         title="{% trans 'Enhance the video with AI' %} ({{ video.title }})"
D'autre part, ce titles, ainsi que les autrces ne sont pas correctement stylisés

2024-07-03 07:33 UTC, SebastienCozeDev commented
> C'est globalement bon, et va grandement améliorer l'expérience utilisateur.
> 
> Remarques supplémentaires :
> 
>     * Je ferai le même principe pour les cartes d'une réunion
> 
>     * Le dropdown menu pour les vidéos dans le tableau de bord ne possèdent pas les icônes. Tu devrais reprendre le même design et améliorer cette partie du tabeau de bord (affiche en lignes)
> 
>     * Bug ultra spécifique.
>       ![image](https://private-user-images.githubusercontent.com/106442526/344993854-e9375480-7697-480f-8122-dd5446f3532d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTIwMjQsIm5iZiI6MTcxOTk5MTcyNCwicGF0aCI6Ii8xMDY0NDI1MjYvMzQ0OTkzODU0LWU5Mzc1NDgwLTc2OTctNDgwZi04MTIyLWRkNTQ0NmYzNTMyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwNzI4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjEwNmY2ZjQ1YWIyM2JlOGY5YjNiNjRkNjNmMjExYzRiNzhjMzE0OTgyODI1NDIyYzg5MmM0N2IzM2EzNDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bf9UWFYKw3_umGiXXp1AKoClnpiYMND3DH3oXzhKJr0)
>       Quand on est dans ce cas précis, lorsque l'on enlève la 2e vidéo des favoris, il y a un refresh de la page.

@AymericJak 
Je ne pense pas que ce soit réellement une plus-value d'ajouter ce principe aux réunions, car ça ajouterait le nombre de clics pour accéder à une feature et qu'il n'y a pas tant d'options que cela

2024-07-03 09:01 UTC, AymericJak commented
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/518fad58-b4bf-4817-ae48-6cd1e5ba55c7)

Je ne mettrai personnellement que l'icône d'édition de la réunion, puis le bouton "More option".

Puisque certaines icônes ne sont pas autant utiles / compréhensible sans passer en hover dessus.

D'autre part, ça rajoute de la cohérence dans l'application.

Ce n'est pas long à faire.

2024-07-05 07:54 UTC, AymericJak reviewed
Ok d'un point de vue code

2024-07-05 07:54 UTC, AymericJak commented on pod/meeting/templates/meeting/link_meeting_dropdown_menu.html
> +</ul>
Il manque une ligne vide en fin de fichier

2024-07-05 07:54 UTC, AymericJak commented on pod/video/templates/videos/link_video_dropdown_menu.html
> +</ul>
Ligne vide

2024-07-05 13:25 UTC, AymericJak approved these changes

2024-07-05 13:47 UTC, ptitloup approved these changes
ok pour moi, merci bcp

2024-07-05 13:50 UTC, merged