[DONE] Add return thumbnail url,width and height to oembed
EsupPortail/Esup-Pod pull request #1194
Opened 2024-08-30 13:55 UTC by MichelAimar

Le provider OEMBED permet de récupérer un fichier au format json ou XML pour intégrer dans une page web une vidéo disponible sur AMUPOD. Le PR ajoute les informations concernant la vignette associée à la vidéo récupérée.

2024-09-04 08:41 UTC, gcondess requested changes
Est ce qu'il ne serait pas utile de traduire la chaine "Url not match" insérée dans la balise H1 ?

2024-09-19 06:37 UTC, MichelAimar commented
Peut être ... J'ai fait des modifs pour que le code fonctionne. Pour les traductions des comportements existants, on fera une autre PR non ?

2024-09-23 09:05 UTC, Badatos approved these changes
Ok pour moi niveau Code.

2024-09-23 09:11 UTC, gcondess approved these changes

2024-09-23 09:13 UTC, merged