[DONE] Fix multi carousel
EsupPortail/Esup-Pod pull request #1200
Opened 2024-09-06 14:50 UTC by cbissler

Corrige le format HTML de l'affichage du bloc "multi caroussel" des pages éditorialisées

2024-09-09 13:36 UTC, LoicBonavent approved these changes
Nickel, merci !

2024-09-11 08:45 UTC, Badatos commented on pod/main/templates/block/multi_carousel.html
> +      <!--</div>-->
Pourquoi mettre ce div en commentaires ?

Ce fichier compte exactement 11 `<div` ouvrants et 11 `div>`fermants. en mettre un en commentaire laisse forcément un `<div `ouvrant orphelin... :/

2024-09-11 08:53 UTC, Badatos commented on pod/main/templates/block/multi_carousel.html
> +      <!--</div>-->
Ok, je vois le souci !! :)

Dans ce cas, peux-tu également modifier la ligne 10 ainsi :

`<div class="carousel-item{% if forloop.first %}active{% endif %}">`

De cette manière, le nombre de balises ouverte dans le template reste cohérent.

2024-09-11 08:54 UTC, Badatos commented on pod/main/templates/block/multi_carousel.html
> +      <!--</div>-->
(et du coup, supprimer completement le div plutot que le mettre en commentaire ^^)

2024-09-25 12:04 UTC, fanfounet approved these changes
Ok pour moi

2024-10-02 09:21 UTC, Badatos requested changes
Coucou @cbissler !

Peux-tu également modifier la ligne 10 ainsi :
`<div class="carousel-item{% if forloop.first %} active{% endif %}">`

De cette manière, le nombre de balises ouvertes dans le template restera cohérent.
(et du coup, supprimer complètement le div plutôt que le mettre en commentaire ^^)

Avec ca, on pourra merger cette PR ;)

2024-10-03 14:05 UTC, cbissler commented
Désolé pour le délai, j'ai corrigé ça devrait être bon.

2024-10-03 15:01 UTC, Badatos requested changes

2024-10-03 15:01 UTC, Badatos commented on pod/main/templates/block/multi_carousel.html
> +      <div class="carousel-item{% if forloop.first %} active{% endif %}">
Désolé, j'ai pas été assez précis ^^.
Dans l'idée, ce `if` de la ligne 10 doit remplacer celui des ligne 09, 11, 12 et 13 ^^

2024-10-04 06:43 UTC, cbissler commented on pod/main/templates/block/multi_carousel.html
> +      <div class="carousel-item{% if forloop.first %} active{% endif %}">
Au contraire, c'était tellement précis que j'ai copié-collé sans regarder autour :-). C'est ma faute, j'ai corrigé !

2024-10-04 08:00 UTC, Badatos approved these changes
Merci pour les corrections ;)

2024-10-04 08:02 UTC, merged