[DONE] Change regroup videos by theme when ORGANIZE_BY_THEME = True
EsupPortail/Esup-Pod pull request #1203
Opened 2024-09-13 12:47 UTC by LoicBonavent

Change regroup videos by theme when ORGANIZE_BY_THEME = True.

Greatly simplifies operation and future developments by modifying the behavior of the _regroup_videos_by_theme() function for videos.
Thus, for videos, this function renders the existing page videos/video_list.html; this avoids having to manage in Javascript what is already done in Python/Django/HTML. Typically, the menu of a video tile is displayed as is, and there's no need to redevelop the management rules, icons and links....

Moreover, this PR corrects bugs when ORGANIZE_BY_THEME = True :

- The link to the video, for videos loaded after a scroll (from the 13th onwards), takes into account the channel and theme.
- Correctly displays pagination and correct titles and links, when there are more than 12 themes/subthemes.

2024-09-30 07:00 UTC, LoicBonavent commented
Hello, je n'avais pas fait attention que la PR #1190 est incluse dans cette PR #1203.
Pour faire une revue de code, le mieux est d'en faire une sur la PR #1190 puis sur cette PR #1203.
Les seuls fichiers concernés sont alors les suivants :

- pod/video/static/js/regroup_video_by_theme.js
- pod/video/templates/channel/channel.html
- pod/video/templates/videos/link_video.html
- pod/video/tests/test_views.py
- pod/video/views.py

Merci

2024-10-03 09:58 UTC, Badatos requested changes
A part la partie Jquery, c'est pas mal ;)

nb : dans infinite.js, on trouve ce code pour réactiver des tooltips :
```js
/* Refresh Bootstrap tooltips after load */
      const tooltipTriggerList = document.querySelectorAll(
        '[data-bs-toggle="tooltip"], [data-pod-tooltip="true"]',
      );
      [...tooltipTriggerList].map(
        (tooltipTriggerEl) => new bootstrap.Tooltip(tooltipTriggerEl),
      );
```

2024-10-03 09:58 UTC, Badatos commented on pod/video/static/js/regroup_videos_by_theme.js
> +  /* */
commentaire à supprimer ?

2024-10-03 09:58 UTC, Badatos commented on pod/video/static/js/regroup_videos_by_theme.js
> +      });
il doit forcément y avoir un moyen d'appeler les tooltips sans passer par Jquery :/

2024-10-04 13:30 UTC, LoicBonavent commented on pod/video/static/js/regroup_videos_by_theme.js
> +  /* */
J'ai ajouté une ligne de commentaire pour que cela soit plus clair : c'est la fin de l'ancien code source, gardé pour l'historique.

2024-10-04 13:31 UTC, LoicBonavent commented on pod/video/static/js/regroup_videos_by_theme.js
> +      });
J'ai fais comme dans infinite.js

2024-10-04 13:32 UTC, LoicBonavent commented
C'est vrai que c'est bourré de code Jquery, mais sur le coup, je n'ai pas le temps de tout modifier :( .
Cela sera pour une prochaine PR... Thx

2024-10-04 13:38 UTC, Badatos approved these changes
Merci pour les modifs ;)

2024-10-08 09:13 UTC, gcondess approved these changes

2024-10-08 09:13 UTC, gcondess commented on pod/video/views.py
Pourquoi virer l'import de 'get_video_data' si on laisse l'appel à la fonction dans 'lambda v: { **get_video_data(v), ...

2024-10-08 09:26 UTC, LoicBonavent commented on pod/video/static/js/regroup_videos_by_theme.js
Je ne comprends pourquoi cet ancien code qui refait tout le menu des actions, déjà existant, en Javascript, a été mis en place.
Mais je l'ai laissé exprès car il est quand même intéressant et aussi, voir  à l'usage si tout fonctionne bien avec le nouveau système.

2024-10-08 09:28 UTC, LoicBonavent commented on pod/video/views.py
Cela fait partie de l'ancien code commenté. Avec flake, comme cette fonction n'est pas appelée, il est nécessaire que l'import soit supprimé.

2024-10-14 07:58 UTC, merged