[DONE] Improve RSS Feeds
EsupPortail/Esup-Pod pull request #1215
Opened 2024-10-03 14:29 UTC by cbissler

Amélioration des flux RSS suggérées dans l'issue : https://github.com/EsupPortail/Esup-Pod/issues/1108

2024-10-03 15:05 UTC, Badatos requested changes

2024-10-03 15:05 UTC, Badatos commented on pod/video/feeds.py
> +        description = sub  # item.description
autant assigner directement `description` au `re.sub` juste au dessus sans passer par une variable `sub` intermédiaire.

2024-10-04 06:34 UTC, cbissler commented on pod/video/feeds.py
> +        description = sub  # item.description
En effet, les restes d'un "j'vais pas tout casser tout de suite". C'est corrigé.

2024-10-04 07:47 UTC, Badatos approved these changes
Merci pour ces modifs ;)

2024-10-04 08:24 UTC, LoicBonavent approved these changes
Nickel ! Merci

2024-10-04 08:26 UTC, merged