[WIP] Maintenance mode
EsupPortail/Esup-Pod pull request #345
Opened 2020-09-29 07:26 UTC by JoshuaBaubry

2020-09-29 07:33 UTC, JoshuaBaubry commented
@meschac38700

2020-09-29 10:37 UTC, meschac38700 reviewed
@JoshuaBaubry  c'est bon pour moi juste une question: l'accès à l'administration reste ouvert, c'est voulu ?

2020-09-29 10:37 UTC, meschac38700 commented on pod/main/templates/base.html
> +	</div>
@JoshuaBaubry tu as oublié peut etre quelque chose ici ?

2020-09-29 11:05 UTC, JoshuaBaubry commented on pod/main/templates/base.html
> +	</div>
Petite erreur en effet je corrige

2020-09-30 12:22 UTC, ptitloup requested changes
Si j'ai bien compris, le mode maintenance empeche l'ajout de video via le formulaire ou l'enregistrement, c'est ca ?

2020-09-30 12:22 UTC, ptitloup commented on pod/main/fixtures/initial_data.json
> +  },
il faudrait prévoir des messages en multilingue comme les titres ci-dessus

2020-09-30 12:29 UTC, JoshuaBaubry commented on pod/main/fixtures/initial_data.json
> +  },
> Si j'ai bien compris, le mode maintenance empeche l'ajout de video via le formulaire ou l'enregistrement, c'est ca ?

Le mode maintenance bloque les pages video_edit et claim_record , donc à fortiori empêche l'ajout ou la modification de vidéos 

Pour les messages multilingues je vois ça demain

2020-09-30 12:33 UTC, ptitloup commented on pod/main/fixtures/initial_data.json
> +  },
du coup, tu devrais également bloquer video_add non ?

2020-09-30 12:34 UTC, ptitloup commented on pod/main/fixtures/initial_data.json
> +  },
ok pour les multinlingues, on voit cela demain !

2020-09-30 12:35 UTC, JoshuaBaubry commented on pod/main/fixtures/initial_data.json
> +  },
video_add redirige vers video_edit il me semble, car lorsqu'on clique sur le bouton "ajouter une vidéo" on arrive sur video_edit

2020-09-30 12:36 UTC, JoshuaBaubry commented on pod/main/fixtures/initial_data.json
> +  },
ah oui dans le cas du chunked upload, je vais corriger ça demain ! bien vu !

2020-10-12 12:26 UTC, ptitloup approved these changes

2020-10-12 12:26 UTC, merged