Gcondess/feature recorder advanced options
EsupPortail/Esup-Pod pull request #347
Opened 2020-10-04 21:34 UTC by gcondess

Add video edit fields to recorder edit form
Additionally users and access restriction options are added by default, other options like "discipline", "channel", "theme"... cant be added by set de USE_ADVANCED_RECORDER to true in settings_local.py

2020-10-05 09:36 UTC, meschac38700 requested changes
Ce serait mieux de rajouter des tests unitaires. @gcondess

2020-10-05 09:36 UTC, meschac38700 commented on pod/locale/fr/LC_MESSAGES/django.po
> -#: pod/video/models.py:563 pod/video/models.py:681
Attention, certaines lignes d'internationalisation sont supprimées !

2020-10-05 09:36 UTC, meschac38700 commented on pod/locale/fr/LC_MESSAGES/django.po
> -msgstr "Vous permet de désactiver les commentaires sur cette vidéo."
Attention, certaines lignes d'internationalisation sont supprimées !

2020-10-06 14:50 UTC, ptitloup approved these changes
ok pour moi

2020-10-06 14:56 UTC, meschac38700 commented
@gcondess il y a test_model.py mais pas pour les deux autres fichiers type_audiovideocast.py et type_video.py ?
Et Il y a des textes enlevés dans le django.po

2020-10-07 14:45 UTC, ptitloup approved these changes

2020-10-12 07:01 UTC, JoshuaBaubry approved these changes
c'est tout bon pour moi

2020-10-14 08:07 UTC, JoshuaBaubry requested changes
Il faut résoudre les conflits avec la branche de dev pour qu'on puisse poursuivre et merger cette PR

2020-10-28 12:17 UTC, merged