bugfix : use broadcaster id instead of 1
EsupPortail/Esup-Pod pull request #366
Opened 2020-10-27 12:54 UTC by JoshuaBaubry

2020-10-27 13:26 UTC, ptitloup commented on pod/live/views.py
> +                        viewkey=key, broadcaster_id=broadcaster_id,
Ne devrait-on pas utiliser une transaction atomic comme pour view count ? 
try:
            viewCount = ViewCount.objects.get(video=video, date=date.today())
        except ViewCount.DoesNotExist:
            try:
                with transaction.atomic():
                    ViewCount.objects.create(video=video, count=1)
                    return HttpResponse("ok")
            except IntegrityError:
                viewCount = ViewCount.objects.get(video=video,
                                                  date=date.today())

2020-10-27 13:28 UTC, JoshuaBaubry commented on pod/live/views.py
> +                        viewkey=key, broadcaster_id=broadcaster_id,
quel est l'intérêt ?

2020-10-27 14:20 UTC, ptitloup commented on pod/live/templates/live/live.html
> +    {% if broadcaster.enable_viewer_count%}
moi j'aurais laissé le compteur mais juste retiré l'affichage, qu'en penses-tu ? par contre, il faudrait pouvoir le retrouver ailleurs....

2020-10-27 14:21 UTC, ptitloup approved these changes
ca peut le faire pour une première version

2020-10-27 14:29 UTC, ptitloup requested changes

2020-10-27 14:29 UTC, ptitloup commented on pod/live/views.py
>                          viewkey=key, broadcaster_id=broadcaster_id)
heartbeat = HeartBeat.objects.filter(viewkey=key)
Le viewkey est unique dans ton model, du coup, tu peux remplacer le filter par un get_or_create car il ne peut pas en avoir 2 c'est 0 et à ce moment la il est créé, sinon il est mis à jour. Du coup, tu peux reprendre le code du viewcount

2020-10-27 14:29 UTC, ptitloup commented on pod/live/views.py
>                          viewkey=key, broadcaster_id=broadcaster_id)
de même pour le broadcast = Broadcaster.objects.get(id=broadcaster_id)
Il faut tester avant si il exsite, c'était le problème que je rencontrais sur mon instance de test (il cherchait un diffuseur avec l'id=1)

2020-10-27 15:36 UTC, ptitloup approved these changes

2020-10-28 08:47 UTC, ptitloup approved these changes
on pourrait retirer un esle mais c'est pour chipoter

2020-10-28 08:47 UTC, ptitloup commented on pod/live/views.py
>      else:
pas besoin du else

2020-10-28 10:17 UTC, merged