save caption maker in video folder instead of home folder
EsupPortail/Esup-Pod pull request #416
Opened 2021-01-18 14:04 UTC by JoshuaBaubry

2021-01-18 14:08 UTC, ptitloup commented on pod/completion/views.py
> +    user_folder = get_object_or_404(
video_folder ? non ?

2021-01-18 14:08 UTC, ptitloup commented on pod/completion/views.py
> +    user_folder = get_object_or_404(
pareil, n'est pas video_folder que tu récupères ?

2021-01-18 14:08 UTC, JoshuaBaubry commented on pod/completion/views.py
> +    user_folder = get_object_or_404(
Oui ça a plus de sens en effet, je modifie

2021-01-18 14:08 UTC, JoshuaBaubry commented on pod/completion/views.py
> +    user_folder = get_object_or_404(
idem

2021-01-18 14:10 UTC, JoshuaBaubry commented
@ptitloup

2021-01-18 14:11 UTC, meschac38700 commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
@JoshuaBaubry  le slug suffit à retrouver le folder ? il n'y a pas une concatenation entre l'id (4chiffres) et le slug  ? Sinon c'est bon pour moi !

2021-01-18 14:12 UTC, JoshuaBaubry commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
Le slug contient déjà l'id de la vidéo 

extrait du models : 
    def save(self, *args, **kwargs):
        self.slug = "%s-%s" % (self.owner.id, slugify(self.title))

2021-01-18 14:14 UTC, meschac38700 commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
d'accord, pour les dossiers nommés home ?

2021-01-18 14:15 UTC, JoshuaBaubry commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
Là le but est justement de ne plus sauvegarder les sous titres dans le titre

2021-01-18 14:17 UTC, ptitloup commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
comment ca ? si on sous-titre, il y a forcement une vidéo associée. L'idée est d'enregistrer automatiquement les fichiers de sous-titre dans le rep de la vidéo. Normalement, il existe forcement

2021-01-18 14:17 UTC, JoshuaBaubry commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
@meschac38700

2021-01-18 14:19 UTC, ptitloup commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
voici le code pour la création du repertoire de la vidéo lors de l'encodage : 
videodir, created = UserFolder.objects.get_or_create(
                    name='%s' % video_to_encode.slug,
                    owner=video_to_encode.owner)

2021-01-18 14:22 UTC, JoshuaBaubry commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
Il y a en effet visiblement un problème sur les nouvelles vidéo, je creuse pour voir

2021-01-18 14:24 UTC, JoshuaBaubry commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
Je crois qu'avec le chunked upload, il y aura également un soucis car le nom du  dossier original est celui de la video d'origine, je creuse aussi

2021-01-18 14:25 UTC, ptitloup commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
en effet, si on change le titre de la vidéo, il risque de ne pas y avoir de dossier, tu devrais faire un répertoire avec get_or_create non ?

2021-01-18 14:26 UTC, JoshuaBaubry commented on pod/completion/views.py
> +        UserFolder, name=video.slug, owner=request.user)
Oui je regarde ça

2021-01-18 15:40 UTC, ptitloup requested changes
un tout petit changement pour retirer le print et c'est ok pour moi

2021-01-18 15:40 UTC, ptitloup commented on pod/completion/views.py
> +    print(video_folder)
il faut retirer le print ;)

2021-01-20 12:53 UTC, ptitloup approved these changes

2021-01-22 08:28 UTC, merged