moodle pod plugin webservices needs
EsupPortail/Esup-Pod pull request #430
Opened 2021-02-10 10:04 UTC by cperves

Please find enclosed work on pod webservices for moodle repository plugin work that we had started
WIP moodle plugin can be find here https://github.com/cperves/moodle-repository_pod/tree/devel
devel branch
do not hesitate to ask me for more suggestions of work on it
meet you on the esup RC channel
Céline

2021-02-10 10:15 UTC, ptitloup reviewed
Ca me parait Ok mais du coup un peu redondant entre get video et get video mp4 ?

2021-02-10 10:15 UTC, ptitloup commented
Aie! si les tests ne passent pas, il faut revoir la copie...

2021-02-10 13:07 UTC, cperves commented
> Ca me parait Ok mais du coup un peu redondant entre get video et get video mp4 ?

je n'ai pas osé retirer , s'il le faut je retire

2021-02-10 13:08 UTC, cperves commented
les derniers flakes sont dû à du code récupéré de la branche dev , je n'arrive pas à formatter avec ce +

2021-02-10 13:14 UTC, cperves commented
:crossed_fingers:

2021-02-10 13:15 UTC, cperves commented
Jolie la CI

2021-02-10 13:19 UTC, ptitloup commented
Merci, tes tests semblent passer. Pour le doublon entre get video et get video mp4, il faudrait voir ou c'est utilisé et vérifier/voir si c'est possible de simplifier

2021-02-10 13:30 UTC, JoshuaBaubry reviewed
Tout à l'air ok de mon coté

2021-02-10 20:44 UTC, meschac38700 requested changes

2021-02-10 20:44 UTC, meschac38700 commented on pod/video/models.py
> +                   self.encoding_format))
Il me semble que la version précendente etait deja mieux indentée non ?

2021-02-10 20:44 UTC, meschac38700 commented on pod/video/models.py
> +    def get_audio_json(self, extensions):
Il y a moyen de d'eviter la répétition sur ces deux méthodes: get_video_json(), get_audio_json()

2021-02-10 20:44 UTC, meschac38700 commented on pod/video/models.py
> +                self.get_video_m4a() is not None)
Bizarre que Flake8 suggère cette indentation ?!

2021-02-10 20:44 UTC, meschac38700 commented on pod/video/models.py
> +LANG_CHOICES_DICT = {
@cperves  Est ce une nouvelle variable ? comment la renseigne t-on ? Si c'est une nouvelle variable de settings, il faudrait également la rajouter dans settings_local.py.example

2021-02-10 20:44 UTC, meschac38700 commented on pod/video/rest_views.py
> +            )
On peut essayer d'appeler qu'une fois get_audio_and_video_json() non ? ca risque de bouffer au niveau perfomance !

2021-02-10 20:44 UTC, meschac38700 commented on pod/video/rest_views.py
> +                    source_file__iendswith=request.GET.get('extension')
Il ne faudrait pas prevoir ici la possibilité qu'on ait pas video dans GET non ? comme c'est fait pour l'extension.

2021-02-10 20:44 UTC, meschac38700 commented on pod/video/rest_views.py
> +        encoded_videos = sorted(encoded_videos, key=lambda x: x.height)
encoded_videos est un queryset, on peut utiliser order_by non ?

2021-02-11 07:12 UTC, cperves commented on pod/video/models.py
> +    def get_audio_json(self, extensions):
je suppose je verrai pour factoriser cela

2021-02-11 07:13 UTC, cperves commented on pod/video/models.py
> +                self.get_video_m4a() is not None)
j'avoue avoir eu des difficultés avec les indentations et les fins de lignes, pas assez souvent sur des dev python désolée

2021-02-11 07:14 UTC, cperves commented on pod/video/rest_views.py
> +            )
je regarde cela

2021-02-11 07:16 UTC, cperves commented on pod/video/rest_views.py
> +        encoded_videos = sorted(encoded_videos, key=lambda x: x.height)
désolée, trop peu souvent sur python et pas toujours consciente des possibilités, je revoie ça

2021-02-11 07:16 UTC, cperves commented on pod/video/rest_views.py
> +        encoded_videos = sorted(encoded_videos, key=lambda x: x.height)
merci pour les review

2021-02-11 15:08 UTC, cperves commented on pod/video/rest_views.py
> +        encoded_videos = sorted(encoded_videos, key=lambda x: x.height)
order_by ne fonctionne pas avec height, il doit être récupéré via l'objet et n'est pas remonté dans le select généré
d'où l'emploi de la lambda à postériori

2021-02-11 15:09 UTC, cperves commented on pod/video/rest_views.py
> +                    source_file__iendswith=request.GET.get('extension')
je regarde

2021-02-11 15:24 UTC, cperves commented on pod/video/rest_views.py
> +                    source_file__iendswith=request.GET.get('extension')
Bien vu sans cela ça ne retournait plus rien

2021-02-25 16:03 UTC, ptitloup reviewed
ok pour moi mais j'ai pas vu si les methodes de rest_views ont été ajoutées au rest_router pour pouvoir être appelées

2021-02-25 16:03 UTC, ptitloup commented on pod/video/models.py
> +    @staticmethod
belle factorisation, c'est rare de voir des méthodes statics en python ;)

2021-02-25 16:03 UTC, ptitloup commented on pod/video/rest_views.py
> +        encoded_videos = sorted(encoded_videos, key=lambda x: x.height)
As-tu rajouté les appels à ces nouvelles méthodes dans le rest_routers ?

2021-02-25 16:39 UTC, ptitloup commented on pod/video/rest_views.py
> +        encoded_videos = sorted(encoded_videos, key=lambda x: x.height)
en fait, je crois que ma question n'a pas lieu d'être puisque tu ne défini pas de nouvelle vu. Ok pour moi je merge

2021-02-25 16:39 UTC, ptitloup approved these changes

2021-02-25 16:39 UTC, merged