Loic bonavent/bbb pod live 1
EsupPortail/Esup-Pod pull request #441
Opened 2021-03-05 14:27 UTC by LoicBonavent

Management for BigBlueButton lives in Pod

2021-03-08 11:47 UTC, JoshuaBaubry approved these changes
Tout est ok pour ma part niveau code

2021-03-18 09:20 UTC, Badatos approved these changes
Bravo pour le gros boulot !
Hormis les quelques remarques, ca me semble ok pour moi.

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/list_meeting.html
> +	<h5><a  href="{% url 'bbb:live_list_meeting' %}" title="{% trans 'Perform a BigBlueButton live' %}"><i data-feather="radio"></i>&nbsp;{% trans 'Perform a BigBlueButton live' %}</a></h5>
Attention à toujours garder une structure cohérente dans les headings : ne jamais sauter un chiffre par exemple apres h3 vient h4, pas h5

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/list_meeting.html
> +<script type="text/javascript">
le type="text/javascript" est implicite en html5 et peut etre omis.

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/list_meeting.html
> +	<h5><a  href="{% url 'bbb:live_list_meeting' %}" title="{% trans 'Perform a BigBlueButton live' %}"><i data-feather="radio"></i>&nbsp;{% trans 'Perform a BigBlueButton live' %}</a></h5>
nb : y'a aussi un double espace sur le "<a  href" ;)

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_card.html
> +		padding-top:  4em !important;
L'indentation me semble assez grosse. 2 espaces suffisent ^^

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_card.html
> +    <div class="card-header" style="">
style="" inutile ?

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_card.html
> +				<span style="width: 100%; height:96px;">
ici aussi des grosses indentations. De manière générale indentez avec 2 espaces pour garder une cohérence

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_list_meeting.html
> +		<li class="breadcrumb-item" aria-current="page"><a href="{% url 'bbb:list_meeting' %}" title="{% trans 'My BigBlueButton records and lives' %}">{% trans 'My BigBlueButton records and lives' %}</a><
grosses indentations

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_list_meeting.html
> +	<h5>{% trans "No BigBlueButton session in progress found"%}</h5>
heading h4

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_list_meeting.html
> +<!--
Est-ce nécessaire d'ajouter ce bloc en commentaires ?

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_list_meeting.html
> +  var infinite = new Waypoint.Infinite({
Je crois que ce script est utilisé dans d'autres pages de Pod. Est-ce que ca vaudrait le coup de le mettre dans un fichier commun plutot que de le dupliquer ?

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_publish_meeting.html
> +		<a href="{% url 'bbb:list_meeting' %}" title="{% trans 'My BigBlueButton records and lives' %}">{% trans 'My BigBlueButton records and lives' %}</a>
indentation 2 espaces

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_publish_meeting.html
> +{% endblock more_script %}
toujours finir par une ligne vide

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_record_list.html
> +		{% include "bbb/live_card.html" %}
indentation 2 spaces

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_record_list.html
> +	Loading...
"Loading" à mettre dans un block {trans} ?

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/live_record_list.html
> +{% endspaceless %}
une petite ligne vide à la fin

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/publish_meeting.html
> +		<a href="{% url 'bbb:list_meeting' %}" title="{% trans 'My BigBlueButton records and lives' %}">{% trans 'My BigBlueButton records and lives' %}</a>
Ne jamais recopier le même texte en title et dans le lien : c'est déja assez contraignant d'être mal voyant, ne leur donnons pas du texte en doublon ^^

2021-03-18 09:20 UTC, Badatos commented on pod/bbb/templates/bbb/publish_meeting.html
> +		<a  href="{% url 'bbb:live_list_meeting' %}" title="{% trans 'Perform a BigBlueButton live' %}">{% trans 'Perform a BigBlueButton live' %}</a>
pas de title en doublon

2021-03-18 09:20 UTC, Badatos commented on pod/live/templates/live/live.html
> +			 <!-- https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 -->
est-ce utile ce lien cloudfront ?

2021-03-18 09:20 UTC, Badatos commented on pod/live/templates/live/live.html
> +					// message_sent
grosses indentations

2021-03-18 09:20 UTC, Badatos commented on pod/main/templates/navbar.html
> +				<a class="dropdown-item" href="{% url 'bbb:list_meeting' %}" title="{% trans 'My BigBlueButton records and lives' %}"><i data-feather="square"></i>&nbsp;{% trans 'My BigBlueButton records and liv
évitez les titles en doublon

2021-03-18 10:45 UTC, meschac38700 requested changes

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/models.py
> +    status = models.IntegerField(
On peut utiliser un ChoiceField, et ce passer par la même occasion de ces commentaires . tu en penses quoi ?

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/models.py
>      meeting = models.ForeignKey(Meeting,
Tant qu'on en est à modifier les noms des variables: pourquoi pas renommer ```meting``` par ```performer``` ou ```speaker``` et ainsi se passer du commentaire

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/forms.py
> +        self.fields['redis_channel'].widget = forms.HiddenInput()
Je verrai bien une boucle pour éviter de se répéter ici non ?
```Python
hidden_fields = ('meeting', 'start_date', 'end_date', 'status', 'user', 'server', 'broadcaster_id', 'redis_hostname', 'redis_port', 'redis_channel' )
for field in hidden_fields:
    self.fields[field].widget = forms.HiddenInput()
```
Voire même prevenir des erreurs, si jamais le champs n'existe pas 
```Python
hidden_fields = ('meeting', 'start_date', 'end_date', 'status', 'user', 'server', 'broadcaster_id', 'redis_hostname', 'redis_port', 'redis_channel' )
for field in hidden_fields:
    if self.fields.get(field, None):
        self.fields[field].widget = forms.HiddenInput()
```

Je vois que ```MeetingForm``` et ```LiveStreamForm``` heritent tous deux de forms.ModelForm et définissent des champs à cacher:

Je propose qu'on ait une classe commune de ces deux Forms (Meeting, LiveStream) qui hériterait de forms.ModelForm et aura comme attributs hidden_fields comme suite:

```Python
class BaseForm(forms.ModelForm):
    hidden_fields: tuple = ()
    def __init__(self, request, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        self.hide_fields()

    def hide_fields(self):
        if not USE_BBB_LIVE_DOWNLOADING:
            self.hidden_fields += ('download_meeting',)
        for field in self.hidden_fields:
            if self.fields.get(field, None):
            self.fields[field].widget = forms.HiddenInput()


class MeetingForm(BaseForm):
    hidden_fields = ('meeting_id', 'internal_meeting_id', 'session_date', 'encoding_step', 'recorded', 'recording_available', 'recording_url', 'thumbnail_url', 'encoded_by', 'last_date_in_progress' )
    def __init__(self, request, *args, **kwargs):
        super(MeetingForm, self).__init__(request, *args, **kwargs)

class LivestreamForm(BaseForm):
    hidden_fields = ('meeting', 'start_date', 'end_date', 'status', 'user', 'server', 'broadcaster_id', 'redis_hostname', 'redis_port', 'redis_channel' )
    def __init__(self, request, *args, **kwargs):
        super(LivestreamForm, self).__init__(request, *args, **kwargs)

```

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/forms.py
> +        # self.fields['meeting_name'].widget = forms.HiddenInput()
Autant l'enlever s'il ne sert plus non ?

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/admin.py
> +class MeetingAdminForm(MeetingForm):
On pourrait pas faire hériter Admin de SuperAdmin (voire, proposition meettingForm et livestreamForm)? ils ont les même props à l'exception de encoding_step

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_models.py
> +                                user=userJaneDoe)
Les indentations ici me semble trop non ? Est ceci ne passe pas avec Flake8 ?
```Python
Attendee.objects.create(
    id=2,
    full_name="Jane Doe",
    role="MODERATOR",
    username="pod2",
    meeting=meeting1,
    user=userJaneDoe)
```

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_models.py
> +                                meeting=meeting1)
Les indentations ici me semble trop non ? Est ceci ne passe pas avec Flake8 ?
```Python
Attendee.objects.create(
    id=1,
    full_name="John Doe",
    role="MODERATOR",
    meeting=meeting1)
```

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_models.py
> +                                          encoding_step=0)
Idem voir proposition indentation plus haut

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_models.py
> +                                  user=user1)
Idem voir proposition indentation plus haut

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_views.py
> +                                user=userJohnDoe)
Idem voir proposition indentation plus haut

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_views.py
>                                            encoding_step=0)
Idem voir proposition indentation plus haut

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_views.py
> +                                          encoding_step=0)
Idem voir proposition indentation plus haut

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_views.py
> +                                user=userJohnDoe)
Idem voir proposition indentation plus haut

2021-03-18 10:45 UTC, meschac38700 commented on pod/bbb/tests/test_views.py
> +                                  user=userJohnDoe)
Idem voir proposition indentation plus haut

2021-03-18 10:45 UTC, meschac38700 commented on pod/live/templates/live/live.html
> +		var returnMessage = "";
Il serait préférable d'utiliser let afin de bloquer la porté de cette variable à cette fonction dysplayReturnMessage et ainsi éviter quelconque bug sur les autres scripts
```Javascript
let returnMessage = "";
```

2021-03-18 10:45 UTC, meschac38700 commented on pod/live/views.py
> +        if len(livestreams_list) > 0:
Je remarque que tu vérifies souvent avant une boucle la taille de ta liste,
Je crois que la boucle for ne fait rien si l'itérable est vide

```Python
for n in []:
    print(n)
````
Out : 
```Python
 Nothing
```

2021-03-18 11:38 UTC, JoshuaBaubry reviewed
Pour moi c'est ok, niveau remarques rien à rajouter par rapport à @meschac38700

2021-03-19 14:45 UTC, ptitloup requested changes
Il manque le fichier .mo, il faudra refaire une passe niveau traduction en dev

2021-03-19 14:45 UTC, ptitloup commented on pod/main/context_processors.py
> +    new_settings['USE_BBB_LIVE'] = USE_BBB_LIVE
si ce paramètre n'est utilisé que dans un seul template, alors on peut le récupérer via le tag get settings plutot que de le passer  dans le context proc qui envoi ces variable pour tous les templates

2021-03-19 14:46 UTC, ptitloup commented
il y a des conflits avec la branche de dev. Pour les résoudre, il faudrait que tu fasses git pull origin dev depuis ta branche pour mettre à jour et gérer les conflits

2021-03-19 14:47 UTC, ptitloup commented
Voudrais-tu qu'on le mette en place  à ULille avant la mise en prod pour vérifier que tout est ok ?

2021-03-19 14:54 UTC, LoicBonavent commented on pod/bbb/admin.py
> +    def encode_video(self, request, queryset):
OK je fais çà

2021-03-19 14:56 UTC, LoicBonavent commented on pod/bbb/forms.py
> +        if instance.encoded_by is not None:
Cela correspond à l'utilisateur qui a encodé la présentation Web : on ne peut réencoder qu'une présentation Web qui appartient à quelqu'un.

2021-03-19 15:00 UTC, LoicBonavent commented on pod/bbb/templates/bbb/list_meeting.html
> +window.setInterval("location.reload(true)",30000);
Dans cette page, c'est pour que l'utilisateur puisse voir une présentation BBB qui vient d'être converti. Dans cette page, cela pourrait être plus que 30s, mais j'ai préféré rester cohérent avec la page de live, où ce refresh de 30s est calculé pour (le CRON pour les lives tournent toutes les minutes).

2021-03-19 15:01 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
Ok, je regarde çà, mais j'ai peur que cela surcharge à d'autres endroits.

2021-03-19 15:03 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    <footer class="card-footer p-0 m-1">
1 icône différent selon le statut, 1 libellé différent selon le statut

2021-03-19 15:05 UTC, LoicBonavent commented on pod/main/context_processors.py
> +    new_settings['USE_BBB_LIVE'] = USE_BBB_LIVE
Je pensais que c'était mieux comme cela : de centraliser les settings, quelque soit le nombre d'appels, non ?
Si faut, dans quelques temps, ce paramètre sera utilisé plusieurs fois.

2021-03-19 15:06 UTC, LoicBonavent commented
> Il manque le fichier .mo, il faudra refaire une passe niveau traduction en dev



> il y a des conflits avec la branche de dev. Pour les résoudre, il faudrait que tu fasses git pull origin dev depuis ta branche pour mettre à jour et gérer les conflits

Arf, je regarde çà.

2021-03-19 15:16 UTC, Badatos commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
attend que j'ai envoyé ma pr pour toucher à pod.css, sinon ca va faire des conflits ^^

2021-03-19 15:17 UTC, Badatos commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
ou si tu veux je l'ajoute moi pour voir

2021-03-19 15:18 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
Oui, je veux bien, merci

2021-03-19 15:52 UTC, LoicBonavent commented
> Voudrais-tu qu'on le mette en place à ULille avant la mise en prod pour vérifier que tout est ok ?

Non, je testerai en 1° en prod et on verra avec le 2° établissement.

2021-03-19 15:58 UTC, LoicBonavent commented
Euh, je ne sais pas quoi faire sur le coup... Suite aux conflits, j'ai modifié chaque conflit pour les résoudre et faire un merge. Et maintenant cela fait une erreur en lien avec flake, que je n'ai pas sur mon environnement.

2021-03-19 16:31 UTC, LoicBonavent commented
J'ai repushé après avoir fait les modifications en local (j'avais résolu les conflits sur l'interface Github) avec la traduction à jour.
Je ne comprends pas cette erreur de flake CI. je regarderai ça lundi. Bon week-end à tous

2021-03-22 07:37 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_list_meeting.html
> +  var infinite = new Waypoint.Infinite({
Non touché à ce jour

2021-03-22 07:38 UTC, LoicBonavent commented on pod/live/templates/live/live.html
> +			 <!-- https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 -->
Lien supprimé

2021-03-22 07:38 UTC, LoicBonavent commented on pod/main/templates/navbar.html
> +				<a class="dropdown-item" href="{% url 'bbb:list_meeting' %}" title="{% trans 'My BigBlueButton records and lives' %}"><i data-feather="square"></i>&nbsp;{% trans 'My BigBlueButton records and liv
Réalisé, mais juste sur les liens BBB

2021-03-22 07:43 UTC, LoicBonavent commented on pod/bbb/models.py
> +    status = models.IntegerField(
Utilisation de choices dans le model

2021-03-22 07:43 UTC, LoicBonavent commented on pod/bbb/models.py
>      meeting = models.ForeignKey(Meeting,
J'ai modifié les commentaires (qui étaient faux)

2021-03-22 07:43 UTC, LoicBonavent commented on pod/bbb/forms.py
> +        self.fields['redis_channel'].widget = forms.HiddenInput()
Yes, utilisation d'une boucle

2021-03-22 07:44 UTC, LoicBonavent commented on pod/bbb/admin.py
> +    def encode_video(self, request, queryset):
encode_video -> encode_meeting

2021-03-22 07:57 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
J'ai supprimé le text-align-center du style card-body et j'ai ajouté la classe py-4 pour le div card-body (<div class="card-body py-4">).
Par contre, je n'ai plus d'entête pour le titre de la session (ni couleur de fond ni style de texte); cela correspond à la classe card-header. Il y a eu des changements de ce côté ?

2021-03-22 07:59 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
Cf. image ci-jointe (titre = Webinaire de test 01)
![Capture d’écran (10)](https://user-images.githubusercontent.com/56730254/111957846-d1b2c100-8aec-11eb-9bee-c2e68e669a8e.png)

2021-03-22 08:13 UTC, LoicBonavent commented on pod/bbb/admin.py
> +class MeetingAdminForm(MeetingForm):
je n'ai pas mis : bool, car cela gênait flake compliance (pas lors de mes tests, mais sur ceux de github). Par contre, j'ai mis en place l'héritage

2021-03-22 08:15 UTC, LoicBonavent commented
> Il manque le fichier .mo, il faudra refaire une passe niveau traduction en dev

J'ai refais une passe sur les traductions et mis le fichier .mo

2021-03-22 08:17 UTC, LoicBonavent commented
Oup, j'ai Closed la PR.. je voulais juste faire un Resolve conversation.. J'espère que cela n'a pas trop d'impact :(

2021-03-22 08:21 UTC, meschac38700 commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
@LoicBonavent petite correction texte ```peut de temps apres avoir [...] et  'sélectionné' ```

2021-03-22 08:23 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
@meschac38700 Olivier voulait également l'ajouter dans pod.css, mais comme ce style n'est utilisé que dans cette seule page, on l'avait laissé comme cela. C'est comme vous voulez. Pour ma part, je pense qu'il ne reste plus que ce point...

2021-03-22 08:25 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
Ouch, merci @meschac38700 : magnifique cette faute :)

2021-03-22 08:27 UTC, meschac38700 commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
@LoicBonavent Ok mais la bonne pratique serait d'avoir un dossier static dans l'app BBB, tu pourrais ajouter une classe ou ID sur les card des live pour pouvoir les distinguer au niveau css des card vidéo ?

2021-03-22 08:31 UTC, meschac38700 commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
> Ouch, merci @meschac38700 : magnifique cette faute :)
cela dit, pareil pour ```1 session [...] trouvée``` :+1:

2021-03-22 08:33 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
un dossier static dans bbb ? Ah oui, je ne savais pas que c'était possible dans Pod. je pensais que c'était seulement via le pod.css de l'appli. Si cela va à tout le monde, je créé un dossier static et je mets un fichier css avec un style bbb-card-live.

2021-03-22 08:38 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
A force de travailler dessus, je ne lis plus les messages ni les fautes :( Je vais refaire une passe pour voir s'il y a d'autres fautes.

2021-03-22 08:39 UTC, ptitloup commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
oui ca nous va d'ailleurs je pense que c'est ce qu'il faut faire

2021-03-22 10:22 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
Au final, je n'ai pas besoin de css spécifique : comme Olivier a ajouté : .card-body { text-align: center; } dans pod.ss

Le seul problème qui reste est que le card-header a été mis en commentaire dans pod.css; s'il s'applique comme avant, ce sera tout bon. @Badatos c'est possible ?

2021-03-22 10:28 UTC, Badatos commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
Quelle est la partie de .card-header{} dont tu as besoin ? il me semble que c'est déjà définit dans bootstrap et qu'il n'y a normalement pas besoin de le rajouter.

2021-03-22 10:30 UTC, Badatos commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
J4ai beau regarder https://github.com/EsupPortail/Esup-Pod/blob/dev/pod/main/static/css/pod.css je ne vois rien en commentaire pour card-header... o_O

2021-03-22 10:33 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
a priori, sur l'ancien pod.css, il y avait un espace entre #videos_list et .card-header.
Ce style s'appliquait dans ce cas.
Maintenant cela ne s'applique plus.

2021-03-22 11:07 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
Tu me dis si je dois faire du style spécifique (ou pas) :) Merci

2021-03-22 11:24 UTC, Badatos commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
il y a plusieurs styles dans pod.css ou il manquaient un espace en effet j'en ai corrigé certains, ptet que celui-la en fait partie et qu'il faut aussi lui ajouter l'espace.

2021-03-22 12:40 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
En y réfléchissant, c'est quand même couillon d'avoir des listes avec un id = videos_list, alors que ce ne sont pas des listes de videos. Je vais alors faire propre et créé un style spécifique dans static local, avec un bon id, style bbb_meetings_list.
Merci

2021-03-22 13:20 UTC, LoicBonavent commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
C'est fait. je viens de pusher.

2021-03-22 13:22 UTC, LoicBonavent commented
Je viens de pusher : j'en ai fini avec cette PR . Enfin.
Au moins, j'ai progressé avec Git :)

2021-03-22 13:23 UTC, ptitloup commented on pod/bbb/templates/bbb/live_card.html
> +    .card-body {
Merci !

2021-03-22 13:28 UTC, ptitloup commented on pod/main/context_processors.py
> +    new_settings['USE_BBB_LIVE'] = USE_BBB_LIVE
ok !

2021-03-22 13:28 UTC, ptitloup approved these changes
Ok pour moi !

2021-03-22 13:34 UTC, merged

2021-03-22 13:46 UTC, Badatos approved these changes
voila j'ai ajouté quelques dernières remarques. essentielement de l'optimisation et un point d'accessibilité.
Rien de bloquant en tout cas si vous voulez merger tout de suite. (faudra juste le faire plus tard ;)

2021-03-22 13:46 UTC, Badatos commented on pod/bbb/templates/bbb/list_meeting.html
> +  <link rel="stylesheet" href="{% static 'css/bbb.css' %}"/>
il faudrait ajouter "?ver={{VERSION}}" après chaque fichier css /js : cela permet de les mettre en cache longtemps, il seront redemandés par le navigateur lors d'une maj de Pod

2021-03-22 13:46 UTC, Badatos commented on pod/bbb/templates/bbb/live_list_meeting.html
> +  <script type="text/javascript">
pareil, ajouter "?ver={{VERSION}}" sur le css, et virer le "type text/javascript" inutile

2021-03-22 13:46 UTC, Badatos commented on pod/bbb/templates/bbb/live_list_meeting.html
> +<script src="{% static 'js/infinite.min.js' %}"></script>
ajouter des ?ver={{VERSION}} sur les .js

2021-03-22 13:46 UTC, Badatos commented on pod/bbb/templates/bbb/live_record_list.html
> +    <a class="infinite-more-link" href="{{ full_path }}{% if '?' in full_path %}&{% else %}?{%endif%}page={{ records.next_page_number }}">More</a>
il manque des balises "trans" sur le texte "More"

2021-03-22 13:46 UTC, Badatos commented on pod/bbb/templates/bbb/record_list.html
>    <a class="infinite-more-link" href="{{ full_path }}{% if '?' in full_path %}&{% else %}?{%endif%}page={{ records.next_page_number }}">More</a>
idem : {% trans  sur "More"

2021-03-22 13:46 UTC, Badatos commented on pod/live/templates/live/live.html
> +				<textarea name="message" rows="2" cols="90" maxlength="100" class="form-control" id="message"></textarea>
Il manque un label à ce textarea