Ptitloup/feature add web recorder
EsupPortail/Esup-Pod pull request #465
Opened 2021-03-24 18:19 UTC by ptitloup

2021-03-31 12:17 UTC, Badatos commented on pod/main/templates/navbar.html
> +          <a class="dropdown-item" href="{% url 'video_record' %}" title="{% trans 'Video Record' %}"><i data-feather="video"></i>&nbsp;{% trans "Video Record" %}</a>
Tu ajoutes le lien "Video record" pour tout le monde ? est-ce qu'on ne le rend pas activable via les settings ?

2021-03-31 12:20 UTC, Badatos commented on pod/video/static/record/browser-workarounds.js
> +    if (adapter.browserDetails.browser == 'firefox') {
est-ce que "=== 'firefox'" ne serait pas mieux ?

2021-03-31 12:25 UTC, Badatos commented on pod/video/static/record/videojs.record.min.css
> +Default styles for videojs-record 4.3.0
Je propose qu'on range les fichiers provenants de tiers dans un dossier du genre "static/vendor", cela permettra de plus facilement les distinguer de nos propres css/js

2021-03-31 12:26 UTC, Badatos commented on pod/video/templates/videos/video_record.html
> +  background-color: #ede4b7;
Peux-t-on utiliser une variable CSS plutôt qu'une couleur définie ?

2021-03-31 12:27 UTC, Badatos commented on pod/video/templates/videos/video_record.html
> +      	<div itemprop="video" itemscope itemtype="http://schema.org/VideoObject">
des grosses indentations ici. merci d'indenter avec 2 espaces dans les templates html svp ^^.

2021-03-31 12:28 UTC, Badatos commented on pod/video/templates/videos/video_record.html
> +var options = {
est-ce que ce script pourrait se mettre dans un fichier .js à part ?

2021-03-31 13:10 UTC, ptitloup commented on pod/main/templates/navbar.html
> +          <a class="dropdown-item" href="{% url 'video_record' %}" title="{% trans 'Video Record' %}"><i data-feather="video"></i>&nbsp;{% trans "Video Record" %}</a>
on pourrait le rendre activable par les settings mais vu que l'enregistrement se fait dans la memoire du navigateur, il n'y a pas d'impact de charge pour la plateforme.

2021-03-31 13:11 UTC, ptitloup commented on pod/main/templates/navbar.html
> +          <a class="dropdown-item" href="{% url 'video_record' %}" title="{% trans 'Video Record' %}"><i data-feather="video"></i>&nbsp;{% trans "Video Record" %}</a>
Qui vote pour rajouter un settings ? @meschac38700 et @JoshuaBaubry  ?

2021-03-31 13:12 UTC, ptitloup commented on pod/video/static/record/browser-workarounds.js
> +    if (adapter.browserDetails.browser == 'firefox') {
je l'ai récupéré telquel sur ce site : https://collab-project.github.io/videojs-record/

2021-03-31 13:13 UTC, ptitloup commented on pod/video/static/record/videojs.record.min.css
> +Default styles for videojs-record 4.3.0
les fichiers js et css des app tiers sont dans un repertoire au nom de l'app ou de la fonctionnalité. i.e.: record ou player... mais bon, je suis pas sur que ce soit tout le temps le cas :'(

2021-03-31 13:14 UTC, ptitloup commented on pod/video/templates/videos/video_record.html
> +  background-color: #ede4b7;
oui tout à fait, on pourrait même le rajouter dans pod.css mais là, c'est pour bien distinguer un player de vidéo, d'un player de device

2021-03-31 13:15 UTC, ptitloup commented on pod/video/templates/videos/video_record.html
> +var options = {
le script fonctionnel si, le script de paramétrage non mais je vais améliorer cela, c'était pour faciliter la relecture

2021-03-31 13:17 UTC, Badatos commented on pod/video/static/record/videojs.record.min.css
> +Default styles for videojs-record 4.3.0
j'avais dans l'idée d'ajouter prochainement une github action pour lancer un "eslint" sur nos fichiers JS.
Ce sera plus facile d'ignorer tout ce qui se trouve dans "vendor/**" que d'ajouter une ligne aux fichiers ignorés à chaque nouveau package ^^. 
On pourrait avoir "vendor/player" et "vendor/recorder" ?

2021-03-31 13:18 UTC, Badatos commented on pod/video/static/record/videojs.record.min.css
> +Default styles for videojs-record 4.3.0
et si ensuite on ajoute aussi un systeme pour minifier automatiquement nos css, pareil ce sera plus facile de minifier tout ce qui n'est pas dans "vendor/*"

2021-03-31 13:19 UTC, ptitloup commented on pod/video/static/record/videojs.record.min.css
> +Default styles for videojs-record 4.3.0
oui tout à fait, ca me convient, je vais faire cela pour recorder. Attention toutefois au fait que déplacer des js ou css implique de bien checker tous les appels qu'il faut modifier

2021-03-31 13:25 UTC, Badatos commented on pod/video/static/record/videojs.record.min.css
> +Default styles for videojs-record 4.3.0
oui tout à fait, c'est pour ca que je ne vais pas tenter avant que la 2.8 soit sortie ^^, mais la autant le faire pour les nouvelles entrées déjà :)

2021-03-31 13:43 UTC, ptitloup commented on pod/video/templates/videos/video_record.html
> +  background-color: #ede4b7;
![Capture d’écran 2021-03-31 à 15 42 55](https://user-images.githubusercontent.com/4640002/113153909-cfacd880-9237-11eb-8496-b52eb3821322.png)

2021-03-31 13:43 UTC, ptitloup commented on pod/video/templates/videos/video_record.html
> +  background-color: #ede4b7;
moi j'aime bien

2021-03-31 14:35 UTC, ptitloup commented on pod/video/static/record/videojs.record.min.css
> +Default styles for videojs-record 4.3.0
c'est fait pour record

2021-04-01 07:08 UTC, meschac38700 requested changes

2021-04-01 07:08 UTC, meschac38700 commented on pod/video/static/vendor/record/RecordRTC.js
> +// Last time updated: 2021-03-09 3:20:22 AM UTC
@ptitloup Si on n'est pas emmené à modifier ce code, je propose de le minifier https://javascript-minifier.com/

2021-04-01 07:08 UTC, meschac38700 commented on pod/video/static/vendor/record/adapter.js
> +
idem pour le minifier

2021-04-01 07:08 UTC, meschac38700 commented on pod/video/static/vendor/record/browser-workarounds.js
> +            // support recording in safari 11/12
idem pour le minifier même si on peut s'en passer au vu de la taille du fichier

2021-04-01 16:26 UTC, ptitloup commented on pod/video/static/vendor/record/RecordRTC.js
> +// Last time updated: 2021-03-09 3:20:22 AM UTC
fait

2021-04-01 16:27 UTC, ptitloup commented on pod/main/templates/navbar.html
> +          <a class="dropdown-item" href="{% url 'video_record' %}" title="{% trans 'Video Record' %}"><i data-feather="video"></i>&nbsp;{% trans "Video Record" %}</a>
je viens de rajouter un settings pour activer le recorder

2021-04-01 16:35 UTC, ptitloup commented on pod/main/templates/navbar.html
> +          <a class="dropdown-item" href="{% url 'video_record' %}" title="{% trans 'Video Record' %}"><i data-feather="video"></i>&nbsp;{% trans "Video Record" %}</a>
fait pour les nbsp !

2021-04-02 17:53 UTC, meschac38700 commented
@ptitloup  c'est bon pour moi, une seule remarque, pourquoi on garde les scripts JS non minifiés ?

2021-04-06 12:23 UTC, JoshuaBaubry approved these changes
Ok pour moi !

2021-04-07 12:08 UTC, ptitloup commented
merci pour vos review, j'ai rajouté un petit test pour la vue histoire de passer mieux le covergage

2021-04-07 12:10 UTC, merged