Fix bug + filter by cursus + some improvement
EsupPortail/Esup-Pod pull request #474
Opened 2021-04-07 14:23 UTC by JoshuaBaubry

2021-04-07 15:44 UTC, ptitloup requested changes
faire une passe pour ajotuer de l'ajax sur tous les select2. Merci !

2021-04-07 15:44 UTC, ptitloup commented on pod/video/models.py
> +    users = select2_fields.ManyToManyField(
mettre ajax à true partout

2021-04-07 15:57 UTC, JoshuaBaubry commented
J'ai mis les options mais au final je pense que le temps de chargement viens du fait qu'on récupère des Owner et pas des User comme dans les autres select2, à tester !

2021-04-08 11:48 UTC, ptitloup approved these changes
ok pour moi !

2021-04-08 11:48 UTC, merged