Ptitloup/add cookie dialog
EsupPortail/Esup-Pod pull request #476
Opened 2021-04-08 16:21 UTC by ptitloup

2021-04-08 16:22 UTC, ptitloup commented
il manque les traductions mais vous pouvez déjà me dire ce que vous en pensez

2021-04-08 16:25 UTC, meschac38700 requested changes

2021-04-08 16:25 UTC, meschac38700 commented on pod/custom/settings_local.py.example
> +# Lien pour en avoir plus sur dialog de consentement du cookie
pour en savoir* tu voulais dire ?

2021-04-08 16:25 UTC, meschac38700 commented on pod/main/static/js/main.js
> +    var expiryDate = new Date();
seulement quand je me réjouissais de voir les 'let' en haut :-1:

2021-04-08 16:26 UTC, ptitloup commented on pod/custom/settings_local.py.example
> +# Lien pour en avoir plus sur dialog de consentement du cookie
ha oui ! :-)

2021-04-08 16:27 UTC, ptitloup commented on pod/main/static/js/main.js
> +    var expiryDate = new Date();
ha oui, un var qui traine, les vieilles habitudes restent !

2021-04-09 08:07 UTC, ptitloup reviewed
ok pour moi.

2021-04-09 08:22 UTC, meschac38700 commented on pod/custom/settings_local.py.example
> +# Lien pour en savoir plus sur dialog de consentement du cookie
@ptitloup  la boite de dialogue de consentement ?

2021-04-09 08:28 UTC, meschac38700 commented
@ptitloup  c'est bon pour moi

2021-04-09 08:35 UTC, merged