multiple small corrections (bugfixes on video chapters + enrichments)
EsupPortail/Esup-Pod pull request #485
Opened 2021-05-11 15:07 UTC by Badatos

BugFix :
+ Corrects a bug when there are both video chapters and enrichments, causing chapter being masked by enrichments.
+ Corrects a bug causing rich text lists (li) inside enrichments behing hidden by css

CSS : 
+ Replace class "special_class" by "required_star", as it represents more its purpose.
+ Replace .card-takenote by #card-takenote as it is an id

Accessibility :
+ correct colors used for enrichments types (replace yellow by orange, and add contrast to blue and green. now use css --vars)
+ correct some tables (add scopes on th and titles on empty th)

Other :
+ Replace licence.md by official GNU lesser GPL (COPYING + COPYING.LESSER)
+ some code formatting
+ remove unwanted </style> in video_edit.html

2021-05-12 08:44 UTC, ptitloup requested changes
Juste une quetion au niveau du tempalte 500. De même, sauf erreur de ma part, il manque le fichier compilé django.mo. Merci bcp !

2021-05-12 08:44 UTC, ptitloup commented on pod/main/templates/500.html
> +{% block page_title %}{% trans 'Server error (500)' %}{% endblock %}
Je ne suis pas certain qu'on puisse faire du templating pour du 500. Par exemple, le trans et/ou l'extend, fonctionne-t-il en erreur 500 ? Joshua, tu sais ca ?

2021-05-12 08:49 UTC, Badatos commented on pod/main/templates/500.html
> +{% block page_title %}{% trans 'Server error (500)' %}{% endblock %}
Le trans est en tout cas géré : ils l'utilisent dans la page "500" de django admin

2021-05-12 08:53 UTC, ptitloup commented on pod/main/templates/500.html
> +{% block page_title %}{% trans 'Server error (500)' %}{% endblock %}
ok merci pour la confirmation, j'avais un doute. On peut laisser le template telquel alors

2021-05-12 09:34 UTC, Badatos commented
En effet, je n'avais pas recompilé les .mo :/ Voila qui est fait ;)

2021-05-12 09:38 UTC, ptitloup approved these changes
Ok, parfait pour moi, merci !

2021-05-17 08:20 UTC, JoshuaBaubry approved these changes
Tout est bon pour moi

2021-05-17 08:57 UTC, merged