add aside iframe
EsupPortail/Esup-Pod pull request #494
Opened 2021-05-25 14:39 UTC by JoshuaBaubry

2021-05-26 12:09 UTC, ptitloup reviewed
ok pour moi niveau code mais pls question : quid de l'affichage de l'iframe ? est-ce que le champ est remplissable dans l'admin ? Merci pour le taf !

2021-05-26 12:09 UTC, ptitloup commented on pod/live/templates/live/live.html
> +
Pour ma part, j'aurai plutôt mis l'iframe dans le code du player avec un bouton afficher/cacher plutot que dans la colonne de droite. Qu'en penses-tu ?

2021-05-26 13:53 UTC, JoshuaBaubry commented on pod/live/templates/live/live.html
> +
> Pour ma part, j'aurai plutôt mis l'iframe dans le code du player avec un bouton afficher/cacher plutot que dans la colonne de droite. Qu'en penses-tu ?

Ah d'accord le but est de mettre l'iframe directement sur le player, je n'avais pas compris ça

2021-05-26 13:55 UTC, ptitloup commented on pod/live/templates/live/live.html
> +
ben moi je le mettrais ici : https://github.com/EsupPortail/Esup-Pod/blob/master/pod/live/templates/live/live.html#L49 avec un partage genre 70/30 ou un truc comme ca

2021-05-26 13:56 UTC, JoshuaBaubry commented on pod/live/templates/live/live.html
> +
ok je vais faire ça !

2021-05-28 06:25 UTC, ptitloup commented on pod/live/templates/live/live.html
> +
merci !

2021-06-08 03:22 UTC, JoshuaBaubry commented on pod/live/templates/live/live.html
> +
J'ai fais des test et l'iframe ne semble pas s'afficher lorsqu'elle est mise ici

2021-06-23 22:45 UTC, JoshuaBaubry commented on pod/live/templates/live/live.html
> +
Du coup on la laisse sur le coté ou tu aurais une solution ? car j'ai tenté de l'intégrer sur le coté du lecteur mais je n'ai rien trouvé de concluant

2021-06-24 06:31 UTC, ptitloup commented
Tu me dis quand c'est bon pour toi que je fasse une review

2021-06-24 15:56 UTC, JoshuaBaubry commented
> Tu me dis quand c'est bon pour toi que je fasse une review

regarde la conversation du haut j'ai répondu

2021-06-25 06:34 UTC, ptitloup commented
ha pardon j'avais pas vu, il me faudrait du temps pour regarder, pour l'instant laisse comme cela et on améliorera s'il faut plus tard. Merci !

2021-07-09 15:03 UTC, JoshuaBaubry commented
@ptitloup prête à être recview

2021-07-09 15:05 UTC, ptitloup commented
ok je regarde ca merci !

2021-07-09 15:21 UTC, ptitloup commented on pod/live/templates/live/live.html
> +
du coup, elle est ou ton iframe, dans le player ou dans la colonne de droite ?

2021-07-12 13:35 UTC, ptitloup commented
tu pourrais remettre en WIP et voir si mettre la video en row/col fonctionne ? merci !

2021-07-12 13:35 UTC, ptitloup commented
et il y a des conflits au niveau de la traduction

2021-07-16 10:15 UTC, JoshuaBaubry commented
Je m'occupe de ça

2021-07-16 12:09 UTC, ptitloup requested changes

2021-07-16 12:09 UTC, ptitloup commented on pod/live/templates/live/live.html
> +        <div class="col">
Attention, pour moi il ne faut faire apparaitre l'iframe de chat que si il y a une url... merci de rajouter le test dans les 2 cas (video on hold et non)

2021-07-16 12:25 UTC, ptitloup approved these changes
ok pour moi, je merge

2021-07-16 12:28 UTC, merged