[WIP] Add camera to screen recording - Not in progress, project with opencast studio in progress
EsupPortail/Esup-Pod pull request #496
Opened 2021-05-26 17:31 UTC by ptitloup

2021-05-28 06:27 UTC, ptitloup commented
@meschac38700 le front est quasi terminé, il me reste le back.

2021-05-28 07:07 UTC, meschac38700 commented
@ptitloup  On pourrait ajouter le dossier static pour extraire les js et css qui sont melangés au html non ?
même avoir des classes Css pour des cas comme celui ci:
![image](https://user-images.githubusercontent.com/36244941/119944110-2a428680-bf94-11eb-9723-3d9c8e2eafcb.png)

2021-05-28 07:17 UTC, ptitloup commented
> @ptitloup On pourrait ajouter le dossier static pour extraire les js et css qui sont melangés au html non ?
> même avoir des classes Css pour des cas comme celui ci:
> ![image](https://user-images.githubusercontent.com/36244941/119944110-2a428680-bf94-11eb-9723-3d9c8e2eafcb.png)

Ok merci, je vais regarder tout ca

2021-07-12 12:55 UTC, meschac38700 requested changes

2021-07-12 12:55 UTC, meschac38700 commented on pod/video/templates/videos/video_record.html
> +}
@ptitloup il serait plus propre de séparer le css du html lorsque ce n'est pas un iframe

2021-07-12 12:55 UTC, meschac38700 commented on pod/video/templates/videos/video_record.html
> +let options = {
@ptitloup  :+1:  `const` `let`
néanmoins un objet est bien souvent une constante si on n'est pas amené à modifier que les attributs de l'objet 
```
options.controls=false;
```
plutôt que l'objet lui meme 
``` 
options = {};
```

2021-07-12 12:55 UTC, meschac38700 commented on pod/video/templates/videos/video_record.html
> +    }
@ptitloup ca fait beaucoup de JS dans le html, faudrait pas également créer un fichier et le charger par la suite ?

2021-07-12 13:08 UTC, ptitloup commented
Bonjour et merci @meschac38700 pour cette review. Cette PR est encore en WIP et oui en effet, il faudrait déplacer la css dans un fichier à part ainsi que le JS qui commence à être conséquent.

2022-01-12 14:17 UTC, closed without merging