Joshua baubry/feature filterchannels
EsupPortail/Esup-Pod pull request #511
Opened 2021-06-23 23:36 UTC by JoshuaBaubry

2021-06-24 06:36 UTC, ptitloup commented
@JoshuaBaubry tu peux rajouter WIP si ta PR est en cours de realisation ? merci ! (ca permet de voir ce qui est en cours de ce qui est terminé)

2021-07-12 12:47 UTC, meschac38700 reviewed
@JoshuaBaubry :+1:  juste une remarque:
   - Pourquoi avoir nommé le model `AddChannelsTab` et pas simplement `ChannelsTab` ?

2021-07-16 10:47 UTC, JoshuaBaubry commented
> @JoshuaBaubry 👍 juste une remarque:
> 
> * Pourquoi avoir nommé le model `AddChannelsTab` et pas simplement `ChannelsTab` ?

AddChannelTab = "Additional channels tab" -> "en plus de la tab de base"

2021-07-16 10:48 UTC, JoshuaBaubry commented
@ptitloup de mémoire cette PR est prête à être review à moins que tu te souviennes d'un détails que j'aurais oublié

2021-07-16 11:45 UTC, ptitloup requested changes
ok pour moi !
peut-etre rajouter des tests unitaires sur ce nouvel element ? merci

2021-07-17 21:45 UTC, meschac38700 requested changes
@JoshuaBaubry  quelques remarques

2021-07-17 21:45 UTC, meschac38700 commented on pod/main/tests/test_models.py
> +        self.assertEqual(tab.name, "Tab0")
@JoshuaBaubry plutôt que de tester l'attribut `name`, on peut tester l'instance non ?
```Python
self.self.assertIsInstance(tab, AddChannelsTab)
```
Par exemple, tester que le name == Tab0 alors que c'est une donnée appliqué à l'instant, n'assure pas vraiment le bon fonctionnement du code. à mon avis.

2021-07-17 21:45 UTC, meschac38700 commented on pod/main/tests/test_models.py
> +        print("   --->  test_exist of AddChannelsTabTestCase : OK !")
@JoshuaBaubry Ces deux tests `test_exist` et `test_attributs` peuvent etre un seul non ? (voire commentaire test_attributs)

2021-07-17 21:45 UTC, meschac38700 commented on pod/main/tests/test_models.py
> +        self.assertEqual(conf.description, "Activation of maintenance mode or not")
Meme remarque que sur AddChannelsTab, tester que le key == "maintenance_mode" alors même qu'on l'a utilisé pour récuperer l'objet conf ou maintenance_conf, ne me parait pas utile.
Merger peut etre les deux tests `test_exists` et `test_attributes` en testant l'existance de l'object lui même et peut etre son type.
```Python
conf = Configuration.objects.filter(key="maintenance_mode").first()
self.assertIsNot(conf, None)
self.assertIsInstance(conf, Configuration)
```

2021-07-17 21:45 UTC, meschac38700 commented on pod/main/tests/test_models.py
> +        self.assertEquals(AddChannelsTab.objects.filter(name="Tab0").count(), 0)
Peut être utiliser `assertIsNone` ici ?
```Python
self.assertIsNone(AddChannelsTab.objects.filter(name="Tab0").first())
```

2021-07-17 21:47 UTC, meschac38700 commented
> > @JoshuaBaubry +1 juste une remarque:
> > 
> > * Pourquoi avoir nommé le model `AddChannelsTab` et pas simplement `ChannelsTab` ?
> 
> AddChannelTab = "Additional channels tab" -> "en plus de la tab de base"

@JoshuaBaubry Ah ok, ben sinon autant le nommer explicitement `AdditionnalChannelTab` non ? parce que perso, j'ai compris Add (ajouter), t'en penses quoi ?

2021-08-20 07:06 UTC, JoshuaBaubry commented on pod/main/tests/test_models.py
> +        self.assertEqual(tab.name, "Tab0")
Je suis plutot d'accord sur le fond de ta remarque mais j'ai simplement pris modèle sur tout les test de modèle qu'on peut trouver dans pod. Je prend pour exemple ceci extrait des tests de l'app recorder : 

        recorder1 = Recorder.objects.get(id=1)
        self.assertEqual(recorder1.name, "recorder1")
        self.assertEqual(recorder1.address_ip, "16.3.10.37")
        self.assertEqual(recorder1.directory, "dir1")

2021-08-20 07:06 UTC, JoshuaBaubry commented on pod/main/tests/test_models.py
> +        self.assertEqual(conf.description, "Activation of maintenance mode or not")
Je suis plutot d'accord sur le fond de ta remarque mais j'ai simplement pris modèle sur tout les test de modèle qu'on peut trouver dans pod. Je prend pour exemple ceci extrait des tests de l'app recorder : 

        recorder1 = Recorder.objects.get(id=1)
        self.assertEqual(recorder1.name, "recorder1")
        self.assertEqual(recorder1.address_ip, "16.3.10.37")
        self.assertEqual(recorder1.directory, "dir1")

2021-08-20 07:13 UTC, JoshuaBaubry commented
> > > @JoshuaBaubry +1 juste une remarque:
> > > 
> > > * Pourquoi avoir nommé le model `AddChannelsTab` et pas simplement `ChannelsTab` ?
> > 
> > 
> > AddChannelTab = "Additional channels tab" -> "en plus de la tab de base"
> 
> @JoshuaBaubry Ah ok, ben sinon autant le nommer explicitement `AdditionalChannelTab` non ? parce que perso, j'ai compris Add (ajouter), t'en penses quoi ?

Yep bonne idée

2021-09-13 12:30 UTC, ptitloup approved these changes
ok pour moi ! Top, merci

2021-09-13 12:31 UTC, merged