Fix playlist bugs (loop, autoplay, player do not select the right cur…
EsupPortail/Esup-Pod pull request #515
Opened 2021-07-09 02:47 UTC by gcondess

Fix playlist bugs (loop, autoplay, current video selection when it is in to 2 playlist)
Enable a plailist to be display in iframe

2021-07-12 12:42 UTC, meschac38700 requested changes
@gcondess quelques remarques:
   - j'aurai bien vu le fichier `videojs-playlist-controlbar.js` dans l'app playlist => `playlist/static/js/videojs-playlist-controlbar.js`
   - les lignes de codes commentées sont à supprimer si elles ne servent plus, Git s'occuper de versionner les modifs

2021-07-16 10:21 UTC, JoshuaBaubry requested changes
A part la remarque que j'ai noté qui rejoins Eliam sur le placement du fichier JS, le reste à l'air OK

2021-07-16 10:21 UTC, JoshuaBaubry commented on pod/main/static/js/videojs-playlist-controlbar.js
> +(function() {
Je rejoins Eliam sur le fait que ce JS devrait se trouver du coup de l'apli playlist pour plus de cohérence, sinon RAS

2021-07-22 14:09 UTC, ptitloup requested changes

2021-07-22 14:09 UTC, ptitloup commented on pod/video/views.py
> +def video_all_info(request, slug, slug_private=None):
pourquoi passer le slug et le slug_private ? Cette vue ne peut s'appeler qu'en Ajax ? si oui, alors il faudrait la sécuriser avec is_ajax et renvoyer du json avec les infos si les autorisations sont là sinon renvoyer une erreur. Qu'en penses-tu ?

2021-07-22 14:09 UTC, ptitloup commented on pod/video/views.py
> +def video_all_info(request, slug, slug_private=None):
il me semble que tu as une commande qui s'appelle render_to_string, regarde dans le fichier view, tu dois avoir des exemples

2021-07-22 15:03 UTC, gcondess commented
Pour l'instant cette vue n'est affectivement appelée que par ajax mais le but est de se servir du template video-all-info (également inclut le template videos/video.html). 
J'avais conservé le slug private au cas ou la possibilité d'ajouter des vidéos privée dans les playlist apparaitrait un jour... Actuellement tu as raison ça ne sert à rien ! 

Je suis d'accord sur la sécurisation avec is_ajax si on peut conserver un rendu HTML plutot que JSON. 
Un rendu JSON nécessiterai de refaire le template video-all-info.html en js => potentiels problèmes de maintenance pour garder la cohérence entre le rendu du template et celui du JS 

Guillaume 

De: "Eliam LOTONGA" ***@***.***> 
À: "EsupPortail/Esup-Pod" ***@***.***> 
Cc: "Guillaume Condesse" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Jeudi 22 Juillet 2021 16:09:36 
Objet: Re: [EsupPortail/Esup-Pod] [WIP] Fix playlist bugs and enable playlist has iframe (#515) 





@ptitloup requested changes on this pull request. 


In [ https://github.com/EsupPortail/Esup-Pod/pull/515#discussion_r674828786 | pod/video/views.py ] : 
> @@ -665,6 +665,52 @@ def get_video_access(request, video, slug_private):

         return True

 

 

+def video_all_info(request, slug, slug_private=None): 


pourquoi passer le slug et le slug_private ? Cette vue ne peut s'appeler qu'en Ajax ? si oui, alors il faudrait la sécuriser avec is_ajax et renvoyer du json avec les infos si les autorisations sont là sinon renvoyer une erreur. Qu'en penses-tu ? 


In [ https://github.com/EsupPortail/Esup-Pod/pull/515#discussion_r674829517 | pod/video/views.py ] : 
> @@ -665,6 +665,52 @@ def get_video_access(request, video, slug_private):

         return True

 

 

+def video_all_info(request, slug, slug_private=None): 


il me semble que tu as une commande qui s'appelle render_to_string, regarde dans le fichier view, tu dois avoir des exemples 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, [ https://github.com/EsupPortail/Esup-Pod/pull/515#pullrequestreview-712826565 | view it on GitHub ] , or [ https://github.com/notifications/unsubscribe-auth/ACRMRYQFVWVJWR5AQYBYYADTZARCBANCNFSM5AB4LTKA | unsubscribe ] .

2021-07-22 16:12 UTC, meschac38700 requested changes
@gcondess voilà quelques remarques pour moi.

2021-07-22 16:12 UTC, meschac38700 commented on pod/playlist/templates/playlist/playlist_player.html
> +  $('#playlist div').first()
@gcondess Il serait plus propre d'extraire ce js dans un fichier JS à part. un fichier dont on nommerait peut être `playlist_player.js` dans le dossier `pod/playlist/static/playlist/js/`
Il serait également préferable de changer là où ces possible les `var` par des `let` ou `const` si la variable ne change pas

2021-07-22 16:12 UTC, meschac38700 commented on pod/playlist/templates/playlist/playlist_player.html
> +    var current_element = $('.playlist-videos div.row .on .card')[0];
@gcondess  ces deux là par exemple `let` plutôt que `var`

2021-07-22 16:12 UTC, meschac38700 commented on pod/playlist/templates/playlist/playlist_player.html
> +      var py = $(window).scrollTop();
@gcondess 
```Javascript
var auto;
var loop;
var py;
``` 
ces variables devraient être:
```Javascript
const auto;
const loop;
const py;
```

2021-07-22 16:12 UTC, meschac38700 commented on pod/playlist/templates/playlist/playlist_player.html
> +      var parameters ='&py='+py;
@gcondess 
```Javascript
let parameters;
```

2021-07-22 16:12 UTC, meschac38700 commented on pod/playlist/templates/playlist/playlist_player.html
> +        var current_url = current_element.children[1].children[0].href
@gcondess 
```Javascript
const current_url;
```

2021-07-22 16:15 UTC, meschac38700 commented on pod/video/views.py
> +def video_all_info(request, slug, slug_private=None):
> pourquoi passer le slug et le slug_private ? Cette vue ne peut s'appeler qu'en Ajax ? si oui, alors il faudrait la sécuriser avec is_ajax et renvoyer du json avec les infos si les autorisations sont là sinon renvoyer une erreur. Qu'en penses-tu ?

@ptitloup il existe un decorateur dans pod/main/decorators.py nommé `ajax_required`
que @gcondess peut ajouter sur cette fonction 
```Python
@ajax_required
def video_all_info(...):
    ...
```

2021-07-23 07:21 UTC, ptitloup commented on pod/video/views.py
> +    ):
hello @meschac38700 oui c'est une bonne idée, à rajouter dans la roadmap !

2021-07-23 09:42 UTC, gcondess commented on pod/video/views.py
> +    if (
Tu as raison je n'ai pas géré le cas ou l'utilisateur ne passe par dans le if. Cependant le render est aussi inclut dans ce if donc il ne devrait pas y avoir de levée d'exception...
Est ce que rajouter un else vers un "Permission denied ne suffirait pas ?
Sinon je peux ajouter les check effectué dans la vue render_video (password authentification etc) mais est-ce bien nécessaire pour l'affichage des infos sur la vidéo (on pourrait considérer que les informations soit accessible même si la vidéo ne l'est pas)
Quand pensez vous ?

2021-07-23 10:10 UTC, mitou38 commented on pod/video/views.py
> +    if (
@gcondess Comme @ptitloup l'a suggéré, c'est une view qui est appelée en Ajax et donc par conséquent devrait renvoyer une réponse même en cas d'erreur et il serait préférable que ça soit un JSONResponse.
Je pense qu'on devrait retourner un `403 Access Denied`

2021-07-23 10:11 UTC, meschac38700 commented on pod/video/views.py
> +    if (
@gcondess Comme @ptitloup l'a suggéré, c'est une view qui est appelée en Ajax et donc par conséquent devrait renvoyer une réponse même en cas d'erreur et il serait préférable que ça soit un JSONResponse.
Je pense qu'on devrait retourner un `403 Access Denied`

2021-07-23 11:27 UTC, closed without merging