Improve video thumbnail
EsupPortail/Esup-Pod pull request #516
Opened 2021-07-12 16:58 UTC by cbissler

Adaptation du code de manière à ce qu'une vignette positionnée sur une vidéo ne soit pas écrasée par la 1ère vignette générée à l'encodage.

2021-07-12 18:33 UTC, meschac38700 requested changes

2021-07-12 18:33 UTC, meschac38700 commented on pod/video/encode.py
> +def add_default_thumbnail_to_video(video_id, thumbnail):
@cbissler il serait mieux de déplacer cette fonction utilitaire dans `pod/video/utils.py` non ?
Et éventuellement rajouter un test-unitaire...

2021-07-12 18:33 UTC, meschac38700 commented on pod/video/encode.py
> +    # video_to_encode.thumbnail = None
@cbissler  si cette ligne n'est plus utile, il serait préférable de la supprimer simplement.

2021-07-12 18:33 UTC, meschac38700 commented on pod/video/encode.py
> +                    add_default_thumbnail_to_video(video_id, thumbnail)
:+1:

2021-07-12 18:33 UTC, meschac38700 commented on pod/video/encode.py
> +                    add_default_thumbnail_to_video(video_id, thumbnail)
:+1:

2021-07-13 10:00 UTC, cbissler commented on pod/video/encode.py
> +def add_default_thumbnail_to_video(video_id, thumbnail):
Ça c'est vous qui me dites. Je connais encore très mal pod et Django. Je vais voir ce que je peux faire.

2021-07-14 18:58 UTC, closed without merging