[WIP] Improve video thumbnail
EsupPortail/Esup-Pod pull request #520
Opened 2021-07-13 23:11 UTC by cbissler

Adaptation du code de manière à ce qu'une vignette positionnée sur une vidéo ne soit pas écrasée par la 1ère vignette générée à l'encodage.
En remplacement de celle-ci : https://github.com/EsupPortail/Esup-Pod/pull/516

2021-07-15 11:32 UTC, meschac38700 approved these changes
@cbissler c'est propre ! :+1:

2021-07-15 11:32 UTC, meschac38700 commented on pod/video/utils.py
> +def add_default_thumbnail_to_video(video_id, thumbnail):
:+1:

2021-07-15 11:32 UTC, meschac38700 commented on pod/video/tests/test_utils.py
> +    def test_add_default_thumbnail_to_video(self):
:+1:

2021-07-15 13:27 UTC, ptitloup commented
A laisser en WIP : reflexion sur la configuration du changement de vignette (Force change ?)

2021-07-15 13:33 UTC, ptitloup requested changes

2021-07-15 13:33 UTC, ptitloup commented on pod/video/utils.py
> +    if video_to_encode.thumbnail is None:
changer par "if settings.KEEP_VIDEO_THUMBNAIL" par exemple

2021-07-23 07:37 UTC, meschac38700 commented on pod/video/tests/test_utils.py
> +        self.assertEqual(Video.objects.get(id=self.v.id).thumbnail.file, "blabla.jpg")
@cbissler juste une question: je n'ai pas compris ce test, on n'est sensé ici tester que le thumbnail soit piapia.jpg ? car plus haut (L48) je constate que self.thumbnail2 a le fichier piapia.jpg

2021-09-13 12:32 UTC, JoshuaBaubry commented
Hello, des nouvelles sur cette PR ?

2021-09-14 10:05 UTC, ptitloup commented
pour l'instant, on la laisse de côté... Pas de consensus sur son implémentation. Idee très interessante cependant

2021-11-29 13:33 UTC, ptitloup commented
Hello Céline, 
Selon mes souvenirs, il faudrait pouvoir traiter 3 cas dans cette implémentation : 
- j'ai pas vignette, j'en créé une
- j'ai déjà une vignette que je veux garder (cas d'une mise à jour de vidéo avec vignette personnalisée)
- j'ai déjà une vignette que je veux mettre à jour (j'en créé une nouvelle à partir de cette nouvelle vidéo)
Or cette proposition ne propose pas ces 3 cas, comment voyez vous les choses ?
Merci
Nicolas

2022-06-15 00:27 UTC, JoshuaBaubry commented
Hello @ptitloup , cette pr n'étant plus du tout a jour par rapport à nos branches actuelles , est ce que ça ne serait pas mieux de la fermer actuellement pour faire un peu le tri et qu'elle puisse être ouverte à nouveau par son auteur si le besoin s'en fait ressentir ?

2022-06-15 07:15 UTC, ptitloup commented
Oui tout à fait ! Je ferme cette PR quitte à en faire une autre plus tard

2022-06-15 07:15 UTC, closed without merging