[BugFix] error 500 when ?page parameter is very high
EsupPortail/Esup-Pod pull request #523
Opened 2021-09-01 15:34 UTC by Badatos

Correct a Server error 500 happening when ?page parameter is very high in video_search

Test this page for sample : http://localhost:8080/search/?q=FOO&page=964&selected_facets=channels.slug:TEST

Now a warning message is displayed to user when page>500, and no error is raised.

2021-09-02 07:10 UTC, ptitloup commented
Hello Olivier, merci bcp mais ta proposition ne passe pas :'( tu pourrais regarder stp ? merci !
flake8 --max-complexity=7 --ignore=E501,W503,E203 --exclude .git,pod/*/migrations/*.py,test_settings.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.5.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.5.10/x64/lib
./pod/video_search/views.py:85:1: C901 'search_videos' is too complex (8)

2021-09-02 07:17 UTC, ptitloup requested changes

2021-09-02 07:17 UTC, ptitloup commented on pod/video_search/views.py
> +    if page > 500:
tu peux créer une fonction get_page(request) par exemple

2021-09-02 07:51 UTC, Badatos commented on pod/video_search/views.py
> +    if page > 500:
Hello Nicolas ! Bonne idée en effet, j'envoie un commit avec cette modif !

2021-09-03 12:13 UTC, ptitloup approved these changes

2021-09-03 12:14 UTC, ptitloup commented
Merci bcp !

2021-09-03 12:14 UTC, merged