New command "clean_video_files"
EsupPortail/Esup-Pod pull request #528
Opened 2021-09-08 13:07 UTC by Badatos

This command delete useless video files (not associated with a video Object)

2021-09-08 14:15 UTC, ptitloup requested changes

2021-09-08 14:15 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
> +        list_dir = listdir(join(settings.MEDIA_ROOT, "videos"))
replace with VIDEOS_DIR = getattr( settings, 'VIDEOS_DIR', 'videos') see https://github.com/EsupPortail/Esup-Pod/blob/master/pod/video/models.py#L57

2021-09-08 14:15 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
> +            mypath = join(settings.MEDIA_ROOT, "videos", video_dir)
idem, https://github.com/EsupPortail/Esup-Pod/blob/master/pod/video/models.py#L57

2021-09-08 14:15 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
> +                    Video.objects.get(video="videos/%s/%s" % (video_dir, myfile))
idem videos must be replace by VIDEOS_DIR https://github.com/EsupPortail/Esup-Pod/blob/master/pod/video/models.py#L57

2021-09-08 14:15 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
> +                    vid_path = join(settings.MEDIA_ROOT, "videos", video_dir, myfile)
Again, videos must be replace by VIDEOS_DIR

2021-09-08 14:16 UTC, Badatos commented on pod/video/management/commands/clean_video_files.py
> +# -*- coding: utf-8 -*-
C'est l'habitude de python 2 ;)

2021-09-08 14:38 UTC, Badatos commented
Voila, j'ai remplacé les chaines "videos" en dur par le parametre "VIDEOS_DIR"

2021-09-09 07:36 UTC, ptitloup approved these changes
mise à part une remarque plus sur la forme que sur le fond, merci bcp pour cette PR !

2021-09-09 07:36 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
> +        VIDEOS_DIR = getattr(settings, "VIDEOS_DIR", "videos")
les variables dites globales sont à positionner en dehors de la fonction... après, on pourra le faire hein !

2021-09-09 07:37 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
> +        VIDEOS_DIR = getattr(settings, "VIDEOS_DIR", "videos")
https://github.com/EsupPortail/Esup-Pod/blob/master/pod/video/models.py#L57

2021-09-09 08:10 UTC, Badatos commented on pod/video/management/commands/clean_video_files.py
> +        VIDEOS_DIR = getattr(settings, "VIDEOS_DIR", "videos")
done ;)

2021-09-09 08:11 UTC, ptitloup approved these changes

2021-09-09 08:11 UTC, ptitloup commented
Merci bcp

2021-09-09 08:11 UTC, merged