Shib as cas
EsupPortail/Esup-Pod pull request #553
Opened 2021-11-09 12:31 UTC by gcondess

Let Shibboleth map affiliation to staff status has it is done with CAS

2021-11-13 19:14 UTC, meschac38700 requested changes
:+1: 
Quelque propositions de changement

2021-11-13 19:14 UTC, meschac38700 commented on pod/authentication/shibmiddleware.py
> +        return False
```Python
def check_user_meta(self, user, shib_meta):
    """Check the access rights to meta user
        user: User,
        shib_meta dict
    """"
    return (
        user and user.owner and
        shib_meta['affiliation'] in [A[0] for A in AFFILIATION] and
        user.owner.affiliation != shib_meta['affiliation']
    )
```

2021-11-13 19:14 UTC, meschac38700 commented on pod/authentication/shibmiddleware.py
> +        return False
```Python
def is_staffable(self, user):
    """Check that given user is staff
        user: User
    """
    if(
        SHIBBOLETH_STAFF_ALLOWED_DOMAINS is None or
        len(SHIBBOLETH_STAFF_ALLOWED_DOMAINS) == 0
    ):
        return True

    for d in SHIBBOLETH_STAFF_ALLOWED_DOMAINS:
        if(user.username.endswith('@' + d)):
            return True
    return False

2021-11-14 14:37 UTC, meschac38700 requested changes

2021-11-14 14:37 UTC, meschac38700 commented on pod/authentication/tests/test_populated.py
> +        lname = u['email'].split('.')[1].split('@')[0]
Ne serait-il pas mieux d'utiliser les expressions régulières ? 
Est-on sûr le format de l'email ne va pas changer ? 
En effet ces scénarios peuvent être possible dans d'autres établissement
```Python
u["email"] # firstName.lastName@pod.fr
u["email"] # firstName-lastName@pod.fr
u["email"] # lastName_firstName@pod.fr
```
Alors peut etre utiliser le module `re`:
```Python
import re

...

# on récupère toutes les suites de chaines de caractères sachant que la 1ere et la 2e suites = firstName, lastName
# ex: email = john.doe@pod.fr, findAll will return ["john", "doe", "gmail", "fr"]
# ex: email = john-doe@pod.fr, findAll will return ["john", "doe", "yahoo", "fr"]
# ex: email = john_doe@pod.fr, findAll will return ["john", "doe", "pod", "fr"]
fname, lname, *_ = re.findall(r"([a-z]+)", u['email']) or [None, None, None] 

# prevent case that operation didn't go well
if not all([fname, lname]): # == if (fname or lname) is None
    # TODO do something maybe raise an exception Invalid user data   --> add test if invalid user data

2021-11-15 09:22 UTC, gcondess commented on pod/custom/settings_local.py.example
> +# Remarque : si vous utilisez Scalelite, il est possible que les URLS générés soient
Ok

2021-11-15 09:23 UTC, gcondess commented on pod/custom/settings_local.py.example
> +# Custom var to allow user of somme domain to be staff
Ok

2021-11-15 09:23 UTC, gcondess commented on pod/authentication/tests/test_populated.py
> +        """ Test if the main affiliation of this same user with new unstaffable affiliation has change """
Ok

2021-11-15 09:23 UTC, gcondess commented on pod/authentication/tests/test_populated.py
> +        """ Test if user can be staff when SHIBBOLETH_STAFF_ALLOWED_DOMAINS is restrict """
Ok

2021-11-15 09:23 UTC, gcondess commented on pod/authentication/tests/test_populated.py
> +        """ Test if user can be staff if SHIBBOLETH_STAFF_ALLOWED_DOMAINS = None """
Ok

2021-11-15 09:23 UTC, gcondess commented on pod/authentication/shibmiddleware.py
> +                user.owner.save()
Ok

2021-11-15 09:23 UTC, gcondess commented on pod/authentication/shibmiddleware.py
> +        return False
Ok

2021-11-15 09:24 UTC, gcondess commented on pod/authentication/shibmiddleware.py
> +        return False
Ok pour l'ajout des commentaires, par contre flake8 génère un warning si je met le 'or' sur la première ligne du 'if':
./pod/authentication/shibmiddleware.py:73:54: W504 line break after binary operator

2021-11-15 09:24 UTC, gcondess commented on pod/authentication/tests/test_populated.py
> +        lname = u['email'].split('.')[1].split('@')[0]
Comme chaque établissement peut effectivement avoir ces règles j'ai ajouté 'first_name' et 'last_name' en paramètre pour éviter des les récupérer plus ou moins hasardeusement à partir de l'adresse mail et un import supplémentaire...

2021-11-15 09:51 UTC, meschac38700 commented on pod/authentication/shibmiddleware.py
> +        return False
@gcondess OK à adapter selon les règles de flak8, il y a également le dernier `else` que j'ai enlevé car on a un `return` dans le `if`

2021-11-15 09:51 UTC, meschac38700 commented on pod/authentication/tests/test_populated.py
> +        lname = u['email'].split('.')[1].split('@')[0]
@gcondess  Bien vu ! :+1:

2021-11-16 04:38 UTC, meschac38700 approved these changes

2021-11-16 08:26 UTC, ptitloup approved these changes
Merci bcp pour cette contribution ! Je merge pour la release

2021-11-16 08:26 UTC, merged