[OrionStudios] add vosk implementation
EsupPortail/Esup-Pod pull request #583
Opened 2022-02-02 14:01 UTC by JoshuaBaubry

2022-03-17 14:27 UTC, ptitloup requested changes

2022-03-17 14:27 UTC, ptitloup commented on pod/completion/views.py
> +ACTIVE_ENRICH = getattr(settings, "ACTIVE_ENRICH", False)
Pourrait-on le renommer en ACTIVE_MODEL_ENRICH pour que ce soit plus parlant ? merci

2022-03-17 14:27 UTC, ptitloup commented on pod/completion/admin.py
> +TRANSCRIPTION_TYPE = getattr(settings, "TRANSCRIPTION_TYPE", "DEEPSPEECH")
quelles sont les valeurs possibles ? il me semble que les solutions retenues sont coqui.ai et vosk non ?

2022-03-17 14:27 UTC, ptitloup commented on pod/video/transcript.py
> +    import json
les imports doivent etre placé au début du fichier

2022-03-17 14:27 UTC, ptitloup commented on pod/video/transcript.py
> +    def convert_vosk_samplerate(audio_path, desired_sample_rate, trim_start, duration):
pour plus de clarté, on évite d'imbriquer les fonctions

2022-03-17 14:27 UTC, ptitloup commented on pod/custom/settings_local.py.example
> +"""
cool

2022-03-17 14:29 UTC, ptitloup commented
Pouvez-vous vérifier que ces modifications sont bien prises en compte : **https://github.com/EsupPortail/Esup-Pod/pull/587** Merci

2022-03-21 13:48 UTC, JoshuaBaubry commented on pod/completion/admin.py
> +TRANSCRIPTION_TYPE = getattr(settings, "TRANSCRIPTION_TYPE", "DEEPSPEECH")
En effet il faut prendre en compte VOSK et COQUI AI suite à la modification dans une autre PR

2022-03-21 13:48 UTC, JoshuaBaubry commented on pod/completion/forms.py
> +
Ne pose pas de soucis de flake8 ?

2022-03-22 14:37 UTC, norphiil commented on pod/completion/views.py
> +ACTIVE_ENRICH = getattr(settings, "ACTIVE_ENRICH", False)
Bien-sur, j'ai renommer tous les ACTIVE_ENRICH  en ACTIVE_MODEL_ENRICH.

2022-03-22 14:37 UTC, norphiil commented on pod/video/transcript.py
> +    import json
Oui merci, je ne sais pas pourquoi je l'ai mis là, je le change tout de suite.

2022-03-24 14:18 UTC, ptitloup commented
Bonjour, Je vois qu'il y a encore des modifications. Merci de me prévenir quand je pourrais faire une nouvelle review. Bon courage

2022-03-24 14:44 UTC, norphiil commented
> Bonjour, Je vois qu'il y a encore des modifications. Merci de me prévenir quand je pourrais faire une nouvelle review. Bon courage

Bonjour, oui, j'ai envoyé la dernière modification pour pouvoir passer les tests de flake8, vous pouvez donc faire de nouvel review, j'essaierai de vous répondre le plus rapidement que possible.

2022-03-24 16:15 UTC, ptitloup requested changes
Merci pour ces modifications. Malheureusement, je pense qu'il y a eu confusion ou mecompréhension avec mes précédentes remarques. Deepspeech n'existe plus et a été remplacé par l'outil stt (speech to text) de Coqui. C'est le sens de la PR #587 . Merci

2022-03-24 16:15 UTC, ptitloup commented on pod/completion/admin.py
> +TRANSCRIPTION_TYPE = getattr(settings, "TRANSCRIPTION_TYPE", "DEEPSPEECH")
Alolrs pourquoi est-ce encore ecrit deepspeech ? dans la PR #587 ils ont rempalcés deepspeech par stt, je pense uq'il faudrait fair ede même pour garder une cohérence

2022-03-24 16:15 UTC, ptitloup commented on pod/custom/settings_local.py.example
> +"""
Transcription use
 * DEEPSPEECH
 * COQUI
 * VOSK

Attention, il n'y a plus deepspeech, il a été remplacé par coqui qui se nomme stt. voir PR #587

2022-03-24 16:15 UTC, ptitloup commented on pod/custom/settings_local.py.example
> +    'COQUI': {
Je pense qu'il vaut mieux mettre STT pour repsecter la PR #587

2022-03-24 16:15 UTC, ptitloup commented on pod/custom/settings_local.py.example
> +    'COQUI': {
Je veux dire à la place de COQUI

2022-03-24 16:15 UTC, ptitloup commented on pod/custom/settings_local.py.example
> +  # le modèle deepspeech
A supprimer, il n'y a plus deepspeech

2022-03-24 16:15 UTC, ptitloup commented on pod/video/transcript.py
> +    if TRANSCRIPTION_TYPE == "DEEPSPEECH":
A supprimer et utiliser STT Merci !

2022-03-24 16:15 UTC, ptitloup commented on pod/video/transcript.py
> +ds_model = get_model("fr")
pas de ds_model (enfin plus) il faut laisser stt_model et mettre main_stt_transcript

2022-03-24 16:15 UTC, ptitloup commented on pod/video/transcript.py
> +def main_deepspeech_transcript(norm_mp3_file, duration, ds_model):
main_stt_transcript

2022-03-24 16:23 UTC, norphiil commented on pod/custom/settings_local.py.example
> +    'COQUI': {
d'accord je change ça

2022-03-24 16:25 UTC, norphiil commented on pod/custom/settings_local.py.example
> +  # le modèle deepspeech
oui je m’excuse, je n'avais pas compris cela, je vais changer tous cela afin de totalement enlever deepspeech. je m'excuse pour le désagrément.

2022-03-24 16:40 UTC, norphiil commented on pod/video/transcript.py
> +    if TRANSCRIPTION_TYPE == "DEEPSPEECH":
Bien compris, je l'ai supprimer et j'ai utiliser STT

2022-03-29 09:20 UTC, ptitloup approved these changes
Ok pour moi, tout me semble bon. Beau travail merci !

2022-03-30 15:48 UTC, merged