Elygames/feature vosk caption maker fix
EsupPortail/Esup-Pod pull request #612
Opened 2022-04-20 09:58 UTC by norphiil

2022-04-25 07:49 UTC, ptitloup commented
Bonjour, je me permet de mettre cette PR en WIP, merci de la mettre en Done quand c'est ok pour vous

2022-04-27 12:10 UTC, JoshuaBaubry commented
@ptitloup C'est bon elle est prête à être review

2022-04-27 12:17 UTC, ptitloup requested changes
Merci pour cette contributions, je ne vois pas de problème particiuluier dans le code, par contre, il faudrait compiler les fichier de lang (.po) en .mo. Merci !

2022-04-27 12:18 UTC, JoshuaBaubry commented
> Merci pour cette contributions, je ne vois pas de problème particiuluier dans le code, par contre, il faudrait compiler les fichier de lang (.po) en .mo. Merci !

@ptitloup Ce qui est étrange c'est que le compilemessages output qu'il n'y a rien à traiter

2022-04-27 12:21 UTC, ptitloup approved these changes
oui ok visiblement, ce ne sont que les lignes qui changent ! autant pour moi ! Merci bcp

2022-04-27 12:22 UTC, ptitloup commented on pod/locale/fr/LC_MESSAGES/django.po
> +#, fuzzy
Toutefois, il y a ces 2 fuzzy qui pourront être ajoutés (plus tard)

2022-04-27 12:23 UTC, merged