[DONE] Feature/videojs wavesurfer
EsupPortail/Esup-Pod pull request #613
Opened 2022-04-28 14:58 UTC by Badatos

Add the video.js "wavesurfer" plugin :
* wavesurfer.js 6.1.0 from https://wavesurfer-js.org
* videojs-wavesurfer 3.8.0 from https://github.com/collab-project/videojs-wavesurfer

And call if for every "video" which is not in video format (= audio only)

(response to #546 feature request)

2022-04-29 13:53 UTC, ptitloup requested changes
Merci de mettre à jour ta branche avecv dev3 pour récupérer bootstrap5. Ensuite, il faut vérifier que le code html que tu édites respecte bien BT5. Merci bcp !

2022-04-29 13:53 UTC, ptitloup commented on pod/video/templates/videos/video-info.html
> +                <i data-feather="eye"></i>
Attention dans les templates, le code a changé. Il faudrait mettre à jour ta branche depuis dev3 pour verifier que tout est ok mais la, il ne devrait plus y avoir data-feather

2022-04-29 13:53 UTC, ptitloup commented on pod/video/templates/videos/video-element.html
> +<video id="podvideoplayer" class="video-js vjs-default-skin {% if not request.GET.is_iframe %}vjs-16-9{% endif %} vjs-big-play-centered vjs-show-big-play-button-on-pause" {% if request.GET.is_iframe
A verifier depuis dev3

2022-04-29 13:53 UTC, ptitloup commented on pod/video/templates/videos/video_record.html
> +        {% if not video.is_video %}
Ce fichier est a supprimé, il a été rempalcé par le studio

2022-04-29 15:07 UTC, Badatos commented on pod/video/templates/videos/video_record.html
> +        {% if not video.is_video %}
ok, en effet autant en profiter pour faire le ménage ^^.

2022-04-29 15:24 UTC, Badatos commented
Mis à jour avec la dernière branche 'dev3', prêt pour une nouvelle review ^^.

2022-05-02 08:43 UTC, ptitloup approved these changes
Ok pour moi, tout me semble bon

2022-05-02 12:59 UTC, JoshuaBaubry reviewed
Hello pour moi tout est bon j'ai juste fais une petite remarque

2022-05-02 12:59 UTC, JoshuaBaubry commented on pod/video/models.py
> +
J'aurais plutôt mis : return 360 if self.is_video else 180

2022-05-02 13:00 UTC, ptitloup commented on pod/video/models.py
> +
pour moi les deux me vont

2022-05-02 13:00 UTC, merged