[WIP2] - Pampletousse/feature add sort videos
EsupPortail/Esup-Pod pull request #633
Opened 2022-06-08 10:07 UTC by pampletousse

WIP - Ajout du tri des vidéos + filter aside dans Mes Vidéos

Fonctionnel :
- Tri dynamique dans Mes Vidéos
- Tri dynamique dans Afficher Toutes les vidéos
- Tri par colonnes fixes
- count des vidéos dynamique actualisé
- Gestion du tri ascendant / descendant
- compatibilité avec l'encart des filtres fonctionnelle
- ajout des filtres dans Mes vidéos
- switch GET -> POST pour ajax calls
- style utiliser le même aside pour catégories et filtres de base

A faire :
- Réparer compatibilité avec les catégories (Mes vidéos)
- Ajouter le tri (+ filtres) pour l'écran de résultat de recherche
- bug Fix des card de vidéos : boutons du footer edit etc non visibles lorsque qu'on lance un tri
- nettoyer le code
- ajout de commentaires
- clean si possible get_videos_list() + code inutilisé
- conformité Pep8

2022-06-08 13:20 UTC, ptitloup reviewed
voir commentaires

2022-06-08 13:20 UTC, ptitloup commented on pod/main/static/js/main.js
> +            $(".form-check-input")[0].addEventListener('change', function() {
rajouter .first() ? ou un ID ca sera plus propre

2022-06-08 13:20 UTC, ptitloup commented on pod/video/templates/channel/channel.html
> +                        <div class="input-group col-5 offset-2 mb-3" style="position:relative;top:0;width:200px;">
ne pas mettre de style dans les balises

2022-06-08 13:20 UTC, ptitloup commented on pod/video/templates/videos/filter_aside.html
> +<form action="{% url 'videos' %}" method="post" id="filters">
à mettre en cookie ? ou en localstorage ?

2022-06-08 13:20 UTC, ptitloup commented on pod/video/templates/videos/videos.html
> +    <div class="col-4">
attention au col-4 / A verifier pour tous les vues desktop/tablet /smartphone

2022-06-08 13:20 UTC, ptitloup commented on pod/video/templates/videos/videos.html
> +    <div class="input-group mb-3 float-left col-3 pl-0 pt-1" style="height:35.8px">
attention au height

2022-06-08 13:20 UTC, ptitloup commented on pod/video/views.py
> +        videos_list = get_filtered_videos_list(videos_list, request)
eventuellement, regarder les **kwargs pour un filter

2022-06-08 13:20 UTC, ptitloup commented on pod/video/views.py
> +    if 'type' in filters:
essaye de regarder les kwargs

2022-06-08 13:20 UTC, ptitloup commented on pod/video/views.py
> +    if 'type' in filters:
idee : reprendre dans un dictionnaire les paramètre de filtre et de tri pour les intégrer dans un filter ou un sort

2022-06-08 13:20 UTC, ptitloup commented on pod/video_search/templates/search/search.html
> +<div class="input-group mb-3 float-left col-4 pr-5 pt-3" style="position:absolute;top:0;right:0;height:35.8px;">
Attention, ne fonctionne pas pour le search

2022-06-08 13:21 UTC, ptitloup commented
pour les pb de pep8, il faut installer flake8 et lancer la commande avant de commiter

2022-06-08 13:22 UTC, ptitloup commented
flake8 --max-complexity=7 --exclude .git,pod/*/migrations/*.py,test_settings.py,settings_local.py

2022-06-30 13:08 UTC, ptitloup requested changes
Encore quelques modifications à apporter ! Courage !

2022-06-30 13:08 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
>    $("#video_count")[0].innerHTML = newCount + " " + gettext(transVideoCount);
Eventuellement à remplacer par   $("#video_count").html(newCount + " " + gettext(transVideoCount));
sinon document.getElementById("video_count").innerHTML = newCount + " " + gettext(transVideoCount);

2022-08-15 13:47 UTC, JoshuaBaubry reviewed
ça me parait ok pour ma part , j'ai juste laissé un petit commentaire

2022-08-15 13:47 UTC, JoshuaBaubry commented on pod/video/templates/videos/filter_aside.html
> +<div class="card card-body" id="filters">
Je trouve le nom de cet id un peu générique

2022-09-05 14:11 UTC, closed without merging