feature liveevent
EsupPortail/Esup-Pod pull request #639
Opened 2022-06-14 06:39 UTC by mattbild

Ajout d'événements programmables.
Pilotage des enregistrements.
Modification de la supervision des diffuseurs (live)

2022-06-14 07:46 UTC, mattbild commented
C'est fini de mon côté, je pensais que c'était pour vous, le temps de faire des reviews

2022-06-14 07:53 UTC, ptitloup commented
ha ok parfait, on va faire une review à ce moment là :-) merci !

2022-06-14 16:27 UTC, ptitloup reviewed
très belle PR, merci bcp pour le taf ! c'est propre, bien indenté mais manque un peu de commentaire... Il faudrait qu'on fasse un petit point visio rapide pour faire une passe ensemble. On se re par RC

2022-06-14 16:27 UTC, ptitloup commented on pod/live/views.py
> +    if broadcaster is None:
pourquoi pas un else ?

2022-06-14 16:27 UTC, ptitloup commented on pod/live/views.py
> +            | (Q(start_date=date.today()) & Q(end_time__gte=datetime.now()))
idem (Q(start_date__gte=date.today()) & Q(end_time__gte=datetime.now())) ???

2022-06-15 00:06 UTC, JoshuaBaubry requested changes
Une très grosse PR et des nouvelles fonctionnalités sympa ! J'ai relevé quelques petits choses de mon coté , mais rien de critique !

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/live/views.py
> +        # and request.is_ajax():
code en commentaire à supprimer

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/live/views.py
> +        # and request.is_ajax():
code en commentaire à supprimer

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/live/views.py
> +        # if attempt_number > 1:
code en commentaire à supprimer

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/live/views.py
> +        # if attempt_number > 1:
code en commentaire à supprimer

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/main/test_settings.py
> +DEBUG = False
pourquoi avoir fait ce changement ?

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/main/test_settings.py
> +DEBUG = False
pourquoi avoir fait ce changement ?

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/main/test_settings.py
> +LANGUAGES = (("fr", "Français"), ("en", "English"))
Oui j'approuve ce changement , ça empêche souvent de faire les test avec l'ancienne version !

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/main/test_settings.py
> +LANGUAGES = (("fr", "Français"), ("en", "English"))
Oui j'approuve ce changement , ça empêche souvent de faire les test avec l'ancienne version !

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/main/test_settings.py
> +EXISTING_BROADCASTER_IMPLEMENTATIONS = ["Wowza", "Test"]
Le "Test" est volontaire ?

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/main/test_settings.py
> +EXISTING_BROADCASTER_IMPLEMENTATIONS = ["Wowza", "Test"]
Le "Test" est volontaire ?

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/settings.py
> +TIME_INPUT_FORMATS = ["%H:%M", *django.conf.global_settings.TIME_INPUT_FORMATS]
Ce setting va changer le format de temps pour tout POD, j'espère que ça ne provoque pas d'effet de bord

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/settings.py
> +TIME_INPUT_FORMATS = ["%H:%M", *django.conf.global_settings.TIME_INPUT_FORMATS]
Ce setting va changer le format de temps pour tout POD, j'espère que ça ne provoque pas d'effet de bord

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/video/encode.py
> +    # video_to_encode.thumbnail = None
code en commentaire à supprimer si non nécessaire

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/video/encode.py
> +    # video_to_encode.thumbnail = None
code en commentaire à supprimer si non nécessaire

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/video/utils.py
> +            # | Q(title_nl__icontains=title)
code en commentaire à supprimer si non nécessaire

2022-06-15 00:06 UTC, JoshuaBaubry commented on pod/video/utils.py
> +            # | Q(title_nl__icontains=title)
code en commentaire à supprimer si non nécessaire

2022-06-15 07:30 UTC, mattbild commented on pod/live/templates/live/events.html
> +            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
Parce que j'ai bêtement recopié le template dans videos :
https://github.com/EsupPortail/Esup-Pod/blob/master/pod/video/templates/videos/my_videos.html#L23

2022-06-15 08:14 UTC, mattbild commented on pod/live/views.py
> +        Q(start_date__gt=date.today())
bonne idée oui, il existe déjà une méthode un is_past() dans le model.
Concernant le filtre que tu proposes effectivement ça fonctionnerait aussi bien

2022-06-15 08:59 UTC, ptitloup commented on pod/live/templates/live/events.html
> +            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
mais du coup, peux-tu vérifier si cela sert ? sinon, plutot que de recopier, on pourrait pas faire des include ? cela permet le DRY

2022-06-15 09:10 UTC, ptitloup commented on pod/live/views.py
> +        Q(start_date__gt=date.today())
pas forcement une property mais une functoin de classe permettrai de centraliser cet appel

2022-06-16 06:18 UTC, mattbild commented on pod/live/templates/live/direct.html
> +        <h3>8 {% trans "Next events" %}</h3>
Non c'est une erreur (je pensais l'avoir supprimée)

2022-06-16 06:47 UTC, cbissler commented on pod/settings.py
> +TIME_INPUT_FORMATS = ["%H:%M", *django.conf.global_settings.TIME_INPUT_FORMATS]
Ça c'est moi qui l'ai fait. J'ai pas trouvé d'autre moyen pour que mon champs de saisie des heures ne soit pas en hh:mm:ss. J'avais vérifié, il n'y avait pas d'autres champs heure (input time) à ce moment là dans POD.

2022-06-16 07:37 UTC, ptitloup commented on pod/live/static/js/viewcounter.js
> +          "/live/ajax_calls/heartbeat/?key=" +
pas de soucis, tu peiux voir pour le corriger dans une autre PR, on le garde telquel dans celle là.

2022-06-16 07:45 UTC, ptitloup commented on pod/live/templates/live/event-iframe.html
> +                    // console.log('MTop: '+player.el().style.top+'\nleft: '+player.el().offsetLeft+'\nwidth: '+player.el().offsetWidth+'\nheight: '+player.el().offsetHeight+' /// '+pb)
{% comment %} {% endcomment %}

2022-06-17 12:27 UTC, mattbild commented on pod/video/utils.py
> +            # | Q(title_nl__icontains=title)
impossible de l=passer les tests avec ce paramètre e mon côté .
Je vais le supprimer plutôt que de le commenter.
A voir si vous voulez le laisser ou non

2022-06-17 12:29 UTC, mattbild commented on pod/video/encode.py
> +    # video_to_encode.thumbnail = None
il y a eu des modifs sur ce fichier de notre côté (pour permettre d'importer le thumbnail original) mais qui n'auraient pas dû être commités.
Je remets l'original

2022-06-17 12:30 UTC, mattbild commented on pod/main/test_settings.py
> +EXISTING_BROADCASTER_IMPLEMENTATIONS = ["Wowza", "Test"]
oui c'était pour les tests unitaires

2022-06-17 13:06 UTC, mattbild commented on pod/live/views.py
> +            | (Q(start_date=date.today()) & Q(end_time__gte=datetime.now()))
en fait pour le filtre que tu proposes ne fonctionnerait pas pour afficher les évènements des prochains jours qui sont finis avant l'heure actuelle.
Exemple: s'il est 10h, on ne verrait pas l'event qui a lieu demain de 8h à 9h

2022-06-17 13:07 UTC, mattbild commented on pod/live/templates/live/events.html
> +            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
elles seront  supprimées car on ne passe jamais dans le test

2022-06-17 13:07 UTC, mattbild commented on pod/live/templates/live/my_events.html
> +                <div></div>
elles seront  supprimées car on ne passe jamais dans le test

2022-06-17 14:21 UTC, mattbild commented on pod/live/views.py
> +            | (Q(start_date=date.today()) & Q(end_time__gte=datetime.now()))
ici je filtre la liste après la query car on récupère tous les events de l'utilisateur, donc on peut utiliser la méthode is_past() du model

2022-06-17 14:42 UTC, mattbild commented on pod/live/views.py
> +        Q(start_date__gt=date.today())
Sur le coup là, je ne trouve pas de bonne manière de faire pour que ça soit défini dans le model et disponible comme un filtre.
Si l'un de  @vous peut m'orienter svp 
@ptitloup @JoshuaBaubry

2022-06-27 15:59 UTC, mattbild commented on pod/live/templates/live/event-info.html
> +{#      </li>#}
supprimé

2022-06-27 16:00 UTC, mattbild commented on pod/main/test_settings.py
> +DEBUG = False
supprimé

2022-07-01 13:40 UTC, mattbild commented on pod/live/views.py
> +    return True
j'a préféré laisser comme ça pour gagner en lisibilité. 
J'ai peur que la factorisation ne complexifie la lecture et n'apporte pas grand chose en terme de nombre de ligne.
A vous de me dire

2022-07-01 13:49 UTC, mattbild commented
la PR est à jour de mes dernières modifications.
Il manquait :
_ l'intégration de la vidéo d'attente avant ou pendant un évènement (si pas de flux reçu).
_ l'intégration de BBB si le chat est configuré sur le broadcaster
Je n'ai pas pu tester la bonne réception de la question sur BBB car je n'ai pas de serveur paramétré de mon côté. Mais j'ai bien un message dans ce sens, ce qui est cohérent. L'un de vous peut-il tester ça ?
Pour être complet il faudrait encore extraire les fonctions JS utilisées dans event.html et event-iframe.html. Si ça pose vraiment problème je m'en chargerai la semaine prochaine mais je me dis qu'en attendant vous pouvez (ré)étudier cette PR. 
J'attends vos retours.
Merci pour la review

2022-07-04 09:55 UTC, ptitloup approved these changes
Ok pour moi dans l'implementation, il restera à l'usage de voir si tout est ok.

2022-07-04 09:56 UTC, ptitloup commented
Pour le JS, on pourra tjs améliorer cela dans la V3. Il manque de toute manière du feedback d'usage qui va permettre d'améliorer cette feature

2022-07-04 14:40 UTC, JoshuaBaubry approved these changes
Tout me parait ok, il ne manque plus qu'a tester tout ça

2022-07-04 14:41 UTC, merged