[WIP] Désinscription des utilisateurs aux groupes gérés automatiquement
EsupPortail/Esup-Pod pull request #713
Opened 2022-12-01 16:31 UTC by cbissler

Les groupes d'accès peuvent être chargés automatiquement en fonction des affiliations et/ou en fonction des groupes récupérés à la connexion de l'utilisateur soit dans ses attributs CAS soit dans ses attributs LDAP. Jusque là POD ne gérait pas la désinscription de l'utilisateur au groupe si ce dernier venait à perdre l'attribut qui avait engendré son assignation à ce dernier. En d'autres termes, POD ne désinscrivait pas des groupes d'accès les utilisateurs qui n'avaient plus rien à y faire. Cette PR vise à corriger ce problème.

2022-12-02 09:14 UTC, ptitloup requested changes
Ok pour moi, serait-il possible de retirer le djangojs.mo de la PR. On ne prends pas les fichier compilé sans le source (le .po) Merci

2022-12-02 10:02 UTC, mattbild approved these changes

2022-12-02 18:24 UTC, ptitloup commented
Petit probleme de syntaxe à corriger ... Merci !

2022-12-05 17:45 UTC, ptitloup commented
Bonsoir, en fait, j'ai l'impression que c'est le fichier .po qui a été retiré de la PR au lieu du fichier djangojs.mo.
Est-ce possible de réimporter la branche develop pour résoudre les conflits et corriger les traductions en ne poussant que les fichiers nécessaires ? n'hésitez pas à revenir vers moi pour tout complément d'information

2022-12-06 08:53 UTC, ptitloup approved these changes

2022-12-06 08:54 UTC, ptitloup commented
Merci !

2022-12-06 08:54 UTC, merged