Live Transcription
EsupPortail/Esup-Pod pull request #729
Opened 2023-01-16 09:25 UTC by Mateo6051

Sous-titrage des évènements en direct

2023-01-16 09:31 UTC, mattbild commented on pod/live/live_transcript.py
> +path_to_media_folder = r"C:\Users\mateo\Desktop\django_projects\podv3\pod\media\transcripts"
ça devrait être un lien en paramètre

2023-01-18 14:26 UTC, ptitloup commented
Merci de dire si la PR est en WIP (work in progress) ou Done si on peut faire les review. Merci

2023-02-06 10:56 UTC, Mateo6051 commented
La PR est prête à être review.

2023-02-06 13:43 UTC, mattbild commented
Il faut ajouter le paramètre dans le fichier de configuration avec la commande : 
`python manage.py addsetting live USE_LIVE_TRANSCRIPTION`

2023-02-06 14:39 UTC, Mateo6051 commented
C'est bon j'ai rajouté toutes les nouvelles variables

2023-02-06 14:40 UTC, ptitloup requested changes

2023-02-06 14:40 UTC, ptitloup commented on pod/live/live_transcript.py
> +VOSK_MODEL = getattr(settings, "LIVE_TRANSCRIPTION_MODEL", None)
le nom de la variable doit porter le mm nom que la configuration. Ici : LIVE_TRANSCRIPTION_MODEL

2023-02-06 14:40 UTC, ptitloup commented on pod/live/forms.py
> -from django import forms
le fichier est non lisibile à la review :'( (il va falloir qu'on se mette d'accord sur les retours à la ligne !)

2023-02-06 14:40 UTC, ptitloup commented on pod/live/live_transcript.py
> +CELERY_TO_TRANSCRIBE_LIVE = getattr(settings, "CELERY_TO_TRANSCRIBE_LIVE", False)
est-ce possible de renommer en LIVE_CELERY_...

2023-02-06 14:40 UTC, ptitloup commented on pod/live/live_transcript.py
> +VOSK_MODEL = getattr(settings, "LIVE_TRANSCRIPTION_MODEL", None)
Mettre LIVE_VOSK_MODEL

2023-02-06 14:40 UTC, ptitloup commented on pod/live/live_transcript.py
> +TRANSCRIPTIONS_FOLDER = getattr(settings, "TRANSCRIPTIONS_FOLDER", None)
Mettre LIVE_TRANSCRIPTIONS_FOLDER

2023-02-06 14:40 UTC, ptitloup commented on pod/live/live_transcript.py
> +TRANSCRIPTIONS_FOLDER = getattr(settings, "TRANSCRIPTIONS_FOLDER", None)
et pas none mais un nom par défaut genre LIVE_TRANSCRIPTIONS_FOLDER = getattr(settings, "LIVE_TRANSCRIPTIONS_FOLDER", "live_transcriptions")

2023-02-06 14:40 UTC, ptitloup commented on pod/live/live_transcript.py
> +    SAMPLE_RATE = 16000
si en majuscule, alors variable globale qui devrait etre au niveau du module et si privée alors __SAMPLE_RATE__ = 16000

2023-02-06 14:40 UTC, ptitloup commented on pod/live/live_transcript.py
> +
retirer lignes vides ici

2023-02-06 14:40 UTC, ptitloup commented on pod/live/models.py
> +from pod.main.lang_settings import ALL_LANG_CHOICES, PREF_LANG_CHOICES
from pod.main.lang_settings import ALL_LANG_CHOICES as __ALL_LANG_CHOICES__
from pod.main.lang_settings import PREF_LANG_CHOICES as __PREF_LANG_CHOICES__

2023-02-06 14:40 UTC, ptitloup commented on pod/live/models.py
> +LANG_CHOICES = getattr(
LANG_CHOICES = getattr(
    settings,
    "LANG_CHOICES",
    ((" ", __PREF_LANG_CHOICES__), ("----------", __ALL_LANG_CHOICES__)),
)

2023-02-06 14:40 UTC, ptitloup commented on pod/live/models.py
> +class RunningTask(models.Model):
il faudrait renommer ce model en LiveTranscriptRunningTask pour que ce soit spécifique aux directs

2023-02-06 14:40 UTC, ptitloup commented on pod/live/templates/live/event.html
> +                              <track kind="captions" src="{% get_setting "TRANSCRIPTIONS_FOLDER_URL" %}{{event.broadcaster.slug}}.vtt" srclang="{{event.broadcaster.main_lang}}">
attention, pour que le fichier soit lisible, il faut qu'il soit dans un sous-répertoire de média. Du coup, dans ton model broadcaster, il faudrait que tu ais une methode pour récupérer l'url du fichier de transcription. Un truc du style 
def get_transcription_file(self):
    return os.path.join(MEDIA_URL, TRANSCRIPTIONS_FOLDER_URL, "%s.vtt" % self.slug

de même, je pense qu'il faudrait rajouter un timestamp à la fin de ton appel pour ne pas etre embete avec les caches des navigateurs : 
` kind="captions" src="{{event.broadcaster.get_transcription_file}}?{{now|U)}" srclang="{{event.broadcaster.main_lang}}"`
Attention, le code proposé n'est qu'une idée qu'il faut implémenter

2023-02-06 14:40 UTC, ptitloup commented on pod/live/templates/live/event.html
> +                let vtt_url ="{% get_setting "TRANSCRIPTIONS_FOLDER_URL" %}" + filename
idem ici ou il faut utiliser la method du broadcaster pour avoir la bonne url

2023-02-06 14:40 UTC, ptitloup commented on pod/main/configuration.json
> +                        "TRANSCRIPTIONS_FOLDER_URL": {
cette variable n'est pas utile

2023-02-06 14:40 UTC, ptitloup commented on pod/main/configuration.json
> +                        "TRANSCRIPTIONS_FOLDER": {
a mettre à jour

2023-02-06 14:40 UTC, ptitloup commented on pod/main/configuration.json
> +                        "CELERY_TO_TRANSCRIBE_LIVE": {
a renommer

2023-02-06 14:40 UTC, ptitloup commented on requirements.txt
> +stt==1.3.0 # linux only
on les retire du requirements, il faut préciser dans la doc qu'il faut les installer pour faire de la transcription. Merci de supprimer ces deux lignes ! :)

2023-02-06 14:56 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +VOSK_MODEL = getattr(settings, "LIVE_TRANSCRIPTION_MODEL", None)
C'est bon

2023-02-06 14:57 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +CELERY_TO_TRANSCRIBE_LIVE = getattr(settings, "CELERY_TO_TRANSCRIBE_LIVE", False)
C'est fait

2023-02-06 14:57 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +TRANSCRIPTIONS_FOLDER = getattr(settings, "TRANSCRIPTIONS_FOLDER", None)
C'est fait

2023-02-06 14:57 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +    SAMPLE_RATE = 16000
C'est fait

2023-02-06 14:57 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +
C'est fait

2023-02-06 14:57 UTC, Mateo6051 commented on pod/live/models.py
> +from pod.main.lang_settings import ALL_LANG_CHOICES, PREF_LANG_CHOICES
C'est fait

2023-02-06 14:58 UTC, Mateo6051 commented on pod/live/models.py
> +LANG_CHOICES = getattr(
Je comprends pas ce qu'il faut modifier ici

2023-02-06 14:58 UTC, Mateo6051 commented on pod/live/models.py
> +class RunningTask(models.Model):
C'est fait

2023-02-06 14:59 UTC, Mateo6051 commented on pod/main/configuration.json
> +                        "CELERY_TO_TRANSCRIBE_LIVE": {
C'est fait

2023-02-06 15:05 UTC, ptitloup commented on pod/live/forms.py
> -from django import forms
je crois que c'est un problème de crlf, donc de retour à la ligne ui diffère selon les environnements de developpement

2023-02-06 15:06 UTC, Mateo6051 commented on pod/main/configuration.json
> +                        "CELERY_TO_TRANSCRIBE_LIVE": {
C'est fait

2023-02-06 15:10 UTC, ptitloup requested changes

2023-02-06 15:10 UTC, ptitloup commented on pod/live/live_transcript.py
> +SAMPLE_RATE = 16000
mettre __SAMPLE_RATE__

2023-02-06 15:10 UTC, ptitloup commented on pod/live/live_transcript.py
> +SAMPLE_RATE = 16000
https://github.com/EsupPortail/Esup-Pod/blob/develop/CONTRIBUTING.md#python-styleguide

2023-02-06 15:10 UTC, ptitloup commented on pod/live/models.py
> +from pod.main.lang_settings import ALL_LANG_CHOICES as ALL_LANG_CHOICES
`as __ALL_LANG_CHOICES__`

2023-02-06 15:10 UTC, ptitloup commented on pod/live/models.py
> +from pod.main.lang_settings import PREF_LANG_CHOICES as PREF_LANG_CHOICES
`as __PREF_LANG_CHOICES__`

2023-02-06 15:10 UTC, ptitloup commented on pod/live/models.py
> +LANG_CHOICES = getattr(
Oui excuse oi, j'ai oublié de mettre le code...

2023-02-06 15:10 UTC, ptitloup commented on pod/live/models.py
> +LANG_CHOICES = getattr(
`LANG_CHOICES = getattr(
    settings,
    "LANG_CHOICES",
    ((" ", __PREF_LANG_CHOICES__), ("----------", __ALL_LANG_CHOICES__)),
)`

2023-02-06 15:10 UTC, ptitloup commented on pod/main/configuration.json
> +                        "TRANSCRIPTIONS_FOLDER_URL": {
je sais pas si tu t'en sers mais si oui il faut la retirer et faire une methode lié au model pour la calculer

2023-02-06 15:10 UTC, ptitloup commented on pod/main/configuration.json
> +                        "TRANSCRIPTIONS_FOLDER": {
en `LIVE_TRANSCRIPTIONS_FOLDER`

2023-02-06 15:21 UTC, ptitloup requested changes
Il manque encore les modifications demandées pour les main lang

2023-02-06 15:25 UTC, ptitloup commented
merci de me dire quand tout est ok pour toi que je puisse refaire une passe

2023-02-06 15:41 UTC, Mateo6051 commented on pod/live/templates/live/event.html
> +                              <track kind="captions" src="{% get_setting "TRANSCRIPTIONS_FOLDER_URL" %}{{event.broadcaster.slug}}.vtt" srclang="{{event.broadcaster.main_lang}}">
c'est bon, j'aurais vraiment faire comme cela depuis le debut, c'est vraiment plus simple et logique.

2023-02-06 15:52 UTC, Mateo6051 commented on requirements.txt
> +stt==1.3.0 # linux only
Pas de souci, c'est fait

2023-02-06 15:55 UTC, Mateo6051 commented on pod/live/templates/live/event.html
> +                let vtt_url ="{% get_setting "TRANSCRIPTIONS_FOLDER_URL" %}" + filename
C'est fait

2023-02-06 15:58 UTC, Mateo6051 commented on pod/live/models.py
> +LANG_CHOICES = getattr(
C'est bon

2023-02-06 16:01 UTC, Mateo6051 commented on pod/live/models.py
> +from pod.main.lang_settings import PREF_LANG_CHOICES as PREF_LANG_CHOICES
C'est bon

2023-02-06 16:01 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +SAMPLE_RATE = 16000
C'est fait

2023-02-06 16:02 UTC, Mateo6051 commented on pod/live/templates/live/event.html
> +                let vtt_url ="{% get_setting "TRANSCRIPTIONS_FOLDER_URL" %}" + filename
c'est fait

2023-02-06 16:05 UTC, Mateo6051 commented on pod/main/configuration.json
> +                        "TRANSCRIPTIONS_FOLDER_URL": {
c'est fait

2023-02-06 16:07 UTC, Mateo6051 commented
Ok, appart les espaces je pense que tout est en ordre. J'ai testé aussi et tout marche niquel de mon coté.

2023-02-06 17:22 UTC, ptitloup requested changes
encore quelques changements à apporter mais on touche au but.
Merci

2023-02-06 17:22 UTC, ptitloup commented on pod/live/live_transcript.py
> +    SetLogLevel(-1)
Pourquoi avoir mis la valeur de logde vosk à -1 ?

2023-02-06 17:22 UTC, ptitloup commented on pod/live/models.py
> +    def get_transcription_file(self):
est-ce possible d'utiliser plutot ce type de fonction : 
`from urllib.parse import urljoin
urljoin(MEDIA_URL, LIVE_TRANSCRIPTIONS_FOLDER, "%s.vtt" % self.slug)`

2023-02-06 17:22 UTC, ptitloup commented on pod/live/models.py
> +    def get_transcription_file(self):
il faut utiliser LIVE_TRANSCRIPTIONS_FOLDER

2023-02-06 17:22 UTC, ptitloup commented on pod/live/templates/live/event.html
> +                              <track kind="captions" src="{{ event.broadcaster.get_transcription_file }}?v={% now "U" %}" srclang="{{event.broadcaster.main_lang}}?v={% now "U" %}">
merci de remplacer v= par d= (v pour ersion, d pour date)
ce n'est pas utile pour srclang

2023-02-07 08:23 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +    SetLogLevel(-1)
Le save path c'est le path où doivent être enregistrés les soustitres, et le nom du ficier correspond au slug du diffuseur. Et puis l'url c'est l'url du stream en m3u8 à traiter par la suite.

2023-02-07 08:31 UTC, Mateo6051 commented on pod/live/models.py
> +    def get_transcription_file(self):
En fait LIVE_TRANSCRIPTIONS_FOLDER de base c'est un chemin absolut qui met ensemble MEDIA_ROOT et le sous dossiers transcripts. Ce n'est donc pas une url.
```py
# settings_local
LIVE_TRANSCRIPTIONS_FOLDER = os.path.join(MEDIA_ROOT, "transcripts")
````

2023-02-07 08:33 UTC, Mateo6051 commented on pod/live/templates/live/event.html
> +                              <track kind="captions" src="{{ event.broadcaster.get_transcription_file }}?v={% now "U" %}" srclang="{{event.broadcaster.main_lang}}?v={% now "U" %}">
c'est fait

2023-02-07 08:44 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +    SetLogLevel(-1)
Et log level c'est pour eviter les logs de vosk. Il spam pas mal donc faux mieux eviter je pense

2023-02-07 08:58 UTC, ptitloup commented on pod/live/models.py
> +    def get_transcription_file(self):
pour moi tu devrais avoir juste LIVE_TRANSCRIPTIONS_FOLDER qui contient le nom du dossier et à ce dossier, tu joins media_root pour avoir le dossier et media_url pour son url

2023-02-07 09:00 UTC, ptitloup requested changes
il faut accorder LIVE_TRANSCRIPTIONS_FOLDER partout

2023-02-07 09:00 UTC, ptitloup commented on pod/live/live_transcript.py
> +    save_path = os.path.join(LIVE_TRANSCRIPTIONS_FOLDER, filename)
ca ne peut pas fonctionner, ton save_path doit etre os.path.join(MEDIA_ROOT, LIVE_TRANSCRIPTIONS_FOLDER, filename

2023-02-07 09:00 UTC, Mateo6051 commented on pod/live/models.py
> +    def get_transcription_file(self):
j'ai du coup fait un petit peux de refactoring, mais  le formatage n'est pas possible.
```py 
urljoin urljoin(MEDIA_URL, LIVE_TRANSCRIPTIONS_FOLDER, "%s.vtt" % self.slug)
```
La methode joinurl ne ressemble pas avec le formatage, je suis obligé de passer par de la concaténation.
```py 
    urljoin(MEDIA_URL, LIVE_TRANSCRIPTIONS_FOLDER + "/" + self.slug + ".vtt")
```

2023-02-07 09:00 UTC, ptitloup commented on pod/live/models.py
> +    def get_transcription_file(self):
d'ailleurs, tu fais bien dans live_transcript

2023-02-07 09:01 UTC, ptitloup commented on pod/live/live_transcript.py
> +    SetLogLevel(-1)
ok pour log level, pourle path, voir mon autre commentaire

2023-02-07 09:03 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +    save_path = os.path.join(LIVE_TRANSCRIPTIONS_FOLDER, filename)
j'ai justement fait ce changement

2023-02-07 09:03 UTC, Mateo6051 commented on pod/live/models.py
> +    def get_transcription_file(self):
ok ok je renomme

2023-02-07 09:04 UTC, ptitloup commented on pod/live/models.py
> +    def get_transcription_file(self):
oui il faut faire `transcript_file =  os.path.join(LIVE_TRANSCRIPTIONS_FOLDER, "%s.vtt" % self.slug)` puis faire un `urljoin(MEDIA_URL,transcript_file)`

2023-02-07 09:11 UTC, Mateo6051 commented on pod/live/models.py
> +    def get_transcription_file(self):
![image](https://user-images.githubusercontent.com/73032218/217201489-ac4d5522-ea2c-4d7c-b2fa-4f1d351a8e18.png)

2023-02-07 09:36 UTC, ptitloup commented on pod/live/models.py
> +    def get_transcription_file(self):
`>>> import os
>>> file_path = os.path.join("toto", "tata.vtt")
>>> file_path
'toto/tata.vtt'
>>> from urllib.parse import urljoin
>>> from django.conf import settings
>>> url = urljoin(settings.MEDIA_URL, file_path)
>>> url
'/media/toto/tata.vtt'
>>> `

2023-02-07 09:37 UTC, ptitloup commented on pod/live/models.py
> +    def get_transcription_file(self):
si cela devrait fonctionner

2023-02-07 09:37 UTC, ptitloup commented on pod/live/live_transcript.py
> +    save_path = os.path.join(LIVE_TRANSCRIPTIONS_FOLDER, filename)
ok je vais regarder

2023-02-07 09:38 UTC, Mateo6051 commented on pod/live/models.py
> +    def get_transcription_file(self):
je vais reessayer, le problème vient au niveau du os.path, le urljoin marche bien

2023-02-07 09:55 UTC, ptitloup commented
Merci pour la doc : https://github.com/Orion-Studios/pod-live-transcription 
je la valide !

2023-02-07 10:00 UTC, Mateo6051 commented on pod/live/models.py
> +    def get_transcription_file(self):
```py
path = os.path.join(LIVE_TRANSCRIPTIONS_FOLDER, filename) # live_transcripts\mateo.vtt
urljoin(settings.MEDIA_URL, path) # /media/live_transcripts\mateo.vtt
```
le probleme est donc que les "\" n'est pas remplacé par un "/".
Ca vous vas je rajoute juste cela après le urljoin?
```py
url = url.replace("\\", "/")
```

2023-02-07 10:01 UTC, Mateo6051 commented on pod/live/models.py
> +    def get_transcription_file(self):
Avec cela ça marche niquel a mon niveau

2023-02-07 10:04 UTC, Mateo6051 commented
Il faudrait modifier un peu la doc avec les dernières modifs qu'on a fait attendez je la mets à jour

2023-02-07 10:12 UTC, Mateo6051 commented
Ok, si ça vous va pour le "get_transcription_file", il resterai juste le problème des retours à la ligne dont vous m'avez parlé tout au début.

2023-02-07 10:15 UTC, ptitloup approved these changes
ok pour moi

2023-02-07 10:15 UTC, ptitloup commented on pod/live/models.py
> +    def get_transcription_file(self):
je comprends mieux, tu développe sous windows.
DU coup, je pense plutot qu'il faut faire 2 url join : 
```
filename_url = urljoin(LIVE_TRANSCRIPTIONS_FOLDER, filename)
media_filename_url = urljoin(MEDIA_URL, filename_url)
```
est-ce que cela te va ?

2023-02-07 10:16 UTC, ptitloup commented
Note pour plus tard, il faudrait voir pour faire un filefield en readonly qui permettra de retrouver plus facilement le fichier de transcription.

2023-02-07 10:19 UTC, Mateo6051 commented
```py
filename_url = urljoin(LIVE_TRANSCRIPTIONS_FOLDER, filename)
media_filename_url = urljoin(MEDIA_URL, filename_url)
```
Avec cela ça ne marche pas l'url finale devient "/media/mateo.vtt"

2023-02-07 10:20 UTC, ptitloup commented
> ```python
> filename_url = urljoin(LIVE_TRANSCRIPTIONS_FOLDER, filename)
> media_filename_url = urljoin(MEDIA_URL, filename_url)
> ```
> 
> Avec cela ça ne marche pas l'url finale devient "/media/mateo.vtt"

ok, je regarderais merci !

2023-02-07 10:25 UTC, ptitloup approved these changes
ok pour moi, merci pour ces derniers changements

2023-02-07 11:28 UTC, Mateo6051 commented
Du coup j'ai creer un field sur le model du diffuseur contentant le lien vers le fichier de soustitres correspondant. Ce fichier est crée lorsque l'on transcrit pour la première fois si le directoire ou le fichier n'ont pas déjà été crées. Si le répertoire n'avait pas été crée je le crée aussi et ensuite je sauvegarde le lien du fichier de soustitre dans le model du diffuseur. J'ai fait des tests à priori tout semble marcher niquel

2023-02-07 13:09 UTC, ptitloup commented
je regarde

2023-02-07 13:26 UTC, ptitloup requested changes

2023-02-07 13:26 UTC, ptitloup commented on pod/live/models.py
> +        null=True,
il fut mettre ce champ en readonly, on ne doit pas pouvoir le modifier, il est géré automatiquement

2023-02-07 13:27 UTC, ptitloup commented on pod/main/tasks.py
> +def task_start_live_transcription(self, url, slug, model):
d'ailleurs, ces taches pourraient se trouver dans pod/live/tasks.py

2023-02-07 13:35 UTC, Mateo6051 commented on pod/live/templates/live/event.html
> +        {{ event.broadcaster.transcription_file.url}}
C'est un coquille, c'était un debug je l'efface :)

2023-02-07 13:35 UTC, Mateo6051 commented on pod/live/models.py
> +        null=True,
c'est bon

2023-02-07 13:36 UTC, Mateo6051 commented on pod/live/live_transcript.py
> +    broadcaster = Broadcaster.objects.get(slug=slug)
Ok je vais voir cela

2023-02-07 14:01 UTC, Mateo6051 commented on pod/main/tasks.py
> +def task_start_live_transcription(self, url, slug, model):
En fait une tache est relié à un diffuseur afin d'être identifiée, du coup je dois recuperer forcément le diffuseur avec le slug pour ensuite créer la tache correspondante. Donc je suis obligé de faire des appels bd. Et pour l'endroit où se trouvent les taches, est ce que seulement avec le décorateur célery arrive à trouver les taches?
Parce que je ne suis pas sur si je mets les taches sur un autre fichier ça va marcher directement.

2023-02-07 14:06 UTC, Mateo6051 commented
J'ai fait du refactoring afin d'éviter les appels de bd dans le "live_transcript.py". J'ai testé pour l'instant avec les threads et ça marche correctement.
Il me faudra par contre tester pour céléry mais je le ferais plus tard puisque je n'ai pas un autre pc actuellement. En théory tout devrait marcher correctement puisque j'ai juste rajouté le paramètre du filepath

2023-02-07 14:50 UTC, ptitloup approved these changes
ok pour moi, merci

2023-02-07 14:51 UTC, ptitloup commented
juste une question que je viens de me poser, comment peut-on mettre à jour un fichier de sous-titre ? si par exemple j'ai un live le lundi et un auter le mardi, que va-t-il se passer ? Merci

2023-02-07 14:56 UTC, ptitloup commented
de plus, et la aussi je viens de m'en rendre compte, le model a été modifié mais pas les tests unitaire, est-ce possible de tester ces champs pour vérifier le bon fonctionnement ? Merci

2023-02-07 14:57 UTC, Mateo6051 commented
Le fichier se met à jour tout seul, une fois le live lancé, on va écrire les nouveaux soustitres et les précedents vont être écrasés.

2023-02-07 15:01 UTC, ptitloup commented
> Le fichier se met à jour tout seul, une fois le live lancé, on va écrire les nouveaux soustitres et les précedents vont être écrasés.

de ce fait, on aura jamais l'ensemble des sous-titres à la fin d'un live ? si ?

2023-02-07 15:07 UTC, Mateo6051 commented
Non, on les aura pas, on peut les écrire dans un autre fichier mais le temps vtt ne correspondra pas à celui du flux.

2023-02-07 15:16 UTC, ptitloup commented
> Non, on les aura pas, on peut les écrire dans un autre fichier mais le temps vtt ne correspondra pas à celui du flux.

Ha ok, merci !

2023-02-08 09:52 UTC, ptitloup commented
Bonjour, est-ce possible de donner l'accès à la doc à @mattbild svp ? Merci !

2023-02-08 10:15 UTC, mattbild commented
si j'ai bien compris le setting MODEL_PARAM a été modifié en TRANSCRIPTION_MODEL_PARAM
Il faudra penser à modifier la [doc esup](https://www.esup-portail.org/wiki/display/ES/Installation+de+l%27autotranscription+en+Pod+V3#Installationdel'autotranscriptionenPodV3-Pourtesterlatranscriptionenlignedecommande) au passage
mais je vois toujours une référence à MODEL_PARAM dans pod/completion/admin.py : 
`MODEL_PARAM = getattr(settings, "MODEL_PARAM", {})`
On a les deux entrées dans le configuration.json du coup.
C'est normal ? 
@ptitloup

2023-02-08 10:17 UTC, Mateo6051 commented
C'est bon, normalement il a accès.

2023-02-08 10:18 UTC, ptitloup commented
En effet, il y a maintenant TRANSCRIPTION_MODEL_PARAM et  LIVE_TRANSCRIPTION_MODEL_PARAM.
S'il reste un, il s'agit d'un oubli. Il faut en effet également retirer l'entrée dans le fichier de configuration

2023-02-08 10:18 UTC, ptitloup commented
Il ne faut pas le faire dans cette PR mais plutot dans develop, je pourrais regarder ca cet après midi

2023-02-08 10:19 UTC, ptitloup commented
Merci pour cette remarque !

2023-02-08 10:53 UTC, mattbild commented
En fait il y a plusieurs param qu'il faudrait revoir dans les différentes docs et dans l'appli :
MODEL_PARAM
TRANSCRIPTION_MODEL_PARAM
LIVE_VOSK_MODEL

2023-02-08 10:56 UTC, mattbild commented
Aussi on ne peut pas paramétrer le transcription_file dans le modèle Broadcaster en admin.
Comment doit-on l'ajouter le champ ?

2023-02-08 12:00 UTC, Mateo6051 commented
Ce champ c'est un champ readonly, on est pas sensé le parametrer.

2023-02-08 12:43 UTC, mattbild commented
mais à quel moment est-il rempli alors ?
A part dans la rest_views, je ne vois pas de méthode qui change sa valeur.

2023-02-08 13:24 UTC, Mateo6051 commented
C'est que dans le rest views. Ca valeur est définie qu'une seule fois.

2023-02-08 13:41 UTC, mattbild commented
j'ai beau être matinal, je ne comprends pas

2023-02-08 13:56 UTC, Mateo6051 commented
En fait, l'utilité de ce champ et de pouvoir facilement récupérer l'url du fichier vtt qui contient les transcriptions correspondantes à un direct (du coup d'un diffuseur). La valeur de ce champ est donc définie dans le rest view pour un nouveau diffuseur lorsque un live est lancé. Après cette valeur est récuperer dans les templates afin d'indiquer à videojs où se trouve le fichier de soustitres.

2023-02-08 14:04 UTC, mattbild commented
ok mais : 

- cela produit une erreur dans l'affichage du live quand la valeur n'est pas saisie sur le Brodacaster 
- on ne peut pas ajouter un nouveau diffuseur dans la partie admin : il faudrait le supprimer des fields et tester si obj is None (comme pour le qrcode)

2023-02-08 14:47 UTC, ptitloup commented
@Mateo6051 il faudrait qu'on puisse echanger, tu pourrais nous inviter sur votre slack ? Merci

2023-02-08 14:53 UTC, Mateo6051 commented
Il y a deja un channel sur slack normalement

2023-02-09 13:28 UTC, ptitloup commented
ok merci bcp

2023-02-09 14:56 UTC, Badatos commented on requirements.txt
> +stt==1.3.0 # linux only
De ce que je vois, stt et vosk apparaissent toujours dans les requirements.

2023-02-09 14:57 UTC, Badatos commented
De ce que je vois, stt et vosk apparaissent toujours dans les requirements.

2023-02-09 15:26 UTC, Mateo6051 commented
C'est fait j'ai enlevé, c'est bien dit dans la doc qu'il faut le installer  vosk et comment le faire

2023-02-09 15:38 UTC, Badatos approved these changes

2023-02-09 15:39 UTC, merged

2023-02-09 15:39 UTC, ptitloup commented
Merci bcp pour cette contribution