fix liveevent qrcode in admin part
EsupPortail/Esup-Pod pull request #743
Opened 2023-01-24 11:16 UTC by mattbild

cannot add a new broadcaster after qrcode feature

2023-01-24 11:30 UTC, Badatos commented on pod/live/admin.py
> +        return ["building"]
video_on_hold n'est plus un `autocomplete_fields` ?

2023-01-24 11:39 UTC, mattbild commented on pod/live/admin.py
> +        return ["building"]
Si bien sûr , bien vu, je l'avais zappé des fields (je suis sur une autre Pr où ce champs disparait justement).
C'est remis

2023-01-25 16:06 UTC, ptitloup requested changes
Il faut préciser l'exception dans la generation du qrcode

2023-01-25 16:06 UTC, ptitloup commented on pod/live/models.py
> +        except Exception:
il faut eviter les exceptions généralistes. Quelle exception leves-tu ici ?

2023-01-26 07:44 UTC, mattbild commented on pod/live/models.py
> +        except Exception:
aucune précise, c'est pour anticiper un problème éventuel de génération du qrcode

2023-01-26 13:18 UTC, ptitloup commented on pod/live/models.py
> +        except Exception:
Alors il faut le retirer sinon on pourra jamais voir s'il y a un pb. Merci :-)

2023-01-27 08:50 UTC, mattbild commented on pod/live/models.py
> +        except Exception:
c'est supprimé. Le test unitaire est modifié en conséquence

2023-01-27 09:19 UTC, ptitloup commented on pod/live/models.py
> +        except Exception:
ok merci !

2023-01-27 09:19 UTC, ptitloup approved these changes
ok pour moi

2023-01-27 09:30 UTC, merged