[WIP] create xapi app to manage and send statements
EsupPortail/Esup-Pod pull request #748
Opened 2023-01-27 14:24 UTC by ptitloup

2023-02-08 09:19 UTC, Badatos commented on pod/main/configuration.json
> +                                    "Activation de l'envoie de statement pour le lecteur video. Attention, il faut mettre USE_XAPI à True pour que les statements soient envoyés"
Correction de typo FR : 

> Active l‘envoi d’instructions xAPI pour le lecteur vidéo.
> Attention, il faut mettre USE_XAPI à True pour que les instructions soient envoyées.

2023-02-08 09:20 UTC, Badatos commented on pod/main/configuration.json
> +                                    ""
Je propose une desc EN :

> Enables sending xAPI statements for the video player.
> Attention, you must set USE_XAPI to True for the statements to be sent.

2023-02-08 09:24 UTC, Badatos commented on pod/main/configuration.json
> +                            "application pour l'envoie de statement xAPI à un LRS.",
Correction typo FR : 

> "Application pour l’envoi d‘instructions xAPI à un LRS.",
> "Aucune instruction ne persiste dans Pod, elles sont toutes envoyées au LRS paramétré.",
> "Attention, il faut configurer *Celery* pour l’envoi des instructions."

2023-02-08 09:26 UTC, Badatos commented on pod/main/configuration.json
> +                        "en": [
proposition de texte EN :

> Application for sending xAPI statements to an LRS.
> No statements persist in Pod, they are all sent to the configured LRS.
> Please note, *Celery* must be set to send statements.

2023-02-08 09:27 UTC, Badatos commented on pod/main/configuration.json
> +                                    "Si False, le nom de l'utilisateur sera stocké en clair dans les statements xAPI, si False, son nom d'utilisateur sera anonymisé"
Il y a 2X "si False". le 2e doit être un "True".

2023-02-08 09:31 UTC, Badatos commented on pod/xapi/tasks.py
> +    """Sends the xapi statement to the specify LRS."""
typo EN : "specified"

2023-02-08 09:31 UTC, Badatos commented on pod/xapi/tasks.py
> +        logger.error('Error during sending statement : %s' % x.text)
typo EN : pas d'espace avant les double points en anglais

2023-02-08 09:36 UTC, Badatos commented on pod/xapi/templates/xapi/xapi_video.html
> +    const endpoint = "{% url "xapi:statement" app="video" %}";
C'est domage de mettre tout ce code en inline html. Je propose de ne garder que les 20 premiere lignes qui nécessitent du code template en html, et de basculer le reste en fichier .js

2023-02-08 09:40 UTC, Badatos commented on requirements.txt
> -stt==1.3.0
est-ce qu'on place les librairies necessaires à la transcription dans un requirements-transcript.txt histoire de garder les version compatibles quelque-part et pour faciliter l'installation ?

2023-02-09 10:43 UTC, ptitloup commented on pod/main/configuration.json
> +                                    "Activation de l'envoie de statement pour le lecteur video. Attention, il faut mettre USE_XAPI à True pour que les statements soient envoyés"
Done

2023-02-09 10:44 UTC, ptitloup commented on pod/xapi/templates/xapi/xapi_video.html
> +    const endpoint = "{% url "xapi:statement" app="video" %}";
C'est fait, ok avec toi

2023-02-09 10:44 UTC, ptitloup commented on requirements.txt
> -stt==1.3.0
On pense pour le moment les spécifier dans la doc

2023-03-01 11:29 UTC, Badatos approved these changes
ok pour moi

2023-03-06 13:41 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +  {% get_setting "USE_XAPI_VIDEO" False as USE_XAPI_VIDEO %}
très bonne question, je vais chercher la valeur du paramètre USE_XAPI_VIDEO dans la configuration de Pod, cela evite de le passer via le context processor ou via la vue

2023-03-06 13:42 UTC, ptitloup commented on pod/xapi/static/xapi/script-video.js
> +const __XAPI_VIDEO_VERBS__ = {
Cette convention de nommage a été validée pour le python, je l'ai egalement utilisée pour le javascript même si cela na pas vraiment d'effet (ni dans un cas ni dans un autre)

2023-03-06 13:43 UTC, ptitloup commented on pod/xapi/static/xapi/script-video.js
> +player.on("seeking", function (e) { });
oui cela ne fait rien à la fin, je m'en étais servi à la base pour savoir quand l'utilisateur se déplacait adns la vidéo mais il fallait le point de épart et je ne l'avais pas via cet evenement, seulement le point d'arrivé

2023-03-06 13:47 UTC, ptitloup commented on pod/xapi/static/xapi/script-video.js
> +player.on("ratechange", function (e) {
la fonction _set_interacted_statement_ sert à créer un dictionnaire our l'action interacted selon le schéma de l'API. Cela vaut egalement pour set_completed_statement. la fonction _active statement_ sert à créer le steatement avec le bon statement et à l'envoyer. Elle fait appel pour cela au fichier script.js de l'app xapi

2023-03-06 13:49 UTC, ptitloup commented on pod/xapi/static/xapi/script-video.js
> +player.on('play', function() {
nope, la variable player est créé dans le même template mais plus en amont, lors de la création du lecteur videojs

2023-03-06 13:55 UTC, pampletousse commented on pod/video/templates/videos/video.html
> +  {% get_setting "USE_XAPI_VIDEO" False as USE_XAPI_VIDEO %}
Ok pour moi, comportement peut être à reporter dans d'autres vues pour uniformiser?

2023-03-06 13:55 UTC, pampletousse commented on pod/xapi/static/xapi/script-video.js
> +player.on("seeking", function (e) { });
On peut l'enlever dans ce cas ?

2023-03-06 13:57 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +  {% get_setting "USE_XAPI_VIDEO" False as USE_XAPI_VIDEO %}
en fait, c'est compliqué d'uniformiser. Dans Django, il y a 3 possibilités de passer des variables dans le contexte de la requete : via le context_processor, via le passage en paramètre dans la vue et en allant checher le paramètre via un template tag (methode choisie dans ce cas car utilise seulement si on active l'application)

2023-03-06 14:02 UTC, pampletousse requested changes

2023-03-06 14:02 UTC, pampletousse commented on pod/xapi/static/xapi/script-video.js
> +player.on("seeking", function (e) { });
L'enlever me semble plus correct s'il n'a aucune utilité

2023-03-06 14:06 UTC, ptitloup commented on pod/xapi/static/xapi/script-video.js
> +player.on("seeking", function (e) { });
c'est fait !

2023-03-06 14:07 UTC, pampletousse approved these changes
ok pour moi

2023-03-06 15:19 UTC, merged