Loic bonavent/meeting thumbnail mode1
EsupPortail/Esup-Pod pull request #769
Opened 2023-03-10 14:38 UTC by LoicBonavent

Implements thumbnail mode : 

- cut the source code in multiple files
- create and manage DEFAULT_MEETING_THUMBNAIL parameter
- add filters, and for meetings (all/active) and for recordings (tags)
- achieve the necessary translations

2023-03-10 16:04 UTC, ptitloup requested changes
première passe qui me semble ok à part une remarque.

2023-03-10 16:07 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +"Vous n'avez pas encore de réunions actives, veuillez utiliser le bouton "
Je mettrais "pas encore de réunions actives" au singulier, vu qu'il n'y en a pas encore ;)

2023-03-10 16:10 UTC, Badatos commented on pod/meeting/static/img/default-meeting.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Quelle est la source et la licence de cette image ?
Si c'est du CC, faut-il indiquer l'auteur dans les crédits de Pod ?

2023-03-10 16:31 UTC, Badatos commented on pod/meeting/templates/meeting/meeting_card.html
> +      <img class="card-img-top" src="{{ DEFAULT_MEETING_THUMBNAIL }}" alt="{% trans 'Meeting' %}" loading="lazy">
Je ne suis pas sûr que l'alt "Meeting" soit très utiles aux mal voyants, surtout s'il est répété à l'identique pour chaque meeting. quand l'image est purement décorative, il est préférable de mettre un alt vide : `alt=""`

2023-03-10 16:31 UTC, LoicBonavent commented on pod/main/settings.py
> +DEFAULT_MEETING_THUMBNAIL = "/img/default-meeting.svg"
OK, c'est retiré

2023-03-10 16:34 UTC, LoicBonavent commented on pod/meeting/templates/meeting/meeting_card.html
> +      <img class="card-img-top" src="{{ DEFAULT_MEETING_THUMBNAIL }}" alt="{% trans 'Meeting' %}" loading="lazy">
Ok, j'ai mis alt=""

2023-03-13 13:42 UTC, LoicBonavent commented
Toutes les modifications demandées ont été réalisées.

2023-03-15 09:18 UTC, merged