[DONE] 3.1 FIX - Pampletousse/fix fvideo list refresh with filters
EsupPortail/Esup-Pod pull request #770
Opened 2023-03-10 14:47 UTC by pampletousse

Fix for 3.1 : video list refresh with dynamic filter -> wrong inject method

2023-03-10 15:29 UTC, ptitloup approved these changes
ok en effet, ca tourne par contre, ca change pas le nombre de vidéo affichée...

2023-03-10 15:47 UTC, Badatos commented
Pour corriger le souci d'affiche du nombre de vidéos je propose cette correction :
### Dans video/template/video/video_list.html
* ajouter data-countvideos="{{ count_videos }}" au div id="videos_list"
* retirer le bloc <script>var countVideos = "{{ count_videos }}";</script>
### Dans video/template/video/video_list.html
remplacer 
`replaceCountVideos(countvideos);`
par 
`replaceCountVideos(document.getElementById("videos_list").dataset.countvideos);`

2023-03-10 15:48 UTC, ptitloup commented
> Pour corriger le souci d'affichagee du nombre de vidéos je propose cette correction :
> ### Dans video/template/video/video_list.html
> 
>     * ajouter data-countvideos="{{ count_videos }}" au div id="videos_list"
> 
>     * retirer le bloc <script>var countVideos = "{{ count_videos }}";</script>
> 
> 
> ### Dans video/template/video/video_list.html
> 
> remplacer `replaceCountVideos(countvideos);` par `replaceCountVideos(document.getElementById("videos_list").dataset.countvideos);`

je regarde ca de suite

2023-03-10 15:53 UTC, ptitloup commented
Super, ca fonctionne ! 
je corrige ma review en ce sens

2023-03-10 15:57 UTC, ptitloup requested changes
Voici mon changelog pour l'ensemble des remarques : 
```
diff --git a/pod/video/static/js/filter_aside_video_list_refresh.js b/pod/video/static/js/filter_aside_video_list_refresh.js
index 7eece9cf..994d870f 100644
--- a/pod/video/static/js/filter_aside_video_list_refresh.js
+++ b/pod/video/static/js/filter_aside_video_list_refresh.js
@@ -75,20 +75,21 @@ function refreshVideosSearch(formCheckedInputs) {
       // parse data into html and replace videos list
       // destroy waypoint id exists
 
-      let html = new DOMParser().parseFromString(data, "text/html").body;
+      let parser = new DOMParser();
+      let html = parser.parseFromString(data, "text/html").body;
+      document.getElementById("videos_list").outerHTML = html.innerHTML;
 
       //document.querySelector(".infiniteloading").style.display = "none";
       //document.querySelector(".infinite-more-link").style.display = "none";
-      document.getElementById("videos_list").outerHTML =
-        html.getElementById("videos_list").outerHTML;
+      //document.getElementById("videos_list").outerHTML =
+      //  html.getElementById("videos_list").outerHTML;
       let nextPage = document
         .getElementById("videos_list")
         .getAttribute("nextPage");
-
-      replaceCountVideos(countVideos);
+      replaceCountVideos(document.getElementById("videos_list").dataset.countvideos);
       window.history.pushState({}, "", this.url);
       hideInfiniteloading();
-      if (nextPage) {
+      f (nextPage != "False") {
         pageNext = document
           .querySelector("a.infinite-more-link")
           .getAttribute("nextPageNumber");
diff --git a/pod/video/templates/videos/video_list.html b/pod/video/templates/videos/video_list.html
index fabf805a..1d364a57 100644
--- a/pod/video/templates/videos/video_list.html
+++ b/pod/video/templates/videos/video_list.html
@@ -1,6 +1,6 @@
 {% load i18n %}
 {% spaceless %}
-<div class="pod-infinite-container infinite-container" id="videos_list" nextPage = "{{ videos.has_next }}">
+<div class="pod-infinite-container infinite-container" id="videos_list" nextPage = "{{ videos.has_next }}" data-countvideos="{{ count_videos }}">
   {% for video in videos %}
     <div class="infinite-item card-group" {% if categories %}data-slug={{video.slug}}{% endif %} >
       {% include "videos/card.html" %}
@@ -23,6 +23,3 @@
   {% trans "Loading…" %}
 </div>
 {% endspaceless %}
-<script>
-var countVideos = "{{ count_videos }}";
-</script>
```

2023-03-10 15:57 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
>          .getAttribute("nextPage");
merci de remplacer replaceCountVideos(countVideos); par replaceCountVideos(document.getElementById("videos_list").dataset.countvideos);

dans le fichier templates video_list.html, merci de changer la div par : 
<div class="pod-infinite-container infinite-container" id="videos_list" nextPage = "{{ videos.has_next }}" data-countvideos="{{ count_videos }}">

2023-03-10 15:57 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      document.getElementById("videos_list").outerHTML = html.outerHTML;
je pense qu'il faut mettre "= html.innerHTML" pour ne pas rajouter le body

2023-03-10 15:58 UTC, ptitloup commented
Merci

2023-03-13 16:06 UTC, ptitloup commented
@pampletousse tu nous diras quand toutes les modifs seront ok pour toi qu'on regarde à nouveau.
Merci

2023-03-14 12:33 UTC, pampletousse commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      document.getElementById("videos_list").outerHTML = html.outerHTML;
J'ai testé pour moi ça marche ça ne change uniquement le contenu = comportement attendu

2023-03-14 12:38 UTC, pampletousse commented
C'est tout bon à priori j'ai fait vos modifs

2023-03-14 12:57 UTC, ptitloup reviewed
ok sauf pour le inner vs outer à verifier

2023-03-14 12:57 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
>          .getAttribute("nextPage");
ok

2023-03-14 12:57 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      document.getElementById("videos_list").outerHTML = html.outerHTML;
je vais regarder

2023-03-14 13:45 UTC, ptitloup requested changes
merci de faire les 2 corrections demandées et ca sera ok. Merci !

2023-03-14 13:45 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      if (nextPage != "False")
il manque une accolade ouvrante

2023-03-14 13:45 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      if (nextPage != "False")
if (nextPage != "False") {

2023-03-14 13:45 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      document.getElementById("videos_list").outerHTML = html.outerHTML;
Je confirme qu'il faut bien préciser innerHTML.
la div à remplacer est cette dernière : `<div class="pod-infinite-container infinite-container" id="videos_list" nextpage="True" data-countvideos="10970"></div>`
Si tu utilises le outerHTML, tu vas remplacer la div par ce code : ```<body><div class="pod-infinite-container infinite-container" id="videos_list" nextpage="False" data-countvideos="1"> [...] </div></body>```
alors que le innerHTML ne va contenir que le code nécessaire : ```<div class="pod-infinite-container infinite-container" id="videos_list" nextpage="False" data-countvideos="1"> [...] </div>```

2023-03-14 13:57 UTC, pampletousse commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      document.getElementById("videos_list").outerHTML = html.outerHTML;
Etrange puisque chez moi ça marchait mais je te fais confiance ^^

2023-03-14 13:59 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      document.getElementById("videos_list").outerHTML = html.outerHTML;
chez moi auss ica fonctionnait mais cela engendrait une interpretation supplémentaire du navigateur

2023-03-14 13:59 UTC, ptitloup commented on pod/video/static/js/filter_aside_video_list_refresh.js
> +      document.getElementById("videos_list").outerHTML = html.outerHTML;
merci pour ces modifs, je vais pouvoir merger la PR

2023-03-14 14:04 UTC, merged