[DONE] live_event disable buttons when stop is clicked
EsupPortail/Esup-Pod pull request #778
Opened 2023-03-14 08:56 UTC by mattbild

2023-03-14 10:00 UTC, Badatos commented on pod/live/templates/live/event-script.html
> +        $("#stoprecord").prop('disabled', true)
Jquery est en passe d'etre retiré de Pod. Y'a-t-il moyen de faire cela en vanilla js ?

2023-03-14 10:08 UTC, mattbild commented on pod/live/templates/live/event-script.html
> +        $("#stoprecord").prop('disabled', true)
je sais qu'il y a plein de jquery dans ce fichier ....
Je pense qu'il faut faire un autre PR avec 'juste' le passage en vanilla js

2023-03-14 10:13 UTC, ptitloup commented on pod/live/templates/live/event-script.html
> +        $("#stoprecord").prop('disabled', true)
je viens de parcourir le fichier event-script.html et en effet, je note encore plein de jquery dedans... Jquery est retiré de Pod, ces scripts ne peuvent plus fonctionné (ou alors je ne sais pas comment)

2023-03-14 10:28 UTC, mattbild commented on pod/live/templates/live/event-script.html
> +        $("#stoprecord").prop('disabled', true)
il est encore dans les dépendances, non ?
https://github.com/EsupPortail/Esup-Pod/blob/develop/pod/package.json#L10-L11

2023-03-14 12:52 UTC, ptitloup requested changes

2023-03-16 14:26 UTC, ptitloup reviewed
quelques remarques, pas testé fonctionnellement

2023-03-16 14:26 UTC, ptitloup commented on pod/bbb/views.py
> +
c pas mal de faire cela en entete des vues ajax

2023-03-16 14:26 UTC, ptitloup commented on pod/live/templates/live/event-script.html
> +                'Content-Type': 'application/json',
tu peux regarder dans le main.js j'ai fait pas mal de dev de fetch dans ce sens si tu veux reprendre mon code

2023-03-16 14:26 UTC, ptitloup commented on pod/live/templates/live/event-script.html
> +            }).then((data) => {
c'est ce que j'utilise dans le main.js, tu peux voir cela pour utiliser la mm methode plus haut à la place du json.strigify mais j'ai peut etre mal lu

2023-03-17 08:38 UTC, Badatos commented on pod/bbb/views.py
> +
En effet ! on pourrait d'ailleurs ajouter ce test dans les décorateurs ajax_login_required et ajax_required de `pod/main/decorators.py` ?

2023-03-17 08:39 UTC, Badatos commented on pod/bbb/views.py
> +
et du coup, appliquer ce décorateur ici si cette vue ne doit etre utilisée que via des appels JS.

2023-03-17 08:48 UTC, ptitloup commented on pod/bbb/views.py
> +
alors j'ai pas fait attention mais il me semble que l'application bbb sera remplacée à terme par l'application meeting

2023-03-17 10:13 UTC, mattbild commented on pod/bbb/views.py
> +
c'est ce que m'a dit Loïc hier, mais ça ne sera pas le cas tout de suite

2023-03-17 13:14 UTC, merged