[WIP] Feature/improve archiving
EsupPortail/Esup-Pod pull request #782
Opened 2023-03-21 11:06 UTC by Badatos

2023-03-21 14:46 UTC, ptitloup requested changes
Merci pour cette contribution

2023-03-21 14:46 UTC, ptitloup commented on .gitignore
> -pod/node_modules/*
je vois pas node_modules ailleurs, pourquoi le retirer ?

2023-03-21 14:46 UTC, ptitloup commented on pod/main/configuration.json
> +                                    "voir `ACTIVE_MODEL_ENRICH"
il manque pas le mm signe ` à la fin ?

2023-03-21 14:46 UTC, ptitloup commented on pod/main/configuration.json
> +                                    "voir `ACTIVE_MODEL_ENRICH"
d'ailleur, la creation du MD est tout pété en master, tu pourrais corriger dans cette branche stp ?

2023-03-21 14:46 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
On pourrait avoir un peu d'info sur cette nouvelle commande ? Quand et comment on peut la lancer ?

2023-03-21 14:46 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
Merci

2023-03-21 15:04 UTC, Badatos commented on .github/workflows/pod.yml
> +          coverage run --source='.' manage.py create_pod_index --settings=pod.main.test_settings
Je me suis dit : ca mange pas de pain : si la création de l'index fait passer le coverage par des ligne qui n'étaient pas encore couvertes autant l'ajouter.

2023-03-21 15:06 UTC, Badatos commented on .github/workflows/pod.yml
> +          coverage run --append --source='.' manage.py runserver localhost:9090 --insecure --settings=pod.main.test_settings &
Jusqu'à présent, seuls les tests unitaires ajoutaient de la couverture. Avec ca, si un test fonctionnel active des fonctions (notamment ajax) qui n'étaient pas couvertes jusqu'ici, elles le seront.

2023-03-21 15:07 UTC, Badatos commented on .gitignore
> -pod/node_modules/*
il est présent ligne 79

2023-03-21 15:19 UTC, Badatos commented on pod/video/management/commands/clean_video_files.py
Ca va servir essentiellement à supprimer des éléments qui n'étaient pas nettoyées dans les anciennes versions de Pod.

2023-03-21 16:42 UTC, ptitloup commented on .github/workflows/pod.yml
> +          coverage run --append --source='.' manage.py runserver localhost:9090 --insecure --settings=pod.main.test_settings &
ok !

2023-03-21 16:44 UTC, ptitloup commented on pod/main/configuration.json
> +                                    "voir `ACTIVE_MODEL_ENRICH"
Merci

2023-03-21 16:45 UTC, ptitloup commented on pod/video/management/commands/clean_video_files.py
ok cool merci (il me semble que c'est moi qui ais développé cette fonction mais m'en souvenais plus :D )

2023-03-21 16:46 UTC, ptitloup approved these changes
ok pour moi

2023-03-21 16:48 UTC, ptitloup commented
ok niveau code mais les tests unitaires ne passent pas, tu peux regarder pourquoi ? merci

2023-03-22 09:04 UTC, Badatos commented
> ok niveau code mais les tests unitaires ne passent pas, tu peux regarder pourquoi ? merci

Ca ne passe plus depuis le merge d'une des dernière PR sur les live :

```
FAIL: test_attributs (pod.live.tests.test_models.BroadcasterTestCase)
[2891](https://github.com/EsupPortail/Esup-Pod/actions/runs/4478116375/jobs/7870479758#step:11:2892)
----------------------------------------------------------------------
[2892](https://github.com/EsupPortail/Esup-Pod/actions/runs/4478116375/jobs/7870479758#step:11:2893)
Traceback (most recent call last):
[2893](https://github.com/EsupPortail/Esup-Pod/actions/runs/4478116375/jobs/7870479758#step:11:2894)
  File "/home/runner/work/Esup-Pod/Esup-Pod/pod/live/tests/test_models.py", line 139, in test_attributs
[2894](https://github.com/EsupPortail/Esup-Pod/actions/runs/4478116375/jobs/7870479758#step:11:2895)
    self.assertEqual(broadcaster.transcription_file.url, "/media/testfile.vtt")
[2895](https://github.com/EsupPortail/Esup-Pod/actions/runs/4478116375/jobs/7870479758#step:11:2896)
AssertionError: '/media/live_transcripts/broadcaster1.vtt' != '/media/testfile.vtt'
[2896](https://github.com/EsupPortail/Esup-Pod/actions/runs/4478116375/jobs/7870479758#step:11:2897)
- /media/live_transcripts/broadcaster1.vtt
[2897](https://github.com/EsupPortail/Esup-Pod/actions/runs/4478116375/jobs/7870479758#step:11:2898)
+ /media/testfile.vtt
```

2023-03-22 09:20 UTC, Badatos commented
J'ai remplacé "testfile.vtt" par "broadcaster1.vtt" pour que ca passe les tests, mais pour faire bien je pense qu'il faudra ajouter un tests supplémentaire pour vérifier que testfile.vtt est bien présent quelque-part. (ou alors c'est qu'il ne faut plus préciser le fichier vtt à la création du Broadcaster)

2023-03-22 10:54 UTC, ptitloup requested changes

2023-03-22 13:10 UTC, ptitloup approved these changes

2023-03-22 13:22 UTC, ptitloup submitted a review, later dismissed
ok pour moi, merci !

2023-03-23 10:16 UTC, ptitloup approved these changes
ok

2023-03-23 10:56 UTC, merged