[Done] Hide channel desc
EsupPortail/Esup-Pod pull request #794
Opened 2023-03-31 15:04 UTC by Badatos

Adress the #785 issue
Collapse channel and theme descriptions on video display

2023-03-31 15:14 UTC, ptitloup requested changes
Il faut traduire les titre des boutons d'ouverture des accordéons

2023-03-31 15:14 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#theme_desc" aria-expanded="true" aria-controls="theme_desc">Description du thème</but
A traduire !

2023-03-31 15:14 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#channel_desc" aria-expanded="true" aria-controls="channel_desc">Description de la chaine<
A traduire !

2023-03-31 15:35 UTC, ptitloup commented on pod/video/templates/videos/video.html
>    {% if channel.description %}
est-ce qu'il faut mettre un accorédon tout le temps ou jsute si la description fait plus d'une dizaine de mot par exmeple ? idem pour les thèmes !

2023-04-01 08:25 UTC, Badatos commented on pod/video/templates/videos/video.html
>    {% if channel.description %}
en effet si la description fait moins d'une phrase l'accordéon n'est pas très utile. Le cas d'une description dourtte de chaine se produit-il ? j'ai l'impression qu'il y a quasiment toujours une description de plusieurs phrases.

2023-04-03 06:50 UTC, ptitloup commented on pod/video/templates/videos/video.html
>    {% if channel.description %}
tu peux mixer https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#striptags et https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#wordcount pour faire un test et si plus de 20 mots par exemple, tu le mets dans un accordéon

2023-04-03 09:13 UTC, Badatos commented
Voila la description ne passe en accordéon que pour les longues desriptions ;)

2023-04-03 12:18 UTC, ptitloup requested changes

2023-04-03 12:18 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +        {% if theme.description|length > 40 %}
même remarque

2023-04-03 12:18 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +            {{ channel.description|safe }}
heu, je pense qu'il faut mettre `theme.description` et le safe n'est pas utile car ce n'est pas un champ riche il me semble ;)

2023-04-03 12:25 UTC, Badatos commented on pod/video/templates/videos/video.html
> +    {% if channel.description|length > 40 %}
Pas vraiment : la description peut contenir peu de mots mais des balises html comme des images ou des iframe qui seront très larges et nécessitent tout de même l’accordéon

2023-04-03 12:30 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +    {% if channel.description|length > 40 %}
je te l'accorde, on peut rajouter une image mais bon, est-ce que ca va être souvent le cas alors qu'on peut mettre un bandeau ? je sais pas. En tout cas, 40 caractères, ca fait peu non ? je laisse le second reviewer donner son avis

2023-04-03 12:47 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +    {% if channel.description|length > 40 %}
ca me va, c'est un bon compromis merci !

2023-04-03 12:52 UTC, Badatos commented on pod/video/templates/videos/video.html
> +            {{ channel.description|safe }}
bien vu en effet, je corrige de suite.
theme.description n'est pas un champ wysiwyg, mais les codes html y sont acceptés et affiché dans la description du theme.

2023-04-03 12:56 UTC, ptitloup approved these changes
ok pour moi !

2023-04-03 14:59 UTC, mattbild requested changes
par hasard, j'ai mis une image alignée à droite dans la description de la chaine et rien après (pourquoi ?, je ne sais pas vraiment ).
Mais l'affichage de cette image n'est pas bonne, la vidéo repasse dessus lorsqu'on déplie l'accordéon.

Edit : 
Bon, il suffit d'ajouter des lignes vides jusqu'en dessous de l'image pour que l'affichage soit correct ...
Ça ne mérite peut être pas de s'énerver trop dessus

2023-04-03 15:06 UTC, mattbild approved these changes

2023-04-03 15:21 UTC, Badatos commented
> par hasard, j'ai mis une image alignée à droite dans la description de la chaine et rien après (pourquoi ?, je ne sais pas vraiment ). Mais l'affichage de cette image n'est pas bonne, la vidéo repasse dessus lorsqu'on déplie l'accordéon.

Bien vu @mattbild :) Le souci n'est pas lié à l'accordéon (ça se produisait déjà avant), mais du coup je l'ai fixé dans les 2 cas ^^.

2023-04-03 15:55 UTC, merged