[WIP] fix podfile
EsupPortail/Esup-Pod pull request #798
Opened 2023-04-06 12:47 UTC by ptitloup

… all folder in the same place

2023-04-07 09:55 UTC, ptitloup reviewed
il ne manque que la traduction mais ca me semble ok

2023-04-07 10:06 UTC, Badatos commented on pod/podfile/views.py
> +def get_filter_user_folder(request, folder_list, search):
Un petit Pydoc (`"""Description de la fonction."""`)  ? ;)

2023-04-07 10:12 UTC, ptitloup commented on pod/podfile/views.py
> +def get_filter_user_folder(request, folder_list, search):
fait

2023-04-11 07:15 UTC, pampletousse requested changes

2023-04-11 07:15 UTC, pampletousse commented on pod/podfile/templates/podfile/customfilewidget.html
> +  //console.log("coucou");
console log à virer ?

2023-04-11 07:15 UTC, pampletousse commented on pod/podfile/templates/podfile/customfilewidget.html
> +  //console.log("id_input : " + id_input);
console.log à virer ?

2023-04-11 07:41 UTC, vsabatie approved these changes

2023-04-11 07:42 UTC, ptitloup commented on pod/podfile/templates/podfile/customfilewidget.html
> +  //console.log("id_input : " + id_input);
fait, merci !

2023-04-11 07:43 UTC, vsabatie approved these changes

2023-04-11 07:43 UTC, ptitloup commented on pod/podfile/templates/podfile/customfilewidget.html
> +  //console.log("coucou");
fait

2023-04-11 12:58 UTC, pampletousse approved these changes

2023-04-11 12:59 UTC, merged