[DONE] Ptitloup/feature improve meeting
EsupPortail/Esup-Pod pull request #817
Opened 2023-04-21 14:22 UTC by ptitloup

- add fieldset to show record field
- add settings to specify default slide for meeting session
- TODO : add slide field to meeting model ?

2023-04-24 08:16 UTC, AymericJak reviewed
Petit soucis au niveau des cards pour les meetings.

![image](https://user-images.githubusercontent.com/106442526/233934293-3c1c945a-89b3-4c33-8cf5-5e0658b7528f.png)

Testé en local, fonctionnel pour les enregistrements.

Néanmoins, pas trop compris pour l'affichage par défaut d'une présentation.

2023-05-09 07:13 UTC, LoicBonavent approved these changes
Le paramétrage MEETING_PRE_UPLOAD_SLIDES fonctionne parfaitement.

2023-05-09 09:26 UTC, AymericJak requested changes
Avec le setting `MEETING_PRE_UPLOAD_SLIDES = True`.

Lorsque la réunion ne comporte pas de fichier 'slide', erreur suivante lors de l'ouverture de la réunion :
```
join() argument must be str or bytes, not 'bool'
```

---

De plus, il faudrait ajouter une vérification pour le formulaire d'ajout de réunion pour la taille du nom.
En effet, nous pouvons créer une réunion avec un nom de 1 caractère.
Puis lors de l'ouverture : 
![image](https://user-images.githubusercontent.com/106442526/237053358-573d9e7c-582a-48dd-807f-2f97a6a07128.png)

---

Nous ne comprenons pas vraiment comment tester les slides.
Où les slides seront-elles visibles ?

2023-05-09 09:33 UTC, ptitloup commented
Merci pour ces retours, je vais regarder les problèmes remontés

2023-05-09 10:01 UTC, ptitloup commented
je viens de rajouter un min validator pour le nom des réunions, merci de me dire @AymericJak si c'est ok avec ca.

2023-05-09 13:49 UTC, ptitloup commented on pod/meeting/models.py
> +        validators=[MinLengthValidator(11)]
Merci ! je viens de le passer à 2, mauvais copier-coller !

2023-05-09 13:59 UTC, ptitloup commented
Merci à tous pour vos remarques

2023-05-09 13:59 UTC, merged