[DONE] edit file js
EsupPortail/Esup-Pod pull request #824
Opened 2023-05-03 13:38 UTC by thinhantran

bonjour,
je trouves quelques fonctions dans file "main/js" qui n'utilise pas ailleurs. Je ne sais pas que je peux les enlever ?

2023-05-09 14:02 UTC, AymericJak commented on pod/main/static/js/main.js
> +// cette fonction (show_messages) n'est pas utilisée ailleurs, il n'y a pas id "show_messages"
Pourrais-tu mettre les commentaires en anglais.

2023-05-09 14:06 UTC, AymericJak commented
Testé en local, fonctionnel.

Vérifie bien les tests unitaires :)

2023-05-10 07:41 UTC, thinhantran commented on pod/locale/fr/LC_MESSAGES/django.po
>  #: pod/video/templates/videos/category_modal.html:16
hmm après verifier sur mon ordinateur, il y a saut de ligne

2023-05-10 07:41 UTC, thinhantran commented on pod/completion/static/js/completion.js
> +        form.style.display = "none";
j'ai pensé il a pas besoin. Mais c'est mieux s'il y a donc je vais modifier

2023-05-10 12:43 UTC, mattbild requested changes

2023-05-10 12:43 UTC, mattbild commented on pod/chapter/static/js/chapters.js
> +      document.getElementById("list_chapter").innerHTML = parsedData.list_chapter;
c'est quoi parsedData ? le nouveau nom de data2

2023-05-10 12:43 UTC, mattbild commented on pod/chapter/static/js/chapters.js
> +    if (action == "new") {
je pense qu'il vaut mieux mettre une comparaison stricte : `action === ` sur tous les tests

2023-05-10 12:43 UTC, mattbild commented on pod/chapter/static/js/chapters.js
> +  }
ajouter une erreur et un return si action n'est ni save ni import

2023-05-10 12:43 UTC, mattbild commented on pod/chapter/static/js/chapters.js
> +      body: action === "save" ? data_form : form_data,
il faudrait que data_form et form_data ne soient en fait qu'une seule variable, ça éviterait ce test

2023-05-10 13:11 UTC, thinhantran commented on pod/chapter/static/js/chapters.js
> +      body: action === "save" ? data_form : form_data,
désolé, je ne comprends pas votre demande. Comme je comprends que "data_form = new FormData(form_save); " et "form_data = new FormData(elt);" dans source code donc il n'est pas seule variable. c'est pas comme ça ?

2023-05-10 13:12 UTC, thinhantran commented on pod/chapter/static/js/chapters.js
> +  }
oui, je vais corriger

2023-05-10 13:15 UTC, thinhantran commented on pod/enrichment/static/js/enrichment.js
>    sendandgetform(e.target, action);
desolé, je ne comprends pas votre reviews. Je dois corriger quoi ou dois faire quoi ?

2023-05-10 13:21 UTC, mattbild commented on pod/chapter/static/js/chapters.js
> +      body: action === "save" ? data_form : form_data,
je pense qu'on peut faire plus simple 
```
let data_form;

  if (action === "save") {
    [...]
    data_form = new FormData(form_save);
    [...]
    
  } else if (action === "import") {
    form_data = new FormData(elt);
    [...]
  }
  try {
    [...]
    body: action === "save" ? data_form : form_data,
```

à remplacer par 
```
  let data_form;

  if (action === "save") {
    [...]
    data_form = new FormData(form_save);
    [...]
    
  } else if (action === "import") {
    data_form = new FormData(elt);
    [...]
  }
  try {
    [...]
    body: data_form,
```
peut être en profiter aussi pour renommer data_form en form_data

2023-05-10 13:28 UTC, thinhantran commented on pod/chapter/static/js/chapters.js
> +      body: action === "save" ? data_form : form_data,
je comprends, je vais le modifier

2023-05-10 13:30 UTC, mattbild commented on pod/enrichment/static/js/enrichment.js
>    sendandgetform(e.target, action);
ligne 86 , deux paramètres en appel de la fonction :
` sendandgetform(e.target, action); `

ligne 95, un paramètre déclaré :
`var sendandgetform = async function (elt) { `

2023-05-10 13:45 UTC, thinhantran commented on pod/locale/fr/LC_MESSAGES/django.po
merci, je vais faire make lang

2023-05-10 14:25 UTC, thinhantran commented on pod/locale/fr/LC_MESSAGES/django.po
je ne peux pas lancer make lang mais je fais django-admin makemessages --locale=fr

2023-05-11 07:35 UTC, mattbild commented
Quand j'ajoute un chapitre puis que je le supprime, j'ai l'erreur vous n'êtes plus authentifié (alors que je le suis).
Le chapitre est bien supprimé en revanche

2023-05-11 07:56 UTC, thinhantran commented
> 
je corrige et repousse

2023-05-11 08:16 UTC, mattbild commented
ok, ça fonctionne maintenant.
Cela dit j'aurais groupé les tests sur l'action 
```
    const data = await response.text();
    if (action === "new" || action === "modify") {
      if (data.indexOf(id_form) === -1) {
        showalert(
          gettext("You are no longer authenticated. Please log in again."),
          "alert-danger"
        );
        return;
      }
      show_form(data);
    } else if (action === "delete") {
      const parsed_data = JSON.parse(data);
```

2023-05-11 08:26 UTC, thinhantran commented
> il y a encore "elt.classList.add("info");" 
dans 
 else if (action === "modify") {
      show_form(data);
      elt.classList.add("info");
  Donc je ne sais pas c'est possible pour regoupe comme ca

2023-05-11 08:31 UTC, mattbild commented
> il y a encore "elt.classList.add("info");"
ok bien vu

2023-05-11 08:33 UTC, mattbild approved these changes
après les différents changements, les modifs me paraissent correctes
.

2023-05-11 08:36 UTC, merged