Ptitloup/fix admin js
EsupPortail/Esup-Pod pull request #835
Opened 2023-05-10 11:45 UTC by ptitloup

Petit fix de la partie admin - il faut vérifier que tout fonctionne bien au niveau de select2 sous différentes parties de l'administration avec différentes version de python (3.7 - 3.8 etc.)

2023-05-10 14:57 UTC, ptitloup reviewed
Ok pour moi, testé de mon coté sur python 3.9 et ca tourne

2023-05-11 07:06 UTC, AymericJak requested changes
La création d'une vidéo depuis l'interface administrateur est fonctionnelle.
Mais son édition ne l'est pas lors de l'encodage.

![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/186196e6-1d84-4117-87ba-24af773dbd87)

2023-05-11 07:08 UTC, ptitloup commented
> La création d'une vidéo depuis l'interface administrateur est fonctionnelle. Mais son édition ne l'est pas lors de l'encodage.
> 
> ![image](https://user-images.githubusercontent.com/106442526/237600814-186196e6-1d84-4117-87ba-24af773dbd87.png)

merci, je vais regarder cela ce matin

2023-05-11 08:34 UTC, AymericJak approved these changes
Tout est OK pour moi.

2023-05-11 08:34 UTC, merged