[WIP] Fix : user list (filter - share)
EsupPortail/Esup-Pod pull request #854
Opened 2023-05-17 08:09 UTC by AymericJak

- user list in aside filter
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/d656d344-4f54-4758-b093-a9fc27b9031c)
- user list when sharing files
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/5a1dec54-257c-4ebd-b542-46e88b6e72ac)
- CSS
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/d40d882f-13d4-4063-817e-36c9200fced5)

2023-05-17 12:23 UTC, Badatos requested changes

2023-05-17 12:23 UTC, Badatos commented on pod/main/static/css/pod.css
>    display: -webkit-box;
on a un "display: -webkit-box;" dans le code ? c'est pas super standard, y'a moyen de le remplacer par un truc plus commun ?

2023-05-17 12:23 UTC, Badatos commented on pod/podfile/static/podfile/js/filewidget.js
> +    type.toLowerCase() === "add"
Je pense que c'est mieux de ne pas laisser l'ancien code en commentaire. si besoin, on pourra revenir le chercher dans l'historique.

2023-05-17 12:23 UTC, Badatos commented on pod/podfile/static/podfile/js/filewidget.js
> +      let remove = gettext("Remove");
idem pour les anciens codes.

2023-05-17 12:23 UTC, Badatos commented on pod/podfile/static/podfile/js/filewidget.js
> +      const formUserId = document.getElementById("formuserid");
idem

2023-05-17 14:03 UTC, AymericJak commented on pod/main/static/css/pod.css
>    display: -webkit-box;
J'ai ajouté un `display: -ms-flexbox;`.

2023-05-17 14:19 UTC, Badatos approved these changes
ok pour moi, juste un petit commentaire à ajouter et ce serait parfait ;)

2023-05-17 14:22 UTC, Badatos commented on pod/main/static/css/pod.css
> +  display: -ms-flexbox;
Arf... est-ce vraiment mieux ?
Est-ce qu'on peux simplement utiliser display:flex ?

2023-05-17 14:25 UTC, Badatos commented on pod/podfile/static/podfile/js/filewidget.js
> +    a.type = "button";
Je n'ai pas connaissance que le type "button" soit un attribut autorisé de la balise "a" ?

2023-05-17 14:25 UTC, Badatos commented on pod/podfile/static/podfile/js/filewidget.js
> +    a.type = "button";
mettons plutot un "role=button" à mon avis.

2023-05-17 14:30 UTC, Badatos commented
Désolé j'ai refait des remarques après mon aproval 😖
@AymericJak si tu peut attendre que j'ai lu les réponses à tes commentaires avant de les marquer "résolus" ca m'évite de tout déplier ;)

2023-05-30 08:13 UTC, AymericJak commented
> Désolé j'ai refait des remarques après mon aproval confounded @AymericJak si tu peux attendre que j'ai lu les réponses aux commentaires avant de les marquer "résolus" ca m'évite de tout déplier ;)

Oups, désolé @Badatos.


Changements effectués !

2023-05-30 08:59 UTC, Badatos approved these changes
2 petits slashs à retirer, sinon c'est ok pour moi.

2023-05-30 12:52 UTC, ptitloup approved these changes
ok pour moi

2023-05-30 12:52 UTC, merged