[WIP] Update : Playlist
EsupPortail/Esup-Pod pull request #857
Opened 2023-05-17 13:58 UTC by SebastienCozeDev

- [ ] Cacher la position de la vidéo dans la playlist.
- [ ] Mettre en place le drap & drop.

2023-07-10 09:11 UTC, ptitloup commented
voici quelques petites remarques suite à mon test fonctionnel : 
- dans la partie visualisation d'une vidéo, quand on clique sur liste de lecture puis favorites, la vidéo est ajoutée à la liste de lecture favorites mais l'étoile n'est pas remplie 
- dans la partie ajouter une liste de lecture, je remplacerai le champ nom par titre, les titres des parties de champs ne sont pas traduits (general informations, security information)
- quand on clique sur le + pour ajotuer une vidéo à une playlist, il faudrait le griser en attendant le retour serveur, cela evite qu'on clique pls fois dessus
- Les vidéos ne s'enchainent pas (en docker) j'ai des erreurs JS

2023-07-10 09:12 UTC, ptitloup commented
<img width="1671" alt="Capture d’écran 2023-07-10 à 11 11 09" src="https://github.com/EsupPortail/Esup-Pod/assets/4640002/c7450d06-7556-4057-82b0-8278797e7ca3">

2023-07-10 10:24 UTC, ptitloup requested changes
Merci pour cette "grosse" PR. Je suppose qu'il y aura d'autres modifications à l'usage !

2023-07-10 10:24 UTC, ptitloup commented on pod/playlist/apps.py
> +
pouve-vous prévoir une suppression de la table favoris à la fin de la migration pour ne plus avoir de données inutilisées ?

2023-07-10 10:24 UTC, ptitloup commented on pod/playlist/context_processors.py
> +    new_settings = {}
est-ce que ces données sont utilisées ? il me semble qu'il y a egalement des templates tags

2023-07-10 10:24 UTC, ptitloup commented on pod/playlist/forms.py
> +    name = forms.CharField(
pourquoi redéclarer les champs s'ils sont défini dans le model ?

2023-07-10 10:24 UTC, ptitloup commented on pod/playlist/signals.py
> +
très bonne idée d'avoir fait un fichier à part, à noter de fair epareil pour les autres applications

2023-07-10 10:24 UTC, ptitloup commented on pod/playlist/static/js/video-header-favorites.js
> +document.addEventListener("DOMContentLoaded", function () {
il faudrait déplacer les fichiers statics (js, css et img) dans un sous répertoire playlist (playlist/static/playlist/js par exemple) pour eviter des conflits de fichier

2023-07-10 10:24 UTC, ptitloup commented on pod/playlist/templates/playlist/add_or_edit.html
> +    <script src="/static/js/add-or-remove.js?ver={{VERSION}}"></script>
il faut utiliser le tag static

2023-07-10 10:24 UTC, ptitloup commented on pod/playlist/templates/playlist/filter_aside.html
> +  if (visibilityValue) {
etrange test...

2023-07-10 10:24 UTC, ptitloup commented on pod/video/templates/videos/video-header.html
> +<!-- Playlist / favorites -->
ne faudrait-il pas charger que si playlist est utilisé ?

2023-07-10 10:24 UTC, ptitloup commented on pod/video/templates/videos/video-script.html
> +  console.log('video_event_tracking');
a retirer

2023-07-10 10:24 UTC, ptitloup commented on pod/video/templates/videos/video-script.html
> +    _paq.push(['trackEvent', 'Videos', '{{video.slug}}', 'ended', player.currentTime()]);$
retirer le $

2023-07-10 10:24 UTC, ptitloup commented on pod/video/templates/videos/video-script.html
> +    console.log('Finish');
a retirer

2023-07-10 10:24 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +    #countdown {
pourquoi ce style ?

2023-07-10 10:24 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +    {% include 'playlist/playlist_player.html' %}
J'ai pas vus pourquoi un player dans playlist plutot que de garder le player video

2023-07-10 10:24 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +      {% include 'videos/video-script.html' %}
on ne peut pas mettre un id sur la balise script ?

2023-07-10 10:24 UTC, ptitloup commented on requirements.txt
> +bs4==0.0.1
pourquoi charger beautiful soup ? il est déjà en dev

2023-07-10 10:24 UTC, ptitloup commented on requirements.txt
> +bs4==0.0.1
beautifulsoup4

2023-07-10 11:38 UTC, SebastienCozeDev commented on pod/meeting/templates/meeting/meeting_card.html
> +      <a class="btn btn-primary btn-sm link-center-pod text-white" href="{% url 'meeting:join' meeting.meeting_id %}" onClick="setTimeout(function(){ location.reload(); }, 4000);" target="_blank" dat
En mode sombre, la card est comme l'image ci-dessous :

![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/44424c08-b759-4a1f-bcbf-c7c12d1901b2)

Néanmoins, la classe `text-white` sert à rien étant donné qu'il est blanc par défaut Je vais donc le retirer.

2023-07-10 11:48 UTC, SebastienCozeDev commented on pod/playlist/forms.py
> +    name = forms.CharField(
C'est pour que, dans le formulaire, le champ `password` apparaisse après le champ `visibility`

2023-07-10 12:01 UTC, ptitloup commented on pod/playlist/forms.py
> +    name = forms.CharField(
il me semble que tu as un field order, il faut mettre un tableau avec les champs dedans (voir meeting/forms.py)

2023-07-10 12:08 UTC, SebastienCozeDev commented on pod/playlist/static/js/video-header-favorites.js
> +document.addEventListener("DOMContentLoaded", function () {
C'est fait :+1:

2023-07-10 12:13 UTC, AymericJak commented on pod/video/templates/videos/video-header.html
> +<!-- Playlist / favorites -->
Fait

2023-07-10 12:14 UTC, AymericJak commented on pod/video/templates/videos/video-script.html
> +  console.log('video_event_tracking');
Fait

2023-07-10 12:14 UTC, AymericJak commented on pod/video/templates/videos/video-script.html
> +    _paq.push(['trackEvent', 'Videos', '{{video.slug}}', 'ended', player.currentTime()]);$
Fait

2023-07-10 12:14 UTC, AymericJak commented on pod/video/templates/videos/video-script.html
> +    console.log('Finish');
Fait

2023-07-10 12:15 UTC, AymericJak commented on pod/video/templates/videos/video-script.html
> +    console.log('Finish');
Fait

2023-07-10 12:16 UTC, SebastienCozeDev commented on pod/playlist/templates/playlist/add_or_edit.html
> +    <script src="/static/js/add-or-remove.js?ver={{VERSION}}"></script>
C'est fait :+1:

2023-07-10 12:17 UTC, AymericJak commented on pod/video/templates/videos/video_list.html
> +<script src="{% static 'js/utils-playlist.js' %}?ver={{VERSION}}"></script>
Fait

2023-07-10 12:35 UTC, AymericJak commented on pod/main/templatetags/navbar.py
> +    return (get_number_video_for_user(user) > 0) or (get_number_playlist_for_user(user) > 0 and USE_PLAYLIST)
Dans l'idée, on affiche la section stats uniquement si il y a des infos à afficher.

Donc dans notre cas, si : au moins une vidéo, ou playlist --> on affiche la section.
Par contre, si l'utilisation des playlist est à False, on raye directement cette possibilité, puis on se repose uniquement sur le nombre de vidéo.

---

Après c'est amené au changement.
Avec l'application `Statistics` que je vais réaliser, ce templatetag ne sera plus d'aucune utilité :)

2023-07-10 12:45 UTC, SebastienCozeDev commented on pod/playlist/forms.py
> +    name = forms.CharField(
Effectivement, j'ai changé ça de ce fait

2023-07-10 12:50 UTC, SebastienCozeDev commented on pod/video/templates/videos/video.html
> +    #countdown {
Ce style est utilisé pour le compte à rebours lorsque, dans la lecture d'une playlist automatique, on passe à la vidéo suivante. C'est `COUNTDOWN_PLAYLIST_PLAYER`.

2023-07-10 12:54 UTC, SebastienCozeDev commented on pod/video/templates/videos/video.html
> +    {% include 'playlist/playlist_player.html' %}
Ça correspond à la liste des vidéos de la playlist qui se situe à droite de la vidéo en cours de lecture :

![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/349a81b2-a6fe-46c9-99b3-25f41873c8fd)

2023-07-10 12:55 UTC, SebastienCozeDev commented on pod/video/templates/videos/video.html
> +      {% include 'videos/video-script.html' %}
Cet identifiant sert à rien, je vais le supprimer

2023-07-10 12:55 UTC, AymericJak commented on pod/playlist/apps.py
> +
Fait

2023-07-10 12:58 UTC, SebastienCozeDev commented on requirements.txt
> +bs4==0.0.1
C'est réglé

2023-07-10 13:06 UTC, SebastienCozeDev commented on pod/main/test_settings.py
> +USER_PLAYLIST = True
J'ai supprimé `USER_PLAYLIST` car il est inutile

2023-07-10 13:50 UTC, SebastienCozeDev commented on pod/main/rest_router.py
> -router.register(r"playlist", playlist_views.PlaylistViewSet)
C'est fait :+1:

2023-07-10 14:05 UTC, SebastienCozeDev commented on pod/playlist/admin.py
> +        "owner",
J'ai remplacé le filtre par plusieurs champs de recherche : 

- Nom de la playlist
- Nom d'utilisateur du propriétaire
- Prénom du propriétaire
- Nom de famille du propriétaire

2023-07-10 14:11 UTC, SebastienCozeDev commented on pod/playlist/context_processors.py
> +    new_settings = {}
Oui, ces données sont utilisées : 

- `USE_PLAYLIST` est utilisée dans la déclaration des URL et dans le navbar
- `USE_FAVORITES` est utilisée dans le navbar
- `DEFAULT_PLAYLIST_THUMBNAIL` est utilisée lorsque que la playlist n'a aucune vidéo
- `COUNTDOWN_PLAYLIST_PLAYER` est utilisée pour le compte à rebours avant de passer à la vidéo suivante dans la lecture d'une playlist en automatique

2023-07-11 07:36 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +    {% include 'playlist/playlist_player.html' %}
ha ok merci ! :) peut être renommer en playlist_list_video_aside.html ?

2023-07-11 08:57 UTC, SebastienCozeDev commented
> voici quelques petites remarques suite à mon test fonctionnel :
> 
>     * dans la partie visualisation d'une vidéo, quand on clique sur liste de lecture puis favorites, la vidéo est ajoutée à la liste de lecture favorites mais l'étoile n'est pas remplie
> 
>     * dans la partie ajouter une liste de lecture, je remplacerai le champ nom par titre, les titres des parties de champs ne sont pas traduits (general informations, security information)
> 
>     * quand on clique sur le + pour ajotuer une vidéo à une playlist, il faudrait le griser en attendant le retour serveur, cela evite qu'on clique pls fois dessus
> 
>     * Les vidéos ne s'enchainent pas (en docker) j'ai des erreurs JS

C'est aussi réglé

2023-07-11 09:19 UTC, ptitloup commented
> > voici quelques petites remarques suite à mon test fonctionnel :
> > ```
> > * dans la partie visualisation d'une vidéo, quand on clique sur liste de lecture puis favorites, la vidéo est ajoutée à la liste de lecture favorites mais l'étoile n'est pas remplie
> > 
> > * dans la partie ajouter une liste de lecture, je remplacerai le champ nom par titre, les titres des parties de champs ne sont pas traduits (general informations, security information)
> > 
> > * quand on clique sur le + pour ajotuer une vidéo à une playlist, il faudrait le griser en attendant le retour serveur, cela evite qu'on clique pls fois dessus
> > 
> > * Les vidéos ne s'enchainent pas (en docker) j'ai des erreurs JS
> > ```
> 
> C'est aussi réglé

Merci !

2023-07-11 13:59 UTC, ptitloup commented on pod/video/templates/videos/video.html
> +    #countdown {
à déplacer dans le fichier  css

2023-07-12 07:44 UTC, ptitloup commented
A la fin de la dernière vidéo de la playlist, il faut revenir à la première (continuer la lecture ?)

2023-07-12 07:55 UTC, ptitloup commented
Faire en sorte que les vidéos se lisent automatiquement (chargement asynchrone ?)

2023-07-12 08:27 UTC, ptitloup commented
changer le terme "visibilité" par accès / si public, casse à cocher "promoouvoir dans le menu de navigation"

2023-07-20 09:08 UTC, SebastienCozeDev commented
> Attention, il faut rajouter la notion (la référence) au site (usage en multi-tenant)

C'est fait

2023-08-28 10:11 UTC, Badatos commented on pod/playlist/templates/playlist/playlist_player.html
> +        <i class="bi bi-list-ul" aria-hidden="true"></i>&nbsp;{% trans "Playlist:" %} <a class="btn-link" href="{% url 'playlist:content' playlist_in_get.slug %}" title="{% trans "View the playlist"
retirer l'attribut aria-label redondant avec le contenu du lien

2023-08-28 10:13 UTC, Badatos commented on pod/playlist/templates/playlist/playlist_visibility_icon.html
> +{% endif %}
ajouter ligne vide en fin de fichier

2023-08-28 10:14 UTC, Badatos commented on pod/playlist/templates/playlist/playlists.html
> +{% endblock more_script %}
+ ligne vide en fin de fichier

2023-08-28 10:19 UTC, Badatos commented on pod/playlist/tests/test_models.py
> +        """
Les pydocs d'une seule ligne ne doivent pas prendre 3 lignes dans le code

2023-08-28 10:19 UTC, Badatos commented on pod/playlist/tests/test_models.py
> +        """
idem (Les pydocs d'une seule ligne ne doivent pas prendre 3 lignes dans le code). a voir sur tous les pydocs du fichier.

2023-08-28 10:22 UTC, Badatos commented on pod/playlist/templates/playlist/playlists.html
> +    <a class="initials btn btn-primary pod-btn-primary btn-sm" href="{% url 'playlist:add' %}" title="{% trans "Add a playlist" %}" aria-label="{% trans "Add a playlist" %}" data-bs-toggle="tooltip"
retirer les aria-label redondants avec le contenu du lien.

2023-08-28 10:24 UTC, ptitloup approved these changes

2023-08-28 10:25 UTC, merged

2023-08-28 14:51 UTC, SebastienCozeDev commented on pod/main/static/css/pod.css
> +div.disabled, a.player-element.disabled {
C'est voulu. C'est pour que l'utilisateur ne puisse pas cliquer sur une vidéo qu'il ne devrait pas avoir accès depuis le player d'une playlist.

2023-08-29 08:01 UTC, SebastienCozeDev commented on pod/playlist/static/playlist/img/default-playlist.svg
Cette image a été trouvé sur [Pinterest](https://www.pinterest.fr/pin/813603488918830398/) mais je ne trouve pas le license et ne suis pas sûr qu'on ait le droit de l'utiliser