[WIP] Add any video in user channel
EsupPortail/Esup-Pod pull request #864
Opened 2023-05-23 08:49 UTC by secale

#795

2023-06-01 13:44 UTC, ptitloup commented
Bonjour, n'hésitez pas à revenir vers nous sur le canal team pour nous signaler vos PR. Quel est le but de cette modification ? merci

2023-06-01 16:41 UTC, secale commented
Bonjour,
l'objectif est, pour un utilisateur avec un droit de modification sur les video ,  de pouvoir ajouter une video à une chaine dont il est propriétaire sans l'enlever d'autres chaines dont il n'est pas propriétaire, ce qui est le comportement jusqu'à présent : un gestionnaire éditorial doit pouvoir ajouter toute vidéo de la plateforme dans une chaine pour une mise en avant, sans modifier les associations de chaines qui existaient.

2023-06-02 07:30 UTC, Badatos requested changes
Merci pour cette PR.
Pouvez-vous également ajouter un test unitaire qui vérifie la partie ajoutée ?

2023-06-02 13:52 UTC, SebastienCozeDev reviewed
@AymericJak et moi avons testé en local. Lorsque nous tentons d'ajouter une vidéo dans une chaîne dont nous sommes propriétaire depuis l'édition d'une vidéo, nous avons ce soucis :

![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/003bf25d-a54c-4b59-9250-dc543bd793bc)

```python
Environment:


Request Method: POST
Request URL: http://localhost:9090/video/edit/0002-le-coucher-du-soleil-111204mp4/

Django Version: 3.2.19
Python Version: 3.7.16
Installed Applications:
['modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.flatpages',
 'ckeditor',
 'sorl.thumbnail',
 'tagging',
 'cas',
 'captcha',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_select2',
 'shibboleth',
 'chunked_upload',
 'mozilla_django_oidc',
 'honeypot',
 'lti_provider',
 'pod.main',
 'django.contrib.admin',
 'pod.authentication',
 'pod.video',
 'pod.podfile',
 'pod.playlist',
 'pod.completion',
 'pod.chapter',
 'pod.enrichment',
 'pod.video_search',
 'pod.live',
 'pod.recorder',
 'pod.lti',
 'pod.bbb',
 'pod.meeting',
 'pod.cut',
 'pod.xapi',
 'pod.favorite',
 'pod.custom']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/src/app/pod/video/views.py", line 1000, in video_edit
    video = save_video_form(request, form)
  File "/usr/src/app/pod/video/views.py", line 1029, in save_video_form
    form.save_m2m()
  File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 451, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related.py", line 1668, in save_form_data
    getattr(instance, self.attname).set(data)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 992, in set
    objs = tuple(objs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 522, in as_sql
    result, params = self.get_combinator_sql(combinator, self.query.combinator_all)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 459, in get_combinator_sql
    raise DatabaseError('ORDER BY not allowed in subqueries of compound statements.')

Exception Type: DatabaseError at /video/edit/0002-le-coucher-du-soleil-111204mp4/
Exception Value: ORDER BY not allowed in subqueries of compound statements.

```

2023-06-15 13:18 UTC, secale commented on pod/video/forms.py
> +    def clean(self):  # noqa: C901
c'est fait :)

2023-06-15 13:23 UTC, secale commented on pod/video/forms.py
> +            user_channels.filter(site=get_current_site(None))
cette ligne avait été  utilisée dans une autre partie de l'application, je l'ai utilisé telle quelle. Je ne vois quel argument autre passer.

2023-06-15 13:24 UTC, secale commented on pod/video/forms.py
> +            user_channels.filter(site=get_current_site(None))
Vous pourriez tester de nouveau ?

2023-06-15 14:38 UTC, ptitloup reviewed
pas testé fonctionnellement mais coté code ca me convient. Je regarde rapidement

2023-06-16 08:13 UTC, ptitloup approved these changes
Testé, ca fonctionne de mon coté. Merci pour cette contribution

2023-06-16 08:15 UTC, Badatos approved these changes

2023-06-16 08:17 UTC, merged