[WIP] separer le code en double
EsupPortail/Esup-Pod pull request #867
Opened 2023-05-25 11:42 UTC by thinhantran

2023-05-26 13:23 UTC, ptitloup requested changes
je crois que ta PR modifie un code déjà modifié par la PR d'Olivier. Il faudrait que tu refasses les modifications sur une nouvelle branche en partant de develop car la, je crains de ne pouvoir valider tes modifications

2023-05-26 13:23 UTC, ptitloup commented on pod/video/utils.py
> +        '</p>%s</p><p>%s</p><p>%s<br><a href="%s"><i>%s</i></a>\
heu il ne faut pas rajotuer de / à l'ouverture de la balise <p>

2023-05-26 13:23 UTC, ptitloup commented on pod/video/views.py
> +        "LOGO_ETB": "img/logo_etb.svg",
nope, il faut laisser "LOGO_ETB": "img/esup-pod.svg",

2023-05-26 13:23 UTC, ptitloup commented on pod/video/views.py
> +    """Return paginated videos in paginator object"""
il faut laisser les "." à la fin des pydoc il me semble

2023-05-26 13:23 UTC, ptitloup commented on pod/video/views.py
> +def sort_videos_list(request, videos_list):
il me semble que cette fonction doit se trouver dans pod/video/utils.py car elle est utilisée egalement dans l'application favorites

2023-05-26 13:23 UTC, ptitloup commented on pod/video/views.py
> +def sort_videos_list(request, videos_list):
je confirme : from pod.video.utils import sort_videos_list

2023-05-30 08:09 UTC, Badatos requested changes

2023-05-30 08:42 UTC, thinhantran commented
Je vais refaire mes modifications dans nouvelle PR qui a les modifications par la PR d'Olivier

2023-05-30 08:42 UTC, closed without merging