[DONE] Recorder, field transcript, from boolean to varchar(2)
EsupPortail/Esup-Pod pull request #874
Opened 2023-06-01 09:25 UTC by LoicBonavent

Change Transcript field : from Boolean to Varchar(2); identical to the Transcript field of the video model.

This fixes the bug when using recorders, which blocked video encoding.

Useful SQL queries for the migration related to this patch:
UPDATE recorder_recorder SET transcript = '' WHERE transcript = 0;
UPDATE recorder_recorder SET transcript = main_lang WHERE transcript = 1;

2023-06-01 12:32 UTC, ptitloup approved these changes
ok pour moi

2023-06-02 12:06 UTC, AymericJak requested changes
Nous n'avons pas réussi à tester en local.
local_settings :
`USE_TRANSCRIPT = True`

Après erreur où le module STT n'est pas trouvé. Donc installé dans le shell du docker.
Aucune langues dans le field transcript lors de l'ajout d'une vidéo.

:exploding_head:

2023-06-02 13:44 UTC, LoicBonavent commented on pod/recorder/models.py
>  def select_recorder_user():
Hello, je t'ai MP via le Rocket Esup pour en parler

2023-06-07 14:52 UTC, LoicBonavent commented on pod/recorder/models.py
>  def select_recorder_user():
Sur le coup, désolé, ce n'est pas une nouvelle fonction et surtout je ne sais même pas si elle est encore utilisée.

2023-06-07 14:57 UTC, ptitloup approved these changes
ok pour moi

2023-06-07 14:57 UTC, merged