[DONE] Manage meeting external recordings v1
EsupPortail/Esup-Pod pull request #876
Opened 2023-06-02 14:25 UTC by LoicBonavent

Management of the external recordings for the meeting module.
With this, users can manage and centralize in Pod external recordings made from anothers platforms.
For the moment, external recordings can be :
- a video file,
- a Big Blue Button video file (playback videos availables since BBB 2.6+). Typically, a BBB recording made in Moodle.
- a Youtube video,
- a PeerTube video
These videos must be publicly available.

2023-06-05 12:23 UTC, Badatos commented
Je viens de rapatrier la branche, et j'ai l'erreur suivante en allant dans "mes réunions" :
```
ERROR [log] Internal Server Error: /meeting/
Traceback (most recent call last):
  File "/Users/olivier/.virtualenvs/django_pod3/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/olivier/.virtualenvs/django_pod3/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/olivier/.virtualenvs/django_pod3/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/olivier/GIT/Esup-Pod-dev3/pod/meeting/views.py", line 118, in my_meetings
    meetings = [
  File "/Users/olivier/GIT/Esup-Pod-dev3/pod/meeting/views.py", line 121, in <listcomp>
    if meeting.is_active
  File "/Users/olivier/GIT/Esup-Pod-dev3/pod/meeting/models.py", line 573, in is_active
    end_datetime = dt.combine(self.recurring_until, self.start_time)
TypeError: combine() argument 1 must be datetime.date, not None
```

2023-06-05 12:31 UTC, SebastienCozeDev requested changes
J'ai testé en local et tout est fonctionnel.

2023-06-05 12:31 UTC, SebastienCozeDev commented on pod/meeting/tests/test_views.py
>      def test_recording_upload_post_request(self):
pydoc

2023-06-05 12:31 UTC, SebastienCozeDev commented on pod/meeting/views.py
> +    def handle_data(self, data):
Il faudrait mettre les commentaires de la forme :

```py
"""Search for title tag"""
```

2023-06-05 14:13 UTC, ptitloup requested changes
A tester fonctionnellement, merci de prendre en compte les autres remarques concernant le code. Enfin pour les langes, il faut utiliser les commandes make pour créer les fichier et les compiler

2023-06-05 14:13 UTC, ptitloup commented on pod/meeting/views.py
> +def display_message_with_icon(request, type, message):
Bonne idée de rajotuer un icon au message. D'aillrus je verrai bien cette methode se généraliser. Il faudrait la mettre dans le utils.py de main pour qu'elle soit accessible par les autres vues de Pod

2023-06-05 14:39 UTC, LoicBonavent commented on pod/meeting/admin.py
>  class RecordingAdmin(admin.ModelAdmin):
Documentation pydoc ajouté

2023-06-05 14:39 UTC, LoicBonavent commented on pod/meeting/forms.py
> +                self.fields[field].widget = forms.HiddenInput()
Documentation pydoc ajouté

2023-06-05 14:40 UTC, LoicBonavent commented on pod/meeting/static/css/meeting.css
> +/* */
Fait

2023-06-05 14:40 UTC, LoicBonavent commented on pod/meeting/templates/meeting/add_or_edit_external_recording.html
> +{% endblock more_script %}
Fait

2023-06-05 14:41 UTC, LoicBonavent commented on pod/meeting/templates/meeting/external_recordings.html
> +{% endblock more_script %}
Fait

2023-06-05 14:41 UTC, LoicBonavent commented on pod/meeting/tests/test_views.py
>      def test_recording_upload_post_request(self):
Documentation pydoc ajouté

2023-06-05 14:42 UTC, LoicBonavent commented on pod/meeting/views.py
> +    def handle_data(self, data):
Pas fait. Faut-il mettre l'ensemble des commentaires de Pod sous la forme """Commentaires""", et non plus # Commentaires ?

2023-06-05 14:42 UTC, LoicBonavent commented on pod/meeting/forms.py
> -        self.fields["owner_copy"].widget.attrs.update({"class": "me-1"})
Erreur de merge. Ligne remise

2023-06-05 15:39 UTC, Badatos commented on pod/meeting/views.py
> +def display_message_with_icon(request, type, message):
il ne faut plus faire la premiere ligne ^^.

Fait un `make lang` à la place.

2023-06-05 15:39 UTC, Badatos commented on pod/meeting/views.py
> +            msg += "<b>%s:</b> %s<br/>" % (key, args[key])
pas de />

2023-06-05 15:39 UTC, Badatos commented on pod/meeting/views.py
> +    def handle_data(self, data):
Non non pas du tout :)
Les commentaires habituels restent sous la forme `# Commentaires`, il faut juste une ligne sous la forme `"""Description de la fonction."""` sous chaque fonction.

2023-06-06 07:27 UTC, SebastienCozeDev requested changes

2023-06-07 11:35 UTC, LoicBonavent commented on pod/meeting/views.py
> +        description = ("%s<br/>%s") % (description, pt_video_description)
Fait

2023-06-07 11:35 UTC, LoicBonavent commented on pod/meeting/views.py
> +            msg += "<strong>%s</strong><br/>" % (args['error'])
Fait

2023-06-07 11:36 UTC, LoicBonavent commented on pod/meeting/templates/meeting/external_recordings.html
> +  function confirmUploadToPod(message) {
Bien vu, fait.

2023-06-07 11:36 UTC, LoicBonavent commented on pod/meeting/templates/meeting/external_recordings.html
> +                </form>
Fait

2023-06-07 11:36 UTC, LoicBonavent commented on pod/meeting/templates/meeting/external_recordings.html
> +    {% trans "If you have achieved Big Blue Button meetings via another interface (typically via Moodle), or if you wish to centralize PeerTube, Youtube or other videos on Pod, it is possible to retr
Fait

2023-06-07 11:36 UTC, LoicBonavent commented on pod/meeting/templates/meeting/add_or_edit_external_recording.html
> +          <span> - {{ error }}</span> <br/>
Fait

2023-06-07 11:36 UTC, LoicBonavent commented on pod/meeting/templates/meeting/add_or_edit_external_recording.html
> +      {% trans "To centralize Big Blue Button, PeerTube, video file, Youtube recordings on this platform, first, please enter the information below." %}<br/>
Fait

2023-06-07 11:36 UTC, LoicBonavent commented on pod/meeting/models.py
> +def default_site_recording(sender, instance, **kwargs):
Fait

2023-06-07 11:37 UTC, LoicBonavent commented on pod/meeting/views.py
> +            msg += "<strong>%s</strong><br/>" % (args['error'])
Fait

2023-06-07 11:37 UTC, LoicBonavent commented on pod/meeting/views.py
> +            msg += "<b>%s:</b> %s<br/>" % (key, args[key])
Fait

2023-06-07 11:37 UTC, LoicBonavent commented on pod/meeting/views.py
> +            msg += "<b>%s:</b> %s<br/>" % (key, args[key])
Fait

2023-06-07 11:37 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
> +                    <input type="hidden" name="recording_name" value="{{ record.name }}" />
Fait

2023-06-07 11:39 UTC, LoicBonavent commented on pod/meeting/forms.py
> +    def filter_fields_admin(form):
Fait

2023-06-07 12:54 UTC, LoicBonavent commented on pod/meeting/templates/meeting/external_recordings.html
> +  <link href="{% static 'css/meeting.css' %}?ver={{ VERSION }}" rel="stylesheet"/>
/> --> >

2023-06-07 13:10 UTC, Badatos commented on pod/meeting/templates/meeting/internal_recordings.html
> +                    <input type="hidden" name="recording_name" value="{{ record.name }}" />
En fait c'était de très bonnes habitudes en xHTML, mais qui ont disparu en HTML5 ;)

2023-06-07 14:26 UTC, Badatos approved these changes
Une dernière micro remarque, sinon OK pour moi ;)

2023-06-07 14:26 UTC, Badatos commented on pod/meeting/templates/meeting/internal_recordings.html
> +                  <a class="initials btn btn-primary pod-btn-primary btn-sm" href="{{ record.videoUrl }}" target="_blank" title="{% trans 'Display the recording in video format'%}" data-bs-toggle="to
La classe "initials" n'est utilisée que pour afficher le bouton de login. à retirer ici.

2023-06-07 14:33 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
> +                  <a class="initials btn btn-primary pod-btn-primary btn-sm" href="{{ record.videoUrl }}" target="_blank" title="{% trans 'Display the recording in video format'%}" data-bs-toggle="to
Thx. C'est supprimé.

2023-06-07 15:11 UTC, ptitloup requested changes
un petit changement svp

2023-06-08 06:53 UTC, LoicBonavent commented on pod/main/utils.py
> +def display_message_with_icon(request, type, message):
C'est fait

2023-06-08 07:20 UTC, SebastienCozeDev commented on pod/meeting/templates/meeting/external_recordings.html
> +    var answer=confirm(message);
Effectivement, je me suis trompé. Je voulais dire remplacer `var` par `const`, étant donné que cette variable n'a pas vocation à être modifié.

2023-06-08 07:24 UTC, SebastienCozeDev approved these changes

2023-06-08 07:24 UTC, LoicBonavent commented on pod/meeting/templates/meeting/external_recordings.html
> +    var answer=confirm(message);
Je le fais tout de suite

2023-06-08 07:26 UTC, LoicBonavent commented on pod/meeting/templates/meeting/external_recordings.html
> +    var answer=confirm(message);
C'est tout bon

2023-06-08 08:32 UTC, merged