[DONE] Ptitloup/feature new encoding
EsupPortail/Esup-Pod pull request #899
Opened 2023-06-29 15:29 UTC by ptitloup

Cette PR permet de découper l'encodage et la transcription sur des docker séparés. Tous communiquent via Redis et Celery. L'ancien système continue de tourner. Vous pouvez choisir l'environnement souhiaté en modifiant le fichier `.env.dev` avec DOCKER_ENV=full (pour tous les dockers) ou light pour un seul docker qui fait tout

2023-07-03 14:37 UTC, aitkarrafarid commented
Ok pour moi, moyennant quelques WARNING dans le pod-encode & pod-transcript :  

`/usr/local/lib/python3.8/site-packages/celery/fixups/django.py:42: FixupWarning: Environment variable DJANGO_SETTINGS_MODULE is defined but Django isn't installed.  Won't apply Django fix-ups!

warnings.warn(FixupWarning(ERR_NOT_INSTALLED))
/usr/local/lib/python3.8/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is absolutely not recommended!`

Mais également un WARNING dans le pod-transcript :  

`...WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@f1f13387fd0d.`

2023-07-04 07:20 UTC, ptitloup commented
> Ok pour moi, moyennant quelques WARNING dans le pod-encode & pod-transcript :
> 
> `/usr/local/lib/python3.8/site-packages/celery/fixups/django.py:42: FixupWarning: Environment variable DJANGO_SETTINGS_MODULE is defined but Django isn't installed. Won't apply Django fix-ups! warnings.warn(FixupWarning(ERR_NOT_INSTALLED)) /usr/local/lib/python3.8/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is absolutely not recommended!`
> 
> Mais également un WARNING dans le pod-transcript :
> 
> `...WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@f1f13387fd0d.`

Pour pod-encode et pod-transcript, je viens de voir pour les warning. Concernant les settings et DJANGO_SETTINGS_MODULE, cela vient du fait que je charge tous les settings via l'import `from .. import settings`. Toutefois je peux remplacer par `from ..custom import settings_local` qui ne va charger que le fichier settings_local.py et donc ne pas charger toute la configuration de Pod. 

Concernant le warning `You're running the worker with superuser privileges: this is absolutely not recommended!` c'est sous docker, on a qu'un seul user donc forcement c'est root mais pas grave si ?

Enfin, concernant DuplicateNodenameWarning, j'ai rajouté des noms aux workers pour faire plus propre et c'est ficé, je pousse tout ca dans le prochain commit

2023-07-04 07:25 UTC, Badatos commented on pod/video_encode_transcript/Encoding_video.py
> +except Exception:  # pragma: no cover
C'est pas un peu trop large comme exception ?

2023-07-04 07:36 UTC, Badatos requested changes
pas mal de pydocs à revoir :)

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/encode.py
> +def store_encoding_info(video_id, encoding_video):
Il manque une pydoc à cette fonction :)

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/encode.py
> +    if CutVideo.objects.filter(video=video_to_encode).exists():
PYDOC

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/encode.py
>      # envois mail fin encodage
Ici le format de la pydoc n'est pas correct. remplacer par `"""Send mail at the end of encoding."""` par exemple.

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/importing_tasks.py
> +    print("Start the importing of the video ID : %s" % video_id)
pas d'espace avant les ponctuations doubles en anglais (` :`)

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/importing_transcript_tasks.py
> +    """Start the encoding of the video."""
Ce pydoc ne me semble pas correspondre à la fonction.

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/importing_transcript_tasks.py
> +    print("temp_vtt_file : %s" % temp_vtt_file)
pas d'espace avant` :`

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript.py
>      if threaded:
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript.py
> +    msg += saveVTT(video_to_encode, webvtt)
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    transript_model = Model(TRANSCRIPTION_MODEL_PARAM[TRANSCRIPTION_TYPE][lang]["model"])
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    if TRANSCRIPTION_NORMALIZE:
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    if TRANSCRIPTION_TYPE == "STT":
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    sox_cmd = "sox {} --type raw --bits 16 --channels 1 --rate {} ".format(
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    filename, file_extension = os.path.splitext(mp3filepath)
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    sox_cmd = "sox {} --type raw --bits 16 --channels 1 --rate {} ".format(
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    while True:
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    words,
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    msg = ""
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    msg = ""
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    if len(webvtt.captions) > 0:
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    return (
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    try:
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +    word = ""
pydoc manquante

2023-07-04 07:36 UTC, Badatos commented on pod/video_encode_transcript/transcripting_tasks.py
> +    """Start the encoding of the video."""
cette pydoc me semble incohérente

2023-07-04 08:03 UTC, ptitloup commented on pod/video_encode_transcript/Encoding_video.py
> +except Exception:  # pragma: no cover
si, ok je viens de fixer j'avais du modifier cela avant pour tester

2023-07-04 09:25 UTC, ptitloup commented
Je viens de terminer la configuration et de corriger vos remarques. Est-ce ok pour vous ?

2023-07-04 09:45 UTC, ptitloup commented
Il manque le docker pour l'xAPI, je vais le rajouter

2023-07-04 09:52 UTC, Badatos approved these changes
reste 2 typo minimes, pour le reste c'est bon pour moi niveau code ;)

2023-07-04 09:52 UTC, Badatos commented on pod/video_encode_transcript/importing_tasks.py
> +    print("Start the importing of the video ID : %s" % video_id)
L'espace est toujours là :)

2023-07-04 09:52 UTC, Badatos commented on pod/video_encode_transcript/importing_transcript_tasks.py
> +    print("temp_vtt_file : %s" % temp_vtt_file)
pas d'espace avant les signes de ponctuation double (ici le double point)

2023-07-05 12:21 UTC, merged