[DONE] Feature import video manage bbb recording v3
EsupPortail/Esup-Pod pull request #905
Opened 2023-07-06 14:59 UTC by LoicBonavent

- Manage BBB URLs with single-use tokens
- Restrict an alert style to only dismissible alerts
- Add a timeout when check that a file exists

2023-07-07 08:34 UTC, ptitloup requested changes
Testé fonctionnellement sur le BBB actuel et le BBB futur version, tout est ok pour moi niveau fonctionnel, par contre, je pense qu'on peut améliorer le code

2023-07-07 08:34 UTC, ptitloup commented on pod/import_video/utils.py
> +        pos_token = video_url.find("/video?token=")
je pense qu'il faut plutot utiliser la lib urllib python. Elle a une methode parse qui permet de retrouver plus facilement les elements comme les query parameters, le schéma, le path ou la location

2023-07-07 08:34 UTC, ptitloup commented on pod/import_video/utils.py
> +            pos_recording = video_url.find("/recording/")
idem

2023-07-07 08:34 UTC, ptitloup commented on pod/import_video/utils.py
> +            return site + "/playback/video/" + uid + "/"
il faudrait mettre /playback/video/ dans une variable qu'on pourra modifier plus facilement

2023-07-07 08:34 UTC, ptitloup commented on pod/import_video/utils.py
> +    response = requests.head(source_url, timeout=2)
2 secondes de timeout ? on peut mettre un peu plus non ? (surtout si a terme on utilise tous le mm BBB. Qu'en pensez-vous ?

2023-07-07 08:34 UTC, ptitloup commented on pod/import_video/views.py
> +        if video_url.find("playback/video") != -1:
idem, plutot que de faire un find, on pourrait faire un urllib parse pour améliorer le code

2023-07-07 08:34 UTC, ptitloup commented on pod/video/forms.py
> +        if self.current_user is not None:
Etrange que ce code se retrouve ici, @LoicBonavent tu peux regarder pourquoi ? (il me semble qu'il est deja dans develop ou un truc comme ca

2023-07-07 08:34 UTC, ptitloup commented
merci de retirer le fichier video/forms.py de la PR car il n'a rien à faire ici ! :)

2023-07-07 08:45 UTC, LoicBonavent commented on pod/import_video/utils.py
> +    response = requests.head(source_url, timeout=2)
Cette fonction vérifie seulement que l'URL existe : elle ne récupère que son entête et pas le contenu.
En fait, j'ai ajouté ce timeout car, dans des cas très particuliers (en lien avec des règles de firewall je pense), cela pouvait bloquer.

2023-07-07 08:50 UTC, SebastienCozeDev requested changes

2023-07-07 08:50 UTC, SebastienCozeDev commented on pod/meeting/static/css/meeting.css
> +div.alert.alert-dismissible {
Ne serait-il pas mieux de placer cette règle dans `pod.css` pour éviter les répétitions ?

2023-07-07 09:02 UTC, Badatos commented on pod/meeting/static/css/meeting.css
> +div.alert.alert-dismissible {
Je pense qu'il y aura un travail d'uniformaisation à faire, mais pas forcément en intégrant tel quel ces regles dans pod.css

2023-07-07 11:26 UTC, LoicBonavent commented on pod/import_video/utils.py
> +        pos_token = video_url.find("/video?token=")
Ok, urllib utilisé

2023-07-07 11:26 UTC, LoicBonavent commented on pod/import_video/utils.py
> +            pos_recording = video_url.find("/recording/")
Ok, urllib utilisé

2023-07-07 11:27 UTC, LoicBonavent commented on pod/import_video/utils.py
> +            return site + "/playback/video/" + uid + "/"
J'ai mis une simple variable : je ne pense qu'il faille mettre cela dans une variable globale de configuration

2023-07-07 11:27 UTC, LoicBonavent commented on pod/import_video/utils.py
> +    response = requests.head(source_url, timeout=2)
Sur le coup, je n'ai pas changé. A voir à l'usage, je pense.

2023-07-07 11:28 UTC, LoicBonavent commented on pod/import_video/views.py
> +        if video_url.find("playback/video") != -1:
Ici, je n'ai pas changé : si l'on utilisait urllib, il faudrait tester tous les cas de figures; les usagers peuvent rentrer n'importe quelle URL à ce niveau. Cela me paraît plus simple et facilement maintenable.

2023-07-07 11:29 UTC, LoicBonavent commented on pod/video/forms.py
> +        if self.current_user is not None:
Je ne l'avais pas ajouté  la PR. Mais en faisant comme tu disais, c'est bon, cela a disparu de cette PR

2023-07-07 11:31 UTC, LoicBonavent commented on pod/meeting/static/css/meeting.css
> +div.alert.alert-dismissible {
Oui, je pense qu'il faudra revoir par la suite le système d'alert au niveau global. Pour l'instant, je n'ai rien touché.

2023-07-07 15:58 UTC, ptitloup commented on pod/import_video/views.py
> +        if video_url.find("playback/video") != -1:
ok

2023-07-07 15:59 UTC, ptitloup approved these changes
un dernier print à retirer et c'est ok pour moi

2023-07-07 15:59 UTC, ptitloup commented on pod/import_video/utils.py
> +        print(url)
retirer le print

2023-07-07 16:22 UTC, LoicBonavent commented on pod/import_video/utils.py
> +        print(url)
Print enlevé

2023-07-10 06:21 UTC, ptitloup commented on pod/import_video/utils.py
> +        print(url)
merci

2023-07-10 07:31 UTC, SebastienCozeDev approved these changes

2023-07-10 08:32 UTC, merged