[WIP] Update : Displaying channels via AJAX.
EsupPortail/Esup-Pod pull request #910
Opened 2023-07-12 12:17 UTC by SebastienCozeDev

* [ ] Supprimer les chaînes du `context_processors.py`.
* [ ] Ajouter des vues pour obtenir les différentes listes de chaînes au format JSON.
* [ ] Ajouter des fonctions JavaScript pour utiliser ces vues via des requêtes AJAX.
* [ ] Mettre en place cette utilisation uniquement lorsque l'utilisateur clique sur le bouton pour les voir grâce à l'événement `shown.bs.modal` de Bootstrap.
* [ ] Mettre en place un infinite loader pour la liste des chaînes.

2023-07-18 14:05 UTC, LoicBonavent requested changes
Hello,
En testant, j'aurais quelques remarques :
 - je ne sais pas pourquoi, mais j'ai l'impression que Channels n'est pas traduit malgré un make compilelang (peut-être que cela vient de mon env de test aussi) - cf. screenshot
 - en test, j'ai une barre de progression qui s'affiche durant le chargement des chaînes (normal vu la requête AJAX). Mais ce qui me fait réfléchir, c'est qu'il n'y a que 2 chaînes et 2 thèmes. Est-ce que les requêtes SQL derrière sont optimisés (en prod, nous avons une quinzaine de chaînes et 200 thèmes, avec  1800 vidéos associées) ?
 - quand on clique plusieurs fois sur le menu des chaînes, les chaînes sont affichées plusieurs fois, cf. screenshot. Dans mon, cas, j'ai cliqué 3 fois.
![image](https://github.com/EsupPortail/Esup-Pod/assets/56730254/03eec7bc-7cfd-4755-8a1e-157996ea09c6)

A ces quelques détails près, c'est du super boulot. Un grand merci

2023-07-19 11:45 UTC, SebastienCozeDev commented
> Hello, En testant, j'aurais quelques remarques :
> 
>     * je ne sais pas pourquoi, mais j'ai l'impression que Channels n'est pas traduit malgré un make compilelang (peut-être que cela vient de mon env de test aussi) - cf. screenshot
> 
>     * en test, j'ai une barre de progression qui s'affiche durant le chargement des chaînes (normal vu la requête AJAX). Mais ce qui me fait réfléchir, c'est qu'il n'y a que 2 chaînes et 2 thèmes. Est-ce que les requêtes SQL derrière sont optimisés (en prod, nous avons une quinzaine de chaînes et 200 thèmes, avec  1800 vidéos associées) ?
> 
>     * quand on clique plusieurs fois sur le menu des chaînes, les chaînes sont affichées plusieurs fois, cf. screenshot. Dans mon, cas, j'ai cliqué 3 fois.
>       ![image](https://user-images.githubusercontent.com/56730254/254286388-03eec7bc-7cfd-4755-8a1e-157996ea09c6.png)
> 
> 
> A ces quelques détails près, c'est du super boulot. Un grand merci

Pour ce qui est de la traduction, il me semble que je ne l'avais pas encore faites.

Pour ce qui est des requêtes SQL, elles me semblent optimisées. Néanmoins, je me demande s'il ne serait pas utile de charger les thèmes uniquement lorsque l'utilisateur souhaite les consulter.

Pour le dernier point, c'est réglé.

2023-07-20 07:18 UTC, LoicBonavent commented
Nickel. Tu me dis quand je peux retester... Merci

2023-07-20 08:51 UTC, SebastienCozeDev commented
> Nickel. Tu me dis quand je peux retester... Merci

Tout est bon

2023-07-20 11:46 UTC, LoicBonavent commented
Oups, j'ai encore le problème qui affiche les chaînes plusieurs fois... Par contre, je n'ai plus l'affichage des thèmes dans le menu :
![image](https://github.com/EsupPortail/Esup-Pod/assets/56730254/beaa9271-7590-4b0a-80da-6a0212254b5f)

2023-07-24 09:39 UTC, AymericJak approved these changes
Fonctionne très bien de mon côté !

Merci :)

2023-07-24 09:39 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgstr "vidéos trouvées"
Modifier la traduction

2023-07-24 09:39 UTC, AymericJak commented on pod/main/templates/navbar.html
> +            <span class="progress" style="height: .6em;">
Peux tu mettre le style dans un fichier CSS ?

2023-08-14 13:06 UTC, SebastienCozeDev commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgstr "vidéos trouvées"
C'est fait :+1:

2023-08-14 13:27 UTC, SebastienCozeDev commented on pod/main/templates/navbar.html
> +            <span class="progress" style="height: .6em;">
C'est fait

2023-08-24 11:41 UTC, merged