[DONE]Feature import_video add MAX_UPLOAD_SIZE_ON_IMPORT parameter
EsupPortail/Esup-Pod pull request #911
Opened 2023-07-12 14:03 UTC by LoicBonavent

Add a new configuration parameter : MAX_UPLOAD_SIZE_ON_IMPORT

This parameter corresponds to maximum size in Gb of video files that can be imported into the platform via the import_video application.
0 is the default value and corresponds to "no maximum size".

2023-07-24 08:29 UTC, AymericJak approved these changes
Hello ! 
Juste une ou 2 remarques, sinon le tout fonctionne très bien !

Merci pour cette PR :)

2023-07-24 08:29 UTC, AymericJak commented on pod/import_video/utils.py
> +def verify_video_existsandsize(video_url):
Il serait plus lisible de changer le nom de la fonction : `verify_video_exists_and_size`

2023-07-24 08:29 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "Fichier trop imposant."
`Fichier trop volumineux` ?

2023-07-24 08:32 UTC, AymericJak commented
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/4558e11f-ab07-4e57-b49c-272070b9808f)

Pourrais-tu modifier un peu le message d'erreur ?
Trop de parenthèses à mon goût.

Merci !

2023-07-24 09:04 UTC, LoicBonavent commented on pod/import_video/utils.py
> +def verify_video_existsandsize(video_url):
Yep, c'est fait

2023-07-24 09:05 UTC, LoicBonavent commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "Fichier trop imposant."
Oups, une traduction non relue... C'est changé

2023-07-24 09:05 UTC, LoicBonavent commented
> ![image](https://user-images.githubusercontent.com/106442526/255532573-4558e11f-ab07-4e57-b49c-272070b9808f.png)
> 
> Pourrais-tu modifier un peu le message d'erreur ? Trop de parenthèses à mon goût.
> 
> Merci !

C'est fait aussi.

2023-07-24 09:43 UTC, AymericJak approved these changes
Merci beaucoup pour ta PR :)

2023-08-14 17:04 UTC, SebastienCozeDev approved these changes
J'ai testé localement et c'est fonctionnel

2023-08-23 08:38 UTC, ptitloup requested changes
2 ou 3 choses à améliorer, supprimer les fichiers md et ca sera parfait, merci !

2023-08-23 08:38 UTC, ptitloup commented on CONFIGURATION_FR.md
Merci de supprimer les fichier configuration EN et FR stp. Ils sont généré automatiquement

2023-08-23 08:38 UTC, ptitloup commented on pod/import_video/utils.py
> +MAX_UPLOAD_SIZE_ON_IMPORT = getattr(settings, "MAX_UPLOAD_SIZE_ON_IMPORT", 0)
ne pourrait-on pas mettre 4 Giga octet comme valeur par défaut plutot que 0 ? comme pour l'ajout de vidéo Merci

2023-08-23 08:38 UTC, ptitloup commented on pod/import_video/utils.py
> +        check_video_size(size)
le check devrait renvoyer un boolean qui si false leverait une exception.

2023-08-23 08:38 UTC, ptitloup commented on pod/import_video/views.py
> +        check_video_size(yt_stream.filesize)
pourquoi d'un cote on appelle directement check_video_size et de l'autre  verify_video_exists_and_size ?

2023-08-23 08:38 UTC, ptitloup commented on pod/import_video/views.py
> +        check_video_size(yt_stream.filesize)
et si c'est directement un fichier vidéo ou un import depuis Pod, ca se apsse comment ?

2023-08-25 13:29 UTC, Badatos commented on pod/import_video/views.py
> +        # Verify that video exists and not oversised
oversiZed ;)

2023-08-25 13:31 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/django.po
> +"Cette vidéo a été téléversée sur Pod; son origine est %(type)s : <a href="
manque un espace insécable entre Pod et le ;

2023-08-28 15:11 UTC, LoicBonavent commented on pod/import_video/utils.py
> +MAX_UPLOAD_SIZE_ON_IMPORT = getattr(settings, "MAX_UPLOAD_SIZE_ON_IMPORT", 0)
OK, changé

2023-08-28 15:17 UTC, LoicBonavent commented on pod/import_video/views.py
> +        check_video_size(yt_stream.filesize)
En fait, dans le cas de Youtube, on manipule un objet particulier qui permet d'avoir directement la taille du fichier vidéo (et non l'URL). Donc, dans ce cas, on vérifie juste que la taille du fichier Youtube n'est pas supérieure à la valeur définie dans la conf (si le fichier n'existe pas, une erreur est déclenchée directement lors de l'instanciation YT).
Quand il s'agit d'un  autre cas, j'appelle directement la fonction qui va checker l'URL pour vérifier et l'existence et la taille du fichier.

2023-08-29 07:47 UTC, LoicBonavent commented on CONFIGURATION_FR.md
Ok, supprimés

2023-08-29 08:36 UTC, ptitloup approved these changes
ok pour moi

2023-08-29 15:11 UTC, merged