[WIP] Fix : accessibility issues
EsupPortail/Esup-Pod pull request #913
Opened 2023-08-22 11:43 UTC by AymericJak

2023-08-28 14:09 UTC, Badatos requested changes

2023-08-28 14:09 UTC, Badatos commented on pod/main/static/css/pod.css
> +    width: 101% !important;
va au minimum falloir ajouter un commentaire sur celui-là ^^

2023-08-28 14:09 UTC, Badatos commented on pod/meeting/templates/meeting/recurring_options_modal_form.html
> +  <legend><i class="bi bi-calendar-check"></i>&nbsp;{% trans 'End' %}</legend>
aria-hidden

2023-08-28 14:09 UTC, Badatos commented on pod/video/templates/videos/filter_aside.html
> +    <i>{% trans "The videos on the left are automatically sorted according to the filters selected. Check options to adjust results." %}</i>
de manière générale, évitez les balises "i" et "b", et préferez plutot leur pendant sémantiques "em" et "strong" (ou alors mettre une classe CSS)

2023-08-28 14:17 UTC, AymericJak commented on pod/main/static/css/pod.css
> +    width: 101% !important;
Oui 101%... comme ça, ça passe parfaitement avec le collapse button.

2023-08-28 14:45 UTC, AymericJak commented on pod/video/static/js/comment-script.js
> +    bodyElement.setAttribute('aria-hidden', 'true');
Je faisais des tests, et je l'avais laissé... ça ne sert à rien. Je l'ai enlevé haha

2023-08-28 15:01 UTC, Badatos commented on pod/live/templates/live/event-info.html
> +                          <span class="visually-hidden">{% trans 'Share on X (Twitter)' %}</span>
Ha ha, bien vu pour le "X" ;)

2023-08-28 15:02 UTC, Badatos commented on pod/main/static/css/pod.css
> +    width: 101% !important;
ok, indique le en commentaire dans le fichier pour qu'on se repose pas la question plus tard ^^

2023-08-28 15:06 UTC, Badatos commented on pod/video/templates/videos/video-info.html
> +                    <a target="_blank" href="https://twitter.com/share?url={{request.build_absolute_uri|urlencode}}" class="btn pod-btn pod-btn-social  m-1" title="{% trans 'Share on' %} Twitter">
ici c'est resté Twitter (sans le X)

2023-08-29 08:41 UTC, ptitloup approved these changes
ok pour moi, merci bcp

2023-08-29 08:53 UTC, SebastienCozeDev approved these changes
Ça me semble bon au niveau du code

2023-08-29 12:51 UTC, Badatos approved these changes
Ok pour moi, beau boulot ;)

2023-08-29 13:17 UTC, merged