[DONE] fix filters on events
EsupPortail/Esup-Pod pull request #916
Opened 2023-08-24 07:57 UTC by mattbild

Ajout d'un fichier Js pour filtrer les évènements.

- rechargement de la liste par appel ajax (avec loader)
- filtrage uniquement  sur les Types d'évènement affichés 
- changement de l'affichage de la pagination (liens => boutons)

2023-08-25 08:56 UTC, ptitloup approved these changes
ok pour moi techniquement, je ne l'ai pas testé. Par contre, je n'ai pas vu les HIDE_TYPE et autres dans le filter aside

2023-08-25 09:14 UTC, mattbild commented
j'ai oublié de push le dernier commit 😅

2023-08-25 11:43 UTC, SebastienCozeDev requested changes
J'ai remarqué quelques petites choses. Par contre, je ne sais pas du tout comment tester cette PR en local.

2023-08-25 11:43 UTC, SebastienCozeDev commented on pod/live/static/js/filter_aside_event_list.js
> +    // Enable / Disable all checkboxes
Il faudrait peut-être mettre la JSDoc sous la forme suivante :

```js
  /**
   * Enable /disable all checkboxes.
   *
   * @param {boolean} value
   */
  function disableCheckboxes(value) {
```

2023-08-25 11:43 UTC, SebastienCozeDev commented on pod/live/templates/live/events.html
>          <i class="bi bi-activity"></i>
Il faut mettre l'attribut `aria-hidden` à `true` pour les icônes

2023-08-25 11:43 UTC, SebastienCozeDev commented on pod/live/templates/live/filter_aside.html
> +        <legend class="h5"><i class="bi bi-tv"></i> {% trans "Types" %} </legend>
Il faut mettre l'attribut `aria-hidden` à `true` pour les icônes

2023-08-28 08:49 UTC, ptitloup commented
Merci pour ces changements

2023-08-28 09:22 UTC, SebastienCozeDev approved these changes

2023-08-28 09:44 UTC, AymericJak reviewed
Je n'ai pas testé, mais niveau code, cela semble OK.

Quelques petits changements tout de même :
- Déplacer le style dans un fichier CSS;
- Changer la documentation : Français --> Anglais

Merci :)

2023-08-28 09:44 UTC, AymericJak commented on pod/live/templates/live/events_list.html
> +                   style="min-width: 12rem; min-height: 11rem;" {% if categories %}data-slug={{ event.slug }}{% endif %}>
Pourrais tu déplacer le style dans un fichier CSS ?

2023-08-28 09:44 UTC, AymericJak commented on pod/live/templates/live/filter_aside.html
> +                    <img src="{{ type.icon.file.url }}" alt="{{ type.title }}" style="max-height:32px; max-width:32px;"
Pareil pour le style :)

2023-08-28 09:44 UTC, AymericJak commented on pod/live/views.py
> +    # pagination
La documentation devrait être en anglais.

2023-08-28 12:59 UTC, AymericJak reviewed
OK pour moi, juste ajouter une ligne vide en fin de fichier pour le CSS :)

Merci pour ta PR

2023-08-28 13:06 UTC, mattbild commented on pod/live/views.py
> +    if request.is_ajax():
exact.
Merci c'est corrigé.
Ainsi que les remarques suivantes

2023-08-29 07:42 UTC, Badatos approved these changes
c'est bon pour moi, juste une petite remarque de style sur les pydocs :)

2023-08-29 07:42 UTC, Badatos commented on pod/live/views.py
> +    """Show all directs of a given building."""
J'utiliserai "lives" plutot que directs ici pour rester cohérent

2023-08-29 07:42 UTC, Badatos commented on pod/live/views.py
> +    """Stops the record."""
Les pydocs doivent être conjugés à l'impératif ("Stop" plutôt que "Stops")
==> Je vous invite à installer un linter pydocstyle dans votre éditeur de texte pour vérifier automatiquement les pydocs.

Cela peut se faire via une extension flake8 par exemple : https://pypi.org/project/flake8-pydocstyle/

2023-08-29 08:46 UTC, mattbild commented on pod/live/views.py
> +    """Show all directs of a given building."""
il y a une différence entre les directs et les lives.
- Direct c'est la visualisation du flux pour les profils autorisés.
- Live c'est un quand il y a un évènement associé (avec des dates et des restrictions éventuelles )

2023-08-29 09:42 UTC, Badatos commented on pod/live/views.py
> +    """Show all directs of a given building."""
ok, dans ce cas c'est sur cette fonction qu'il y a une incohérence live/direct entre l'intitulé et la pydoc :
`deff directs_all(request):
     """Show all lives."""`

2023-08-29 10:04 UTC, mattbild commented on pod/live/views.py
> +    """Show all directs of a given building."""
c'est exact et maintenant corrigé

2023-08-29 12:57 UTC, Badatos approved these changes
ok pour moi pour le code

2023-08-29 13:12 UTC, merged