[WIP] Fix: Accessibility for the label for form fields (11.01)
EsupPortail/Esup-Pod pull request #930
Opened 2023-08-31 07:56 UTC by SebastienCozeDev

Before sending your pull request, make sure the following are done :

* [ ] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [ ] Your PR targets the `develop` branch.
* [ ] The title of your PR starts with `[WIP]` or `[DONE]`.

# Page 8

## Non-conformité :
Absence d’étiquette visible sur le champ de réponse à un commentaire

## Piste de correction :
- [ ] Soit ajouter un label visible pour assurer la meilleure accessibilité (modifier l'ID car il est dupliqué). Soit, s’il faut absolument garder le même affichage, ajouter un attribut title avec une valeur pertinente sur le champ (lui donner la même valeur que le placeholder) ou utiliser la technique du label flottant https://getbootstrap.com/docs/5.0/forms/floating-labels/. *---> le title a été modifié*

# Page 10 à 13 et page 15

## Non-conformité :
Absence d’étiquette visible sur le champ "Chercher un dossier" dans la fenêtre "sélectionner une image"

## Piste de correction :
- [ ] Soit ajouter un label visible pour assurer la meilleure accessibilité. Soit, s’il faut absolument garder le même affichage, ajouter un attribut title avec une valeur pertinente sur le champ (lui donner la même valeur que le placeholder) ou utiliser la technique du label flottant

# Page 15

## Non-conformité :

Présence d’ étiquettes non associées à leur champ respetif dans la modale "Récurrence"

## Piste de correction :
- [ ] Ajouter une balise <label> autour des étiquettes, avec un attribut for="xxx" où xxx est la valeur d’id unique sur la page du champ à associer
**Notes :** dans la modale récurrence, ajouter un aria-describedby="XXX" sur le champ "ou après", où XXX est l'ID de "occurrences"

# Autres

- [ ] Faire la traduction pour les réponses aux commentaires.

2023-08-31 12:46 UTC, Badatos commented on pod/meeting/templates/meeting/recurring_options_modal_form.html
> +            <label id="nb-occurrences-help" class="input-group-text p-1" for="id_nb_occurrences">{% trans 'occurrences' %}</label>
attention , un input ne peut avoir qu'un seul label

2023-08-31 13:01 UTC, Badatos commented on pod/meeting/templates/meeting/recurring_options_modal_form.html
> +  document.getElementById('id_nb_occurrences').setAttribute('aria-descrbedby', 'nb-occurrences-help');
Ne fait rien la dessus : je travaille dans ma branche à une fonction "add_describedby_attr" qui sera dans form_utils et dont le but est d'ajouter d'un coup les aria-describedby à tous les champs, du moment qu'ils ont bien été déclarés en "field.help_text"

2023-08-31 13:12 UTC, SebastienCozeDev commented on pod/meeting/templates/meeting/recurring_options_modal_form.html
> +            <label id="nb-occurrences-help" class="input-group-text p-1" for="id_nb_occurrences">{% trans 'occurrences' %}</label>
C'est réglé

2023-08-31 13:32 UTC, Badatos commented on pod/meeting/templates/meeting/recurring_options_modal_form.html
> +  document.getElementById('id_nb_occurrences').setAttribute('aria-descrbedby', 'nb-occurrences-help');
Pour que ma fonction soit simplifiée, il faut que les help texts aient des id normés.
Peux-tu faire en sorte que l'id du help texte soit toujours `"id_%sHelp" % fieldName`?

Ici par exemple ca donnerait "id_nb_occurrencesHelp"

2023-08-31 13:56 UTC, AymericJak requested changes

2023-08-31 13:56 UTC, AymericJak commented on pod/podfile/static/podfile/css/podfile.css
> +  -webkit-transition: -webkit-transform 0.3s ease-out;ation-triangle-fill warning-icon"
Erreur dans le code

2023-08-31 13:56 UTC, AymericJak commented on pod/podfile/static/podfile/css/podfile.css
> +  -webkit-transition: -webkit-transform 0.3s ease-out;ation-triangle-fill warning-icon"
Le `-webkit-transition` est aussi obsolète.

Je te renvoie sur cette page : [-webkit-transition, doc](https://developer.mozilla.org/fr/docs/Web/CSS/@media/-webkit-transition)

2023-08-31 14:20 UTC, SebastienCozeDev commented on pod/podfile/static/podfile/css/podfile.css
> +  -webkit-transition: -webkit-transform 0.3s ease-out;ation-triangle-fill warning-icon"
Réglé

2023-08-31 14:46 UTC, SebastienCozeDev commented on pod/podfile/static/podfile/css/podfile.css
> +  -webkit-transition: -webkit-transform 0.3s ease-out;ation-triangle-fill warning-icon"
Réglé également

2023-09-01 07:10 UTC, Badatos approved these changes

2023-09-01 07:10 UTC, Badatos commented on pod/podfile/static/podfile/css/podfile.css
> +  /* display: -ms-grid;
ca continue à bien s'afficher sans toute cette partie ?

2023-09-01 07:38 UTC, SebastienCozeDev commented on pod/meeting/templates/meeting/recurring_options_modal_form.html
> +  document.getElementById('id_nb_occurrences').setAttribute('aria-descrbedby', 'nb-occurrences-help');
C'est fait

2023-09-01 08:03 UTC, AymericJak approved these changes
ok pour moi !

Merci pour cette PR :)

2023-09-01 08:28 UTC, merged