[WIP] Fix links (accessibility)
EsupPortail/Esup-Pod pull request #931
Opened 2023-08-31 08:53 UTC by AymericJak

# RGAA 6.2

- Changement de l'affichage d'un utilisateur dans un template. Mettre `{{ owner }}` simplement suffit, la méthode `__str__` est redéfinie dans le modèle. Ainsi, le username est aussi affiché.

2023-08-31 14:08 UTC, SebastienCozeDev reviewed
Testé localement et fonctionnel :+1:

2023-08-31 15:04 UTC, ptitloup requested changes
merci

2023-08-31 15:08 UTC, Badatos requested changes

2023-08-31 15:08 UTC, Badatos commented on pod/main/templates/base.html
> +                  {% if request.path == '/' %}
j'aurai simplifié en mettant directement 
`{% if request.path == '/' %}active{% endif %}`dans la classe

2023-08-31 15:08 UTC, Badatos commented on pod/main/templates/footer.html
> +          <a href="https://github.com/EsupPortail/Esup-Pod" target="_blank" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans "Show Esup-Pod project on GitHub" %} - {% trans "New wi
pourquoi une target="_blank" sur github et pas sur Esup-portail ?
Autant n'en mettre sur aucun des 2 et laisser l'utilisateur choisir d'ouvrir dans un nouvel onglet s'il le désire ^^.

2023-08-31 15:08 UTC, Badatos commented on pod/main/templates/navbar.html
> +      <input class="form-control form-control-sm hide-search-input" id="s" placeholder="{% trans 'Search a video' %}" type="search" name="q">
attention : parfois les contenus sont des podcast audio, pas que des vidéos. Mettre plutot "Search a media" non ?

2023-08-31 15:08 UTC, Badatos commented on pod/main/templates/navbar.html
> +          <a class="btn btn-primary btn-sm ps-2 pe-2 d-flex" href="{% url 'authentication:authentication_login' %}{{ url_referrer }}" aria-label="{% trans 'Log in' %}" title="{% trans "Open login pag
L'aria-label est redondant, je le supprimerais je pense.

2023-09-01 07:14 UTC, AymericJak commented on pod/live/templates/live/event-info.html
> +          {{ video.owner }}
Bien vu !

Erreur de copier / coller

2023-09-01 07:18 UTC, AymericJak commented on pod/main/templates/base.html
> +                  {% if request.path == '/' %}
Il y a aussi le `aria-current="page"`.

2023-09-01 07:21 UTC, AymericJak commented on pod/main/templates/footer.html
> +          <a href="https://github.com/EsupPortail/Esup-Pod" target="_blank" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans "Show Esup-Pod project on GitHub" %} - {% trans "New wi
Comme c'est un changement de site web, je préfère laisser le target _blank.

Ainsi, je l'ai ajouté pour Esup-portail.

2023-09-01 07:21 UTC, Badatos commented on pod/main/templates/base.html
> +                  {% if request.path == '/' %}
alors ca pourrait donner :
`class="breadcrumb-item {% if request.path == '/' %}active" aria-current="page{% endif %}"`
;)

2023-09-01 08:16 UTC, AymericJak commented
Je l'ai changé ta condition @Badatos :roll_eyes:

```html
<li class="breadcrumb-item {% if request.path == '/' %}active" aria-current="page{% endif %}">
  {% trans 'Home' %}
</li>
```

Bon, en vrai ça évite de répéter ces trois ligne, c'est bien.
Merci :clap:

2023-09-01 08:32 UTC, ptitloup approved these changes

2023-09-01 09:02 UTC, Badatos commented on pod/main/templates/footer.html
> +          <a href="https://www.esup-portail.org/" target="_blank" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans 'Esup Portal: Community of French higher education establishments
attention : target blank est en double ici

2023-09-01 09:03 UTC, Badatos commented on pod/main/templates/footer.html
> +          <a href="https://www.esup-portail.org/" target="_blank" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans 'Esup Portal: Community of French higher education establishments
et mettre "new window" entre simple quotes pour éviter des soucis de coloration syntaxique sur certains éditeurs

2023-09-01 09:03 UTC, Badatos commented on pod/main/templates/navbar.html
> +              <a class="btn btn-primary btn-sm" href="{% url 'video:video_add' %}" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans "Add a new video on" %} {{ TITLE_SITE }}">
simple quotes

2023-09-01 09:04 UTC, Badatos commented on pod/main/templates/navbar.html
> +        <button class="btn btn-sm nav-item {% if not request.user.owner.userpicture  %}initials btn btn-primary {% else %} nav-link{% endif %} ps-2 pe-2 d-flex justify-content-center align-items-cent
faire une recherche de tous les ` title="{% trans "`pour remplacer les double quotes par des simples

2023-09-01 09:11 UTC, SebastienCozeDev requested changes

2023-09-01 10:14 UTC, Badatos commented on pod/video/templates/videos/filter_aside.html
> +  <legend class="h5"><i class="bi bi-tv"></i> {% trans 'Types' %} </legend>
manque un aria-hidden ici

2023-09-01 10:15 UTC, Badatos commented on pod/video/templates/videos/filter_aside.html
> +  <legend class="h5"><i class="bi bi-book"></i> {% trans 'Disciplines' %} </legend>
ici aussi

2023-09-01 10:17 UTC, Badatos commented on pod/video/templates/videos/video_page_content.html
> +    {% if video.get_encoding_step == "5 : transcripting audio' %}
attention ici ca doit rester une double quote

2023-09-01 11:01 UTC, SebastienCozeDev approved these changes

2023-09-01 12:08 UTC, Badatos commented on pod/video/templates/videos/filter_aside.html
> +  <legend class="h5"><i class="bi bi-tag"></i> {% trans 'Tags' %}</legend>
un autre aria-hidden ^^

2023-09-01 12:08 UTC, Badatos commented on pod/video/templates/videos/filter_aside.html
> +  <legend class="h5"><i class="bi bi-archive"></i> {% trans 'University course' %}</legend>
+1

2023-09-01 12:09 UTC, Badatos approved these changes
Plus que 2 petits aria-hidden et c'est bon pour moi ^^

2023-09-01 12:48 UTC, merged