[DONE] Yaal Coop/Add PWA functionality to app and notifications capabilities
EsupPortail/Esup-Pod pull request #937
Opened 2023-09-05 13:44 UTC by LoanR

# PWA
L'application est installable sur différents os : iOS, macOS, Windows, Android, Linux...
Cette fonctionnalité se base sur la lib [django-pwa](https://github.com/silviolleite/django-pwa) qui permet de configurer la création du `manifest.json` et du service worker.

# Notifications
Le système de base de notifications est implémenté et s'appuie sur la lib [django-webpush](https://github.com/safwanrahman/django-webpush).

## Standard web push
L'usage standard est le suivant :
- Accepter de recevoir des notifications doit être fait par une action de l'utilisateur. La demande sera toujours double, le navigateur doit lui aussi demander cette autorisation
- Suivant le navigateur utilisé (PWA ou non), le navigateur contacte le serveur distant qui lui correspond (Mozilla Push Service avec autopush-rs pour Firefox par exemple)
- Le navigateur fournit la clé VAPID publique
- Le push service répond avec un endpoint sur lequel poster les notifications
- Lorsque l'application veut envoyer une notification, elle envoie le contenu sur ce endpoint avec la clé VAPID privée
- Le push service authentifie l'information puis envoie le contenu de la notification sur les appareils enregistrés. Le message peut avoir une durée de vie, ce qui fait que les appareils éteints pourront tout de même recevoir la notification par la suite si nécessaire.

## Conditions de notification
### Notification métier : fin d'encodage
Pour le moment, Esup-Pod utilise ces notifications pour un cas métier particulier : la fin de l'encodage d'une vidéo. Le flow suivi est le suivant :
- Lorsqu'un utilisateur upload une vidéo, l'app demande la permission d'envoyer des notifications
- Si l'utilisateur accepte, le navigateur s'inscrit au push service correspondant et le serveur va enregistrer la valeur de l'attribut `accepts_notifications` de l'`Owner`
- Dans le même temps le navigateur demande l'autorisation de notifier sur l'appareil
- Si l'utilisateur accepte, l'autorisation de notifier depuis cette url est enregistrée dans les paramètres du navigateur
- Si ces conditions sont remplies, lorsque l'encoding d'une vidéo appartenant à l'utilisateur est terminé, une notification sera envoyé sur ses appareils enregistrés.

### Conditions de demande de notification
Un utilisateur peut paramétrer sa préférence de notification depuis son volet menu utilisateur.
Si la préférence de notification d'un utilisateur n'a pas encore été définie, la demande de notification se fera pendant l'encodage d'une vidéo, sur la page d'édition de la vidéo.

### Règles de notifications
Pour être notifié de la fin d'un encoding, un utilisateur doit avoir accepté les notifications (`accepts_notifications` à `True`), et au moins un de ses appareils doit être enregistré à un push service.
Il doit également donner l'autorisation a un site de notifier son appareil depuis les paramètres du navigateur. Le fait qu'un utilisateur décide finalement de retirer la permission de notification d'un site dans son navigateur ne peut pas être contrôlé, cela ne rentre pas en compte dans le choix de l'envoi d'une notification.
Si un utilisateur refuse d'être notifié (`accepts_notification` à `False`) ou qu'aucun de ses appareil n'est enregistré à un push service, il recevra un mail à la fin de l'encodage (si le paramètre `EMAIL_ON_ENCODING_COMPLETION` est à `True`)

## Cas particulier
Sur iOS, pour utiliser le service de notification et les recevoir, il faut impérativement installer la PWA.

## Tests
Pour tester les notifications, une url est à disposition pour les superusers, `/pwa`
Un bouton permet d'envoyer une notification sur tous les appareils enregistrés (et autorisés à notifier) de l'utilisateur connecté.

resolves #912
cc @azmeuk

2023-09-05 13:59 UTC, LoanR commented
Il y a un peu d'infos dans dockerfile-dev-with-volumes/README.adoc et dans pod/main/configuration.json
Dans ce dernier fichier, `pod_version_init` n'est pas précisé, ne sachant pas à quelle version la PWA sera déployée.

Y a-t-il un endroit indiqué pour documenter la PWA et les notification (ce qui a été décrit dans la PR) ?
La meilleure place semble être https://www.esup-portail.org/wiki/display/ES/esup-pod mais nous n'y avons pas accès...

2023-09-06 07:45 UTC, ptitloup commented
Bonjour et merci pour votre contribution. Je viens de solliciter l'équipe en charge du développement pour faire les review. Pour la documentation, en effet, je vais ouvrir une page sur le wiki mais je ne pourrais malheureusement pas vous donner accès. Je vous propose donc de faire la doc au format markdown et je la mettrai en ligne sur le wiki. Bonne journée

2023-09-06 08:02 UTC, Badatos requested changes
Merci pour cette fonctionnalité !
J’ai fait quelques remarques, principalement lié au QoC et à l'accessibilité.

2023-09-06 08:02 UTC, Badatos commented on pod/video_encode_transcript/utils.py
> +def send_notification_encoding(video_to_encode):
courte pydoc

2023-09-06 08:02 UTC, Badatos commented on pod/video_encode_transcript/utils.py
> +def send_notification(video_to_encode, subject_prefix):
courte pydoc

2023-09-08 13:37 UTC, LoicBonavent requested changes
Bonjour,

Voici le retour après mes premiers tests.
Pour informations, j'ai mis à jour Pod, sur un environnement de test fonctionnel, via les commandes habituelles :
 - python3 -m pip install -r requirements.txt
 - make updatedb
 - make migrate
 - make statics
 - make compilelang
Puis, j'ai réalisé la configuration adéquate dans custom/settings_local.py en utilisant des clés générées via https://web-push-codelab.glitch.me/
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "xxx",
    "VAPID_PRIVATE_KEY": "xxxx",
    "VAPID_ADMIN_EMAIL": "xxx"
}
Et final un restart du service uwsgi-pod.

Côté installation, aucun problème !

Par la suite, j'ai réalisé des tests sur différents navigateurs Firefox / Chrome / Edge sur mon PC (je testerai lundi sur un téléphone/tablette).
Voici alors mes remarques :
 - Quand je vais dans le menu, dans Paramètres de notification et que je clique sur Autoriser :
  * sur Chrome et Edge, le navigateur me demande de confirmer l'autorisation, mais cela me provoque une erreur 403 dans la Console du navigateur lors d'une requête sur https://xxx.umontpellier.fr/accounts/set-notifications/ 403 (forbidden)
  * sur Firefox, le navigateur ne me demande rien et cela provoque une erreur dans la Console : Uncaught (in promise) TypeError: reg is undefined
      subscribe https://xxx.umontpellier.fr/static/webpush/webpush.js:95
      setPushPreference https://xxx.umontpellier.fr/static/js/notification-toast.js?ver=3.3.1.2:25
      onclick https://xxx.umontpellier.fr/:1

Pour continuer mes tests sur les notifications, j'ai alors modifier directement la valeur du champ authentication_owner.accepts_notifications pour mon compte (j'ai mis 1 pour les accepter).

Après cette manip, les notifications de fin d'encodage s'affichaient bien sur tous les navigateurs.

 - Sur Chrome/Edge, sur toutes les pages, j'ai une erreur non bloquante dans la console : Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed
 
 - Sur la route /pwa, les boutons n'ont pas de style et le bouton Send notification n'est pas traduit. J'imagine que c'est seulement une page de test, c'est donc peu important.
 
 - Dans l'Administration, il manque quelques traductions (push information, User, subscription, Group).
 
 - Sur Chrome/Edge, j'ai pu installer l'application sur le bureau (sous Firefox, je n'ai pas trouvé mais il me semble que c'est lié à Firefox, qui ne l'autorise plus depuis 2 ans).
 Par contre, l'application se nomme Podeduc et les icônes correspondent aux icônes "de base" (non surchargés) de Pod.
 Serait-il possible de pouvoir réaliser une surcharge du nom de l'application et du(es) icône(s) ? Typiquement, via le fichier de configuration custom/setting_local.py.
 Par exemple, chez nous, nous mettrions Plateforme vidéo UM comme nom d'application et l'icône correspondant à la charte de l'université.

Encore merci pour ce travail de qualité.

Bonne journée,

2023-09-12 16:07 UTC, ptitloup commented
Bonjour @LoanR est-ce possible de répondre aux remarques svp ?

2023-09-12 16:08 UTC, ptitloup commented
Est-ce possible d'apporter les modifications demandées ? merci bcp

2023-09-13 12:49 UTC, LoanR commented
Hello @ptitloup, c'est bien pris en compte de notre côté, on est sur les modifs demandées et on enquête sur les erreurs rencontrées.
On reviendra ici dès qu'on aura suffisamment avancé ou si on a des questions.

2023-09-13 16:12 UTC, azmeuk commented
Bonjour,

Je viens de pousser les modifications de codes demandées par @Batados.

@LoicBonnavent

> Par la suite, j'ai réalisé des tests sur différents navigateurs Firefox / Chrome / Edge sur mon PC (je testerai lundi sur un téléphone/tablette).

Nous n'avons pas testé sur Edge car le cahier des charges listait Chrome, Firefox et Safari.

Me confirmes-tu que tu as fais tes tests depuis un Windows ?

Me confirmes-tu que tu tests depuis une URL publique en https ?

Peux-tu m'indiquer les versions des navigateurs avec lesquelles tu effectues tes tests ?

> sur Chrome et Edge, le navigateur me demande de confirmer l'autorisation, mais cela me provoque une erreur 403 dans la Console du navigateur lors d'une requête sur https://xxx.umontpellier.fr/accounts/set-notifications/ 403 (forbidden)

Étrange. À première vue je dirais que ça pourrait être un souci de CSRF. Vois-tu passer le token CSRF dans la requête ?

> Sur Chrome/Edge, sur toutes les pages, j'ai une erreur non bloquante dans la console : Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed

Le serviceworker essayait de mettre en cache un fichier avec un mauvais chemin. C'est corrigé.

> Sur la route /pwa, les boutons n'ont pas de style et le bouton Send notification n'est pas traduit. J'imagine que c'est seulement une page de test, c'est donc peu important.

Effectivement nous avons fais cette simple page pour pouvoir tester la réception des notifications sans avoir besoin de mettre en ligne une vidéo. Cette page n'est disponible qu'aux super utilisateurs. Si c'est important on peut le traduire.

> Dans l'Administration, il manque quelques traductions (push information, User, subscription, Group).

En effet ces éléments viennent de l'extension django-webpush. Il n'y a pas de traduction pour le moment mais [une PR a été soumise](https://github.com/safwanrahman/django-webpush/pull/113) à ce sujet.

> Sur Chrome/Edge, j'ai pu installer l'application sur le bureau (sous Firefox, je n'ai pas trouvé mais il me semble que c'est lié à Firefox, qui ne l'autorise plus depuis 2 ans).

Il existe une extension qui permet l'installation avec Firefox : https://github.com/filips123/PWAsForFirefoxhttps://github.com/filips123/PWAsForFirefox

> Par contre, l'application se nomme Podeduc et les icônes correspondent aux icônes "de base" (non surchargés) de Pod.
> Serait-il possible de pouvoir réaliser une surcharge du nom de l'application et du(es) icône(s) ? Typiquement, via le fichier de configuration custom/setting_local.py.
> Par exemple, chez nous, nous mettrions Plateforme vidéo UM comme nom d'application et l'icône correspondant à la charte de l'université.

On peut surcharger n'importe quel [élément de configuration décrit dans django-pwa](https://github.com/silviolleite/django-pwa?tab=readme-ov-file#configuration) dans `setting_local.py` et notamment `PWA_APP_NAME` qui contrôle le nom d'affichage, ou bien `PWA_APP_ICONS` et `PWA_APP_ICONS_APPLE` pour qui contrôlent les icônes.

2023-09-15 10:48 UTC, LoanR commented
Nous allons mettre ces questions de configuration de django-pwa dans la doc, ça simplifiera l'usage.

2023-09-15 13:17 UTC, LoicBonavent commented
Bonjour,

Dans mon cas, je vous confirme que le problème de 403 venait de mon environnement de test et non de votre développement (la valeur du cookie csrftoken n'était pas fournie).

Encore une petite remarque, il semblerait qu'il y ait 2 traductions en double, ce qui pose problème pour la compilation :
"Don't forget to allow notifications from this website in your browser's settings!"
et
"Error during unsubscription..."

Merci.

2023-09-15 13:22 UTC, azmeuk commented
> Dans mon cas, je vous confirme que le problème de 403 venait de mon environnement de test et non de votre développement (la valeur du cookie csrftoken n'était pas fournie).

Merci pour l'info. Par curiosité, qu'est-ce qui a provoqué le souci ?

> Encore une petite remarque, il semblerait qu'il y ait 2 traductions en double, ce qui pose problème pour la compilation.

On s'en occupe rapidement.

2023-09-15 13:30 UTC, LoicBonavent commented
Je pense que cela doit être lié à la conf Nginx vis-à-vis de proxy_set_header Cookie ou quelque chose dans ce style.
Pour tester, j'ai modifié le fichier notification-toast.js comme ceci :
  _var csrftoken = Cookies.get('csrftoken');
  // Check if token is undefined or null
  if (csrftoken == null) {
    csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
  }
  formData.append("csrfmiddlewaretoken", csrftoken);

  const response = await fetch(post_url, {
    method: "POST",
    body: formData,
    headers: {
      "X-Requested-With": "XMLHttpRequest",
      "X-CSRFToken": csrftoken,
    },
  });_

Je pense qu'il y a également un petit problème de traduction pour le message d'encodage; j'obtiens du Franglais :) :
The vidéo "" has been encodé aux formats Web, and is now available on Pod.

2023-09-18 09:36 UTC, AymericJak requested changes
Bonjour, quelques petits changements attendus de mon côté.
Merci

2023-09-18 09:36 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +#| msgid "Get push notifications from your devices."
Il faut enlever ces deux lignes.

2023-09-18 09:36 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr "Paramètres de notification"
`notifications` avec un s.

2023-09-18 09:36 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +#| msgid "Error…"
Supprimer ces deux lignes.

2023-09-18 09:36 UTC, AymericJak commented on pod/progressive_web_app/urls.py
> +
Comme pour les autres fichiers `urls.py`, il serait bien d'ajouter cette ligne : `app_name = "progressive_web_app"`

2023-09-18 09:36 UTC, AymericJak commented on pod/urls.py
> +    url(r"^pwa/", include("pod.progressive_web_app.urls")),
Maintenant, on peut simplement utiliser la fonction `path`.

On peut juste mettre :
`path("pwa/", include("pod.progressive_web_app.urls", namespace="progressive_web_app"),`

2023-09-19 09:59 UTC, azmeuk commented
> Je pense qu'il y a également un petit problème de traduction pour le message d'encodage; j'obtiens du Franglais :) :
> The vidéo "" has been encodé aux formats Web, and is now available on Pod.

C'est réglé.

@AymericJak

Les différents points sont réglés aussi.

2023-09-19 11:38 UTC, LoicBonavent approved these changes
D'après mes tests, cela semble concluant.
Un grand merci pour ce travail !

2023-09-19 14:07 UTC, ptitloup commented
Test effectués sur MacOS (Mac Book Pro) : Ok sur Firefox et Safari. (pas d'installation possible)

Voici quelques retours de mes tests sur mon telephone pro sur Android.
Navigateur utilisé : Firefox
Pour l'installation, il faut aller dans le menu du navigateur puis cliquer sur installer. Il me rajoute bien un reccourci sur la page d'accueil mais l'icone est blanc :'( 
j'aurai bien aimé un systeme identique aux notifications pour l'installation.
Au niveau des notifications, je clique sur Autoriser mais rien ne se passe :'(

Second test effectué sur Chrome. Il ne propose pas d'installer mais d'ajouter à l'ecran d'accueil. L'icone est bien présent (mais il me semble qu'il s'agit du favicon et non des icons fourni dans l'application)
Concernant les notifications, je clique sur paramètres de notification puis sur Autoriser mais rien ne se passe...

Avez-vous tester de votre côté ? Ai-je oublié quelque chose ? merci pour votre aide

2023-09-19 14:25 UTC, ptitloup commented
enfin, est-ce possible de rajouter une entrée du menu pour installer l'application ?

2023-09-20 08:49 UTC, AymericJak approved these changes
C'est bon pour moi.

Merci à vous pour cette PR !

2023-09-20 09:04 UTC, ptitloup commented
Bonjour @LoanR , pourriez-vous me faire un retour sur les deux point remontés suite à mes tests fonctionnels : 
- est-ce possible de rajouter une entrée du menu pour installer l'application ? (dans le cas ou l'installation est possible !)
- Est-ce possible de voir pour récupérer l'évènement d'autorisation du navigateur et d'enregistrer directement plutot que de devoir recliquer sur autoriser ?
Merci bcp

2023-09-20 09:04 UTC, Badatos approved these changes

2023-09-20 09:12 UTC, ptitloup commented
Nous aimerions sortir la V3.4.0 la semaine prochaine, pensez-vous pouvoir répondre aux deux dernières demandes d'ici cette fin de semaine ? Merci bcp

2023-09-20 09:36 UTC, ptitloup commented
Il faudrait fixer egalement les conflits svp :)

2023-09-20 12:42 UTC, azmeuk commented
> Par contre, il faut cliquer une première fois sur autoriser, puis autoriser du côté du navigateur et cliquer à nouveau sur autoriser. Je trouve que ce n'est pas très ergonomique. Est-ce possible de voir pour récupérer l'évènement d'autorisation du navigateur et d'enregistrer directement ?

Si en théorie JS permet de récupérer l'évènement d'autorisation, en pratique c'est django-webpush qui gère cette partie et ne permet pas d'enregistrer une callback pour exécuter du code perso à ce moment.

La manière de faire pérenne ça serait de proposer un patch à django-webpush qui permette d'exécuter des callbacks. Par contre il y a peu de chances que ce soit prêt pour la semaine prochaine.

En attendant, on peut dupliquer le code de django-webpush et l'adapter. Par contre ça n'est pas une option très pérenne : si le code JS de django-webpush est mis à jour alors ça risque de casser.

On peut faire ça si vous êtes OK avec le code dupliqué.

> Petite question, comment est choisi le nom de l'application car de mon coté, elle s'appelle podeduc ... j'aurai préféré pod ulille !

La variable de configuration [PWA_APP_NAME](https://github.com/silviolleite/django-pwa?tab=readme-ov-file#configuration) de django-pwa permet de personnaliser le nom de l'application.

> enfin, est-ce possible de rajouter une entrée du menu pour installer l'application ? (dans le cas ou l'installation est possible !)

Je regarde ça.

> Il faudrait fixer egalement les conflits svp :)

C'est fait.

2023-09-20 12:57 UTC, ptitloup commented
> > Par contre, il faut cliquer une première fois sur autoriser, puis autoriser du côté du navigateur et cliquer à nouveau sur autoriser. Je trouve que ce n'est pas très ergonomique. Est-ce possible de voir pour récupérer l'évènement d'autorisation du navigateur et d'enregistrer directement ?
> 
> Si en théorie JS permet de récupérer l'évènement d'autorisation, en pratique c'est django-webpush qui gère cette partie et ne permet pas d'enregistrer une callback pour exécuter du code perso à ce moment.
> 
> La manière de faire pérenne ça serait de proposer un patch à django-webpush qui permette d'exécuter des callbacks. Par contre il y a peu de chances que ce soit prêt pour la semaine prochaine.
> 
> En attendant, on peut dupliquer le code de django-webpush et l'adapter. Par contre ça n'est pas une option très pérenne : si le code JS de django-webpush est mis à jour alors ça risque de casser.
> 
> On peut faire ça si vous êtes OK avec le code dupliqué.

Merci pour votre retour rapide.
Non pas de duplication. Je préfère qu'on reste avec la version officiel de webpush.
Dans ce fichier, https://github.com/yaal-coop/Esup-Pod/blob/pwa-django-webpush/pod/progressive_web_app/static/js/notification-toast.js#L27C28-L27C52
Plutot que de faire un `let subscription = await registration.pushManager.getSubscription();`, on pourrait faire ceci : 
```
function getSubscription() {
    if (registration.pushManager) {
        return registration.pushManager.getSubscription()
            .then(function(subscription) {
                if (subscription) {
                    return subscription;
                }
                throw new Error('User not subscribed');
            });
    }
    throw new Error('error evaluating pushManager');
}

let subscription = getSubscription();
if (subscription && subscription.endpoint) {
   //record subscription and remove modal
}
```
Attention, ce n'est qu'un code que j'ai trouvé rapidement, c'est surement à adpater mais je pense qu'il est possible de faire quelque chose...
> 
> > Petite question, comment est choisi le nom de l'application car de mon coté, elle s'appelle podeduc ... j'aurai préféré pod ulille !
> 
> La variable de configuration [PWA_APP_NAME](https://github.com/silviolleite/django-pwa?tab=readme-ov-file#configuration) de django-pwa permet de personnaliser le nom de l'application.

Merci !

> 
> > enfin, est-ce possible de rajouter une entrée du menu pour installer l'application ? (dans le cas ou l'installation est possible !)
> 
> Je regarde ça.

Merci

> 
> > Il faudrait fixer egalement les conflits svp :)
> 
> C'est fait.

Top !

2023-09-20 13:02 UTC, ptitloup commented
Encore une fois, j'ai repondu trop vite, le fonction que j'ai trouvé permet de voir si l'utilisateur a déjà autorisé les notifications. S'il ne l'a pas deja fait, on peut faire quelque comme cela : 
```
var options = {
    userVisibleOnly: true,
    applicationServerKey: urlBase64ToUint8Array(applicationServerKey)
};
serviceWorkerRegistration.pushManager.subscribe(options).then(
    function(pushSubscription) {
        if (pushSubscription) {
              //record subscription and remove modal
         }
     });
```

2023-09-20 13:02 UTC, ptitloup commented
> Concernant un lien d'installation, visiblement les méthodes pour déclencher en JS l'installation des PWA ne sont [pas disponibles pour firefox ni safari](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeinstallprompt_event#browser_compatibility). Est-ce qu'on l'implémente quand même ?

Oui svp.
Et concernant le lien de menu comme le lien de notifications, est-ce possible de l'afficher que quand c'est possible. Merci !

2023-09-25 09:13 UTC, ptitloup commented
Bonjour @LoanR , on attends presque plus que vous pour sortir notre version 3.4.0, pourriez-vous nous tenir informé de quand vous pourriez apporter les dernières modifications demandées ? merci bcp

2023-09-25 13:43 UTC, ptitloup commented
Je viens de passer develop en freeze, des que c'est ok sur cette PR, on pourra sortir la V3.4.0 avec votre contribution. :)

2023-09-25 14:23 UTC, azmeuk commented
Bonjour @ptitloup 
Désolé pour les délais de réponse. Je m'occupe de tous les points restants dans la journée de demain.
Éloi

2023-09-26 13:21 UTC, azmeuk commented
@ptitloup 

> S'il ne l'a pas deja fait, on peut faire quelque comme cela :

`serviceWorkerRegistration.pushManager.subscribe(options).then` permet en effet de déclencher un traitement après acceptation des notifications par le navigateur de l'utilisateur, mais c'est une action qui est [déjà exécutée par django-webpush](https://github.com/safwanrahman/django-webpush/blob/0561306f133619297d7d66dd683690edf55cf325/webpush/static/webpush/webpush.js#L111-L115). En cas d'accord django-webpush appelle la méthode `postSubscribeObj` qui enregistre en base de données les informations du device.

Si on appelle `serviceWorkerRegistration.pushManager.subscribe` nous-même alors il faut aussi faire un appel à `postSubscribeObj`, et c'était en partie ce dont je parlai avec ma question sur la réplication du code.

Par ailleurs, django-webpush prépare les options à passer à `serviceWorkerRegistration.pushManager.subscribe` [dans sa méthode `subscribe`](https://github.com/safwanrahman/django-webpush/blob/0561306f133619297d7d66dd683690edf55cf325/webpush/static/webpush/webpush.js#L102-L109) et notamment la transmission de la clé publique. C'est encore une partie du code qu'il sera nécessaire de dupliquer si l'on veut appeler `serviceWorkerRegistration.pushManager.subscribe` nous-même.

On peut envisager une manière non intrusive en écoutant l'évènement de souscription grâce à [l'évènement `pushsubscriptionchange`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event), mais le support navigateur est encore anecdotique (et encore que je n'arrive pas à le faire fonctionner correctement avec Firefox, et que je ne suis pas sûr qu'il s'agisse de l'événement d'acceptation de la souscription ou bien juste d'une modification sur une souscription).

![Screenshot 2023-09-26 at 14-58-14 ServiceWorkerGlobalScope pushsubscriptionchange event - Web APIs MDN](https://github.com/EsupPortail/Esup-Pod/assets/60163/d5aca617-a77e-4401-ade2-efc220252f20)

Je vois donc 2 options :

1. Implémentation de la fonctionnalité avec duplication d'une partie du code de django-webpush.
2. Garder le comportement actuel et ouvrir un ticket de demande de fonctionnalité sur le dépôt de `django-webpush`.

Tu me confirmes que j'implémente la 1 avec duplication d'une partie du code ?

2023-09-26 14:32 UTC, azmeuk commented
Je viens de pousser l'affichage d'une entrée de menu permettant l'installation de la PWA pour les navigateurs qui la supportent, à savoir pour le moment Chrome.

2023-09-26 14:45 UTC, azmeuk commented
Voici le texte de documentation qui peut être ajouté au wiki:

```markdown
# PWA

L'application implémente quelques fonctionnalités des [applications web progressives](https://developer.mozilla.org/fr/docs/Web/Progressive_web_apps),
comme l'installation ou les notifications.

## Configuration

Les métadonnées de l'application sont pré-remplies, mais toutes les options (icônes, nom de l'application, etc.) peuvent être surchargées.
La liste exhaustive des paramètres de configuration est disponible [sur le dépôt de django-pwa](https://github.com/silviolleite/django-pwa?tab=readme-ov-file#configuration).
Notamment, le nom et la description de l'application sont contrôlés par les variables `PWA_APP_NAME` et `PWA_APP_DESCRIPTION`.

## Notifications push

Afin de permettre à l'application d'envoyer aux utilisateurs des notifications natives, il est nécessaire de générer une paire de clés VAPID, par exemple avec des outils tels que https://web-push-codelab.glitch.me/

Ensuite, les clés doivent être indiqués dans la configuration via les paramètres suivants:

```python
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "<clé-publique>",
    "VAPID_PRIVATE_KEY": "<clé-privée>",
    "VAPID_ADMIN_EMAIL": "contact@example.org"
}
``````

2023-09-26 15:50 UTC, ptitloup commented
Bonjour Eloi,
merci pour l'implementation et ton retour.
Ok pour la doc, je vias rajouter une page dans le wiki.
Pour ta question, en fait, je cherche quelque chose d'ergonomique pour nos utilisateurs. Le fait d'avoir à cliquer sur "notification" puis de devoir autoriser puis après de rappuyer ne l'est pas, bcp d'utilisateurs ne vont pas le faire. J'opte donc pour la V1 en attendant mieux. J'aurai aimé que ce ne soit pas le cas. Merci

2023-09-26 15:51 UTC, ptitloup commented
CC @azmeuk !

2023-09-26 15:59 UTC, ptitloup commented
La doc est en ligne : https://www.esup-portail.org/wiki/display/ES/Mode+PWA+et+Notifications

2023-09-26 16:03 UTC, azmeuk commented
> Bonjour Eloi, merci pour l'implementation et ton retour. Ok pour la doc, je vias rajouter une page dans le wiki. Pour ta question, en fait, je cherche quelque chose d'ergonomique pour nos utilisateurs. Le fait d'avoir à cliquer sur "notification" puis de devoir autoriser puis après de rappuyer ne l'est pas, bcp d'utilisateurs ne vont pas le faire. J'opte donc pour la V1 en attendant mieux. J'aurai aimé que ce ne soit pas le cas. Merci

C'est bien compris. J'implémente ça demain matin.

2023-09-26 16:04 UTC, azmeuk commented
> La doc est en ligne : https://www.esup-portail.org/wiki/display/ES/Mode+PWA+et+Notifications

On dirait que le la mise en forme markdown n'a pas fonctionné.

2023-09-26 16:05 UTC, ptitloup commented
> > La doc est en ligne : https://www.esup-portail.org/wiki/display/ES/Mode+PWA+et+Notifications
> 
> On dirait que le la mise en forme markdown n'a pas fonctionné.

Pas grave, je referais cela tranquillement

2023-09-26 16:09 UTC, ptitloup commented
Voilà, c'est fait

2023-09-27 10:45 UTC, ptitloup commented
Bonjour, je confirme la bonne installation de Pod. Testé via chromium sous Mac OS. Il m'a proposé de l'installer et j'ai maintenant l'application de disponible directement. Etrange, l'application se nomme podeduc !

2023-09-27 12:11 UTC, azmeuk commented
> Etrange, l'application se nomme podeduc !

@ptitloup as-tu configuré la variable `PWA_APP_NAME` ? Vois-tu les modifications dans `https://ton-installation.tld/manifest.json` ?

2023-09-27 12:15 UTC, ptitloup commented
Quand je modifie la variable PWA_APP_NAME, je vois bien la modification. Donc tout est ok mais pourquoi PodEduc par défaut ? c'est plutot ca ma question :)

2023-09-27 12:16 UTC, azmeuk commented
Je ne sais plus d'où ce nom vient. Tu préfères un autre nom par défaut ?

2023-09-27 12:18 UTC, ptitloup commented
Pod Educ est le nom de l'instance Pod de l'education nationale. Certes, c'est une grosse instance mais nous sommes plutot enseignement supérieur. Ne voulant froisser personne, on pourrait mettre Pod tout simplement.

2023-09-27 12:20 UTC, ptitloup commented
ok j'ai trouvé, tout se trouve dans pod/settings.py, est-ce possible de déplacer ces paramètres dans pod/main/settings.py et de remplacer podeduc par Pod svp ? Merci bcp

2023-09-27 14:18 UTC, ptitloup approved these changes
ok pour moi

2023-09-27 14:21 UTC, azmeuk commented
J'ai poussé les modifications que tu as demandé tout à l'heure, et aussi un changement sur la partie front pour l'activation des notifications.

Activation / désactivation des notifications par l'utilisateur
![ok](https://github.com/EsupPortail/Esup-Pod/assets/60163/d3f6b34d-3803-4ff9-985b-3db5846d73ec)

L'utilisateur active les notifications dans l'interface, mais les refuse dans le navigateur
![ko](https://github.com/EsupPortail/Esup-Pod/assets/60163/56284c10-74e2-4803-9230-5b114c86ed37)

2023-09-27 14:25 UTC, ptitloup commented
testé sur macOS, installation ok et notifications ok. Merci pour ces changements. Tout cela me convient.

2023-09-27 14:27 UTC, merged