[WIP] fix recuring date in edit meeting
EsupPortail/Esup-Pod pull request #946
Opened 2023-09-12 13:50 UTC by ptitloup

Before sending your pull request, make sure the following are done :

* [ ] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [ ] Your PR targets the `develop` branch.
* [ ] The title of your PR starts with `[WIP]` or `[DONE]`.

2023-09-14 15:02 UTC, Badatos approved these changes
quelques pydocs et c'est bon pour le code ^^

2023-09-14 15:02 UTC, Badatos commented on pod/meeting/forms.py
> +    def clean_start_date(self):
manque une pydoc

2023-09-14 15:02 UTC, Badatos commented on pod/meeting/forms.py
> +    def clean_add_owner(self):
pydoc

2023-09-18 10:15 UTC, AymericJak requested changes
Pas de problèmes majeurs rencontrés.
Néanmoins, un petit soucis.

Lorsque l'on créé une réunion (admettons à la date du 20 septembre) et que l'on applique une récurrence. La date affichée sous la vignette est incorrecte. En effet, celle indiquée correspond à la prochaine date de récurrence.

![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/1f97415e-1981-4860-9ff3-1d872f030797)

Ci-dessus, on peut voir, que la date affichée est le 27 septembre, soit une semaine après (puisque récurrence hebdomadaire).

2023-09-18 14:03 UTC, SebastienCozeDev requested changes
J'ai testé localement et j'ai remarqué plusieurs soucis. 

### Choix de la fréquence

Sur le choix de la fréquence, j'ai pu choisir `---------` et je n'ai pas eu d'erreur. La création de la réunion a été validé.

### Ciblage des erreurs

Lorsqu'il y a des erreurs au niveau des champs de la modale de récurrence, on ne voit pas directement là où il y a une erreur. L'utilisateur doit chercher de lui-même. Ce serait peut-être un bonne idée d'ajouter une bordure rouge sur le bouton "Récurrence".

### IntegrityError

Lorsque je met 0 dans le champs `id_frequency`, je n'ai pas d'erreur directement dans le formulaire, mais une IntegrityError.

![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/78f15adf-504c-4612-a7b2-66c74a4a3dad)

2023-09-18 14:39 UTC, ptitloup commented
> Pas de problèmes majeurs rencontrés. Néanmoins, un petit soucis.
> 
> Lorsque l'on créé une réunion (admettons à la date du 20 septembre) et que l'on applique une récurrence. La date affichée sous la vignette est incorrecte. En effet, celle indiquée correspond à la prochaine date de récurrence.
> 
> ![image](https://user-images.githubusercontent.com/106442526/268615252-1f97415e-1981-4860-9ff3-1d872f030797.png)
> 
> Ci-dessus, on peut voir, que la date affichée est le 27 septembre, soit une semaine après (puisque récurrence hebdomadaire).

Je viens de refaire les fonctions de calcul, peux-tu retester stp ? merci !

2023-09-18 14:40 UTC, ptitloup commented
> J'ai testé localement et j'ai remarqué plusieurs soucis.
> ### Choix de la fréquence
> 
> Sur le choix de la fréquence, j'ai pu choisir `---------` et je n'ai pas eu d'erreur. La création de la réunion a été validé.
> ### Ciblage des erreurs
> 
> Lorsqu'il y a des erreurs au niveau des champs de la modale de récurrence, on ne voit pas directement là où il y a une erreur. L'utilisateur doit chercher de lui-même. Ce serait peut-être un bonne idée d'ajouter une bordure rouge sur le bouton "Récurrence".
> ### IntegrityError
> 
> Lorsque je met 0 dans le champs `id_frequency`, je n'ai pas d'erreur directement dans le formulaire, mais une IntegrityError.
> 
> ![image](https://user-images.githubusercontent.com/96086580/268667769-78f15adf-504c-4612-a7b2-66c74a4a3dad.png)

Je viens de faire un patch pour corriger les pb remontés, peux-tu tester à nouveau stp ? Merci

2023-09-18 14:43 UTC, Badatos requested changes

2023-09-18 14:43 UTC, Badatos commented on pod/meeting/forms.py
> +                <button type="button" id="%s" class="%s" data-bs-toggle="%s" data-bs-target="%s">
il manque un `aria-hidden="true"` sur les icones

2023-09-18 14:43 UTC, Badatos commented on pod/meeting/models.py
> +        next_one = self.next_occurrence(timezone.now().date())
petite pydoc ?

2023-09-19 08:18 UTC, AymericJak reviewed
Ton fix est ok pour moi !

Après, une amélioration serait intéressante, le optgroup pour le champs de sélection.

Je proposerais quelque chose du style :+1: 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/92e3166e-5a23-45de-99ec-38e358ba3c85)

Soit on laisse les "----" soit on met quelque chose de plus clair comme "Ne pas répéter".

Pour faire ça, il faut juste modifier `INTERVAL_CHOICES` dans le modèle.

```python
    INTERVAL_FREQUENCIES = (
        (DAILY, _("Daily")),
        (WEEKLY, _("Weekly")),
        (MONTHLY, _("Monthly")),
        (YEARLY, _("Yearly")),
    )

    INTERVAL_CHOICES = (
        ('', 'Ne pas répéter'),
        ('-- Fréquences --', INTERVAL_FREQUENCIES),
    )
```

Dans le cas où on souhaite laisser "---", il faut juste supprimer cette ligne `('', 'Ne pas répéter'),`

2023-09-19 10:06 UTC, Badatos approved these changes

2023-09-19 12:39 UTC, SebastienCozeDev approved these changes

2023-09-20 09:31 UTC, AymericJak approved these changes
Merci :)

2023-09-20 09:35 UTC, merged