[DONE] Features for meeting: manage recording with token and send email when BBB recording available
EsupPortail/Esup-Pod pull request #958
Opened 2023-09-22 13:32 UTC by LoicBonavent

This PR is useful to:
 - Manage BBB recordings with single-use token.
 _BBB recordings without token are also managed._
 
 - Send an email when a recording was saved and available on Pod.
 _This is possible if BBB servers can realize a POST request on Pod servers._

 - Correct some bome bugs (example: use destination path, and not destination file when save a video)

2023-09-22 13:45 UTC, ptitloup requested changes
quelques petites remarques mais une questio, pourquoi enregistrer en session des données ?

2023-09-22 13:45 UTC, ptitloup commented on pod/import_video/utils.py
> +                # Ex for ESR URL:
commentaire en doublon

2023-09-22 13:45 UTC, ptitloup commented on pod/meeting/models.py
> +    def get_recording(self, record_id):
il manque un "s" c'est "get_recordings" ;)

2023-09-22 13:45 UTC, ptitloup commented on pod/meeting/templates/meeting/internal_recordings.html
> +        <i class="bi bi-info-circle"></i> {% trans "When a new recording is available at this level, you will receive an email to inform you." %}
manque un aria-hidden=True

2023-09-22 13:45 UTC, ptitloup commented on pod/meeting/views.py
> +def recording_ready_url(request):
recording_ready aurait suffit, ce n'est pas une url mais une vue ;)

2023-09-22 13:52 UTC, AymericJak requested changes

2023-09-22 13:52 UTC, AymericJak commented on pod/import_video/utils.py
> +        source_url (String): Source file URL
En Python, ce sont des `str` à la pace des `String`

2023-09-22 13:52 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr ""
Traduction manquante :)

2023-09-22 13:52 UTC, AymericJak commented on pod/meeting/templates/meeting/internal_recordings.html
> +        <i class="bi bi-info-circle"></i> {% trans "When a new recording is available at this level, you will receive an email to inform you." %}
Un petit `aria-hidden=true`

2023-09-22 13:52 UTC, AymericJak commented on pod/meeting/templates/meeting/internal_recordings.html
>                      <i class="bi bi-file-earmark-play"></i>
Ici aussi

2023-09-22 13:52 UTC, AymericJak commented on pod/meeting/templates/meeting/internal_recordings.html
>                      <i class="bi bi-camera-video"></i>
De même

2023-09-22 13:52 UTC, AymericJak commented on pod/meeting/templates/meeting/internal_recordings.html
>                      <button type="submit" class="btn btn-secondary pod-btn-secondary btn-sm" title="{% trans 'Upload to Pod as a video'%}" data-bs-toggle="tooltip" data-bs-placement="top"><i class="b
Pareil

2023-09-22 14:23 UTC, LoicBonavent commented on pod/import_video/utils.py
> +                # Ex for ESR URL:
Commentaire modifié, doublon supprimé

2023-09-22 14:24 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
> +        <i class="bi bi-info-circle"></i> {% trans "When a new recording is available at this level, you will receive an email to inform you." %}
Ajouté

2023-09-22 14:25 UTC, LoicBonavent commented on pod/meeting/views.py
> +def recording_ready_url(request):
Ok, recording_ready_url modifié en recording_ready dans l'ensemble des fichiers (urls, views...)

2023-09-22 14:30 UTC, LoicBonavent commented on pod/import_video/utils.py
> +        source_url (String): Source file URL
Comme c'est des commentaires, je trouve que c'est plus lisible String que str.
Ok, j'ai fait aussi du Java il y a très longtemps :)

2023-09-22 14:32 UTC, LoicBonavent commented on pod/locale/fr/LC_MESSAGES/django.po
> +msgstr ""
Ajouté

2023-09-22 14:32 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
> +        <i class="bi bi-info-circle"></i> {% trans "When a new recording is available at this level, you will receive an email to inform you." %}
Ajouté

2023-09-22 14:32 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
>                      <i class="bi bi-file-earmark-play"></i>
Ajouté

2023-09-22 14:33 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
>                      <i class="bi bi-camera-video"></i>
Ajouté

2023-09-22 14:33 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
>                      <button type="submit" class="btn btn-secondary pod-btn-secondary btn-sm" title="{% trans 'Upload to Pod as a video'%}" data-bs-toggle="tooltip" data-bs-placement="top"><i class="b
Ajouté

2023-09-22 14:39 UTC, ptitloup requested changes
Attention, au niveau des traduction, il manque un fichier. As-tu bien utilisé le make lang et le make compilelang pour générer les fichiers ? si oui, peux-tu rajotuer les fichiers manquant et faire un dernier commit, ca sera tout bon pour moi. Merci !

2023-09-22 14:40 UTC, AymericJak approved these changes
Ok pour moi.

2023-09-22 14:45 UTC, LoicBonavent commented
Oui, j'ai bien lancé make lang et make compilelang. Au cas où, je viens de le refaire et de pusher les fichiers impactés.
Il manque quel fichier sinon ?

2023-09-22 15:24 UTC, Badatos requested changes

2023-09-22 15:24 UTC, Badatos commented on pod/meeting/templates/meeting/internal_recordings.html
> +  <div class="pod-first-content">
à priori, il ne faut pas ajouter "pod-first-content" : il est ajouté plus haut du bloc "page_content" dans base.html

2023-09-22 15:24 UTC, Badatos commented on pod/meeting/templates/meeting/internal_recordings.html
> +    let meetingId = element.getAttribute("data-bs-meeting-id");
les attributs de type "data-..." peuvent être directement obtenus ainsi :
`let meetingId = element.dataset.bs-meeting-id;`

Mais attention : les  variables nommées "data-bs-..." sont réservées à BootStrap. Pour nos propres variables, préférez un nommage du genre "data-pod-meeting-id"
ce qui donnerait du coup :
`let meetingId = element.dataset.pod-meeting-id;`

2023-09-22 15:24 UTC, Badatos commented on pod/meeting/templates/meeting/internal_recordings.html
> +    let meetingId = element.getAttribute("data-bs-meeting-id");
idem ci-dessous pour les autres data-xxx

2023-09-25 11:49 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
> +  <div class="pod-first-content">
Class pod-first-content supprimé

2023-09-25 11:51 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
> +    let meetingId = element.getAttribute("data-bs-meeting-id");
Id data-bs-meeting-id et data-bs-recording-* remplacés par pod-meeting-id et pod-recording-*.
Par contre, j'ai laissé le code utilisant getAttribute et setAttribute; en remplaçant par dataset (au moins les 2 premières lignes), cela me provoquait une erreur...

2023-09-25 12:26 UTC, Badatos requested changes

2023-09-25 12:26 UTC, Badatos commented on pod/meeting/templates/meeting/internal_recordings.html
> +                    pod-meeting-id="{{ meeting.meeting_id }}" pod-recording-id="{{ record.id }}" pod-recording-video-url="{{ record.videoUrl }}">
Attention, il ne faut pas retirer le "data-". L'attribut doit s'appeler `data-pod-recording-id` (et `data-pod-recording-video-url`)

2023-09-25 12:27 UTC, Badatos commented on pod/meeting/templates/meeting/internal_recordings.html
> +    let meetingId = element.getAttribute("data-bs-meeting-id");
ok, à mon avis l'erreur venait du fait qu'il n'y avait plus "data-" dans l'attribut : dataset liste automatiquement tous les attributs qui commencent par "data-".

2023-09-25 13:14 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
> +    let meetingId = element.getAttribute("data-bs-meeting-id");
Oui, data- ajouté

2023-09-25 13:15 UTC, LoicBonavent commented on pod/meeting/templates/meeting/internal_recordings.html
> +                    pod-meeting-id="{{ meeting.meeting_id }}" pod-recording-id="{{ record.id }}" pod-recording-video-url="{{ record.videoUrl }}">
Yep, ajouté

2023-09-25 13:40 UTC, Badatos approved these changes
C'est parfait, merci Loic ! ;)

2023-09-25 13:41 UTC, merged

2023-09-25 13:41 UTC, LoicBonavent commented
> C'est parfait, merci Loic ! ;)

Merci à toi.