[DONE] Change is_staff to follow affiliation
EsupPortail/Esup-Pod pull request #972
Opened 2023-10-03 10:47 UTC by CartierPierre

Follow is_staff dynamictly with AFFILIATION_STAFF and user affiliation.
It also revoke if user isn't part of affiliation staff anymore.

2023-10-03 12:19 UTC, Badatos commented on pod/authentication/models.py
> +        if self.affiliation in AFFILIATION_STAFF :
Il y a déjà un `self.user.is_staff = True` dans la fonction pod/authentication/backend.py. Est-ce que ce n'est pas redondant du coup ?

2023-10-03 17:04 UTC, CartierPierre commented on pod/authentication/models.py
> +        if self.affiliation in AFFILIATION_STAFF :
Pour Shibboleth et OIDC, oui, mais pour le CAS ? (et LDAP je crois que c'est bon aussi)

2023-10-05 07:28 UTC, ptitloup requested changes

2023-10-05 07:28 UTC, ptitloup commented on pod/authentication/models.py
> +        if self.affiliation in AFFILIATION_STAFF :
Bonjour,
la modification du staff se fait pour le ldap : https://github.com/EsupPortail/Esup-Pod/blob/master/pod/authentication/populatedCASbackend.py#L240 mais egalement pour le CAS : https://github.com/EsupPortail/Esup-Pod/blob/master/pod/authentication/populatedCASbackend.py#L293
J'avoue ne pas comprendre le besoin, est-ce possible de m'expliquer ?
Merci

2023-10-05 17:11 UTC, CartierPierre commented
J'en ai parlé sur le rocketchat, en gros le champ is_staff ne se met pas à jour en fonction de l'affiliation (pourtant défini dans `AFFILIATION_STAFF`).
Pour tous mes users existants, j'ai du passer un petit script pour changer leur statut à la main.  
Je me suis dit que c'était peut être qu'il fallait se deco/reco pour que ca charge les changements, mais affiliation a changé sans changer is_staff.

2023-10-09 07:27 UTC, ptitloup commented
> J'en ai parlé sur le rocketchat, en gros le champ is_staff ne se met pas à jour en fonction de l'affiliation (pourtant défini dans `AFFILIATION_STAFF`). Pour tous mes users existants, j'ai du passer un petit script pour changer leur statut à la main. Je me suis dit que c'était peut être qu'il fallait se deco/reco pour que ca charge les changements, mais affiliation a changé sans changer is_staff.

Bonjour Pierre et merci pour ton retour. Je vais regarder tout ca d'ici cette fin de semaine et reviens vite vers toi.

2023-10-09 12:31 UTC, Badatos commented
au passage, la PR ne passe pas le test "flake8" car elle contient des espaces en fin de lignes.
Si vous utilisez l'éditeur "VS Code", je vous invite à activer le paramètre "editor.renderWhitespace": "all" pour vmieux visualiser ces espaces récalcitrants
"editor.renderWhitespace": "all"
cf https://code.visualstudio.com/docs/getstarted/tips-and-tricks
nb 1 : la commande "⌘K ⌘X" permet de se débarasser des ces caractères dans un fichier
Et pour ne plus s'en occuper du tout, je recommende de chercher l'option "Editor: Trim Auto Whitespace" et de l'activer dans les paramètres de VS code.

2023-10-24 08:33 UTC, closed without merging

2023-10-24 08:33 UTC, ptitloup commented
Vu avec Pierre en visio, le problème provenait de sa configuration du serveur SSO-CAS, son serveur ne remonte pas les affiliations de ses utilisateurs