[DONE] New 3.4.0 fixes
EsupPortail/Esup-Pod pull request #981
Opened 2023-10-12 12:01 UTC by LoicBonavent

Fixes 3 bugs for 3.4.0 version:

- [ ] Bugfix for create a thumbnail.
To check, execute a command like this: "python manage.py create_thumbnail id" 

- [ ] Fixed bug preventing change of pages or number of lines in statistics interface
To check, on a statistics page (/stats_view/), try to change the number of lines or page. Without this bugfix, you can see an "data.filter is not a function" error in the browser console and an icon Loading, and no changes.

- [ ] Bugfix for issue #948 (An error appears in the form for adding a video, for a super admin, for the owner attribute).
To check, with a super admin user, upload a video file, wait for encoding to finish (while still on the editing page) and save. Without this bugfix, you can see an "owner  - this field is required" error.

2023-10-12 12:37 UTC, Badatos requested changes
Merci pour ces corrections !
Y'a que pour la correction JS que je mets une remarque.

2023-10-12 12:37 UTC, Badatos commented on pod/video/static/js/video_stats_view.js
> +      try {
Ca me semble pas super propre comme correction :)
Est-ce qu'on peut mieux definir le cas dans lequel on souhaite éviter une exception ?

2023-10-12 12:37 UTC, Badatos commented on pod/video/static/js/video_stats_view.js
> +        document.querySelector("#jsperiode").min = min_date[0].min_date;
je propose de remplacer querySelector("# par getElementById(" ici

2023-10-12 12:42 UTC, LoicBonavent commented on pod/video/static/js/video_stats_view.js
> +      try {
C'est çà le problème; je n'ai pas bien compris ce qui a été fait sur les données envoyées. J'ai l'impression qu'il y a un mix de données différentes; je n'ai alors pas souhaité toucher l'ensemble du  process.
En plus, il me semble que les statistiques sont en train d'être refaites, d'où, le fait de seulement faire en sorte que cela marche dans l'état actuel des choses.

2023-10-12 13:35 UTC, Badatos commented on pod/video/static/js/video_stats_view.js
> +      try {
Ok ! 
Met ptet juste un commentaire pour se rappeler le bug qu'on essaye d'éviter ^^

2023-10-12 14:35 UTC, LoicBonavent commented on pod/video/static/js/video_stats_view.js
> +      try {
Yes, fait

2023-10-13 07:38 UTC, AymericJak requested changes
- L'upload des vidéos en mode super admin est maintenant bien corrigé !
- Quand je vais sur la page des statistiques, je constate une autre erreur dans la console : 
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/5e434ba6-5d03-47d3-bbe5-b5690379c4f3)
- Pour ce qui est du reste, c'est tout bon pour moi :)

2023-10-13 08:23 UTC, LoicBonavent commented
Sur le coup, je n'ai pas touché au fichier webpush.js. Il concerne les notifications : je ne vois pas trop son utilité pour les stats...

2023-10-13 08:29 UTC, AymericJak commented
Yess, je sais bien que tu n'y a pas touché, mais comme tu fais du bug fix de la 3.4.0, je trouve ça intéressant de le corriger :)

Je suis du même avis, je ne vois pas trop l'utilité des notifications pour les stats :)

2023-10-13 08:38 UTC, LoicBonavent commented
On voit que tu bosses avec Nicolas :)
Ok, je regarde cela cet après-midi

2023-10-13 09:06 UTC, SebastienCozeDev requested changes
Merci pour cette PR !

J'ai pu remarquer un petit soucis avec le thème noir, le champ est en fond blanc alors qu'habituellement, il est sur fond foncé.

![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/6f44a7e6-6983-4191-974e-19342876653a)

![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/a813f59b-01df-4f43-b963-926bb6559cf2)

Il n'y a également pas de texte informatif sur le champ.

2023-10-13 09:16 UTC, AymericJak commented
En fait @SebastienCozeDev, pour le JQuery de la partie Stats, cela a été laissé ainsi puisqu'une PR sur les stats est en cours.

Autant éviter de faire 2 fois le même boulot, puisque JQuery a totalement été retiré dans la PR Stats.

2023-10-13 13:47 UTC, LoicBonavent commented
> On voit que tu bosses avec Nicolas :) Ok, je regarde cela cet après-midi

Concernant l'erreur Javascript non bloquante, il faudrait modifier le fichier webpush.js, qui est fourni par le module django-webpush, pour gérer le fait que subBtn peut être null. A voir si l'on veut par la suite contribuer à ce projet... Pour l'instant, je préfère ne pas toucher.

2023-10-13 13:53 UTC, LoicBonavent commented
> Merci pour cette PR !
> 
> J'ai pu remarquer un petit soucis avec le thème noir, le champ est en fond blanc alors qu'habituellement, il est sur fond foncé.
> 
> ![image](https://user-images.githubusercontent.com/96086580/274853053-6f44a7e6-6983-4191-974e-19342876653a.png)
> 
> ![image](https://user-images.githubusercontent.com/96086580/274853477-a813f59b-01df-4f43-b963-926bb6559cf2.png)
> 
> Il n'y a également pas de texte informatif sur le champ.

Le texte informatif provient du modèle; il y a pas mal de champs qui n'ont pas de texte informatif (disciplines, licence, date d'ajout...). Ce n'est pas trop utile quand c'est clair. Bref, je n'en ai pas ajouté pour Propriétaire.
Par contre, j'ai modifié le fichier dark.css pour tenir compte de l'autre point : cela venait du style de select2 pour le cas single et non multiple. J'en ai aussi profité pour modifier le fond lors de l'affichage des résultats d'une recherche dans un champ select2.
Je pense que c'est tout bon maintenant :)

2023-10-13 13:53 UTC, AymericJak approved these changes
Ok, merci à toi pour ta PR.

Bonne fin de journée, et bon week-end :)

2023-10-13 16:00 UTC, merged