[DONE] A11y for caption_maker
EsupPortail/Esup-Pod pull request #982
Opened 2023-10-12 13:32 UTC by Badatos

* [x] Now caption-maker textareas are limited to 40 chars max per row, with max chars at 80
* [x] When editing a caption/subtitle, the player auto-seek at related time
* [x] add missing aria-hidden + aria-label on some button-icons
* [x] Uniformize caption/subtitle naming
* [x] Reorder CSS for code styling

2023-10-12 13:45 UTC, AymericJak requested changes
Pas grand chose à dire :)

C'est très bien, merci !

Juste 2 petites modifications et c'est ok pour moi

2023-10-12 13:45 UTC, AymericJak commented on pod/completion/static/js/caption_maker.js
>  function GenerateWEBVTT() {
Est-ce que tu pourrais en profiter pour mettre la documentation des fonctions ?

2023-10-12 13:45 UTC, AymericJak commented on pod/main/static/css/pod.css
>  /** vignettes video **/
Peux tu traduire ce commentaire en français :)

2023-10-12 14:06 UTC, Badatos commented on pod/completion/static/js/caption_maker.js
>  function GenerateWEBVTT() {
"Juste 2 petites modifications" qu'il dit 🤣 !
Ca va, y'a que 40 fonctions dans ce fichier de 1400 lignes 😨 ...

2023-10-13 07:16 UTC, AymericJak commented on pod/completion/static/js/caption_maker.js
>  function GenerateWEBVTT() {
Hahaha, tu n'es pas obligé de tout faire :joy:

2023-10-13 08:17 UTC, SebastienCozeDev approved these changes

2023-10-13 14:04 UTC, Badatos commented
Voila, j'ai pris en compte les remarques et ajouté autant de JsDoc que possible dans caption_maker.
J'en ai profité pour uniformiser les noms des fonctions (majuscules pour les Objets et Classes mais minuscules pour le reste) -> J'ai ajouter cette règle dans un fichier .eslint à la racine de pod pour que vos IDE favoris fassent des alertes sur ce point si vous avez activé eslint
Et pour finir, j'ai mis en place des validation côté client pour le caption maker, de manière que lorsque quelqu'un chargera un ancien fichier de sous-titre ne respectant pas la nouvelle règle des 80 caractères max cla l'avertissent, en placant bien le focus sur le sous-titre en erreur.
@AymericJak tu peux reviewer :)

2023-10-13 14:07 UTC, AymericJak approved these changes
J'ai une petite remarque concernant les traductions, sinon c'est tout bon !!

Merci pour ta détermination avec la documentation de toutes ces fonctions !!!
Du travail de pro :muscle:

2023-10-13 14:07 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/djangojs.po
>  msgstr "Il n’y a aucun sous-titre à sauvegarder."
À des endroits 'caption' est traduit par sous-titre, sous-titre/légende.

Manque un peu d'uniformisation :)

2023-10-13 14:07 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/djangojs.po
> +msgstr "Ajouter un(e) légende/sous-titre ci-dessous"
Ici aucun espace avant et après le `/`

2023-10-13 14:07 UTC, AymericJak commented on pod/locale/fr/LC_MESSAGES/djangojs.po
>  msgstr "Légende / Sous-titre"
Ici on met un espace avant et après le `/`

2023-10-13 14:28 UTC, Badatos commented on pod/locale/fr/LC_MESSAGES/djangojs.po
>  msgstr "Il n’y a aucun sous-titre à sauvegarder."
bien, vu ! c'est corrigé ;)

2023-10-16 09:01 UTC, AymericJak reviewed
J'ai juste refait un petit tour dans le code.

Tout ce que j'ai noté c'est :
- Les mauvaises convention de nommage des variables. (Ne fais pas, c'est tellement long !!!)
- Une condition un peu étrange.

2023-10-16 12:13 UTC, Badatos commented on pod/completion/static/js/caption_maker.js
> +  }
ah ben non ca ne marche pas : ici on cherche à arrêter prématurément la fonction, pas à simplement renvoyer le résultat de validateForms ;)

2023-10-16 12:14 UTC, ptitloup commented on pod/completion/static/js/caption_maker.js
> +  }
ok !

2023-10-16 12:15 UTC, Badatos commented on pod/completion/static/js/caption_maker.js
> +  }
J'ajoute un commentaire pour que ce soit plus clair.

2023-10-16 12:50 UTC, merged