[WIP] Bugfix of 3.4.0
EsupPortail/Esup-Pod pull request #983
Opened 2023-10-13 12:21 UTC by AymericJak

- Un propriétaire additionnel d'une playlist protégée devait entrer le mot de passe. Maintenant, ce n'est plus le cas.

2023-10-13 13:51 UTC, ptitloup approved these changes
ok pour moi niveau code, je vais voir avec les collègues pour les tests fonctionnels

2023-10-13 14:22 UTC, SebastienCozeDev requested changes
J'ai testé localement et j'ai remarqué deux soucis :

- Le message d'erreur n'est pas vraiment correct lorsque que l'on ne rentrer pas de mot de passe :
![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/f404ecac-c222-4ac4-aa92-219705d4459f)

- Il n'y a plus de titre lorsque le formulaire comporte des erreurs : 
![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/28fcdbe3-8849-4926-8e83-6e4aa475c5e0)

2023-10-16 13:14 UTC, Badatos commented on dockerfile-dev-with-volumes/pod-back/Dockerfile
> +RUN apt-get clean && apt-get update && apt-get install -y netcat && apt-get install -y gettext
pour ma part, j'utilise maintenant `apt` à la place d’`apt-get`. Ca fait la même chose, mais c'est plus court :)

2023-10-16 13:26 UTC, Badatos commented on pod/playlist/views.py
> +        page_title = _("Edit the playlist") + f' "{playlist.name}"'
ici il faudrait plutôt écrire ceci pour une traduction correcte dans toutes les langues (pensons aux langues qui se lisent de droite à gauche) :

`page_title = _("Edit the playlist “%(pname)s”") % {"pname": playlist.name}`

2023-10-16 13:32 UTC, ptitloup commented on pod/meeting/models.py
> +        self.meeting_id = "%s-%s" % (newid, slugify(self.name).replace("-", "_"))
une erreur de ma part pour des tests, je l'ai retiré

2023-10-16 14:20 UTC, merged