[DONE] force end of BBB meeting if not create or get status
EsupPortail/Esup-Pod pull request #988
Opened 2023-10-18 15:15 UTC by ptitloup

Fix issues of BBB Scalite : https://github.com/bigbluebutton/bigbluebutton/issues/18913

Before sending your pull request, make sure the following are done :

* [x] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [x] Your PR targets the `develop` branch.
* [x] The title of your PR starts with `[WIP]` or `[DONE]`.

2023-10-18 15:18 UTC, Badatos commented on pod/meeting/models.py
> +                return self.create()
un petit commentaire serait le bienvenue ;)

2023-10-18 15:18 UTC, Badatos requested changes

2023-10-19 07:43 UTC, LoicBonavent approved these changes
Cela me semble correct, mais non testé

2023-10-19 12:11 UTC, Badatos approved these changes
une petite pydoc et c'est bon ^^

2023-10-19 12:11 UTC, Badatos commented on pod/meeting/models.py
> +    def get_meeting_parameters(self):
manque une petite pydoc

2023-10-19 12:26 UTC, merged