[WIP] Add Whisper transcription
EsupPortail/Esup-Pod pull request #991
Opened 2023-10-23 13:20 UTC by david42

Before sending your pull request, make sure the following are done :

* [x] You have read our [contribution guidelines](https://github.com/EsupPortail/Esup-Pod/blob/master/CONTRIBUTING.md).
* [x] Your PR targets the `develop` branch.
* [x] The title of your PR starts with `[WIP]` or `[DONE]`.

2023-10-23 13:35 UTC, david42 commented
Déployer Whisper : 

Sur les encodeurs : 
`pip install git+https://github.com/openai/whisper.git`

Sur le frontal : 
`pip3 install openai-whisper`

Exemple de configuration du custom/settings_local : 
`TRANSCRIPTION_TYPE = "WHISPER"`

`TRANSCRIPTION_MODEL_PARAM = {`
`     'WHISPER':{`
`       'fr': {`
`         'model': "small",`
`         'download_root': "/pod-transcription/transcription/whisper/",`
`       },`
`       'en': {`
`         'model': "small",`
`         'download_root': "/pod-transcription/transcription/whisper/",`
`       }`
`    }`
`}`

[Voir détails ici pour le choix du modèle](https://github.com/openai/whisper#available-models-and-languages)
Le small n'est pas plus gourmand que vosk et est déjà performant

2023-10-23 14:03 UTC, ptitloup commented
Voici les erreurs de typo à corriger svp : 
```
Run flake8 --max-complexity=7 --ignore=E501,W503,E203 --exclude .git,pod/*/migrations/*.py,*_settings.py
./pod/video_encode_transcript/transcript_model.py:406:1: E302 expected 2 blank lines, found 1
./pod/video_encode_transcript/transcript_model.py:414:13: E126 continuation line over-indented for hanging indent
./pod/video_encode_transcript/transcript_model.py:416:9: E121 continuation line under-indented for hanging indent
./pod/video_encode_transcript/transcript_model.py:417:1: W293 blank line contains whitespace
./pod/video_encode_transcript/transcript_model.py:433:1: E302 expected 2 blank lines, found 1
Error: Process completed with exit code 1.
```

2023-10-23 14:20 UTC, Badatos commented
Attention : il faut merger vers la branche "develop" et non "master"

2023-10-23 14:22 UTC, Badatos requested changes

2023-10-23 14:22 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +        msg, webvtt, all_text = main_whisper_transcript(
Pourquoi réattribuer des valeurs à msg, webvtt, all_text ici alors qu'elle l'ont déja été ligne 100 ? je pense qu'il faut revoir le test.

2023-10-23 14:22 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +def main_whisper_transcript(norm_mp3_file, lang):
Merci d'ajouter un commentaire desciptif sous chaque nouvelle fonction sous la forme :
`"""Description courte de l'action réalisée."""`

2023-10-24 06:40 UTC, david42 commented on pod/video_encode_transcript/transcript_model.py
> +def main_whisper_transcript(norm_mp3_file, lang):
Ok, fait

2023-10-24 06:46 UTC, david42 commented on pod/video_encode_transcript/transcript_model.py
> +        msg, webvtt, all_text = main_whisper_transcript(
Possible que je loupe une subtilité; ce sont mes toutes 1ères lignes python/django; je suis donc un grand débutant de cet environnement mais ceci me semble nécessaire et cohérent avec ce qui précède. Pour moi ces valeurs sont attribuées en effet par la méthode "start_transcripting" mais à partir des valeurs renvoyées par "start_main_transcript" qui elle même valorise ces var par le retour d'une des méthodes de transcription en fonction de la conf.

2023-10-24 07:27 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +        msg, webvtt, all_text = main_whisper_transcript(
En fait, ligne 100 on fait appel à `start_main_transcript` et met le retour dans les variables "msg, webvtt, all_text" qu'on écrase ensuite ligne 120 dans le cas de Whisper. De ce que je comprend, il pourrait y avoir un test `if TRANSCRIPTION_TYPE == "WHISPER":`avant la ligne 100 pour ne faire qu'un des 2 types de transcriptions.

2023-10-24 10:28 UTC, Badatos commented on pod/video_encode_transcript/transcript_model.py
> +        msg, webvtt, all_text = main_whisper_transcript(
Ca semble pas mal en effet ;)

2023-10-24 12:12 UTC, ptitloup commented
je teste de mon cote

2023-10-24 12:24 UTC, ptitloup commented on pod/video_encode_transcript/transcript_model.py
> +    model = whisper.load_model(
tu aurais pu faire le load model dans le definition "get_model" et ainsi reprendre le code précédent ;)

2023-10-24 12:26 UTC, Badatos approved these changes

2023-10-24 12:28 UTC, ptitloup commented
petite question, j'ai pas trouvé comment récupérer les models. Ils sont ou ?

2023-10-24 12:36 UTC, david42 commented on pod/video_encode_transcript/transcript_model.py
> +    transcription = model.transcribe(norm_mp3_file, language=lang)
En effet pas testé avec des vidéos de plusieurs heures, je vais voir pour en récupérer afin de tester

2023-10-24 12:36 UTC, Badatos commented
> petite question, j'ai pas trouvé comment récupérer les models. Ils sont ou ?

J'avais compris que Whisper télécharge lui-même le modèle demandé, ce n'est pas le cas ?

2023-10-24 12:37 UTC, ptitloup commented
> > petite question, j'ai pas trouvé comment récupérer les models. Ils sont ou ?
> 
> J'avais compris que Whisper télécharge lui-même le modèle demandé, ce n'est pas le cas ?

Si en effet, c'est ce que je constate

2023-10-24 12:38 UTC, david42 commented
Oui c'est ça, c'est Whisper qui télécharge les modèles, ils sont déposés dans le path défini par download_root; voir exemple de la conf en exemple en haut de page

2023-10-24 12:54 UTC, ptitloup commented
Voici le résultat sur une video type reportage : 

# Whisper 
Inference start 13968.871s.
Running inference.
Inference took 60.399s.
00:00:00.000 00:00:06.000  Plus on utilise les antibiotiques, plus ils tendent à perdre leur efficacité.
00:00:06.000 00:00:13.000  1975, des médecins a alerté sur les conséquences de la surconsommation d'antibiotiques.
00:00:13.000 00:00:19.000  Certaines bactéries sont tellement accoutumées à l'antibiotique, qu'elles en ont besoin.
00:00:19.000 00:00:23.000  Elles en sont dépendantes, elles ne peuvent se multiplier qu'en présence de l'antibiotique.
00:00:23.000 00:00:28.000  Vous voyez que dans le monde bactérien, il est aussi des toxicomètre.
00:00:28.000 00:00:33.000  A cette époque, la résistance aux antibiotiques était déjà un problème majeur de santé publique.
00:00:33.000 00:00:36.000  Pour le docteur Maurice Rappin, qui n'a cessé d'alerté sur le risque,
00:00:36.000 00:00:41.000  une meilleure communication autour de ces médicaments était alors primordiale.
00:00:41.000 00:00:47.000  Il est donc nécessaire que le public restreigne son emploi des antibiotiques en supprimant l'automédication
00:00:47.000 00:00:54.000  et d'autre part qu'ils n'incitent pas les médecins à user trop précocement d'antibiotiques.
00:00:54.000 00:01:00.000  Malgré ses recommandations 19 ans plus tard, la surconsommation d'antibiotiques est toujours un problème en France.
00:01:00.000 00:01:05.000  Les Français sont de grands consommateurs de médicaments, parfois 2 à 3 fois plus que leurs voisins,
00:01:05.000 00:01:08.000  notamment pour les antibiotiques ou encore les anti-dépresseurs.
00:01:08.000 00:01:13.000  En 2000, dans une étude, un groupe de médecins tirait encore une fois la senette d'alarme.
00:01:13.000 00:01:18.000  Il s'inquiétait de l'inefficacité des antibiotiques, notamment sur les enfants.
00:01:18.000 00:01:22.000  Contre l'abus d'antibiotiques, ces professionnels de la santé vont se rendre dans les cabinets médicaux,
00:01:22.000 00:01:25.000  les pharmacies, les crèches pour une campagne de sensibilisation.
00:01:25.000 00:01:30.000  En 2002, la science maladie lancée aussi une campagne nationale de sensibilisation,
00:01:30.000 00:01:32.000  une campagne aux stegons efficaces.
00:01:32.000 00:01:36.000  Les antibiotiques, c'est pas automatique, par les ans avec votre médecin.
00:01:36.000 00:01:40.000  Depuis 2000, la consommation d'antibiotiques a diminué en France,
00:01:40.000 00:01:43.000  mais la résistance à ces médicaments fait toujours des dégâts.
00:01:43.000 00:01:50.000  Selon l'Agence du Médicament, près de 160 000 personnes développent une infection liée à une bactérie multirésistante
00:01:50.000 00:01:54.000  et plus de 12 500 personnes en meurt chaque année.

# Vosk
Inference start 14357.180s.
Running inference.
Inference took 17.025s.
00:00:01.200 00:00:05.880 plus on utilise des antibiotiques plus ils tendent à perdre leur efficacité
00:00:06.514 00:00:12.450 mille neuf cent soixante-quinze des médecins alertent sur les conséquences de la surconsommation d'antibiotiques
00:00:13.080 00:00:27.630 certaines bactéries sont tellement accoutumés à l'antibiotique et qu'elles en ont besoin elles en sont dépendantes elles ne peuvent se multiplier qu'en présence de l'antibiotique vous voyez que dans le monde bactérien il est aussi des toxicomanes
00:00:28.320 00:00:32.430 a cette époque la résistance aux antibiotiques était déjà un problème majeur de santé publique
00:00:33.120 00:00:40.470 pour le docteur maurice sera pas qu n'a cessé d'alerter sur le risque une meilleure communication autour de ces médicaments étaient alors primordial
00:00:41.040 00:01:01.200 il est donc nécessaire que le public restreignent son emploi des antibiotiques en supprimant l'automédication et autre part qu il n incite pas eux les médecins à user précocement trois précocement un antibiotique malgré ces recommandations dix-neuf ans plus tard la surconsommation d'antibiotiques toujours un problème en france les français
00:01:01.262 00:01:13.530 sont de grands consommateurs de médicaments parfois deux à trois fois plus que leurs voisins notamment pour les antibiotiques ou encore les antidépresseurs en deux mille dans une étude un groupe de médecins tiraient encore une fois la sonnette d'alarme
00:01:14.190 00:01:17.790 inquiétait de l'inefficacité des antibiotiques notamment sur les enfants
00:01:18.510 00:01:29.730 contre l'abus d'antibiotiques ces professionnels de la santé vont se rendre dans les cabinets médicaux les pharmacies les crèches pour une campagne de sensibilisation en deux mille de l assurance maladie lancer aussi une campagne nationale de sensibilisation
00:01:30.270 00:01:32.190 une campagne pour slogan efficace
00:01:32.970 00:01:42.630 les antibiotiques c'est pas automatique parlez-en avec votre médecin depuis deux mille la consommation d'antibiotiques a diminué en france mais la résistance à ces médicaments fait toujours des dégâts
00:01:43.290 00:01:50.370 selon l'agence du médicament près de cent soixante mille personnes développent une infection liée à une bactérie multi résistante
00:01:51.000 00:01:54.000 et plus de douze mille cinq cents personnes en meurent chaque année

2023-10-24 12:55 UTC, ptitloup commented
Whisper est plus long mais pas forcement plus efficace, toutefois, il apporte la ponctuation !

2023-10-24 12:58 UTC, ptitloup commented
Enfin voici deux modifs que j'ai du faire : 
```
diff --git a/pod/video_encode_transcript/transcript.py b/pod/video_encode_transcript/transcript.py
index df21e392..a845192c 100644
--- a/pod/video_encode_transcript/transcript.py
+++ b/pod/video_encode_transcript/transcript.py
@@ -16,6 +16,7 @@ import importlib.util
 if (
     importlib.util.find_spec("vosk") is not None
     or importlib.util.find_spec("stt") is not None
+    or importlib.util.find_spec("whisper")  is not None
 ):
     from .transcript_model import start_transcripting
```
et 
```
diff --git a/requirements-transcripts.txt b/requirements-transcripts.txt
index 42d98945..7f939174 100644
--- a/requirements-transcripts.txt
+++ b/requirements-transcripts.txt
@@ -5,3 +5,6 @@ stt==1.4.0 # linux only
 
 # Offline open source speech recognition API based on Kaldi and Vosk
 vosk==0.3.45
+
+# Whisper
+openai-whisper
```

2023-10-24 13:04 UTC, Badatos commented
> Whisper est plus long mais pas forcement plus efficace, toutefois, il apporte la ponctuation !

On peut aussi noter que les phrases sont moins longues : il y a un meilleur découpage qu'avec VOSK

2023-10-24 13:09 UTC, ptitloup commented
> > Whisper est plus long mais pas forcement plus efficace, toutefois, il apporte la ponctuation !
> 
> On peut aussi noter que les phrases sont moins longues : il y a un meilleur découpage qu'avec VOSK

Oui globalement un peu moins de retravaille avec whisper ! Il a pris 4x plus de temps que vosk mais j'ai fait les tests sous docker avec des ressources limitées. C'est vrai qu'il est gourmand

2023-10-24 13:31 UTC, david42 commented
J'ai reporté  tes modifes Nicolas. 

Sur les noms propres et l'orthographe; j'ai eu des meilleurs rendus avec Whisper avec le modèle small comme dans l'exemple.  En passant à medium et mieux à large on augmente la qualité du rendu mais aussi la conso de ressource qui se fait ressentir. 
Je suis également en docker sur mon poste, je lui attribue 6 cores CPU.
Le modèle small est le plus proche de vosk d'un mon point de vue au niveau du rapport conso/qualité. On peut aussi descendre en "base" et "tiny"

2023-10-24 13:55 UTC, ptitloup approved these changes
ok pour moi

2023-10-24 13:58 UTC, ptitloup commented
DOC EN LIGNE : https://www.esup-portail.org/wiki/display/ES/Installation+de+l%27autotranscription+en+Pod+V3#Installationdel'autotranscriptionenPodV3-Whisper

2023-10-24 13:58 UTC, merged

2023-10-24 14:01 UTC, ptitloup commented
Merci @david42 pour cette contribution